local consequence_trade = require("npc.base.consequence.trade")
local condition_language = require("npc.base.condition.language")
local basic = require("npc.base.basic")
local trade = require("npc.base.trade")
local talk = require("npc.base.talk")
local consequence_inform = require("npc.base.consequence.inform")
local function initNpc()
local mainNPC = basic()
mainNPC:setAffiliation(3)
local talkingNPC = talk(mainNPC)
local tradingNPC = trade(mainNPC)
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Help")
talkEntry:addConsequence(consequence_inform("[Game Help] This NPC is Antonius Copperhand the smith. Keywords: Buy, sell, trade, job, your name."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hilfe")
talkEntry:addConsequence(consequence_inform("[Spielhilfe] Dieser NPC ist Antonius Copperhand der Schmied. Schlüsselwörter: Kaufe, verkaufe, Handel, Beruf, dein Name."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("sell")
talkEntry:addTrigger("buy")
talkEntry:addTrigger("wares")
talkEntry:addTrigger("price")
talkEntry:addTrigger("trade")
talkEntry:addTrigger("purchase")
talkEntry:addResponse("You came to the right man. Let's see what I can offer you.")
talkEntry:addResponse("Money, money, money. Always funny.")
talkEntry:addConsequence(consequence_trade(tradingNPC))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("kauf")
talkEntry:addTrigger("waren")
talkEntry:addTrigger("preis")
talkEntry:addTrigger("Handel")
talkEntry:addTrigger("veräußer")
talkEntry:addTrigger("veräusser")
talkEntry:addTrigger("erwerb")
talkEntry:addResponse("Du bist genau zum richtigen Mann gekommen. Schaun 'mer mal, was ich anzubieten habe.")
talkEntry:addResponse("Geld, Geld, Geld. Das gefällt!")
talkEntry:addConsequence(consequence_trade(tradingNPC))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hello")
talkEntry:addTrigger("Greet")
talkEntry:addTrigger("Hail")
talkEntry:addTrigger("Good day")
talkEntry:addTrigger("Good morning")
talkEntry:addTrigger("Good evening")
talkEntry:addResponse("Be greeted in Irmorom's name.")
talkEntry:addResponse("Greetings.")
talkEntry:addResponse("Good day.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Grüß")
talkEntry:addTrigger("Gruß")
talkEntry:addTrigger("Grüss")
talkEntry:addTrigger("Gruss")
talkEntry:addTrigger("Guten Tag")
talkEntry:addTrigger("Guten Abend")
talkEntry:addTrigger("Mahlzeit")
talkEntry:addTrigger("Tach")
talkEntry:addTrigger("Moin")
talkEntry:addResponse("Zum Gruße.")
talkEntry:addResponse("Seid gegrüßt in Namen Irmoroms.")
talkEntry:addResponse("Guten Tach.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Hiho")
talkEntry:addTrigger("Hallo")
talkEntry:addTrigger("Hey")
talkEntry:addTrigger("Greeb")
talkEntry:addResponse("Be greeted.")
talkEntry:addResponse("Greetings.")
talkEntry:addResponse("Good day.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hiho")
talkEntry:addTrigger("Hallo")
talkEntry:addTrigger("Hey")
talkEntry:addTrigger("Greeb")
talkEntry:addResponse("Zum Gruße.")
talkEntry:addResponse("Seid gegrüßt.")
talkEntry:addResponse("Guten Tach.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Farewell")
talkEntry:addTrigger("Bye")
talkEntry:addTrigger("Fare well")
talkEntry:addTrigger("See you")
talkEntry:addResponse("Farewell.")
talkEntry:addResponse("Goodbye.")
talkEntry:addResponse("May Irmorom be with you.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Tschüß")
talkEntry:addTrigger("Tschüss")
talkEntry:addTrigger("Wiedersehen")
talkEntry:addTrigger("Gehab wohl")
talkEntry:addResponse("Auf bald.")
talkEntry:addResponse("Bis bald.")
talkEntry:addResponse("Möge Irmorom über Euch wachen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Ciao")
talkEntry:addTrigger("Adieu")
talkEntry:addTrigger("Au revoir")
talkEntry:addTrigger("Farebba")
talkEntry:addResponse("Farewell.")
talkEntry:addResponse("Goodbye.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Ciao")
talkEntry:addTrigger("Adieu")
talkEntry:addTrigger("Au revoir")
talkEntry:addTrigger("Farebba")
talkEntry:addResponse("Auf bald.")
talkEntry:addResponse("Bis bald.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("How are you")
talkEntry:addTrigger("How feel")
talkEntry:addTrigger("How do you do")
talkEntry:addResponse("I'm fine, thanks... and how are ya?")
talkEntry:addResponse("Good, good.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Wie geht")
talkEntry:addTrigger("Wie fühlst")
talkEntry:addTrigger("Wie ist es ergangen")
talkEntry:addTrigger("Wie Befind")
talkEntry:addResponse("Mir jeht ett wunderbar und wie jeht et Euch?")
talkEntry:addResponse("Jut, jut.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("your name")
talkEntry:addTrigger("who are you")
talkEntry:addTrigger("who art thou")
talkEntry:addResponse("Me? I'm the goldsmith of Galmair, the hard working Antonius.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("dein name")
talkEntry:addTrigger("wer bist du")
talkEntry:addTrigger("wer seid ihr")
talkEntry:addTrigger("wie heißt")
talkEntry:addTrigger("wie heisst")
talkEntry:addResponse("Ick? Ick bin der Goldchmied von Galmair, der fleißge Antonius.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("At the moment I have nothing for ya to do. Sorry.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Zur Zeit gibbet für dich nix zu tun. T'schuldigung.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addResponse("At the moment I have nothing for ya to do. Sorry.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addResponse("Zur Zeit gibbet für dich nix zu tun. T'schuldigung.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("profession")
talkEntry:addResponse("I am a smith. Can't ya tell?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("beruf")
talkEntry:addResponse("Ich bin 'nen Schmied. Siehste datt nich'?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("job")
talkEntry:addResponse("I am a smith. Can't ya tell?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("job")
talkEntry:addResponse("Ich bin 'nen Schmied. Siehste datt nich'?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Gobaith")
talkEntry:addTrigger("Gobiath")
talkEntry:addResponse("Never heard of that place...")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Gobaith")
talkEntry:addTrigger("Gobiath")
talkEntry:addResponse("Kenn' ich nich'...")
talkingNPC:addTalkingEntry(talkEntry)
end
talkingNPC:addCycleText("#me pfeift eine Melodie.", "#me whistles a melody.")
talkingNPC:addCycleText("#me wischt sich den Schweiß von der Stirn.", "#me wipes the sweat off his forehead.")
talkingNPC:addCycleText("#me betrachtet zufrieden seine geschmiedeten Werke.", "#me looks at his smithed works with a content face.")
talkingNPC:addCycleText("#me hält ein Amulett gegen das Licht, um es besser zu betrachten.", "#me holds an amulet up to the light to have a better look at it.")
talkingNPC:addCycleText("Schmiedewaren! Schöner Schmuck! Kaufste woanders, dann bereustes!", "Smithed goods! Fine Jewelry! Ya buy elsewhere, and ya will regret it!")
tradingNPC:addItem(trade.tradeNPCItem(122,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2140,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(3558,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(3535,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(222,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(3554,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(3526,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(3528,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(79,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(3539,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(3541,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(67,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(3536,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(3538,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(82,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(3559,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(3543,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(71,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(3546,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(3548,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(465,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(225,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(3557,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(3556,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(399,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(92,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(393,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(3553,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(235,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(3555,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(3527,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(3529,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(277,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(3540,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(3560,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(68,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(3537,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(3561,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(278,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(3542,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(3544,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(279,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(3547,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(3545,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(223,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1840,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1001,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1858,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(224,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2647,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(311,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(450,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(447,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(446,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(197,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(46,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(284,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(283,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(45,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(4095,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(4800,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(4793,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(4459,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(4591,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(4517,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(4549,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(4797,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(4790,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(4432,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(4576,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(4493,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(4552,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(4801,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(4794,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(4468,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(4581,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(4509,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(4550,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(4799,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(4792,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(4450,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(4586,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(4501,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(4551,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(3558,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3535,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(222,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3554,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3526,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3528,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(79,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3539,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3541,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(67,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3536,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3538,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(82,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3559,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3543,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(71,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3546,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3548,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(62,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3549,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3551,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(83,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3530,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3532,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(334,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3534,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(465,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(225,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3557,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3556,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(399,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(92,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(393,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(336,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3553,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(235,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3555,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3527,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3529,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(277,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3540,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3560,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(68,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3537,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3561,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(278,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3542,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3544,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(279,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3547,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3545,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(281,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3550,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3552,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(282,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3531,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3533,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(2559,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(280,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(223,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1840,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1001,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1858,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(224,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(2647,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(311,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(450,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(447,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(446,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(449,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(448,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(451,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(452,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(197,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(46,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(284,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(283,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(45,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(198,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(285,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4095,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4800,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4793,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4459,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4591,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4517,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4549,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4797,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4790,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4432,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4576,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4493,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4552,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4801,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4794,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4468,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4581,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4509,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4550,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4799,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4792,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4450,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4586,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4501,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4551,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4601,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4602,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4603,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4604,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4609,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4610,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4611,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4612,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4613,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4614,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4615,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(4616,"buyPrimary"))
tradingNPC:addNotEnoughMoneyMsg("Pleite, wah?", "Are ye broke or something?")
tradingNPC:addDialogClosedMsg("Und tschüss.", "And goodbye.")
tradingNPC:addDialogClosedNoTradeMsg("Arr? Nichts für dich dabeit?", "Arr? Nothing for you in my stock?")
tradingNPC:addWrongItemMsg("Behalt das mal. Ich kaufe das nicht.", "Keep that, I won't buy it.")
mainNPC:addLanguage(0)
mainNPC:addLanguage(2)
mainNPC:setDefaultLanguage(0)
mainNPC:setLookat("Dieser NPC ist Antonius Copperhand der fleißige Goldschmied.", "This NPC is Antonius Copperhand the hardworking goldsmith.")
mainNPC:setUseMessage("Fasst mich nicht an!", "Do not touch me!")
mainNPC:setConfusedMessage("#me schaut verwirrt.", "#me looks around confused.")
mainNPC:setEquipment(1, 0)
mainNPC:setEquipment(3, 182)
mainNPC:setEquipment(11, 195)
mainNPC:setEquipment(5, 23)
mainNPC:setEquipment(6, 8)
mainNPC:setEquipment(4, 48)
mainNPC:setEquipment(9, 34)
mainNPC:setEquipment(10, 53)
mainNPC:setAutoIntroduceMode(true)

mainNPC:initDone()
return mainNPC
end
local mNPC = initNpc()
initNpc = nil
local M = {}
function M.receiveText(npcChar, texttype, message, speaker) mNPC:receiveText(npcChar, texttype, speaker, message) end
function M.nextCycle(npcChar) mNPC:nextCycle(npcChar) end
function M.lookAtNpc(npcChar, char, mode) mNPC:lookAt(npcChar, char, mode) end
function M.useNPC(npcChar, char, counter, param) mNPC:use(npcChar, char) end
return M
