local consequence_item = require("npc.base.consequence.item")
local condition_item = require("npc.base.condition.item")
local consequence_quest = require("npc.base.consequence.quest")
local condition_skill = require("npc.base.condition.skill")
local condition_language = require("npc.base.condition.language")
local consequence_deleteitem = require("npc.base.consequence.deleteitem")
local basic = require("npc.base.basic")
local condition_town = require("npc.base.condition.town")
local talk = require("npc.base.talk")
local consequence_money = require("npc.base.consequence.money")
local condition_quest = require("npc.base.condition.quest")
local consequence_inform = require("npc.base.consequence.inform")
local function initNpc()
local mainNPC = basic()
mainNPC:setAffiliation(2)
local talkingNPC = talk(mainNPC)
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Help")
talkEntry:addConsequence(consequence_inform("[Game Help] This NPC is Daniel Brock the carpenter. Keywords: Hello, Quest, Carpentry."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hilfe")
talkEntry:addConsequence(consequence_inform("[Spielhilfe] Dieser NPC ist Daniel Brock der Schreiner. Schlüsselwörter: Hallo, Quest, Schreinern."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hello")
talkEntry:addTrigger("Greet")
talkEntry:addTrigger("Hail")
talkEntry:addTrigger("Good day")
talkEntry:addTrigger("Good morning")
talkEntry:addTrigger("Good Evening")
talkEntry:addResponse("I am a busy man. What do you need?")
talkEntry:addResponse("I hope you have a good reason to disturb me.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Grüß")
talkEntry:addTrigger("Gruß")
talkEntry:addTrigger("Grüss")
talkEntry:addTrigger("Gruss")
talkEntry:addTrigger("Guten Morgen")
talkEntry:addTrigger("Guten Tag")
talkEntry:addTrigger("Guten Abend")
talkEntry:addTrigger("Gute Nacht")
talkEntry:addTrigger("Mahlzeit")
talkEntry:addTrigger("Tach")
talkEntry:addTrigger("Moin")
talkEntry:addTrigger("Mohltied")
talkEntry:addResponse("Ich ein vielbeschäftiger Mann. Was brauchst du?")
talkEntry:addResponse("Ich hoffe, du hast einen guten Grund, mich zu stören.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Hiho")
talkEntry:addTrigger("Hallo")
talkEntry:addTrigger("Hey")
talkEntry:addTrigger("Greeb")
talkEntry:addResponse("I am a busy man. What do you need?")
talkEntry:addResponse("I hope you have a good reason to disturb me.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hiho")
talkEntry:addTrigger("Hallo")
talkEntry:addTrigger("Hey")
talkEntry:addTrigger("Greeb")
talkEntry:addResponse("Ich ein vielbeschäftiger Mann. Was brauchst du?")
talkEntry:addResponse("Ich hoffe, du hast einen guten Grund, mich zu stören.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Farewell")
talkEntry:addTrigger("Bye")
talkEntry:addTrigger("Fare well")
talkEntry:addTrigger("See you")
talkEntry:addResponse("May I carry on now?")
talkEntry:addResponse("Aye, exactly, see you.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Tschüß")
talkEntry:addTrigger("Tschüss")
talkEntry:addTrigger("Wiedersehen")
talkEntry:addResponse("Darf ich jetzt weiterarbeiten?")
talkEntry:addResponse("Ja, genau, bis dann.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Ciao")
talkEntry:addTrigger("Adieu")
talkEntry:addTrigger("Au revoir")
talkEntry:addTrigger("Farebba")
talkEntry:addResponse("May I carry on now?")
talkEntry:addResponse("Aye, exactly, see you.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Ciao")
talkEntry:addTrigger("Adieu")
talkEntry:addTrigger("Au revoir")
talkEntry:addTrigger("Farebba")
talkEntry:addResponse("Darf ich jetzt weiterarbeiten?")
talkEntry:addResponse("Ja, genau, bis dann.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("How are you")
talkEntry:addTrigger("How feel")
talkEntry:addTrigger("How do you do")
talkEntry:addResponse("That's not important. There is work left to be done.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Wie geht")
talkEntry:addTrigger("Wie fühlst")
talkEntry:addTrigger("Wie ist es ergangen")
talkEntry:addTrigger("Wie Befind")
talkEntry:addResponse("Unwichtig. Es gibt Arbeit zu erledigen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("your name")
talkEntry:addTrigger("who are you")
talkEntry:addTrigger("who art thou")
talkEntry:addResponse("The name is Brock. Daniel Brock.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("ihr name")
talkEntry:addTrigger("dein name")
talkEntry:addTrigger("wer bist du")
talkEntry:addTrigger("wer seid ihr")
talkEntry:addTrigger("wie heißt")
talkEntry:addTrigger("wie heisst")
talkEntry:addResponse("Mein Name ist Brock. Daniel Brock.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("sell")
talkEntry:addTrigger("buy")
talkEntry:addTrigger("wares")
talkEntry:addTrigger("price")
talkEntry:addTrigger("trade")
talkEntry:addTrigger("purchase")
talkEntry:addResponse("I am not a trader.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("kauf")
talkEntry:addTrigger("waren")
talkEntry:addTrigger("preis")
talkEntry:addTrigger("Handel")
talkEntry:addTrigger("veräußer")
talkEntry:addTrigger("veräusser")
talkEntry:addTrigger("erwerb")
talkEntry:addResponse("Ich bin kein Händler.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("profession")
talkEntry:addResponse("I carve and plane. I'm a carpenter. Now I need to carve and plane again.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("beruf")
talkEntry:addResponse("Ich schnitze und hobel. Ich bin ein Schreiner. Und nun muss ich wieder schnitzen und hobeln.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("job")
talkEntry:addResponse("I carve and plane. I'm a carpenter. Now I need to carve and plane again.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("job")
talkEntry:addResponse("Ich schnitze und hobel. Ich bin ein Schreiner. Und nun muss ich wieder schnitzen und hobeln.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("carpent")
talkEntry:addTrigger("craft")
talkEntry:addResponse("As a carpenter, you'll need at least two tools: A plane and carving tools. The plane is used for straight contours while filigree shapes require using carving tools.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Schreiner")
talkEntry:addTrigger("Handwerk")
talkEntry:addResponse("As Schreiner benötigst du wenigstens zwei Werkzeuge: Einen Hobel und Schnitzmesser. Der Hobel wird für gerade Konturen verwendet. Schnitzmesser sind für filigrane Formen unerlässlich.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(713, "=", 0))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_item(74, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 1))
talkEntry:addResponse("The Carpentry Association accepts you as an apprentice. But you'll have to work hard first. Take this hatchet and collect ten logs of apple wood from the apple trees outside the city.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Carpentry Association of Runewick I. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(713, "=", 0))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_item(74, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 1))
talkEntry:addResponse("The Carpentry Association accepts you as an apprentice. But you'll have to work hard first. Take this hatchet and collect ten logs of apple wood from the apple trees outside the city.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Carpentry Association of Runewick I. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(713, "=", 0))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addConsequence(consequence_item(74, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 1))
talkEntry:addResponse("Die Schreinerinnung wird deine Ausbildung übernehmen. Zunächst aber steht harte Arbeit an. Nimm dieses Beil und sammle zehn Apfelholzscheite von den Apfelbäumen außerhalb der Stadt.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Die Schreinerinnung von Runewick I. Detaillierte Informationen findest du im Questlog (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(713, "=", 1))
talkEntry:addCondition(condition_item(2560, "all", ">", 9, nil))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_quest(713, "=", 2))
talkEntry:addResponse("Nice wood. But it takes more to become a real carpenter. Keep the wood for the next part of your apprenticeship.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Ask Daniel Brock for your next task."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(713, "=", 1))
talkEntry:addCondition(condition_item(2560, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("apple")
talkEntry:addTrigger("wood")
talkEntry:addConsequence(consequence_quest(713, "=", 2))
talkEntry:addResponse("Nice wood. But it takes more to become a real carpenter. Keep the wood for the next part of your apprenticeship.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Ask Daniel Brock for your next task."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(713, "=", 1))
talkEntry:addCondition(condition_item(2560, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Apfel")
talkEntry:addTrigger("Holz")
talkEntry:addConsequence(consequence_quest(713, "=", 2))
talkEntry:addResponse("Gutes Holz. Aber es erfordert schon noch etwas mehr, um ein Schreiner zu werden. Behalte das Holz für den nächsten Schritt in deiner Ausbildung.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Frage Daniel Brock nach deiner nächsten Aufgaben."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(713, "=", 1))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("I am very busy and can't nurse you all day long. As your master, I'll repeat my order: Get apple wood.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(713, "=", 1))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("apple")
talkEntry:addTrigger("wood")
talkEntry:addResponse("I am very busy and can't nurse you all day long. As your master, I'll repeat my order: Get apple wood.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(713, "=", 1))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Apfel")
talkEntry:addTrigger("Holz")
talkEntry:addResponse("Ich bin sehr beschäftigt und kann mich nicht den ganzen Tag um dich kümmern. Als dein Meister werde ich meine Anordnung noch einmal wiederholen: Besorge Apfelholz!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(713, "=", 2))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_item(9, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 3))
talkEntry:addResponse("Boards. Boards that mean the world. Make ten of them from the apple wood you brought me. Here is a rusty saw, don't get rusty yourself.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Carpentry Association of Runewick II. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(713, "=", 2))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_item(9, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 3))
talkEntry:addResponse("Boards. Boards that mean the world. Make ten of them from the apple wood you brought me. Here is a rusty saw, don't get rusty yourself.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Carpentry Association of Runewick II. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(713, "=", 2))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addConsequence(consequence_item(9, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 3))
talkEntry:addResponse("Bretter. Bretter, die die Welt bedeuten. Mache bitte zehn aus dem Apfelholz, welches du mir gebracht hast. Hier ist eine rostige Säge. Nicht rasten, sonst rostest du.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Die Schreinerinnung von Runewick II. Detaillierte Informationen findest du im Questlog (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(713, "=", 3))
talkEntry:addCondition(condition_item(2716, "all", ">", 9, nil))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_quest(713, "=", 4))
talkEntry:addResponse("You are able to make boards, fine. You'll need them for the next part of your apprenticeship.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Ask Daniel Brock for your next task."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(713, "=", 3))
talkEntry:addCondition(condition_item(2716, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("apple")
talkEntry:addTrigger("board")
talkEntry:addConsequence(consequence_quest(713, "=", 4))
talkEntry:addResponse("You are able to make boards, fine. You'll need them for the next part of your apprenticeship.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Ask Daniel Brock for your next task."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(713, "=", 3))
talkEntry:addCondition(condition_item(2716, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Apfel")
talkEntry:addTrigger("Brett")
talkEntry:addConsequence(consequence_quest(713, "=", 4))
talkEntry:addResponse("Du bist in der Lage, Bretter herzustellen. Wunderbar, du wirst sie für den nächsten Teil deiner Ausbildung benötigen.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Frage Daniel Brock nach deiner nächsten Aufgaben."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(713, "=", 3))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Sawing ten apple boards is your task. Without apple boards, we cannot continue your apprenticeship.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(713, "=", 3))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("apple")
talkEntry:addTrigger("board")
talkEntry:addResponse("Sawing ten apple boards is your task. Without apple boards, we cannot continue your apprenticeship.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(713, "=", 3))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Apfel")
talkEntry:addTrigger("Brett")
talkEntry:addResponse("Zehn Apfelholzbretter zu sägen ist deine Aufgabe. Ohne Apfelholzbretter können wir deine Ausbildung nicht fortsetzen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(713, "=", 4))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_item(2752, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 5))
talkEntry:addResponse("Now the real work begins. Carving. I'll give you some old carving tools and you bring back ten axe handles. I do not want to see you leaving the work bench before you are done.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Carpentry Association of Runewick III. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(713, "=", 4))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_item(2752, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 5))
talkEntry:addResponse("Now the real work begins. Carving. I'll give you some old carving tools and you bring back ten axe handles. I do not want to see you leaving the work bench before you are done.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Carpentry Association of Runewick III. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(713, "=", 4))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addConsequence(consequence_item(2752, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 5))
talkEntry:addResponse("Jetzt wird es anstrengend. Schnitzen. Ich gebe dir ein paar alte Schnitzmesser und du bringst mir zehn Axtgriffe zurück. Und verlasse ja nicht die Werkbank, bis du fertig damit bist.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Die Schreinerinnung von Runewick III. Detaillierte Informationen findest du im Questlog (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(713, "=", 5))
talkEntry:addCondition(condition_item(2525, "all", ">", 9, nil))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Layman with the Carpentry Association of Runewick. You are awarded twenty silver coins."))
talkEntry:addConsequence(consequence_deleteitem(2525, 10, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 6))
talkEntry:addConsequence(consequence_money("+", 2000))
talkEntry:addResponse("The Carpentry Association of Runewick accepts you as new member. Here is some money to get you started. I recommend you buy a plane from it. And come back once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(713, "=", 5))
talkEntry:addCondition(condition_item(2525, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("axe")
talkEntry:addTrigger("handle")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Layman with the Carpentry Association of Runewick. You are awarded twenty silver coins."))
talkEntry:addConsequence(consequence_deleteitem(2525, 10, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 6))
talkEntry:addConsequence(consequence_money("+", 2000))
talkEntry:addResponse("The Carpentry Association of Runewick accepts you as new member. Here is some money to get you started. I recommend you buy a plane from it. And come back once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(713, "=", 5))
talkEntry:addCondition(condition_item(2525, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Axt")
talkEntry:addTrigger("Griff")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Schreinerinnung von Runewick erhebt dich in den Rang eines Laiens. Du erhältst zwanzig Silberstücke."))
talkEntry:addConsequence(consequence_deleteitem(2525, 10, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 6))
talkEntry:addConsequence(consequence_money("+", 2000))
talkEntry:addResponse("Die Schreinerinnung von Runewick nimmt dich als neues Mitglied auf. Hier ist etwas monetäre Starthilfe. Mein Vorschlag wäre, dass du davon einen Hobel kaufst. Und komm zu mir zurück, sobald du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(713, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Please do not waste my time. Use yours to carve ten axe handles.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(713, "=", 5))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("axe")
talkEntry:addTrigger("handle")
talkEntry:addResponse("Please do not waste my time. Use yours to carve ten axe handles.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(713, "=", 5))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Axt")
talkEntry:addTrigger("Griff")
talkEntry:addResponse("Verschwende nicht meine Zeit sondern nutze deine, um zehn Axtgriffe zu schnitzen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, ">", 9))
talkEntry:addCondition(condition_quest(713, "=", 6))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Novice with the Carpentry Association of Runewick. You are awarded ten logs of conifer wood."))
talkEntry:addConsequence(consequence_item(3, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 7))
talkEntry:addResponse("Good job. I see you really worked hard. The Carpentry Association of Runewick supports your efforts with some conifer wood. Come back to me once your are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, ">", 9))
talkEntry:addCondition(condition_quest(713, "=", 6))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Novice with the Carpentry Association of Runewick. You are awarded ten logs of conifer wood."))
talkEntry:addConsequence(consequence_item(3, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 7))
talkEntry:addResponse("Good job. I see you really worked hard. The Carpentry Association of Runewick supports your efforts with some conifer wood. Come back to me once your are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, ">", 9))
talkEntry:addCondition(condition_quest(713, "=", 6))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Schreinerinnung von Runewick erhebt dich in den Rang eines Anfängers. Du erhältst zehn Scheite Nadelholz."))
talkEntry:addConsequence(consequence_item(3, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 7))
talkEntry:addResponse("Gut gemacht. Wie ich sehe, hast du hart gearbeitet. Die Schreinerinnung von Runewick unterstützt deine Bemühungen mit etwas Nadelholz. Komm erneut zu mir, wenn du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, "<", 10))
talkEntry:addCondition(condition_quest(713, "=", 6))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Work on! You have to improve your skills in carpentry to be eligible for a promotion. Your current rank is Layman.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 10 in carpentry to advance in the ranks of the Carpentry Association of Runewick."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, "<", 10))
talkEntry:addCondition(condition_quest(713, "=", 6))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Work on! You have to improve your skills in carpentry to be eligible for a promotion. Your current rank is Layman.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 10 in carpentry to advance in the ranks of the Carpentry Association of Runewick."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, "<", 10))
talkEntry:addCondition(condition_quest(713, "=", 6))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Weiterarbeiten! Du musst dein Können im Schreinerhandwerk verbessern, um befördert zu werden. Du wirst im Rang eines Laiens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 10 in Schreinern um in der Schreinerinnung von Runewick aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, ">", 19))
talkEntry:addCondition(condition_quest(713, "=", 7))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Apprentice with the Carpentry Association of Runewick. You are awarded twenty logs of cherry wood."))
talkEntry:addConsequence(consequence_item(543, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 8))
talkEntry:addResponse("Good job. I see you really worked hard. The Carpentry Association of Runewick supports your efforts with some cherry wood. Come back to me once your are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, ">", 19))
talkEntry:addCondition(condition_quest(713, "=", 7))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Apprentice with the Carpentry Association of Runewick. You are awarded twenty logs of cherry wood."))
talkEntry:addConsequence(consequence_item(543, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 8))
talkEntry:addResponse("Good job. I see you really worked hard. The Carpentry Association of Runewick supports your efforts with some cherry wood. Come back to me once your are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, ">", 19))
talkEntry:addCondition(condition_quest(713, "=", 7))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Schreinerinnung von Runewick erhebt dich in den Rang eines Lehrlings. Du erhältst zwanzig Scheite Kirschholz."))
talkEntry:addConsequence(consequence_item(543, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 8))
talkEntry:addResponse("Gut gemacht. Wie ich sehe, hast du hart gearbeitet. Die Schreinerinnung von Runewick unterstützt deine Bemühungen mit etwas Kirschholz. Komm erneut zu mir, wenn du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, "<", 20))
talkEntry:addCondition(condition_quest(713, "=", 7))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Work on! You have to improve your skills in carpentry to be eligible for a promotion. Your current rank is Novice.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 20 in carpentry to advance in the ranks of the Carpentry Association of Runewick."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, "<", 20))
talkEntry:addCondition(condition_quest(713, "=", 7))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Work on! You have to improve your skills in carpentry to be eligible for a promotion. Your current rank is Novice.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 20 in carpentry to advance in the ranks of the Carpentry Association of Runewick."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, "<", 20))
talkEntry:addCondition(condition_quest(713, "=", 7))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Weiterarbeiten! Du musst dein Können im Schreinerhandwerk verbessern, um befördert zu werden. Du wirst im Rang eines Anfängers geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 20 in Schreinern um in der Schreinerinnung von Runewick aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, ">", 29))
talkEntry:addCondition(condition_quest(713, "=", 8))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Initiate with the Carpentry Association of Runewick. You are awarded ten naldor wood boards."))
talkEntry:addConsequence(consequence_item(546, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 9))
talkEntry:addResponse("Good job. I see you really worked hard. The Carpentry Association of Runewick supports your efforts with some naldor wood boards. Come back to me once your are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, ">", 29))
talkEntry:addCondition(condition_quest(713, "=", 8))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Initiate with the Carpentry Association of Runewick. You are awarded ten naldor wood boards."))
talkEntry:addConsequence(consequence_item(546, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 9))
talkEntry:addResponse("Good job. I see you really worked hard. The Carpentry Association of Runewick supports your efforts with some naldor wood boards. Come back to me once your are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, ">", 29))
talkEntry:addCondition(condition_quest(713, "=", 8))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Schreinerinnung von Runewick erhebt dich in den Rang eines Initiatens. Du erhältst zehn Naldorholzbretter."))
talkEntry:addConsequence(consequence_item(546, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 9))
talkEntry:addResponse("Gut gemacht. Wie ich sehe, hast du hart gearbeitet. Die Schreinerinnung von Runewick unterstützt deine Bemühungen mit einigen Naldorholzbrettern. Komm erneut zu mir, wenn du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, "<", 30))
talkEntry:addCondition(condition_quest(713, "=", 8))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Work on! You have to improve your skills in carpentry to be eligible for a promotion. Your current rank is Apprentice.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 30 in carpentry to advance in the ranks of the Carpentry Association of Runewick."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, "<", 30))
talkEntry:addCondition(condition_quest(713, "=", 8))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Work on! You have to improve your skills in carpentry to be eligible for a promotion. Your current rank is Apprentice.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 30 in carpentry to advance in the ranks of the Carpentry Association of Runewick."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, "<", 30))
talkEntry:addCondition(condition_quest(713, "=", 8))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Weiterarbeiten! Du musst dein Können im Schreinerhandwerk verbessern, um befördert zu werden. Du wirst im Rang eines Lehrlings geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 30 in Schreinern um in der Schreinerinnung von Runewick aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, ">", 39))
talkEntry:addCondition(condition_quest(713, "=", 9))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Journeyman with the Carpentry Association of Runewick. You are awarded twenty apple wood boards and a journeyman's certificate."))
talkEntry:addConsequence(consequence_item(2716, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 10))
talkEntry:addResponse("Good job. I see you really worked hard. The Carpentry Association of Runewick supports your efforts with some apple wood boards. Come back to me once your are more experienced.")
talkEntry:addConsequence(consequence_item(3109, 1, 333, {["descriptionEn"] = "The owner of this certificate has successfully passed the examination as Journeyman. Daniel Brock - Carpentry Association of Runewick", ["descriptionDe"] = "Der Inhaber dieses Gesellenbriefes hat erfolgreich das Examen zum Gesellen bestanden. Daniel Brock - Schreinerinnung von Runewick", ["nameDe"] = "Gesellenbrief", ["nameEn"] = "Journeyman's Certificate", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, ">", 39))
talkEntry:addCondition(condition_quest(713, "=", 9))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Journeyman with the Carpentry Association of Runewick. You are awarded twenty apple wood boards and a journeyman's certificate."))
talkEntry:addConsequence(consequence_item(2716, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 10))
talkEntry:addResponse("Good job. I see you really worked hard. The Carpentry Association of Runewick supports your efforts with some apple wood boards. Come back to me once your are more experienced.")
talkEntry:addConsequence(consequence_item(3109, 1, 333, {["descriptionEn"] = "The owner of this certificate has successfully passed the examination as Journeyman. Daniel Brock - Carpentry Association of Runewick", ["descriptionDe"] = "Der Inhaber dieses Gesellenbriefes hat erfolgreich das Examen zum Gesellen bestanden. Daniel Brock - Schreinerinnung von Runewick", ["nameDe"] = "Gesellenbrief", ["nameEn"] = "Journeyman's Certificate", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, ">", 39))
talkEntry:addCondition(condition_quest(713, "=", 9))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Schreinerinnung von Runewick erhebt dich in den Rang eines Gesellens. Du erhältst zwanzig Apfelholzbretter und einen Gesellenbrief."))
talkEntry:addConsequence(consequence_item(2716, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 10))
talkEntry:addResponse("Gut gemacht. Wie ich sehe, hast du hart gearbeitet. Die Schreinerinnung von Runewick unterstützt deine Bemühungen mit einigen Apfelholzbrettern. Komm erneut zu mir, wenn du erfahrener bist.")
talkEntry:addConsequence(consequence_item(3109, 1, 333, {["descriptionEn"] = "The owner of this certificate has successfully passed the examination as Journeyman. Daniel Brock - Carpentry Association of Runewick", ["descriptionDe"] = "Der Inhaber dieses Gesellenbriefes hat erfolgreich das Examen zum Gesellen bestanden. Daniel Brock - Schreinerinnung von Runewick", ["nameDe"] = "Gesellenbrief", ["nameEn"] = "Journeyman's Certificate", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, "<", 40))
talkEntry:addCondition(condition_quest(713, "=", 9))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Work on! You have to improve your skills in carpentry to be eligible for a promotion. Your current rank is Initiate.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 40 in carpentry to advance in the ranks of the Carpentry Association of Runewick."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, "<", 40))
talkEntry:addCondition(condition_quest(713, "=", 9))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Work on! You have to improve your skills in carpentry to be eligible for a promotion. Your current rank is Initiate.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 40 in carpentry to advance in the ranks of the Carpentry Association of Runewick."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, "<", 40))
talkEntry:addCondition(condition_quest(713, "=", 9))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Weiterarbeiten! Du musst dein Können im Schreinerhandwerk verbessern, um befördert zu werden. Du wirst im Rang eines Initiatens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 40 in Schreinern um in der Schreinerinnung von Runewick aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, ">", 49))
talkEntry:addCondition(condition_quest(713, "=", 10))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Specialist with the Carpentry Association of Runewick. You are awarded ten iron ingots."))
talkEntry:addConsequence(consequence_item(2535, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 11))
talkEntry:addResponse("Good job. I see you really worked hard. The Carpentry Association of Runewick supports your efforts with some iron ingots. Come back to me once your are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, ">", 49))
talkEntry:addCondition(condition_quest(713, "=", 10))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Specialist with the Carpentry Association of Runewick. You are awarded ten iron ingots."))
talkEntry:addConsequence(consequence_item(2535, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 11))
talkEntry:addResponse("Good job. I see you really worked hard. The Carpentry Association of Runewick supports your efforts with some iron ingots. Come back to me once your are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, ">", 49))
talkEntry:addCondition(condition_quest(713, "=", 10))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Schreinerinnung von Runewick erhebt dich in den Rang eines Spezialistens. Du erhältst zehn Eisenbarren."))
talkEntry:addConsequence(consequence_item(2535, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 11))
talkEntry:addResponse("Gut gemacht. Wie ich sehe, hast du hart gearbeitet. Die Schreinerinnung von Runewick unterstützt deine Bemühungen mit einigen Eisenbarren. Komm erneut zu mir, wenn du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, "<", 50))
talkEntry:addCondition(condition_quest(713, "=", 10))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Work on! You have to improve your skills in carpentry to be eligible for a promotion. Your current rank is Journeyman.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 50 in carpentry to advance in the ranks of the Carpentry Association of Runewick."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, "<", 50))
talkEntry:addCondition(condition_quest(713, "=", 10))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Work on! You have to improve your skills in carpentry to be eligible for a promotion. Your current rank is Journeyman.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 50 in carpentry to advance in the ranks of the Carpentry Association of Runewick."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, "<", 50))
talkEntry:addCondition(condition_quest(713, "=", 10))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Weiterarbeiten! Du musst dein Können im Schreinerhandwerk verbessern, um befördert zu werden. Du wirst im Rang eines Gesellens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 50 in Schreinern um in der Schreinerinnung von Runewick aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, ">", 59))
talkEntry:addCondition(condition_quest(713, "=", 11))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Expert with the Carpentry Association of Runewick. You are awarded twenty iron plates."))
talkEntry:addConsequence(consequence_item(2537, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 12))
talkEntry:addResponse("Good job. I see you really worked hard. The Carpentry Association of Runewick supports your efforts with some iron plates. Come back to me once your are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, ">", 59))
talkEntry:addCondition(condition_quest(713, "=", 11))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Expert with the Carpentry Association of Runewick. You are awarded twenty iron plates."))
talkEntry:addConsequence(consequence_item(2537, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 12))
talkEntry:addResponse("Good job. I see you really worked hard. The Carpentry Association of Runewick supports your efforts with some iron plates. Come back to me once your are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, ">", 59))
talkEntry:addCondition(condition_quest(713, "=", 11))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Schreinerinnung von Runewick erhebt dich in den Rang eines Expertens. Du erhältst zwanzig Eisenplatten."))
talkEntry:addConsequence(consequence_item(2537, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 12))
talkEntry:addResponse("Gut gemacht. Wie ich sehe, hast du hart gearbeitet. Die Schreinerinnung von Runewick unterstützt deine Bemühungen mit einigen Eisenplatten. Komm erneut zu mir, wenn du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, "<", 60))
talkEntry:addCondition(condition_quest(713, "=", 11))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Work on! You have to improve your skills in carpentry to be eligible for a promotion. Your current rank is Specialist.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 60 in carpentry to advance in the ranks of the Carpentry Association of Runewick."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, "<", 60))
talkEntry:addCondition(condition_quest(713, "=", 11))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Work on! You have to improve your skills in carpentry to be eligible for a promotion. Your current rank is Specialist.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 60 in carpentry to advance in the ranks of the Carpentry Association of Runewick."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, "<", 60))
talkEntry:addCondition(condition_quest(713, "=", 11))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Weiterarbeiten! Du musst dein Können im Schreinerhandwerk verbessern, um befördert zu werden. Du wirst im Rang eines Spezialistens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 60 in Schreinern um in der Schreinerinnung von Runewick aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, ">", 69))
talkEntry:addCondition(condition_quest(713, "=", 12))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Adept with the Carpentry Association of Runewick. You are awarded five merinium ingots."))
talkEntry:addConsequence(consequence_item(2571, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 13))
talkEntry:addResponse("Good job. I see you really worked hard. The Carpentry Association of Runewick supports your efforts with some merinium ingots. Come back to me once your are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, ">", 69))
talkEntry:addCondition(condition_quest(713, "=", 12))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Adept with the Carpentry Association of Runewick. You are awarded five merinium ingots."))
talkEntry:addConsequence(consequence_item(2571, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 13))
talkEntry:addResponse("Good job. I see you really worked hard. The Carpentry Association of Runewick supports your efforts with some merinium ingots. Come back to me once your are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, ">", 69))
talkEntry:addCondition(condition_quest(713, "=", 12))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Schreinerinnung von Runewick erhebt dich in den Rang eines Adeptens. Du erhältst fünf Meriniumbarren."))
talkEntry:addConsequence(consequence_item(2571, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 13))
talkEntry:addResponse("Gut gemacht. Wie ich sehe, hast du hart gearbeitet. Die Schreinerinnung von Runewick unterstützt deine Bemühungen mit einigen Meriniumbarren. Komm erneut zu mir, wenn du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, "<", 70))
talkEntry:addCondition(condition_quest(713, "=", 12))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Work on! You have to improve your skills in carpentry to be eligible for a promotion. Your current rank is Expert.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 70 in carpentry to advance in the ranks of the Carpentry Association of Runewick."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, "<", 70))
talkEntry:addCondition(condition_quest(713, "=", 12))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Work on! You have to improve your skills in carpentry to be eligible for a promotion. Your current rank is Expert.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 70 in carpentry to advance in the ranks of the Carpentry Association of Runewick."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, "<", 70))
talkEntry:addCondition(condition_quest(713, "=", 12))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Weiterarbeiten! Du musst dein Können im Schreinerhandwerk verbessern, um befördert zu werden. Du wirst im Rang eines Expertens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 70 in Schreinern um in der Schreinerinnung von Runewick aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, ">", 79))
talkEntry:addCondition(condition_quest(713, "=", 13))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Artisan with the Carpentry Association of Runewick. You are awarded ten logs of heartwood."))
talkEntry:addConsequence(consequence_item(3786, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 14))
talkEntry:addResponse("Good job. I see you really worked hard. The Carpentry Association of Runewick supports your efforts with some logs of heartwood. Come back to me once your are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, ">", 79))
talkEntry:addCondition(condition_quest(713, "=", 13))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Artisan with the Carpentry Association of Runewick. You are awarded ten logs of heartwood."))
talkEntry:addConsequence(consequence_item(3786, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 14))
talkEntry:addResponse("Good job. I see you really worked hard. The Carpentry Association of Runewick supports your efforts with some logs of heartwood. Come back to me once your are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, ">", 79))
talkEntry:addCondition(condition_quest(713, "=", 13))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Schreinerinnung von Runewick erhebt dich in den Rang eines Artisanens. Du erhältst zehn Scheite Kernholz."))
talkEntry:addConsequence(consequence_item(3786, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 14))
talkEntry:addResponse("Gut gemacht. Wie ich sehe, hast du hart gearbeitet. Die Schreinerinnung von Runewick unterstützt deine Bemühungen mit etwas Kernholz. Komm erneut zu mir, wenn du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, "<", 80))
talkEntry:addCondition(condition_quest(713, "=", 13))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Work on! You have to improve your skills in carpentry to be eligible for a promotion. Your current rank is Adept.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 80 in carpentry to advance in the ranks of the Carpentry Association of Runewick."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, "<", 80))
talkEntry:addCondition(condition_quest(713, "=", 13))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Work on! You have to improve your skills in carpentry to be eligible for a promotion. Your current rank is Adept.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 80 in carpentry to advance in the ranks of the Carpentry Association of Runewick."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, "<", 80))
talkEntry:addCondition(condition_quest(713, "=", 13))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Weiterarbeiten! Du musst dein Können im Schreinerhandwerk verbessern, um befördert zu werden. Du wirst im Rang eines Adeptens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 80 in Schreinern um in der Schreinerinnung von Runewick aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, ">", 89))
talkEntry:addCondition(condition_quest(713, "=", 14))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Master with the Carpentry Association of Runewick. You are awarded five pieces of pure earth and a special tool."))
talkEntry:addConsequence(consequence_item(2552, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 15))
talkEntry:addResponse("Good job. I see you really worked hard. The Carpentry Association of Runewick supports your efforts with some pure earth. Come back to me once your are more experienced.")
talkEntry:addConsequence(consequence_item(2752, 1, 999, {["descriptionEn"] = "Master of the Carpentry Association of Runewick", ["descriptionDe"] = "Meister der Schreinerinnung von Runewick", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, ">", 89))
talkEntry:addCondition(condition_quest(713, "=", 14))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Master with the Carpentry Association of Runewick. You are awarded five pieces of pure earth and a special tool."))
talkEntry:addConsequence(consequence_item(2552, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 15))
talkEntry:addResponse("Good job. I see you really worked hard. The Carpentry Association of Runewick supports your efforts with some pure earth. Come back to me once your are more experienced.")
talkEntry:addConsequence(consequence_item(2752, 1, 999, {["descriptionEn"] = "Master of the Carpentry Association of Runewick", ["descriptionDe"] = "Meister der Schreinerinnung von Runewick", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, ">", 89))
talkEntry:addCondition(condition_quest(713, "=", 14))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Schreinerinnung von Runewick erhebt dich in den Rang eines Meisters. Du erhältst fünf Stück reiner Erde und ein besonderes Werkzeug."))
talkEntry:addConsequence(consequence_item(2552, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 15))
talkEntry:addResponse("Gut gemacht. Wie ich sehe, hast du hart gearbeitet. Die Schreinerinnung von Runewick unterstützt deine Bemühungen mit etwas reiner Erde. Komm erneut zu mir, wenn du erfahrener bist.")
talkEntry:addConsequence(consequence_item(2752, 1, 999, {["descriptionEn"] = "Master of the Carpentry Association of Runewick", ["descriptionDe"] = "Meister der Schreinerinnung von Runewick", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, "<", 90))
talkEntry:addCondition(condition_quest(713, "=", 14))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Work on! You have to improve your skills in carpentry to be eligible for a promotion. Your current rank is Artisan.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 90 in carpentry to advance in the ranks of the Carpentry Association of Runewick."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, "<", 90))
talkEntry:addCondition(condition_quest(713, "=", 14))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Work on! You have to improve your skills in carpentry to be eligible for a promotion. Your current rank is Artisan.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 90 in carpentry to advance in the ranks of the Carpentry Association of Runewick."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, "<", 90))
talkEntry:addCondition(condition_quest(713, "=", 14))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Weiterarbeiten! Du musst dein Können im Schreinerhandwerk verbessern, um befördert zu werden. Du wirst im Rang eines Artisanens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 90 in Schreinern um in der Schreinerinnung von Runewick aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, ">", 99))
talkEntry:addCondition(condition_quest(713, "=", 15))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Grandmaster with the Carpentry Association of Runewick. You are awarded ten pieces of pure air and a grandmaster's medal."))
talkEntry:addConsequence(consequence_item(2551, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 16))
talkEntry:addResponse("Was about time. I bow to a new Grandmaster of the Carpentry Association of Runewick. With this pure air, you shall help carve the most valuable goods of Illarion.")
talkEntry:addConsequence(consequence_item(3535, 1, 999, {["descriptionEn"] = "Grandmaster of the Carpentry Association of Runewick", ["descriptionDe"] = "Großmeister der Schreinerinnung von Runewick", ["nameDe"] = "Großmeistermedallie", ["nameEn"] = "Grandmaster's Medal", ["rareness"] = "2"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, ">", 99))
talkEntry:addCondition(condition_quest(713, "=", 15))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Grandmaster with the Carpentry Association of Runewick. You are awarded ten pieces of pure air and a grandmaster's medal."))
talkEntry:addConsequence(consequence_item(2551, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 16))
talkEntry:addResponse("Was about time. I bow to a new Grandmaster of the Carpentry Association of Runewick. With this pure air, you shall help carve the most valuable goods of Illarion.")
talkEntry:addConsequence(consequence_item(3535, 1, 999, {["descriptionEn"] = "Grandmaster of the Carpentry Association of Runewick", ["descriptionDe"] = "Großmeister der Schreinerinnung von Runewick", ["nameDe"] = "Großmeistermedallie", ["nameEn"] = "Grandmaster's Medal", ["rareness"] = "2"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, ">", 99))
talkEntry:addCondition(condition_quest(713, "=", 15))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Schreinerinnung von Runewick erhebt dich in den Rang eines Großmeisters. Du erhältst zehn Stück reiner Luft und eine Großmeistermedallie."))
talkEntry:addConsequence(consequence_item(2551, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(713, "=", 16))
talkEntry:addResponse("Wurd ja auch mal Zeit. Ich verneige mich vor einem neuen Großmeister der Schreinerinnung von Runewick. Mit dieser reinen Luft wirst du die teuersten Waren Illarions herstellen.")
talkEntry:addConsequence(consequence_item(3535, 1, 999, {["descriptionEn"] = "Grandmaster of the Carpentry Association of Runewick", ["descriptionDe"] = "Großmeister der Schreinerinnung von Runewick", ["nameDe"] = "Großmeistermedallie", ["nameEn"] = "Grandmaster's Medal", ["rareness"] = "2"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, "<", 100))
talkEntry:addCondition(condition_quest(713, "=", 15))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Work on! You have to improve your skills in carpentry to be eligible for a promotion. Your current rank is Master.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 100 in carpentry to advance in the ranks of the Carpentry Association of Runewick."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, "<", 100))
talkEntry:addCondition(condition_quest(713, "=", 15))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Work on! You have to improve your skills in carpentry to be eligible for a promotion. Your current rank is Master.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 100 in carpentry to advance in the ranks of the Carpentry Association of Runewick."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.carpentry, "<", 100))
talkEntry:addCondition(condition_quest(713, "=", 15))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Weiterarbeiten! Du musst dein Können im Schreinerhandwerk verbessern, um befördert zu werden. Du wirst im Rang eines Meisters geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 100 in Schreinern um in der Schreinerinnung von Runewick aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(713, "=", 16))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("One day, you will tell your grandchildren about you apprenticeship with the Carpentry Association of Runewick, Grandmaster %CHARNAME.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(713, "=", 16))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addResponse("One day, you will tell your grandchildren about you apprenticeship with the Carpentry Association of Runewick, Grandmaster %CHARNAME.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(713, "=", 16))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addResponse("Du wirst noch deinen Enkeln von deiner Lehre bei der Schreinerinnung von Runewick erzählen, Großmeister %CHARNAME.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("The Carpentry Association is restricted to Runewick's citizens.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addResponse("The Carpentry Association is restricted to Runewick's citizens.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addResponse("Die Schreinerinnung steht nur Bürgern Runewicks offen.")
talkingNPC:addTalkingEntry(talkEntry)
end
talkingNPC:addCycleText("#me kratzt sich am Kopf.", "#me scratches his head.")
talkingNPC:addCycleText("#me schaut sich kurz um und kratzt sich anschließend an seinem Hintern.", "#me looks around briefly and scratches his bum.")
talkingNPC:addCycleText("#me schnitzt eine Holzfigur mit einem kleinen Messer.", "#me carves a figurine in wood with a small knife.")
talkingNPC:addCycleText("#me hat Sägespäne auf seinem Hemd.", "#me has sawdust on his shirt.")
talkingNPC:addCycleText("#me hat eine abgenutzte Axt in seinem Gürtel.", "#me has a worn hatchet hanging from his belt.")
talkingNPC:addCycleText("#me hobelt sorgfältig an einem Stück Holz.", "#me carefully planes a piece of lumber.")
talkingNPC:addCycleText("Es gibt keine bessere Arbeit als mit Holz.", "There is no finer work than woodwork.")
talkingNPC:addCycleText("Die Schreinerinnung sucht stets neue Lehrlinge.", "The Carpentry Association looks for new apprentices.")
talkingNPC:addCycleText("Holz sieht sehr schön aus, Holz ist vielseitig.", "Wood looks great, wood is versatile.")
mainNPC:addLanguage(0)
mainNPC:addLanguage(1)
mainNPC:setDefaultLanguage(0)
mainNPC:setLookat("Dieser NPC ist Daniel Brock der Schreiner.", "This NPC is Daniel Brock the carpenter.")
mainNPC:setUseMessage("Fass mich nicht an!", "Hands off!")
mainNPC:setConfusedMessage("#me schaut dich verwirrt an.", "#me looks at you confused.")
mainNPC:setEquipment(1, 831)
mainNPC:setEquipment(3, 814)
mainNPC:setEquipment(11, 0)
mainNPC:setEquipment(5, 0)
mainNPC:setEquipment(6, 0)
mainNPC:setEquipment(4, 0)
mainNPC:setEquipment(9, 827)
mainNPC:setEquipment(10, 53)
mainNPC:setAutoIntroduceMode(true)

mainNPC:initDone()
return mainNPC
end
local mNPC = initNpc()
initNpc = nil
local M = {}
function M.receiveText(npcChar, texttype, message, speaker) mNPC:receiveText(npcChar, texttype, speaker, message) end
function M.nextCycle(npcChar) mNPC:nextCycle(npcChar) end
function M.lookAtNpc(npcChar, char, mode) mNPC:lookAt(npcChar, char, mode) end
function M.useNPC(npcChar, char, counter, param) mNPC:use(npcChar, char) end
return M
