local consequence_item = require("npc.base.consequence.item")
local consequence_quest = require("npc.base.consequence.quest")
local condition_language = require("npc.base.condition.language")
local basic = require("npc.base.basic")
local condition_chance = require("npc.base.condition.chance")
local talk = require("npc.base.talk")
local condition_quest = require("npc.base.condition.quest")
local consequence_inform = require("npc.base.consequence.inform")
local function initNpc()
local mainNPC = basic()
mainNPC:setAffiliation(1)
local talkingNPC = talk(mainNPC)
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Help")
talkEntry:addConsequence(consequence_inform("[Game Help] This NPC is named Egon. There is not much to be learnt from that half-smart ratman."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hilfe")
talkEntry:addConsequence(consequence_inform("[Spielhilfe] Dieser NPC heißt Egon. Von diesem halbklugen Rattenmenschen ist nur wenig zu erfahren."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(5.0))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addResponse("#me squeaks loudly and takes two herbs from the chest, which he then pushes into the person's hands standing in front of him.")
talkEntry:addConsequence(consequence_inform("[Quest solved] You got your reward. You were handed the following plants: night angels blossom, night angels blossom"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(5.0))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addResponse("#me quiekt laut und holt zwei Kräuter aus der Kiste, die er der Person vor sich in die Hand drückt.")
talkEntry:addConsequence(consequence_inform("[Quest gelöst] Du hast deine Belohnung abgeholt. Folgende Pflanzen hast du erhalten: Nachtengelsblüte, Nachtengelsblüte"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(5.5555555555556))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addResponse("#me squeaks loudly and takes two herbs from the chest, which he then pushes into the person's hands standing in front of him.")
talkEntry:addConsequence(consequence_inform("[Quest solved] You got your reward. You were handed the following plants: night angels blossom, desert sky capsule"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(5.5555555555556))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addResponse("#me quiekt laut und holt zwei Kräuter aus der Kiste, die er der Person vor sich in die Hand drückt.")
talkEntry:addConsequence(consequence_inform("[Quest gelöst] Du hast deine Belohnung abgeholt. Folgende Pflanzen hast du erhalten: Nachtengelsblüte, Wüstenhimmelskapsel"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(6.25))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addResponse("#me squeaks loudly and takes two herbs from the chest, which he then pushes into the person's hands standing in front of him.")
talkEntry:addConsequence(consequence_inform("[Quest solved] You got your reward. You were handed the following plants: night angels blossom, dark moss"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(6.25))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addResponse("#me quiekt laut und holt zwei Kräuter aus der Kiste, die er der Person vor sich in die Hand drückt.")
talkEntry:addConsequence(consequence_inform("[Quest gelöst] Du hast deine Belohnung abgeholt. Folgende Pflanzen hast du erhalten: Nachtengelsblüte, Dunkelmoos"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(7.1428571428571))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addResponse("#me squeaks loudly and takes two herbs from the chest, which he then pushes into the person's hands standing in front of him.")
talkEntry:addConsequence(consequence_inform("[Quest solved] You got your reward. You were handed the following plants: night angels blossom, desert berry"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(7.1428571428571))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addResponse("#me quiekt laut und holt zwei Kräuter aus der Kiste, die er der Person vor sich in die Hand drückt.")
talkEntry:addConsequence(consequence_inform("[Quest gelöst] Du hast deine Belohnung abgeholt. Folgende Pflanzen hast du erhalten: Nachtengelsblüte, Wüstenbeere"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(8.3333333333333))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addResponse("#me squeaks loudly and takes two herbs from the chest, which he then pushes into the person's hands standing in front of him.")
talkEntry:addConsequence(consequence_inform("[Quest solved] You got your reward. You were handed the following plants: desert sky capsule, desert sky capsule"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(8.3333333333333))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addResponse("#me quiekt laut und holt zwei Kräuter aus der Kiste, die er der Person vor sich in die Hand drückt.")
talkEntry:addConsequence(consequence_inform("[Quest gelöst] Du hast deine Belohnung abgeholt. Folgende Pflanzen hast du erhalten: Wüstenhimmelskapsel, Wüstenhimmelskapsel"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(10.0))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addResponse("#me squeaks loudly and takes two herbs from the chest, which he then pushes into the person's hands standing in front of him.")
talkEntry:addConsequence(consequence_inform("[Quest solved] You got your reward. You were handed the following plants: desert sky capsule, dark moss"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(10.0))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addResponse("#me quiekt laut und holt zwei Kräuter aus der Kiste, die er der Person vor sich in die Hand drückt.")
talkEntry:addConsequence(consequence_inform("[Quest gelöst] Du hast deine Belohnung abgeholt. Folgende Pflanzen hast du erhalten: Wüstenhimmelskapsel, Dunkelmoos"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(12.5))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addResponse("#me squeaks loudly and takes two herbs from the chest, which he then pushes into the person's hands standing in front of him.")
talkEntry:addConsequence(consequence_inform("[Quest solved] You got your reward. You were handed the following plants: desert sky capsule, desert berry"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(12.5))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addResponse("#me quiekt laut und holt zwei Kräuter aus der Kiste, die er der Person vor sich in die Hand drückt.")
talkEntry:addConsequence(consequence_inform("[Quest gelöst] Du hast deine Belohnung abgeholt. Folgende Pflanzen hast du erhalten: Wüstenhimmelskapsel, Wüstenbeere"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(16.666666666667))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addResponse("#me squeaks loudly and takes two herbs from the chest, which he then pushes into the person's hands standing in front of him.")
talkEntry:addConsequence(consequence_inform("[Quest solved] You got your reward. You were handed the following plants: dark moss, dark moss"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(16.666666666667))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addResponse("#me quiekt laut und holt zwei Kräuter aus der Kiste, die er der Person vor sich in die Hand drückt.")
talkEntry:addConsequence(consequence_inform("[Quest gelöst] Du hast deine Belohnung abgeholt. Folgende Pflanzen hast du erhalten: Dunkelmoos, Dunkelmoos"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(25.0))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addResponse("#me squeaks loudly and takes two herbs from the chest, which he then pushes into the person's hands standing in front of him.")
talkEntry:addConsequence(consequence_inform("[Quest solved] You got your reward. You were handed the following plants: dark moss, desert berry"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(25.0))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addResponse("#me quiekt laut und holt zwei Kräuter aus der Kiste, die er der Person vor sich in die Hand drückt.")
talkEntry:addConsequence(consequence_inform("[Quest gelöst] Du hast deine Belohnung abgeholt. Folgende Pflanzen hast du erhalten: Dunkelmoos, Wüstenbeere"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(50.0))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addResponse("#me squeaks loudly and takes two herbs from the chest, which he then pushes into the person's hands standing in front of him.")
talkEntry:addConsequence(consequence_inform("[Quest solved] You got your reward. You were handed the following plants: desert berry, desert berry"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(50.0))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addResponse("#me quiekt laut und holt zwei Kräuter aus der Kiste, die er der Person vor sich in die Hand drückt.")
talkEntry:addConsequence(consequence_inform("[Quest gelöst] Du hast deine Belohnung abgeholt. Folgende Pflanzen hast du erhalten: Wüstenbeere, Wüstenbeere"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(52.5))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addResponse("#me squeaks loudly and takes three herbs from the chest, which he then pushes into the person's hands standing in front of him.")
talkEntry:addConsequence(consequence_inform("[Quest solved] You got your reward. You were handed the following plants: night angels blossom, night angels blossom, night angels blossom"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(52.5))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addResponse("#me quiekt laut und holt drei Kräuter aus der Kiste, die er der Person vor sich in die Hand drückt.")
talkEntry:addConsequence(consequence_inform("[Quest gelöst] Du hast deine Belohnung abgeholt. Folgende Pflanzen hast du erhalten: Nachtengelsblüte, Nachtengelsblüte,Nachtengelsblüte"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(52.631578947368))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addResponse("#me squeaks loudly and takes three herbs from the chest, which he then pushes into the person's hands standing in front of him.")
talkEntry:addConsequence(consequence_inform("[Quest solved] You got your reward. You were handed the following plants: night angels blossom, night angels blossom, desert sky capsule"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(52.631578947368))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addResponse("#me quiekt laut und holt drei Kräuter aus der Kiste, die er der Person vor sich in die Hand drückt.")
talkEntry:addConsequence(consequence_inform("[Quest gelöst] Du hast deine Belohnung abgeholt. Folgende Pflanzen hast du erhalten: Nachtengelsblüte, Nachtengelsblüte,Wüstenhimmelskapsel"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(52.777777777778))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addResponse("#me squeaks loudly and takes three herbs from the chest, which he then pushes into the person's hands standing in front of him.")
talkEntry:addConsequence(consequence_inform("[Quest solved] You got your reward. You were handed the following plants: night angels blossom, night angels blossom, dark moss"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(52.777777777778))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addResponse("#me quiekt laut und holt drei Kräuter aus der Kiste, die er der Person vor sich in die Hand drückt.")
talkEntry:addConsequence(consequence_inform("[Quest gelöst] Du hast deine Belohnung abgeholt. Folgende Pflanzen hast du erhalten: Nachtengelsblüte, Nachtengelsblüte,Dunkelmoos"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(52.941176470588))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addResponse("#me squeaks loudly and takes three herbs from the chest, which he then pushes into the person's hands standing in front of him.")
talkEntry:addConsequence(consequence_inform("[Quest solved] You got your reward. You were handed the following plants: night angels blossom, night angels blossom, desert berry"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(52.941176470588))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addResponse("#me quiekt laut und holt drei Kräuter aus der Kiste, die er der Person vor sich in die Hand drückt.")
talkEntry:addConsequence(consequence_inform("[Quest gelöst] Du hast deine Belohnung abgeholt. Folgende Pflanzen hast du erhalten: Nachtengelsblüte, Nachtengelsblüte,Wüstenbeere"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(53.125))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addResponse("#me squeaks loudly and takes three herbs from the chest, which he then pushes into the person's hands standing in front of him.")
talkEntry:addConsequence(consequence_inform("[Quest solved] You got your reward. You were handed the following plants: night angels blossom, desert sky capsule, desert sky capsule"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(53.125))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addResponse("#me quiekt laut und holt drei Kräuter aus der Kiste, die er der Person vor sich in die Hand drückt.")
talkEntry:addConsequence(consequence_inform("[Quest gelöst] Du hast deine Belohnung abgeholt. Folgende Pflanzen hast du erhalten: Nachtengelsblüte, Wüstenhimmelskapsel,Wüstenhimmelskapsel"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(53.333333333333))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addResponse("#me squeaks loudly and takes three herbs from the chest, which he then pushes into the person's hands standing in front of him.")
talkEntry:addConsequence(consequence_inform("[Quest solved] You got your reward. You were handed the following plants: night angels blossom, desert sky capsule, dark moss"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(53.333333333333))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addResponse("#me quiekt laut und holt drei Kräuter aus der Kiste, die er der Person vor sich in die Hand drückt.")
talkEntry:addConsequence(consequence_inform("[Quest gelöst] Du hast deine Belohnung abgeholt. Folgende Pflanzen hast du erhalten: Nachtengelsblüte, Wüstenhimmelskapsel,Dunkelmoos"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(53.571428571429))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addResponse("#me squeaks loudly and takes three herbs from the chest, which he then pushes into the person's hands standing in front of him.")
talkEntry:addConsequence(consequence_inform("[Quest solved] You got your reward. You were handed the following plants: night angels blossom, desert sky capsule, desert berry"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(53.571428571429))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addResponse("#me quiekt laut und holt drei Kräuter aus der Kiste, die er der Person vor sich in die Hand drückt.")
talkEntry:addConsequence(consequence_inform("[Quest gelöst] Du hast deine Belohnung abgeholt. Folgende Pflanzen hast du erhalten: Nachtengelsblüte, Wüstenhimmelskapsel,Wüstenbeere"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(53.846153846154))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addResponse("#me squeaks loudly and takes three herbs from the chest, which he then pushes into the person's hands standing in front of him.")
talkEntry:addConsequence(consequence_inform("[Quest solved] You got your reward. You were handed the following plants: night angels blossom, dark moss, dark moss"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(53.846153846154))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addResponse("#me quiekt laut und holt drei Kräuter aus der Kiste, die er der Person vor sich in die Hand drückt.")
talkEntry:addConsequence(consequence_inform("[Quest gelöst] Du hast deine Belohnung abgeholt. Folgende Pflanzen hast du erhalten: Nachtengelsblüte, Dunkelmoos,Dunkelmoos"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(54.166666666667))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addResponse("#me squeaks loudly and takes three herbs from the chest, which he then pushes into the person's hands standing in front of him.")
talkEntry:addConsequence(consequence_inform("[Quest solved] You got your reward. You were handed the following plants: night angels blossom, dark moss, desert berry"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(54.166666666667))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addResponse("#me quiekt laut und holt drei Kräuter aus der Kiste, die er der Person vor sich in die Hand drückt.")
talkEntry:addConsequence(consequence_inform("[Quest gelöst] Du hast deine Belohnung abgeholt. Folgende Pflanzen hast du erhalten: Nachtengelsblüte, Dunkelmoos,Wüstenbeere"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(54.545454545455))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addResponse("#me squeaks loudly and takes three herbs from the chest, which he then pushes into the person's hands standing in front of him.")
talkEntry:addConsequence(consequence_inform("[Quest solved] You got your reward. You were handed the following plants: night angels blossom, desert berry, desert berry"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(54.545454545455))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(138, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addResponse("#me quiekt laut und holt drei Kräuter aus der Kiste, die er der Person vor sich in die Hand drückt.")
talkEntry:addConsequence(consequence_inform("[Quest gelöst] Du hast deine Belohnung abgeholt. Folgende Pflanzen hast du erhalten: Nachtengelsblüte, Wüstenbeere,Wüstenbeere"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(55.0))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addResponse("#me squeaks loudly and takes three herbs from the chest, which he then pushes into the person's hands standing in front of him.")
talkEntry:addConsequence(consequence_inform("[Quest solved] You got your reward. You were handed the following plants: desert sky capsule, desert sky capsule, desert sky capsule"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(55.0))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addResponse("#me quiekt laut und holt drei Kräuter aus der Kiste, die er der Person vor sich in die Hand drückt.")
talkEntry:addConsequence(consequence_inform("[Quest gelöst] Du hast deine Belohnung abgeholt. Folgende Pflanzen hast du erhalten: Wüstenhimmelskapsel, Wüstenhimmelskapsel,Wüstenhimmelskapsel"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(55.555555555556))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addResponse("#me squeaks loudly and takes three herbs from the chest, which he then pushes into the person's hands standing in front of him.")
talkEntry:addConsequence(consequence_inform("[Quest solved] You got your reward. You were handed the following plants: desert sky capsule, desert sky capsule, dark moss"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(55.555555555556))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addResponse("#me quiekt laut und holt drei Kräuter aus der Kiste, die er der Person vor sich in die Hand drückt.")
talkEntry:addConsequence(consequence_inform("[Quest gelöst] Du hast deine Belohnung abgeholt. Folgende Pflanzen hast du erhalten: Wüstenhimmelskapsel, Wüstenhimmelskapsel,Dunkelmoos"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(56.25))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addResponse("#me squeaks loudly and takes three herbs from the chest, which he then pushes into the person's hands standing in front of him.")
talkEntry:addConsequence(consequence_inform("[Quest solved] You got your reward. You were handed the following plants: desert sky capsule, desert sky capsule, desert berry"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(56.25))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addResponse("#me quiekt laut und holt drei Kräuter aus der Kiste, die er der Person vor sich in die Hand drückt.")
talkEntry:addConsequence(consequence_inform("[Quest gelöst] Du hast deine Belohnung abgeholt. Folgende Pflanzen hast du erhalten: Wüstenhimmelskapsel, Wüstenhimmelskapsel,Wüstenbeere"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(57.142857142857))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addResponse("#me squeaks loudly and takes three herbs from the chest, which he then pushes into the person's hands standing in front of him.")
talkEntry:addConsequence(consequence_inform("[Quest solved] You got your reward. You were handed the following plants: desert sky capsule, dark moss, dark moss"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(57.142857142857))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addResponse("#me quiekt laut und holt drei Kräuter aus der Kiste, die er der Person vor sich in die Hand drückt.")
talkEntry:addConsequence(consequence_inform("[Quest gelöst] Du hast deine Belohnung abgeholt. Folgende Pflanzen hast du erhalten: Wüstenhimmelskapsel, Dunkelmoos,Dunkelmoos"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(58.333333333333))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addResponse("#me squeaks loudly and takes three herbs from the chest, which he then pushes into the person's hands standing in front of him.")
talkEntry:addConsequence(consequence_inform("[Quest solved] You got your reward. You were handed the following plants: desert sky capsule, dark moss, desert berry"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(58.333333333333))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addResponse("#me quiekt laut und holt drei Kräuter aus der Kiste, die er der Person vor sich in die Hand drückt.")
talkEntry:addConsequence(consequence_inform("[Quest gelöst] Du hast deine Belohnung abgeholt. Folgende Pflanzen hast du erhalten: Wüstenhimmelskapsel, Dunkelmoos,Wüstenbeere"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(60.0))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addResponse("#me squeaks loudly and takes three herbs from the chest, which he then pushes into the person's hands standing in front of him.")
talkEntry:addConsequence(consequence_inform("[Quest solved] You got your reward. You were handed the following plants: desert sky capsule, desert berry, desert berry"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(60.0))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(146, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addResponse("#me quiekt laut und holt drei Kräuter aus der Kiste, die er der Person vor sich in die Hand drückt.")
talkEntry:addConsequence(consequence_inform("[Quest gelöst] Du hast deine Belohnung abgeholt. Folgende Pflanzen hast du erhalten: Wüstenhimmelskapsel, Wüstenbeere,Wüstenbeere"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(62.5))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addResponse("#me squeaks loudly and takes three herbs from the chest, which he then pushes into the person's hands standing in front of him.")
talkEntry:addConsequence(consequence_inform("[Quest solved] You got your reward. You were handed the following plants: dark moss, dark moss, dark moss"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(62.5))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addResponse("#me quiekt laut und holt drei Kräuter aus der Kiste, die er der Person vor sich in die Hand drückt.")
talkEntry:addConsequence(consequence_inform("[Quest gelöst] Du hast deine Belohnung abgeholt. Folgende Pflanzen hast du erhalten: Dunkelmoos, Dunkelmoos,Dunkelmoos"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(66.666666666667))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addResponse("#me squeaks loudly and takes three herbs from the chest, which he then pushes into the person's hands standing in front of him.")
talkEntry:addConsequence(consequence_inform("[Quest solved] You got your reward. You were handed the following plants: dark moss, dark moss, desert berry"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(66.666666666667))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addResponse("#me quiekt laut und holt drei Kräuter aus der Kiste, die er der Person vor sich in die Hand drückt.")
talkEntry:addConsequence(consequence_inform("[Quest gelöst] Du hast deine Belohnung abgeholt. Folgende Pflanzen hast du erhalten: Dunkelmoos, Dunkelmoos,Wüstenbeere"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(75.0))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addResponse("#me squeaks loudly and takes three herbs from the chest, which he then pushes into the person's hands standing in front of him.")
talkEntry:addConsequence(consequence_inform("[Quest solved] You got your reward. You were handed the following plants: dark moss, desert berry, desert berry"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(75.0))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(764, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addResponse("#me quiekt laut und holt drei Kräuter aus der Kiste, die er der Person vor sich in die Hand drückt.")
talkEntry:addConsequence(consequence_inform("[Quest gelöst] Du hast deine Belohnung abgeholt. Folgende Pflanzen hast du erhalten: Dunkelmoos, Wüstenbeere,Wüstenbeere"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(100.0))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addResponse("#me squeaks loudly and takes three herbs from the chest, which he then pushes into the person's hands standing in front of him.")
talkEntry:addConsequence(consequence_inform("[Quest solved] You got your reward. You were handed the following plants: desert berry, desert berry, desert berry"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(504, "=", 5))
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(100.0))
talkEntry:addTrigger(".+")
talkEntry:addConsequence(consequence_quest(504, "=", 6))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addConsequence(consequence_item(769, 1, 999, nil))
talkEntry:addResponse("#me quiekt laut und holt drei Kräuter aus der Kiste, die er der Person vor sich in die Hand drückt.")
talkEntry:addConsequence(consequence_inform("[Quest gelöst] Du hast deine Belohnung abgeholt. Folgende Pflanzen hast du erhalten: Wüstenbeere, Wüstenbeere,Wüstenbeere"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(10.0))
talkEntry:addTrigger(".+")
talkEntry:addResponse("Yep, yep, yep, yep.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(10.0))
talkEntry:addTrigger(".+")
talkEntry:addResponse("Jap, jap, jap, jap.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(11.111111111111))
talkEntry:addTrigger(".+")
talkEntry:addResponse("#me licks his teeth and stares at the person in front of him, mumbling something incomprehensible.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(11.111111111111))
talkEntry:addTrigger(".+")
talkEntry:addResponse("#me leckt seine Zähne und starrt die Person vor sich an. Dabei murmelt er etwas Unverständliches.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(12.5))
talkEntry:addTrigger(".+")
talkEntry:addResponse("Egon! Me Egon! Egon!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(12.5))
talkEntry:addTrigger(".+")
talkEntry:addResponse("Egon! Ich Egon! Egon!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(14.285714285714))
talkEntry:addTrigger(".+")
talkEntry:addResponse("#me hits his head a couple of times.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(14.285714285714))
talkEntry:addTrigger(".+")
talkEntry:addResponse("#me schlägt sich einige Male selbst gegen den Kopf.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(16.666666666667))
talkEntry:addTrigger(".+")
talkEntry:addResponse("#me stares at the person in front of him before he hisses and begins to wildly pull herbs apart.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(16.666666666667))
talkEntry:addTrigger(".+")
talkEntry:addResponse("#me starrt die Person vor sich eine Weile an, ehe er faucht und wie wild Kräuter zu rupfen beginnt.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(20.0))
talkEntry:addTrigger(".+")
talkEntry:addResponse("Red... red cloud...cloud extract. You have?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(20.0))
talkEntry:addTrigger(".+")
talkEntry:addResponse("Rot...Rotwolken...wolkenextrakt. Du hast?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(25.0))
talkEntry:addTrigger(".+")
talkEntry:addResponse("#me bows forward to sniff at the person in front of him.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(25.0))
talkEntry:addTrigger(".+")
talkEntry:addResponse("#me beugt sich vor, um an der Person vor sich zu schnuppern.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(33.333333333333))
talkEntry:addTrigger(".+")
talkEntry:addResponse("#me cries: 'No, no, you not hurting me!'")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(33.333333333333))
talkEntry:addTrigger(".+")
talkEntry:addResponse("#me kreischt: 'Nein, nein, nicht verletzen!'")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(50.0))
talkEntry:addTrigger(".+")
talkEntry:addResponse("#me flips his tail hectically and claps his hands.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(50.0))
talkEntry:addTrigger(".+")
talkEntry:addResponse("#me wedelt hektisch mit dem Schwanz und klatscht mit den Händen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_chance(100.0))
talkEntry:addTrigger(".+")
talkEntry:addResponse("#me shakes his head several times and cries out: 'Me good, me good!'")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("german"))
talkEntry:addCondition(condition_chance(100.0))
talkEntry:addTrigger(".+")
talkEntry:addResponse("#me schüttelt seinen Kopf einige Male und schreit auf: 'Mir gut, mir gut!'")
talkingNPC:addTalkingEntry(talkEntry)
end
talkingNPC:addCycleText("#mes starrer Blick richtet sich auf den Zwerg am Kessel.", "#me stares to the dwarf standing by the cauldron.")
talkingNPC:addCycleText("#me wedelt mit seinem Schwanz.", "#me wags his tail.")
talkingNPC:addCycleText("#me zerrupft mit seinen Krallenhänden Pflanzen.", "#me pulls herbs to pieces with his claws.")
talkingNPC:addCycleText("#me jault laut und monoton auf.", "#me yowls loudly and monotonously.")
talkingNPC:addCycleText("#mes Körper zuckt einige Male zusammen.", "#me's body cringes a couple of times.")
mainNPC:addLanguage(0)
mainNPC:setDefaultLanguage(0)
mainNPC:setLookat("Dieser NPC ist Egon, Granor Bergenhiebs Assistent.", "This NPC is Ego, Granor Bergenhieb's assistant.")
mainNPC:setUseMessage("#me fuchtelt wild herum.", "#me fidgets his claws wildly around.")
mainNPC:setConfusedMessage("Ne. Nein... nein verstehen.", "N-No... no understand")
mainNPC:setEquipment(1, 0)
mainNPC:setEquipment(3, 0)
mainNPC:setEquipment(11, 0)
mainNPC:setEquipment(5, 0)
mainNPC:setEquipment(6, 0)
mainNPC:setEquipment(4, 0)
mainNPC:setEquipment(9, 0)
mainNPC:setEquipment(10, 0)
mainNPC:setAutoIntroduceMode(true)

mainNPC:initDone()
return mainNPC
end
local mNPC = initNpc()
initNpc = nil
local M = {}
function M.receiveText(npcChar, texttype, message, speaker) mNPC:receiveText(npcChar, texttype, speaker, message) end
function M.nextCycle(npcChar) mNPC:nextCycle(npcChar) end
function M.lookAtNpc(npcChar, char, mode) mNPC:lookAt(npcChar, char, mode) end
function M.useNPC(npcChar, char, counter, param) mNPC:use(npcChar, char) end
return M
