local consequence_item = require("npc.base.consequence.item")
local condition_item = require("npc.base.condition.item")
local consequence_quest = require("npc.base.consequence.quest")
local condition_skill = require("npc.base.condition.skill")
local condition_language = require("npc.base.condition.language")
local consequence_deleteitem = require("npc.base.consequence.deleteitem")
local basic = require("npc.base.basic")
local condition_town = require("npc.base.condition.town")
local talk = require("npc.base.talk")
local consequence_money = require("npc.base.consequence.money")
local condition_quest = require("npc.base.condition.quest")
local consequence_inform = require("npc.base.consequence.inform")
local function initNpc()
local mainNPC = basic()
mainNPC:setAffiliation(2)
local talkingNPC = talk(mainNPC)
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Help")
talkEntry:addConsequence(consequence_inform("[Game Help] This NPC is Francine Leonard the cook and baker. Keywords: Hello, quest, cook, baker."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hilfe")
talkEntry:addConsequence(consequence_inform("[Spielhilfe] Dieser NPC ist Francine Leonard die Köchin und Bäckerin. Schlüsselwörter: Hallo, Quest, Köchin, Bäcker."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hello")
talkEntry:addTrigger("Greet")
talkEntry:addTrigger("Hail")
talkEntry:addTrigger("Good day")
talkEntry:addTrigger("Good morning")
talkEntry:addTrigger("Good Evening")
talkEntry:addResponse("Hello, can I help you?")
talkEntry:addResponse("Nice to meet you, I'm Francine Leonard.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Grüß")
talkEntry:addTrigger("Gruß")
talkEntry:addTrigger("Grüss")
talkEntry:addTrigger("Gruss")
talkEntry:addTrigger("Guten Morgen")
talkEntry:addTrigger("Guten Tag")
talkEntry:addTrigger("Guten Abend")
talkEntry:addTrigger("Gute Nacht")
talkEntry:addTrigger("Mahlzeit")
talkEntry:addTrigger("Tach")
talkEntry:addTrigger("Moin")
talkEntry:addTrigger("Mohltied")
talkEntry:addResponse("Hallo, kann ich Euch helfen?")
talkEntry:addResponse("Freut mich, Euch zu treffen. Ich bin Francine Leonard.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Hiho")
talkEntry:addTrigger("Hallo")
talkEntry:addTrigger("Hey")
talkEntry:addTrigger("Greeb")
talkEntry:addResponse("Hello, can I help you?")
talkEntry:addResponse("Nice to meet you, I'm Francine Leonard.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hiho")
talkEntry:addTrigger("Hallo")
talkEntry:addTrigger("Hey")
talkEntry:addTrigger("Greeb")
talkEntry:addResponse("Hallo, kann ich Euch helfen?")
talkEntry:addResponse("Freut mich, Euch zu treffen. Ich bin Francine Leonard.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Farewell")
talkEntry:addTrigger("Bye")
talkEntry:addTrigger("Fare well")
talkEntry:addTrigger("See you")
talkEntry:addResponse("I wish you a nice day.")
talkEntry:addResponse("I hope we meet again, goodbye.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Tschüß")
talkEntry:addTrigger("Tschüss")
talkEntry:addTrigger("Wiedersehen")
talkEntry:addResponse("Ich wünsche Euch noch einen schönen Tag.")
talkEntry:addResponse("Ich hoffe, wir sehen uns wieder, auf bald!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Ciao")
talkEntry:addTrigger("Adieu")
talkEntry:addTrigger("Au revoir")
talkEntry:addTrigger("Farebba")
talkEntry:addResponse("I wish you a nice day.")
talkEntry:addResponse("I hope we meet again, goodbye.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Ciao")
talkEntry:addTrigger("Adieu")
talkEntry:addTrigger("Au revoir")
talkEntry:addTrigger("Farebba")
talkEntry:addResponse("Ich wünsche Euch noch einen schönen Tag.")
talkEntry:addResponse("Ich hoffe, wir sehen uns wieder, auf bald!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("How are you")
talkEntry:addTrigger("How feel")
talkEntry:addTrigger("How do you do")
talkEntry:addResponse("I feel fine, thank you for asking.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Wie geht")
talkEntry:addTrigger("Wie fühlst")
talkEntry:addTrigger("Wie ist es ergangen")
talkEntry:addTrigger("Wie Befind")
talkEntry:addResponse("Mir geht es gut, danke für die Nachfrage.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("your name")
talkEntry:addTrigger("who are you")
talkEntry:addTrigger("who art thou")
talkEntry:addResponse("I'm Francine Leonard, who are you?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("ihr name")
talkEntry:addTrigger("dein name")
talkEntry:addTrigger("wer bist du")
talkEntry:addTrigger("wer seid ihr")
talkEntry:addTrigger("wie heißt")
talkEntry:addTrigger("wie heisst")
talkEntry:addResponse("Ich bin Francine Leonard, wer seid Ihr?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("sell")
talkEntry:addTrigger("buy")
talkEntry:addTrigger("wares")
talkEntry:addTrigger("price")
talkEntry:addTrigger("trade")
talkEntry:addTrigger("purchase")
talkEntry:addResponse("I am not a trader.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("kauf")
talkEntry:addTrigger("waren")
talkEntry:addTrigger("preis")
talkEntry:addTrigger("Handel")
talkEntry:addTrigger("veräußer")
talkEntry:addTrigger("veräusser")
talkEntry:addTrigger("erwerb")
talkEntry:addResponse("Ich bin keine Marktfrau.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("profession")
talkEntry:addResponse("I'm a cook and baker. Do you want to know more about these jobs? Then just ask me for a task!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("beruf")
talkEntry:addResponse("Ich bin Köchin und Bäckerin. Wollt Ihr mehr darüber wissen? Dann fragt mich einfach nach einer Aufgabe!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("job")
talkEntry:addResponse("I'm a cook and baker. Do you want to know more about these jobs? Then just ask me for a task!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("job")
talkEntry:addResponse("Ich bin Köchin und Bäckerin. Wollt Ihr mehr darüber wissen? Dann fragt mich einfach nach einer Aufgabe!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("cook")
talkEntry:addTrigger("baker")
talkEntry:addTrigger("craft")
talkEntry:addResponse("Peel, oven, spoon, kettle; that is all you'll ever need.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Köchin")
talkEntry:addTrigger("Koch")
talkEntry:addTrigger("Bäcker")
talkEntry:addTrigger("Handwerk")
talkEntry:addResponse("Ofenschieber, Ofen, Kochlöffel, Kessel; das ist alles, was Ihr je brauchen werdet.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(714, "=", 0))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_item(51, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 1))
talkEntry:addResponse("The Baker and Cook League accepts you as an apprentice. To learn what you need, you have to work hard first. Take these buckets and get water from the next well, clean water only.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Baker and Cook League of Runewick I. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(714, "=", 0))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_item(51, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 1))
talkEntry:addResponse("The Baker and Cook League accepts you as an apprentice. To learn what you need, you have to work hard first. Take these buckets and get water from the next well, clean water only.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Baker and Cook League of Runewick I. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(714, "=", 0))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addConsequence(consequence_item(51, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 1))
talkEntry:addResponse("Die Liga der Köche und Bäcker wird Eure Ausbildung übernehmen. Zu lernen was Ihr wissen müsst, ist harte Arbeit. Nehmt diese Eimer und füllt sie am nächsten Brunnen mit Wasser, sauberen Wasser!")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Die Liga der Köche und Bäcker von Runewick I. Detaillierte Informationen findest du im Questlog (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(714, "=", 1))
talkEntry:addCondition(condition_item(52, "all", ">", 9, nil))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_quest(714, "=", 2))
talkEntry:addResponse("Clean water, very well but you don't know anything yet about cooking. So, keep the water for the next part of your apprenticeship.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Ask Francine Leonard for your next task."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(714, "=", 1))
talkEntry:addCondition(condition_item(52, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("water")
talkEntry:addTrigger("bucket")
talkEntry:addConsequence(consequence_quest(714, "=", 2))
talkEntry:addResponse("Clean water, very well but you don't know anything yet about cooking. So, keep the water for the next part of your apprenticeship.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Ask Francine Leonard for your next task."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(714, "=", 1))
talkEntry:addCondition(condition_item(52, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Wasser")
talkEntry:addTrigger("Eimer")
talkEntry:addConsequence(consequence_quest(714, "=", 2))
talkEntry:addResponse("Das Wasser ist sauber, sehr schön. Aber noch wisst Ihr gar nichts über das Kochen. Behaltet deshalb das Wasser für den nächsten Schritt Eurer Ausbildung.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Frage Francine Leonard nach deiner nächsten Aufgaben."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(714, "=", 1))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Can't remember what I've said? As your master, I'll repeat my order: Fill the buckets with water.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(714, "=", 1))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("water")
talkEntry:addTrigger("bucket")
talkEntry:addResponse("Can't remember what I've said? As your master, I'll repeat my order: Fill the buckets with water.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(714, "=", 1))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Wasser")
talkEntry:addTrigger("Eimer")
talkEntry:addResponse("Könnt Ihr Euch nicht merken, was ich gesagt habe? Als Eure Meisterin werde ich meine Anordnung noch einmal wiederholen: Füllt die Eimer mit Wasser!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(714, "=", 2))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_item(312, 1, 333, nil))
talkEntry:addConsequence(consequence_item(259, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 3))
talkEntry:addResponse("You can't bake anything without flour. Make ten bags of flour with this grain at the mill. Here is an old shovel, don't waste your time dreaming until the work is done.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Baker and Cook League of Runewick II. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(714, "=", 2))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_item(312, 1, 333, nil))
talkEntry:addConsequence(consequence_item(259, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 3))
talkEntry:addResponse("You can't bake anything without flour. Make ten bags of flour with this grain at the mill. Here is an old shovel, don't waste your time dreaming until the work is done.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Baker and Cook League of Runewick II. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(714, "=", 2))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addConsequence(consequence_item(312, 1, 333, nil))
talkEntry:addConsequence(consequence_item(259, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 3))
talkEntry:addResponse("Ohne Mehl werdet Ihr schwerlich was backen können. Mahlt bitte in der Mühle zehn Säckchen Mehl aus diesem Getreide. Hier ist eine alte Holzkelle aber träumt nicht, die Arbeit macht sich nicht von alleine.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Die Liga der Köche und Bäcker von Runewick II. Detaillierte Informationen findest du im Questlog (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(714, "=", 3))
talkEntry:addCondition(condition_item(2, "all", ">", 9, nil))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_quest(714, "=", 4))
talkEntry:addResponse("You learned to grind grain, good. You'll need them for the next task I want to teach you.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Ask Francine Leonard for your next task."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(714, "=", 3))
talkEntry:addCondition(condition_item(2, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("flour")
talkEntry:addTrigger("grain")
talkEntry:addConsequence(consequence_quest(714, "=", 4))
talkEntry:addResponse("You learned to grind grain, good. You'll need them for the next task I want to teach you")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Ask Francine Leonard for your next task."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(714, "=", 3))
talkEntry:addCondition(condition_item(2, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Getreide")
talkEntry:addTrigger("Mehl")
talkEntry:addConsequence(consequence_quest(714, "=", 4))
talkEntry:addResponse("Ihr habt gelernt, Getreide zu mahlen. Wunderbar, Ihr werdet es brauchen, wenn ich Euch noch was beibringen soll.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Frage Francine Leonard nach deiner nächsten Aufgaben."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(714, "=", 3))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Where did you lose your brain? Your task is to grind ten bags of flour. Without flour, we cannot continue your apprenticeship.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(714, "=", 3))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("flour")
talkEntry:addTrigger("grain")
talkEntry:addResponse("Where did you lose your brain? Your task is to grind ten bags of flour. Without flour, we cannot continue your apprenticeship.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(714, "=", 3))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Mehl")
talkEntry:addTrigger("Getreide")
talkEntry:addResponse("Wo habt Ihr nur Eure Gedanken? Zehn Sack Mehl zu mahlen ist Eure Aufgabe. Ohne diese können wir Eure Ausbildung nicht fortsetzen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(714, "=", 4))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_item(121, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 5))
talkEntry:addResponse("Now we can start in the kitchen. I'll give you an old peel and you bring back ten bread rolls. I do not want to see you reading a book in front of the baking oven before you are done.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Baker and Cook League of Runewick III. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(714, "=", 4))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_item(121, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 5))
talkEntry:addResponse("Now we can start in the kitchen. I'll give you an old peel and you bring back ten bread rolls. I do not want to see you reading a book in front of the baking oven before you are done.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Baker and Cook League of Runewick III. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(714, "=", 4))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addConsequence(consequence_item(121, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 5))
talkEntry:addResponse("Jetzt kann es in der Küche losgehen. Ich gebe Euch einen alten Brotschieber und Ihr bringt mir zehn Brötchen zurück. Und lest ja kein Buch vor dem Backofen, während Ihr aufpassen sollst.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Die Liga der Köche und Bäcker von Runewick III. Detaillierte Informationen findest du im Questlog (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(714, "=", 5))
talkEntry:addCondition(condition_item(191, "all", ">", 9, nil))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Layman with the Baker and Cook League of Runewick. You are awarded ten silver coins."))
talkEntry:addConsequence(consequence_deleteitem(191, 10, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 6))
talkEntry:addConsequence(consequence_money("+", 1000))
talkEntry:addResponse("The Baker and Cook League of Runewick is glad to have a new person willing to learn in it's rows. Here is some money to get you started. I recommend you buy a cooking spoon from it. And come back once you have improved your knowledge.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(714, "=", 5))
talkEntry:addCondition(condition_item(191, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("bread")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Layman with the Baker and Cook League of Runewick. You are awarded ten silver coins."))
talkEntry:addConsequence(consequence_deleteitem(191, 10, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 6))
talkEntry:addConsequence(consequence_money("+", 1000))
talkEntry:addResponse("The Baker and Cook League of Runewick is glad to have a new person willing to learn in it's rows. Here is some money to get you started. I recommend you buy a cooking spoon from it. And come back once you have improved your knowledge.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(714, "=", 5))
talkEntry:addCondition(condition_item(191, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Brötchen")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Liga der Köche und Bäcker von Runewick erhebt dich in den Rang eines Laiens. Du erhältst zehn Silberstücke."))
talkEntry:addConsequence(consequence_deleteitem(191, 10, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 6))
talkEntry:addConsequence(consequence_money("+", 1000))
talkEntry:addResponse("Die Liga der Köche und Bäcker von Runewick freut sich ein neues lernwilliges Mitglied zu begrüßen. Hier ist etwas monetäre Starthilfe. Mein Vorschlag wäre, dass Ihr davon einen Kochlöffel kaufst. Und kommt zu mir zurück, wenn Ihre Eure Kenntnisse erweitert habt.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(714, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Don't blame your brain. Use it to bake ten bread rolls.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(714, "=", 5))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("bread")
talkEntry:addResponse("Don't blame your brain. Use it to bake ten bread rolls.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(714, "=", 5))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Brötchen")
talkEntry:addResponse("Stellt Euch nicht dümmer an, als Ihr seid. Beeilt Euch und backt zehn Brötchen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, ">", 9))
talkEntry:addCondition(condition_quest(714, "=", 6))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Novice with the Baker and Cook League of Runewick. You are awarded ten bags of grain."))
talkEntry:addConsequence(consequence_item(259, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 7))
talkEntry:addResponse("Very well, I see you do everything to improve your knowledge. The Baker and Cook League of Runewick supports your way to wisdom with some grain. Come back to me once you have improved your knowledge.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, ">", 9))
talkEntry:addCondition(condition_quest(714, "=", 6))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Novice with the Baker and Cook League of Runewick. You are awarded ten bags of grain."))
talkEntry:addConsequence(consequence_item(259, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 7))
talkEntry:addResponse("Very well, I see you do everything to improve your knowledge. The Baker and Cook League of Runewick supports your way to wisdom with some grain. Come back to me once you have improved your knowledge.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, ">", 9))
talkEntry:addCondition(condition_quest(714, "=", 6))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Liga der Köche und Bäcker von Runewick erhebt dich in den Rang eines Anfängers. Du erhältst zehn Sack Getreide."))
talkEntry:addConsequence(consequence_item(259, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 7))
talkEntry:addResponse("Ausgezeichnet. Wie ich sehe, tut Ihr alles um Euer Wissen zu erweitern. Die Liga der Köche und Bäcker von Runewick unterstützt Euren Weg zu Können und Weisheit mit etwas Getreide. Kommt erneut zu mir, wenn Ihr mehr könnt.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, "<", 10))
talkEntry:addCondition(condition_quest(714, "=", 6))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Keep on learning! You have to improve your knowledge in cooking and baking to be eligible for a promotion. Your current rank is Layman.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 10 in cooking and baking to advance in the ranks of the Baker and Cook League."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, "<", 10))
talkEntry:addCondition(condition_quest(714, "=", 6))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Keep on learning! You have to improve your knowledge in cooking and baking to be eligible for a promotion. Your current rank is Layman.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 10 in cooking and baking to advance in the ranks of the Baker and Cook League."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, "<", 10))
talkEntry:addCondition(condition_quest(714, "=", 6))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Weiterlernen! Ihr müsst Euer Wissen als Koch und Bäcker verbessern, um befördert zu werden. Ihr werdet im Rang eines Laiens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 10 in Kochen und Backen um in der Liga der Köche und Bäcker aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, ">", 19))
talkEntry:addCondition(condition_quest(714, "=", 7))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Apprentice with the Baker and Cook League of Runewick. You are awarded twenty pieces of pork."))
talkEntry:addConsequence(consequence_item(307, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 8))
talkEntry:addResponse("Very well. I see you do everything to improve your knowledge. The Baker and Cook League of Runewick supports your way to wisdom with some pork. Come back to me once you have improved your knowledge.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, ">", 19))
talkEntry:addCondition(condition_quest(714, "=", 7))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Apprentice with the Baker and Cook League of Runewick. You are awarded pieces of twenty pork."))
talkEntry:addConsequence(consequence_item(307, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 8))
talkEntry:addResponse("Very well. I see you do everything to improve your knowledge. The Baker and Cook League of Runewick supports your way to wisdom with some pork. Come back to me once you have improved your knowledge.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, ">", 19))
talkEntry:addCondition(condition_quest(714, "=", 7))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Liga der Köche und Bäcker von Runewick erhebt dich in den Rang eines Lehrlings. Du erhältst zwanzig Stück Schweinefleisch."))
talkEntry:addConsequence(consequence_item(307, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 8))
talkEntry:addResponse("Ausgezeichnet. Wie ich sehe, tut Ihr alles um Euer Wissen zu erweitern. Die Liga der Köche und Bäcker von Runewick unterstützt Euren Weg zu Können und Weisheit mit etwas Schweinefleisch. Kommt erneut zu mir, wenn Ihr mehr könnt.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, "<", 20))
talkEntry:addCondition(condition_quest(714, "=", 7))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Keep on learning! You have to improve your knowledge in cooking and baking to be eligible for a promotion. Your current rank is Novice.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 20 in cooking and baking to advance in the ranks of the Baker and Cook League."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, "<", 20))
talkEntry:addCondition(condition_quest(714, "=", 7))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Keep on learning! You have to improve your knowledge in cooking and baking to be eligible for a promotion. Your current rank is Novice.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 20 in cooking and baking to advance in the ranks of the Baker and Cook League."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, "<", 20))
talkEntry:addCondition(condition_quest(714, "=", 7))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Weiterlernen! Ihr müsst Euer Wissen als Koch und Bäcker verbessern, um befördert zu werden. Ihr werdet im Rang eines Anfängers geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 20 in Kochen und Backen um in der Liga der Köche und Bäcker aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, ">", 29))
talkEntry:addCondition(condition_quest(714, "=", 8))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Initiate with the Baker and Cook League of Runewick. You are awarded ten sausages."))
talkEntry:addConsequence(consequence_item(3051, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 9))
talkEntry:addResponse("Very well. I see you do everything to improve your knowledge. The Baker and Cook League of Runewick supports your way to wisdom with some sausages. Come back to me once you have improved your knowledge.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, ">", 29))
talkEntry:addCondition(condition_quest(714, "=", 8))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Initiate with the Baker and Cook League of Runewick. You are awarded ten sausages."))
talkEntry:addConsequence(consequence_item(3051, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 9))
talkEntry:addResponse("Very well. I see you do everything to improve your knowledge. The Baker and Cook League of Runewick supports your way to wisdom with some sausages. Come back to me once you have improved your knowledge.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, ">", 29))
talkEntry:addCondition(condition_quest(714, "=", 8))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Liga der Köche und Bäcker von Runewick erhebt dich in den Rang eines Initiatens. Du erhältst zehn Würste."))
talkEntry:addConsequence(consequence_item(3051, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 9))
talkEntry:addResponse("Ausgezeichnet. Wie ich sehe, tut Ihr alles um Euer Wissen zu erweitern. Die Liga der Köche und Bäcker von Runewick unterstützt Euren Weg zu Können und Weisheit mit einigen Würsten. Kommt erneut zu mir, wenn Ihr mehr könnt.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, "<", 30))
talkEntry:addCondition(condition_quest(714, "=", 8))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Keep on learning! You have to improve your knowledge in cooking and baking to be eligible for a promotion. Your current rank is Apprentice.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 30 in cooking and baking to advance in the ranks of the Baker and Cook League."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, "<", 30))
talkEntry:addCondition(condition_quest(714, "=", 8))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Keep on learning! You have to improve your knowledge in cooking and baking to be eligible for a promotion. Your current rank is Apprentice.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 30 in cooking and baking to advance in the ranks of the Baker and Cook League."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, "<", 30))
talkEntry:addCondition(condition_quest(714, "=", 8))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Weiterlernen! Ihr müsst Euer Wissen als Koch und Bäcker verbessern, um befördert zu werden. Ihr werdet im Rang eines Lehrlings geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 30 in Kochen und Backen um in der Liga der Köche und Bäcker aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, ">", 39))
talkEntry:addCondition(condition_quest(714, "=", 9))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Journeyman with the Baker and Cook League of Runewick. You are awarded twenty wooden plates and a journeyman's certificate."))
talkEntry:addConsequence(consequence_item(2952, 20, 333, nil))
talkEntry:addConsequence(consequence_item(3109, 1, 333, {["descriptionEn"] = "The owner of this certificate has successfully passed the examination as Journeyman. Francine Leonard - Baker and Cook League of Runewick", ["descriptionDe"] = "Der Inhaber dieses Gesellenbriefes hat erfolgreich das Examen zum Gesellen bestanden. Francine Leonard - Liga der Koeche und Baecker Runewicks", ["nameDe"] = "Gesellenbrief", ["nameEn"] = "Journeyman's Certificate", ["rareness"] = "1"}))
talkEntry:addConsequence(consequence_quest(714, "=", 10))
talkEntry:addResponse("I'm glad to welcome a new Journeyman in our rows. The Baker and Cook League of Runewick supports your way to wisdom with some wooden plates. Come back to me once you have improved your knowledge.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, ">", 39))
talkEntry:addCondition(condition_quest(714, "=", 9))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Journeyman with the Baker and Cook League of Runewick. You are awarded twenty wooden plates and a journeyman's certificate."))
talkEntry:addConsequence(consequence_item(2952, 20, 333, nil))
talkEntry:addConsequence(consequence_item(3109, 1, 333, {["descriptionEn"] = "The owner of this certificate has successfully passed the examination as Journeyman. Francine Leonard - Baker and Cook League of Runewick", ["descriptionDe"] = "Der Inhaber dieses Gesellenbriefes hat erfolgreich das Examen zum Gesellen bestanden. Francine Leonard - Liga der Koeche und Baecker Runewicks", ["nameDe"] = "Gesellenbrief", ["nameEn"] = "Journeyman's Certificate", ["rareness"] = "1"}))
talkEntry:addConsequence(consequence_quest(714, "=", 10))
talkEntry:addResponse("I'm glad to welcome a new Journeyman in our rows. The Baker and Cook League of Runewick supports your way to wisdom with some wooden plates. Come back to me once you have improved your knowledge.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, ">", 39))
talkEntry:addCondition(condition_quest(714, "=", 9))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Liga der Köche und Bäcker von Runewick erhebt dich in den Rang eines Gesellens. Du erhältst zwanzig Holzteller und einen Gesellenbrief."))
talkEntry:addConsequence(consequence_item(2952, 20, 333, nil))
talkEntry:addConsequence(consequence_item(3109, 1, 333, {["descriptionEn"] = "The owner of this certificate has successfully passed the examination as Journeyman. Francine Leonard - Baker and Cook League of Runewick", ["descriptionDe"] = "Der Inhaber dieses Gesellenbriefes hat erfolgreich das Examen zum Gesellen bestanden. Francine Leonard - Liga der Koeche und Baecker Runewicks", ["nameDe"] = "Gesellenbrief", ["nameEn"] = "Journeyman's Certificate", ["rareness"] = "1"}))
talkEntry:addConsequence(consequence_quest(714, "=", 10))
talkEntry:addResponse("Ich freu mich einen neuen Gesellen in unseren Reihen begrüßen zu können. Die Liga der Köche und Bäcker von Runewick unterstützt Euren Weg zu Können und Weisheit mit einigen Holztellern. Kommt erneut zu mir, wenn Ihr mehr könnt.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, "<", 40))
talkEntry:addCondition(condition_quest(714, "=", 9))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Keep on learning! You have to improve your knowledge in cooking and baking to be eligible for a promotion. Your current rank is Initiate.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 40 in cooking and baking to advance in the ranks of the Baker and Cook League."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, "<", 40))
talkEntry:addCondition(condition_quest(714, "=", 9))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Keep on learning! You have to improve your knowledge in cooking and baking to be eligible for a promotion. Your current rank is Initiate.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 40 in cooking and baking to advance in the ranks of the Baker and Cook League."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, "<", 40))
talkEntry:addCondition(condition_quest(714, "=", 9))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Weiterlernen! Ihr müsst Euer Wissen als Koch und Bäcker verbessern, um befördert zu werden. Ihr werdet im Rang eines Initiatens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 40 in Kochen und Backen um in der Liga der Köche und Bäcker aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, ">", 49))
talkEntry:addCondition(condition_quest(714, "=", 10))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Specialist with the Baker and Cook League of Runewick. You are awarded ten soup bowls."))
talkEntry:addConsequence(consequence_item(2935, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 11))
talkEntry:addResponse("Very well. I see you do everything to improve your knowledge. The Baker and Cook League of Runewick supports your way to wisdom with some soup bowls. Come back to me once you have improved your knowledge.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, ">", 49))
talkEntry:addCondition(condition_quest(714, "=", 10))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Specialist with the Baker and Cook League of Runewick. You are awarded ten soup bowls."))
talkEntry:addConsequence(consequence_item(2935, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 11))
talkEntry:addResponse("Very well. I see you do everything to improve your knowledge. The Baker and Cook League of Runewick supports your way to wisdom with some soup bowls. Come back to me once you have improved your knowledge.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, ">", 49))
talkEntry:addCondition(condition_quest(714, "=", 10))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Liga der Köche und Bäcker von Runewick erhebt dich in den Rang eines Spezialistens. Du erhältst zehn Suppenschüsseln."))
talkEntry:addConsequence(consequence_item(2935, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 11))
talkEntry:addResponse("Ausgezeichnet. Wie ich sehe, tut Ihr alles um Euer Wissen zu erweitern. Die Liga der Köche und Bäcker von Runewick unterstützt Euren Weg zu Können und Weisheit mit einigen Suppenschüsseln. Kommt erneut zu mir, wenn Ihr mehr könnt.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, "<", 50))
talkEntry:addCondition(condition_quest(714, "=", 10))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Keep on learning! You have to improve your knowledge in cooking and baking to be eligible for a promotion. Your current rank is Journeyman.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 50 in cooking and baking to advance in the ranks of the Baker and Cook League."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, "<", 50))
talkEntry:addCondition(condition_quest(714, "=", 10))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Keep on learning! You have to improve your knowledge in cooking and baking to be eligible for a promotion. Your current rank is Journeyman.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 50 in cooking and baking to advance in the ranks of the Baker and Cook League."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, "<", 50))
talkEntry:addCondition(condition_quest(714, "=", 10))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Weiterlernen! Ihr müsst Euer Wissen als Koch und Bäcker verbessern, um befördert zu werden. Ihr werdet im Rang eines Gesellens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 50 in Kochen und Backen um in der Liga der Köche und Bäcker aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, ">", 59))
talkEntry:addCondition(condition_quest(714, "=", 11))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Expert with the Baker and Cook League of Runewick. You are awarded twenty onions."))
talkEntry:addConsequence(consequence_item(201, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 12))
talkEntry:addResponse("Very well. I see you do everything to improve your knowledge. The Baker and Cook League of Runewick supports your way to wisdom with some onions. Come back to me once you have improved your knowledge.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, ">", 59))
talkEntry:addCondition(condition_quest(714, "=", 11))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Expert with the Baker and Cook League of Runewick. You are awarded twenty onions."))
talkEntry:addConsequence(consequence_item(201, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 12))
talkEntry:addResponse("Very well. I see you do everything to improve your knowledge. The Baker and Cook League of Runewick supports your way to wisdom with some onions. Come back to me once you have improved your knowledge.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, ">", 59))
talkEntry:addCondition(condition_quest(714, "=", 11))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Liga der Köche und Bäcker von Runewick erhebt dich in den Rang eines Expertens. Du erhältst zwanzig Zwiebeln."))
talkEntry:addConsequence(consequence_item(201, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 12))
talkEntry:addResponse("Ausgezeichnet. Wie ich sehe, tut Ihr alles um Euer Wissen zu erweitern. Die Liga der Köche und Bäcker von Runewick unterstützt Euren Weg zu Können und Weisheit mit einigen Zwiebeln. Kommt erneut zu mir, wenn Ihr mehr könnt.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, "<", 60))
talkEntry:addCondition(condition_quest(714, "=", 11))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Keep on learning! You have to improve your knowledge in cooking and baking to be eligible for a promotion. Your current rank is Specialist.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 60 in cooking and baking to advance in the ranks of the Baker and Cook League."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, "<", 60))
talkEntry:addCondition(condition_quest(714, "=", 11))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Keep on learning! You have to improve your knowledge in cooking and baking to be eligible for a promotion. Your current rank is Specialist.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 60 in cooking and baking to advance in the ranks of the Baker and Cook League."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, "<", 60))
talkEntry:addCondition(condition_quest(714, "=", 11))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Weiterlernen! Ihr müsst Euer Wissen als Koch und Bäcker verbessern, um befördert zu werden. Ihr werdet im Rang eines Spezialistens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 60 in Kochen und Backen um in der Liga der Köche und Bäcker aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, ">", 69))
talkEntry:addCondition(condition_quest(714, "=", 12))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Adept with the Baker and Cook League of Runewick. You are awarded five bottles of milk."))
talkEntry:addConsequence(consequence_item(2502, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 13))
talkEntry:addResponse("Very well. I see you do everything to improve your knowledge. The Baker and Cook League of Runewick supports your way to wisdom with some bottles of milk. Come back to me once you have improved your knowledge.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, ">", 69))
talkEntry:addCondition(condition_quest(714, "=", 12))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Adept with the Baker and Cook League of Runewick. You are awarded fifty nuts."))
talkEntry:addConsequence(consequence_item(2502, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 13))
talkEntry:addResponse("Very well. I see you do everything to improve your knowledge. The Baker and Cook League of Runewick supports your way to wisdom with some bottles of milk. Come back to me once you have improved your knowledge.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, ">", 69))
talkEntry:addCondition(condition_quest(714, "=", 12))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Liga der Köche und Bäcker von Runewick erhebt dich in den Rang eines Adeptens. Du erhältst fünf Flaschen Milch."))
talkEntry:addConsequence(consequence_item(2502, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 13))
talkEntry:addResponse("Ausgezeichnet. Wie ich sehe, tut Ihr alles um Euer Wissen zu erweitern. Die Liga der Köche und Bäcker von Runewick unterstützt Euren Weg zu Können und Weisheit mit einigen Flaschen Milch. Kommt erneut zu mir, wenn Ihr mehr könnt.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, "<", 70))
talkEntry:addCondition(condition_quest(714, "=", 12))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Keep on learning! You have to improve your knowledge in cooking and baking to be eligible for a promotion. Your current rank is Expert.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 70 in cooking and baking to advance in the ranks of the Baker and Cook League."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, "<", 70))
talkEntry:addCondition(condition_quest(714, "=", 12))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Keep on learning! You have to improve your knowledge in cooking and baking to be eligible for a promotion. Your current rank is Expert.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 70 in cooking and baking to advance in the ranks of the Baker and Cook League."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, "<", 70))
talkEntry:addCondition(condition_quest(714, "=", 12))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Weiterlernen! Ihr müsst Euer Wissen als Koch und Bäcker verbessern, um befördert zu werden. Ihr werdet im Rang eines Expertens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 70 in Kochen und Backen um in der Liga der Köche und Bäcker aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, ">", 79))
talkEntry:addCondition(condition_quest(714, "=", 13))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Artisan with the Baker and Cook League of Runewick. You are awarded twenty bottles of beer."))
talkEntry:addConsequence(consequence_item(2501, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 14))
talkEntry:addResponse("Very well. I see you do everything to improve your knowledge. The Baker and Cook League of Runewick supports your way to wisdom with some bottles of beer. Come back to me once you have improved your knowledge.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, ">", 79))
talkEntry:addCondition(condition_quest(714, "=", 13))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Artisan with the Baker and Cook League of Runewick. You are awarded twenty bottles of beer."))
talkEntry:addConsequence(consequence_item(2501, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 14))
talkEntry:addResponse("Very well. I see you do everything to improve your knowledge. The Baker and Cook League of Runewick supports your way to wisdom with some bottles of beer. Come back to me once you have improved your knowledge.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, ">", 79))
talkEntry:addCondition(condition_quest(714, "=", 13))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Liga der Köche und Bäcker von Runewick erhebt dich in den Rang eines Artisanens. Du erhältst zwanzig Flaschen Bier."))
talkEntry:addConsequence(consequence_item(2501, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 14))
talkEntry:addResponse("Ausgezeichnet. Wie ich sehe, tut Ihr alles um Euer Wissen zu erweitern. Die Liga der Köche und Bäcker von Runewick unterstützt Euren Weg zu Können und Weisheit mit einigen Flaschen Bier. Kommt erneut zu mir, wenn Ihr mehr könnt.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, "<", 80))
talkEntry:addCondition(condition_quest(714, "=", 13))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Wisdom doesn't come easy. We know that well. But you are already an Adept.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 80 in cooking and baking to advance in the ranks of the Baker and Cook League."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, "<", 80))
talkEntry:addCondition(condition_quest(714, "=", 13))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Wisdom doesn't come easy. We know that well. But you are already an Adept.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 80 in cooking and baking to advance in the ranks of the Baker and Cook League."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, "<", 80))
talkEntry:addCondition(condition_quest(714, "=", 13))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Weisheit ist schwer zu erlangen. Das braucht Ihr mir nicht erklären. Ihr seid ja bereits ein Adept.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 80 in Kochen und Backen um in der Liga der Köche und Bäcker aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, ">", 89))
talkEntry:addCondition(condition_quest(714, "=", 14))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Master with the Baker and Cook League of Runewick. You are awarded five pieces of pure air and a special tool."))
talkEntry:addConsequence(consequence_item(2551, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 15))
talkEntry:addResponse("Very well. I see you do everything to improve your knowledge. The Baker and Cook League of Runewick supports your way to wisdom with some pure air and this engraved spoon. Come back to me once you have improved your knowledge.")
talkEntry:addConsequence(consequence_item(227, 1, 999, {["descriptionEn"] = "Master of the Baker and Cook League of Runewick", ["descriptionDe"] = "Meister der Liga der Bäcker und Köche von Runewick", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, ">", 89))
talkEntry:addCondition(condition_quest(714, "=", 14))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Master with the Baker and Cook League of Runewick. You are awarded five pieces of pure air and a special tool."))
talkEntry:addConsequence(consequence_item(2551, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 15))
talkEntry:addResponse("Very well. I see you do everything to improve your knowledge. The Baker and Cook League of Runewick supports your way to wisdom with some pure air and this engraved spoon. Come back to me once you have improved your knowledge.")
talkEntry:addConsequence(consequence_item(227, 1, 999, {["descriptionEn"] = "Master of the Baker and Cook League of Runewick", ["descriptionDe"] = "Meister der Liga der Bäcker und Köche von Runewick", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, ">", 89))
talkEntry:addCondition(condition_quest(714, "=", 14))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Liga der Köche und Bäcker von Runewick erhebt dich in den Rang eines Meisters. Du erhältst fünf Stück reiner Luft und ein besonderes Werkzeug."))
talkEntry:addConsequence(consequence_item(2551, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 15))
talkEntry:addResponse("Ausgezeichnet. Wie ich sehe, tut Ihr alles um Euer Wissen zu erweitern. Die Liga der Köche und Bäcker von Runewick unterstützt Euren Weg zu Können und Weisheit mit etwas reiner Luft und diesem besonderen Kochlöffel. Kommt erneut zu mir, wenn Ihr mehr könnt.")
talkEntry:addConsequence(consequence_item(227, 1, 999, {["descriptionEn"] = "Master of the Baker and Cook League of Runewick", ["descriptionDe"] = "Meister der Liga der Bäcker und Köche von Runewick", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, "<", 90))
talkEntry:addCondition(condition_quest(714, "=", 14))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Wisdom doesn't come easy. We know that well. But you are already an Artisan.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 90 in cooking and baking to advance in the ranks of the Baker and Cook League."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, "<", 90))
talkEntry:addCondition(condition_quest(714, "=", 14))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Wisdom doesn't come easy. We know that well. But you are already an Artisan.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 90 in cooking and baking to advance in the ranks of the Baker and Cook League."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, "<", 90))
talkEntry:addCondition(condition_quest(714, "=", 14))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Weisheit ist schwer zu erlangen. Das braucht Ihr mir nicht erklären. Ihr seid ja bereits ein Artisan.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 90 in Kochen und Backen um in der Liga der Köche und Bäcker aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, ">", 99))
talkEntry:addCondition(condition_quest(714, "=", 15))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Grandmaster with the Baker and Cook League of Runewick. You are awarded ten pieces of pure fire and a grandmaster's medal."))
talkEntry:addConsequence(consequence_item(2553, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 16))
talkEntry:addResponse("Grandmaster of the Baker and Cook League of Runewick. You shall bear this title proudly from this day on. With this pure fire, you shall help made the most valuable goods of Illarion.")
talkEntry:addConsequence(consequence_item(3535, 1, 999, {["descriptionEn"] = "Grandmaster of the Baker and Cook League of Runewick", ["descriptionDe"] = "Großmeister der Liga der Köche und Bäcker von Runewick", ["nameDe"] = "Großmeistermedallie", ["nameEn"] = "Grandmaster's Medal", ["rareness"] = "2"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, ">", 99))
talkEntry:addCondition(condition_quest(714, "=", 15))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Grandmaster with the Baker and Cook League of Runewick. You are awarded ten pieces of pure fire and a grandmaster's medal."))
talkEntry:addConsequence(consequence_item(2553, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 16))
talkEntry:addResponse("Grandmaster of the Baker and Cook League of Runewick. You shall bear this title proudly from this day on. With this pure fire, you shall help made the most valuable goods of Illarion.")
talkEntry:addConsequence(consequence_item(3535, 1, 999, {["descriptionEn"] = "Grandmaster of the Baker and Cook League of Runewick", ["descriptionDe"] = "Großmeister der Liga der Köche und Bäcker von Runewick", ["nameDe"] = "Großmeistermedallie", ["nameEn"] = "Grandmaster's Medal", ["rareness"] = "2"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, ">", 99))
talkEntry:addCondition(condition_quest(714, "=", 15))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Liga der Köche und Bäcker von Runewick erhebt dich in den Rang eines Großmeisters. Du erhältst zehn Stück reines Feuer und eine Großmeistermedallie."))
talkEntry:addConsequence(consequence_item(2553, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(714, "=", 16))
talkEntry:addResponse("Großmeister der Liga der Köche und Bäcker von Runewick. Tragt diesen Titel mit Stolz. Mit diesem reinen Feuer werdet Ihr die teuersten Waren Illarions herstellen.")
talkEntry:addConsequence(consequence_item(3535, 1, 999, {["descriptionEn"] = "Grandmaster of the Baker and Cook League of Runewick", ["descriptionDe"] = "Großmeister der Liga der Köche und Bäcker von Runewick", ["nameDe"] = "Großmeistermedallie", ["nameEn"] = "Grandmaster's Medal", ["rareness"] = "2"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, "<", 100))
talkEntry:addCondition(condition_quest(714, "=", 15))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Wisdom doesn't come easy. We know that well. But you are already a Master.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 100 in cooking and baking to advance in the ranks of the Baker and Cook League."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, "<", 100))
talkEntry:addCondition(condition_quest(714, "=", 15))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Wisdom doesn't come easy. We know that well. But you are already a Master.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 100 in cooking and baking to advance in the ranks of the Baker and Cook League."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.cookingAndBaking, "<", 100))
talkEntry:addCondition(condition_quest(714, "=", 15))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Weisheit ist schwer zu erlangen. Das braucht Ihr mir nicht erklären. Ihr seid ja bereits ein Meister.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 100 in Kochen und Backen um in der Liga der Köche und Bäcker aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(714, "=", 16))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Grandmaster %CHARNAME. Sounds pretty awesome, doesn't it?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(714, "=", 16))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addResponse("Grandmaster %CHARNAME. Sounds pretty awesome, doesn't it?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(714, "=", 16))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addResponse("Großmeister %CHARNAME. Klingt klasse, oder?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("The Baker and Cook League is restricted to Runewick's citizens.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addResponse("The Baker and Cook League is restricted to Runewick's citizens.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addResponse("Die Liga der Köche und Bäcker steht nur Bürgern Runewicks offen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("elvaine")
talkEntry:addTrigger("morgan")
talkEntry:addResponse("The Archmage Elvaine Morgan patrons everybody who is willing to learn, this includes our league.")
talkEntry:addResponse("I wish I could understand everything Elvaine Morgan wrote.")
talkEntry:addResponse("Yesterday I was able to serve the Archmage a special dish.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Archmage")
talkEntry:addResponse("The Archmage Elvaine Morgan patrons everybody who is willing to learn, this includes our league.")
talkEntry:addResponse("I wish I could understand everything Elvaine Morgan wrote.")
talkEntry:addResponse("Yesterday I was able to serve the Archmage a special dish.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Erzmagier")
talkEntry:addTrigger("elvaine")
talkEntry:addTrigger("morgan")
talkEntry:addResponse("Der Erzmagier behütet jeden, der gewillt ist zu lernen. Auch unsere Liga.")
talkEntry:addResponse("Ich wünschte ich könnte verstehen, was Elvaine Morgan alles geschrieben hat.")
talkEntry:addResponse("Gestern durfte ich dem Erzmagier ein besonders Gericht auftischen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("farm")
talkEntry:addTrigger("field")
talkEntry:addTrigger("vegetable")
talkEntry:addTrigger("grain")
talkEntry:addResponse("I buy the food for my dishes from the farmers of our city.")
talkEntry:addResponse("On the fields in front of the city, almost everything a good cook needs grows.")
talkEntry:addResponse("You could plant everything yourself, but the farmers also want to sell something.")
talkEntry:addResponse("I only put fresh vegetables in the pot.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("landwirt")
talkEntry:addTrigger("feld")
talkEntry:addTrigger("gemüse")
talkEntry:addTrigger("getreide")
talkEntry:addResponse("Die Lebensmittel für meine Gerichte kaufe ich bei den Landwirten unserer Stadt.")
talkEntry:addResponse("Auf den Feldern vor der Stadt wächst fast alles was ein guter Koch braucht.")
talkEntry:addResponse("Man könnte ja alles selber anpflanzen, aber die Landwirte wollen ja auch was verkaufen.")
talkEntry:addResponse("Mir kommt nur frisches Gemüse in den Topf.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("honey")
talkEntry:addResponse("Mmmm... honey!")
talkEntry:addResponse("I'd eat all the honey myself, but cakes taste good, too. A hard decision, you know?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Honig")
talkEntry:addResponse("Mmmm... Honig!")
talkEntry:addResponse("Ich würde glatt den ganzen Honig aufessen, wenn Kuchen nicht auch so gut schmecken würden. Eine schwere Entscheidung. Versteht Ihr?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("god")
talkEntry:addTrigger("temple")
talkEntry:addResponse("Many Gods have a temple in Runewick. Adron in the tavern, Ushara on the isle of earth, Tanora near the harbour, Bragon on the isle of fire, Oldra in Yewdale, Elara in the library, Eldan on the isle of the Archmage and Findari here on the isle of air.")
talkEntry:addResponse("You may find temples to the Old and the Younger Gods in Runewick.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Gott")
talkEntry:addTrigger("Tempel")
talkEntry:addResponse("Viele Götter haben einen Tempel in Runewick. Adron in der Taverne, Ushara auf der Insel der Erde, Tanora in der Nähe des Hafens, Bragon auf der Insel des Feuers, Oldra in Eibenthal, Elara in der Bücherei, Eldan auf der Insel der Erzmagiers und Findari hier bei uns auf der Insel der Luft.")
talkEntry:addResponse("Hier in Runewick findet Ihr Tempel der alten und der jungen Götter.")
talkingNPC:addTalkingEntry(talkEntry)
end
talkingNPC:addCycleText("#me rührt den Eintopf, der über dem Feuer brodelt, um.", "#me stirs a pot of stew bubbling over the fire.")
talkingNPC:addCycleText("Wenn Ihr Hilfe beim Kochen und Backen braucht, dann fragt nur mich!", "If you need any help with baking and cooking, just ask me!")
talkingNPC:addCycleText("#me schaut sich freundlich um.", "#me looks around friendly.")
talkingNPC:addCycleText("#me pfeift eine Melodie.", "#me whistles a melody.")
talkingNPC:addCycleText("#me liest einen Brief.", "#me reads a letter.")
talkingNPC:addCycleText("#me schneidet eine Zwiebel in kleine Stücke und weint dabei.", "#me carefully cuts some onions into small pieces, a tear rolling from her eye.")
talkingNPC:addCycleText("Das ist das beste Gericht, das ich je gemacht habe!", "This is the best dish I have ever made!")
talkingNPC:addCycleText("Die geheime Zutat ist eine Prise Liebe!", "The secret ingredient is a pinch of love!")
talkingNPC:addCycleText("#me wendet ein Stück Fleisch welches über dem Feuer brät.", "#me turns a piece of meat roasting over the fire.")
mainNPC:addLanguage(0)
mainNPC:addLanguage(1)
mainNPC:setDefaultLanguage(0)
mainNPC:setLookat("Dieser NPC ist Francine Leonard die Köchin und Bäckerin.", "This NPC is Francine Leonard the cook and baker.")
mainNPC:setUseMessage("Fass mich nicht an!", "Hands off!")
mainNPC:setConfusedMessage("#me schaut dich verwirrt an.", "#me looks at you confused.")
mainNPC:setEquipment(1, 0)
mainNPC:setEquipment(3, 182)
mainNPC:setEquipment(11, 2419)
mainNPC:setEquipment(5, 0)
mainNPC:setEquipment(6, 0)
mainNPC:setEquipment(4, 0)
mainNPC:setEquipment(9, 843)
mainNPC:setEquipment(10, 0)
mainNPC:setAutoIntroduceMode(true)

mainNPC:initDone()
return mainNPC
end
local mNPC = initNpc()
initNpc = nil
local M = {}
function M.receiveText(npcChar, texttype, message, speaker) mNPC:receiveText(npcChar, texttype, speaker, message) end
function M.nextCycle(npcChar) mNPC:nextCycle(npcChar) end
function M.lookAtNpc(npcChar, char, mode) mNPC:lookAt(npcChar, char, mode) end
function M.useNPC(npcChar, char, counter, param) mNPC:use(npcChar, char) end
return M
