local consequence_trade = require("npc.base.consequence.trade")
local condition_language = require("npc.base.condition.language")
local basic = require("npc.base.basic")
local trade = require("npc.base.trade")
local talk = require("npc.base.talk")
local consequence_inform = require("npc.base.consequence.inform")
local function initNpc()
local mainNPC = basic()
mainNPC:setAffiliation(1)
local talkingNPC = talk(mainNPC)
local tradingNPC = trade(mainNPC)
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Help")
talkEntry:addConsequence(consequence_inform("[Game Help] This NPC is the blacksmith Frobenius. Keywords: buy, sell, trade, Hello, blacksmith, iron."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hilfe")
talkEntry:addConsequence(consequence_inform("[Spielhilfe] Dieser NPC ist der Schmied Frobenius. Schlüsselwörter: Kaufe, verkaufe, Handel, hallo, Schmied, Eisen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("sell")
talkEntry:addTrigger("buy")
talkEntry:addTrigger("wares")
talkEntry:addTrigger("price")
talkEntry:addTrigger("trade")
talkEntry:addTrigger("purchase")
talkEntry:addResponse("A sharp blade to kill some scum? Here you go.")
talkEntry:addResponse("Choose wisely as your life depends on your armour.")
talkEntry:addConsequence(consequence_trade(tradingNPC))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("kauf")
talkEntry:addTrigger("waren")
talkEntry:addTrigger("preis")
talkEntry:addTrigger("Handel")
talkEntry:addTrigger("veräußer")
talkEntry:addTrigger("veräusser")
talkEntry:addTrigger("erwerb")
talkEntry:addResponse("Eine scharfe Klinge um damit etwas Abschaum niederzustrecken? Wir wäre es mit dieser?")
talkEntry:addResponse("Wählt weise, denn euer Leben hängt von eurer Rüstung ab.")
talkEntry:addConsequence(consequence_trade(tradingNPC))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hello")
talkEntry:addTrigger("Greet")
talkEntry:addTrigger("Hail")
talkEntry:addTrigger("Good day")
talkEntry:addTrigger("Good morning")
talkEntry:addTrigger("Good evening")
talkEntry:addTrigger("Good night")
talkEntry:addResponse("Let's get to business, alright?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Grüß")
talkEntry:addTrigger("Gruß")
talkEntry:addTrigger("Grüss")
talkEntry:addTrigger("Gruss")
talkEntry:addTrigger("Guten Morgen")
talkEntry:addTrigger("Guten Tag")
talkEntry:addTrigger("Guten Abend")
talkEntry:addTrigger("Gute Nacht")
talkEntry:addTrigger("Mahlzeit")
talkEntry:addTrigger("Tach")
talkEntry:addTrigger("Moin")
talkEntry:addTrigger("Mohltied")
talkEntry:addResponse("Lasst uns zum Geschäft kommen, ja?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Hiho")
talkEntry:addTrigger("Hallo")
talkEntry:addTrigger("Hey")
talkEntry:addTrigger("Greeb")
talkEntry:addResponse("Let's get to business, alright?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hiho")
talkEntry:addTrigger("Hallo")
talkEntry:addTrigger("Hey")
talkEntry:addTrigger("Greeb")
talkEntry:addResponse("Lasst uns zum Geschäft kommen, ja?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Farewell")
talkEntry:addTrigger("Bye")
talkEntry:addTrigger("Fare well")
talkEntry:addTrigger("See you")
talkEntry:addResponse("Kill some scum with my weapons, will you?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Tschüß")
talkEntry:addTrigger("Tschüss")
talkEntry:addTrigger("Wiedersehen")
talkEntry:addTrigger("Gehab wohl")
talkEntry:addResponse("Tötet Abschaum mit meinen Waffen, ja?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Ciao")
talkEntry:addTrigger("Adieu")
talkEntry:addTrigger("Au revoir")
talkEntry:addTrigger("Farebba")
talkEntry:addResponse("Kill some scum with my weapons, will you?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Ciao")
talkEntry:addTrigger("Adieu")
talkEntry:addTrigger("Au revoir")
talkEntry:addTrigger("Farebba")
talkEntry:addResponse("Tötet Abschaum mit meinen Waffen, ja?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("How are you")
talkEntry:addTrigger("How feel")
talkEntry:addTrigger("How do you do")
talkEntry:addResponse("Pardon me, but I do not want to talk about my feelings.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Wie geht")
talkEntry:addTrigger("Wie fühlst")
talkEntry:addTrigger("Wie ist es ergangen")
talkEntry:addResponse("Entschuldigt, aber ich möchte nicht über meine Gefühle reden.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("your name")
talkEntry:addTrigger("who are you")
talkEntry:addTrigger("who art thou")
talkEntry:addResponse("Frobenius!")
talkEntry:addResponse("I am Frobenius, the blacksmith.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("ihr name")
talkEntry:addTrigger("dein name")
talkEntry:addTrigger("wer bist du")
talkEntry:addTrigger("wer seid ihr")
talkEntry:addTrigger("wie heißt")
talkEntry:addTrigger("wie heisst")
talkEntry:addResponse("Frobenius!")
talkEntry:addResponse("Ich bin Frobenius, der Schmied.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Your quest today: Defend Cadomyr with my weapons. You have to buy one first...")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Euer Auftrag heute: Verteidigt Cadomyr mit meinen Waffen. Ihr müßt aber erstmal eine kaufen...")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addResponse("Your quest today: Defend Cadomyr with my weapons. You have to buy one first...")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addResponse("Euer Auftrag heute: Verteidigt Cadomyr mit meinen Waffen. Ihr müßt aber erstmal eine kaufen...")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("profession")
talkEntry:addResponse("I am a blacksmith, that means I craft weapons of death.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("beruf")
talkEntry:addResponse("Ich bin ein Schmied. Das bedeutet, ich fertige Waffen des Todes.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("job")
talkEntry:addResponse("I am a blacksmith, that means I craft weapons of death.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("job")
talkEntry:addResponse("Ich bin ein Schmied. Das bedeutet, ich fertige Waffen des Todes.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Gobaith")
talkEntry:addTrigger("Gobiath")
talkEntry:addResponse("That reminds me of a story I once heard... a very sad story.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Gobaith")
talkEntry:addTrigger("Gobiath")
talkEntry:addResponse("Das erinnert mich an eine alte Geschichte, die ich einst hörte... eine traurige Geschichte.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("my name")
talkEntry:addResponse("Ah.")
talkEntry:addResponse("Well?")
talkEntry:addResponse("Need weapons?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("mein Name")
talkEntry:addResponse("Aha.")
talkEntry:addResponse("Nun?")
talkEntry:addResponse("Braucht ihr eine Waffe?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("iron")
talkEntry:addResponse("Iron is tough, stiff and hard... The perfect material for weapons.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Eisen")
talkEntry:addResponse("Eisen ist zäh, steif und hart. Das perfekte Material für Waffen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Erz")
talkEntry:addResponse("Eisen gewinnt man aus Erzen. Cadomyr hat zwar keine reichen Minen, aber wir machen das beste daraus.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("ore")
talkEntry:addResponse("Iron you can make from ore. Cadomyr does not have rich mines, but we're doing our best.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("steel")
talkEntry:addResponse("What is that supposed to be?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Stahl")
talkEntry:addResponse("Was soll das sein?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("smith")
talkEntry:addResponse("Use my forged items to smite the foes of Cadomyr.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Schmied")
talkEntry:addResponse("Benutze meine Schmiedewaren um die Feinde Cadomyrs zu zerschmettern.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("trader")
talkEntry:addTrigger("merchant")
talkEntry:addTrigger("collegue")
talkEntry:addTrigger("vendor")
talkEntry:addTrigger("market")
talkEntry:addResponse("Buy whatever you want on this marketplace, but in the end only weapons will make Cadomyr prosper.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("händler")
talkEntry:addTrigger("kollege")
talkEntry:addTrigger("höker")
talkEntry:addTrigger("markt")
talkEntry:addResponse("Kauft, was immer ihr wollt auf diesem Marktplatz, aber am Ende werden nur Waffen Cadomyr voran bringen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("archmage")
talkEntry:addResponse("The Archmage is the best that could happen to Runewick. He is such a bad leader that we do not have to bother about Runewick too much.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Erzmagier")
talkEntry:addResponse("Der Erzmagier ist das beste, was Runewick passieren konnte. Er ist so ein schlechter Anführer, dass wir uns nicht um Runewick sorgen müssen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Elvaine")
talkEntry:addTrigger("Morgan")
talkEntry:addResponse("The Archmage is the best that could happen to Runewick. He is such a bad leader that we do not have to bother about Runewick too much.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Elvaine")
talkEntry:addTrigger("Morgan")
talkEntry:addResponse("Der Erzmagier ist das beste, was Runewick passieren konnte. Er ist so ein schlechter Anführer, dass wir uns nicht um Runewick sorgen müssen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Runewick")
talkEntry:addResponse("Runewick will fall to ruins one day, so do not bother. If you do, I have a good sword for you.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Runewick")
talkEntry:addResponse("Runewick wird eines Tages eine Ruine sein, sorgt euch nicht. Wenn ihr euch dennoch sorgt, ich habe ein gutes Schwert für euch.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Valerio")
talkEntry:addTrigger("Guilianni")
talkEntry:addTrigger("Don")
talkEntry:addResponse("I assume the dagger that will slash the Don's throat has already been crafted... Hopefully, by me.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Valerio")
talkEntry:addTrigger("Guilianni")
talkEntry:addTrigger("Don")
talkEntry:addResponse("Ich denke, dass der Dolch, der die Kehle des Dons aufschlitzen wird, bereits gefertigt wurde. Hoffentlich ist es einer von meinen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Galmair")
talkEntry:addResponse("Galmair is rich, but they don't use their wealth properly, like for buying weapons.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Galmair")
talkEntry:addResponse("Galmair ist reich, aber sie verstehen es nicht, ihren Reichtum richtig einzusetzen, zum Beispiel, um Waffen zu kaufen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Queen")
talkEntry:addResponse("Any weapon I craft is meant to protect the Queen. So, raise your hand against the Queen and hundreds of swords will chop it off.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Königin")
talkEntry:addResponse("Jede Waffe, die ich schmiede, ist gemacht, um die Königin zu schützen. Erhebe deine Hand gegen sie und hunderte Schwerter werden sie abschlagen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("rosaline")
talkEntry:addTrigger("edwards")
talkEntry:addResponse("Any weapon I craft is meant to protect the Queen. So, raise your hand against the Queen and hundreds of swords will chop it off.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("rosaline")
talkEntry:addTrigger("edwards")
talkEntry:addResponse("Jede Waffe, die ich schmiede, ist gemacht, um die Königin zu schützen. Erhebe deine Hand gegen sie und hunderte Schwerter werden sie abschlagen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Cadomyr")
talkEntry:addResponse("Cadomyr is our home and I hope my goods help to defend it against any enemies.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Cadomyr")
talkEntry:addResponse("Cadomyr ist unsere Heimat und ich hoffe, meine Waren leisten ihren Beitrag, es gegen Feinde zu verteidigen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("albar")
talkEntry:addResponse("Spears and swords built the Albarian kingdom. Need any?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("albar")
talkEntry:addResponse("Speere und Schwerter haben Albar aufgebaut. Braucht ihr welche?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("gynk")
talkEntry:addTrigger("gync")
talkEntry:addResponse("Gynk is far away and their weapons are lies and treason.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("gync")
talkEntry:addTrigger("gynk")
talkEntry:addResponse("Gynk ist weit entfernt und ihre Waffen sind Lügen und Verrat.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("salkama")
talkEntry:addResponse("Salkamaerian armour might shine brightly, but it is ineffective.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("salkama")
talkEntry:addResponse("Salkamaerische Rüstungen mögen funkeln und blitzen, aber sie sind nicht effektiv.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("god")
talkEntry:addResponse("I just have faith in Malachín and Irmorom. I mean, what use is Sirani, the Goddess of hugs?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Gott")
talkEntry:addTrigger("Götter")
talkEntry:addResponse("Ich vertraue nur auf Malachín und Irmorom. Ich meine, was ist der Nutzen von Sirani, Göttin der Umarmungen?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Malachin")
talkEntry:addTrigger("Malachín")
talkEntry:addResponse("Every sword I craft, I craft for Malachin himself.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Malachin")
talkEntry:addTrigger("Malachín")
talkEntry:addResponse("Jedes Schwert, welches ich schmiede, schmiede ich für Malachin!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Irmorom")
talkEntry:addResponse("Irmorom would be proud if he saw my art. I'm his most hard working scholar.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Irmorom")
talkEntry:addResponse("Irmorom wäre stolz, wenn er meine Schmiedekunst sehen würde. Ich bin sein fleißigster Schüler.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Sirani")
talkEntry:addResponse("Oh, come on, you don't want to talk to a person like me about Sirani, do you?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Sirani")
talkEntry:addResponse("Oh, ich denkt doch nicht etwa, dass ein Kerl wie ich gerne mit euch über Sirani reden will!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("tell something")
talkEntry:addResponse("I tell you, sharpen you blade and commit deeds for the glory of Cadomyr.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("erzähl was")
talkEntry:addTrigger("erzähl etwas")
talkEntry:addResponse("Ich sag euch: Schärft eure Klinge und vollbringt Taten für die Ehre von Cadomyr.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Frobenius")
talkEntry:addResponse("That's me.")
talkEntry:addResponse("Frobenius is my name and I am the local blacksmith.")
talkEntry:addResponse("My weapons bring doom over the foes of Cadomyr.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Frobenius")
talkEntry:addResponse("Das bin ich.")
talkEntry:addResponse("Frobenius ist meine Name und ich bin der Schmied hier.")
talkEntry:addResponse("Meine Waffen bringen Verderben über die Feinde Cadomyrs.")
talkingNPC:addTalkingEntry(talkEntry)
end
talkingNPC:addCycleText("#me knallt einen Hammer auf ein glühendes Stück Metall.", "#me slams a hammer on a glowing piece of metal.")
talkingNPC:addCycleText("Was!", "What!")
talkingNPC:addCycleText("Hört auf zu glotzen, kauft, oder geht weiter!", "Stop looking, buy something or go away.")
talkingNPC:addCycleText("Scharfe Klingen, beste Helme für die Schlacht!", "Sharp blades, best helmets for battle!")
talkingNPC:addCycleText("Meine Klingen sind zum Töten da, nicht zum Holzschnitzen.", "My swords are made to kill, not to carve wood.")
talkingNPC:addCycleText("Hier gibt es die besten Waffen zum Töten von Orks und Galmairern!", "Best weapons for killing orcs and Galmairians!")
talkingNPC:addCycleText("Ihr da! Eure Waffe ist der letzte Schrott. Ich hätte da was im Angebot für euch.", "Hey you! Your weapon is scrap. I'd have something for you.")
talkingNPC:addCycleText("#me poliert eine Schwertklinge.", "#me polishes the blade of a sword.")
talkingNPC:addCycleText("Jeden Tag eine gute Tat.", "An axe a day keeps the raptor away.")
talkingNPC:addCycleText("Heute ist ein guter Tag zum Sterben... für die Feinde der Königin!", "Today is a good day to die fighting the foes of the Queen.")
talkingNPC:addCycleText("Meine Schwerter werden niemals stumpf.", "My swords never go blunt.")
talkingNPC:addCycleText("Ich habe eine gute Waffe für euch.", "I have a good weapon for you.")
talkingNPC:addCycleText("Vielleicht wollt ihr einen Helm?", "Per chance you want a helmet?")
tradingNPC:addItem(trade.tradeNPCItem(2709,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(23,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1507,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1508,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1057,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1056,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1058,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1509,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1054,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1460,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1461,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1462,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1463,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1464,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(528,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1465,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1485,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2194,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1486,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1487,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2193,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1488,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1489,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(324,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(16,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1425,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2444,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1426,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2441,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1427,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(101,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2359,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2360,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1095,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2403,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1438,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(696,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1439,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1520,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1513,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(326,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1514,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1515,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1055,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1516,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(771,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1470,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(325,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1471,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1472,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1473,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(529,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1474,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1475,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1492,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2117,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1493,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1494,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2116,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1495,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1496,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(202,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1429,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(187,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1430,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2290,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(94,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1431,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(4,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1441,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2364,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1443,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1442,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1444,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2395,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1445,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2369,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2390,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(27,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(189,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1524,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(398,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(190,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2740,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(389,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2629,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2711,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2946,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(192,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(229,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(124,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2776,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(25,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(78,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2757,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2701,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(85,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2723,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(88,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(383,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(188,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1525,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(204,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1526,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2738,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2537,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(739,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(466,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2645,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(294,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2709,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2752,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(737,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2751,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(122,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(23,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(74,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2710,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(47,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2495,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2763,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2715,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2697,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2746,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(9,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(6,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(271,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(24,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(126,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2140,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(58,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(3918,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1507,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1508,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1057,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1056,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1058,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1509,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1054,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1510,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1511,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(699,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1512,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1460,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1461,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1462,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1463,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1464,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(528,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1465,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1466,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1467,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1468,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1469,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1485,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2194,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1486,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1487,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2193,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1488,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1489,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2112,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1490,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2111,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1491,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(324,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(16,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1425,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2444,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1426,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2441,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1427,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2302,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1428,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2291,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2286,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(101,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2359,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2360,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1095,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2403,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1438,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(696,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1439,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2389,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1440,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2365,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2400,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1520,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1513,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(326,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1514,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1515,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1055,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1516,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(771,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1517,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1518,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(770,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1519,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1470,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(325,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1471,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1472,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1473,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(529,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1474,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1475,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(530,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(531,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1476,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1477,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1492,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2117,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1493,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1494,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2116,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1495,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1496,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2172,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1497,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1498,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1499,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(202,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1429,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(187,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1430,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2290,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(94,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1431,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1432,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2287,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(184,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(185,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(4,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1441,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2364,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1443,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1442,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1444,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2395,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1445,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2369,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2390,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1446,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2367,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2393,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2363,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(27,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(189,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1524,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(398,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(190,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2740,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(389,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(297,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2672,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2675,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(91,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(444,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2671,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2742,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2629,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2711,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2946,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(192,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(229,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(124,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2642,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2660,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(296,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2662,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2776,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(25,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(78,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2757,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2701,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(85,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2658,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2778,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(98,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2775,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(84,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2788,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(206,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2704,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2693,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(123,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2656,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2654,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2723,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(88,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(383,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(188,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1527,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(205,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2627,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2640,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2626,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1525,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(204,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1526,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2731,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2738,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2537,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(739,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(466,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2645,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(294,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2709,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2752,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(737,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2751,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(122,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(23,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(74,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2710,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(47,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2495,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2763,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2715,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2697,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2746,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(9,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(6,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(271,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(24,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(126,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2140,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(58,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(3918,"buySecondary"))
tradingNPC:addNotEnoughMoneyMsg("Ich gewähre keine Rabatte.", "No discount today.")
tradingNPC:addDialogClosedMsg("Bis zum nächsten Mal.", "See you next time.")
tradingNPC:addDialogClosedNoTradeMsg("Adé.", "Adé.")
tradingNPC:addWrongItemMsg("Diesen Handel lehne ich ab.", "I decline this deal.")
mainNPC:addLanguage(0)
mainNPC:addLanguage(1)
mainNPC:setDefaultLanguage(0)
mainNPC:setLookat("Dieser NPC ist der Schmied Frobenius.", "This NPC is the blacksmith Frobenius.")
mainNPC:setUseMessage("Fass mich nicht an!", "Do not touch me!")
mainNPC:setConfusedMessage("#me schaut verwirrt.", "#me looks around confused.")
mainNPC:setEquipment(1, 0)
mainNPC:setEquipment(3, 365)
mainNPC:setEquipment(11, 2419)
mainNPC:setEquipment(5, 23)
mainNPC:setEquipment(6, 0)
mainNPC:setEquipment(4, 48)
mainNPC:setEquipment(9, 34)
mainNPC:setEquipment(10, 53)
mainNPC:setAutoIntroduceMode(true)

mainNPC:initDone()
return mainNPC
end
local mNPC = initNpc()
initNpc = nil
local M = {}
function M.receiveText(npcChar, texttype, message, speaker) mNPC:receiveText(npcChar, texttype, speaker, message) end
function M.nextCycle(npcChar) mNPC:nextCycle(npcChar) end
function M.lookAtNpc(npcChar, char, mode) mNPC:lookAt(npcChar, char, mode) end
function M.useNPC(npcChar, char, counter, param) mNPC:use(npcChar, char) end
return M
