local consequence_trade = require("npc.base.consequence.trade")
local consequence_talkstate = require("npc.base.consequence.talkstate")
local condition_language = require("npc.base.condition.language")
local basic = require("npc.base.basic")
local trade = require("npc.base.trade")
local talk = require("npc.base.talk")
local consequence_inform = require("npc.base.consequence.inform")
local function initNpc()
local mainNPC = basic()
mainNPC:setAffiliation(3)
local talkingNPC = talk(mainNPC)
local tradingNPC = trade(mainNPC)
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Help")
talkEntry:addConsequence(consequence_inform("[Game Help] This NPC is Laramir Silverwood the carpenter. Keywords: buy, sell, trade."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hilfe")
talkEntry:addConsequence(consequence_inform("[Spielhilfe] Dieser NPC ist Laramir Silverwood der Schreiner. Schlüsselwörter: kaufe, verkaufe, Handel."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("sell")
talkEntry:addTrigger("buy")
talkEntry:addTrigger("wares")
talkEntry:addTrigger("price")
talkEntry:addTrigger("trade")
talkEntry:addTrigger("purchase")
talkEntry:addResponse("I trade in wooden goods. Feel free to take a look, my friend.")
talkEntry:addConsequence(consequence_trade(tradingNPC))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("kauf")
talkEntry:addTrigger("waren")
talkEntry:addTrigger("preis")
talkEntry:addTrigger("Handel")
talkEntry:addTrigger("veräußer")
talkEntry:addTrigger("veräusser")
talkEntry:addTrigger("erwerb")
talkEntry:addResponse("I handle mit hölzernen Waren. Bitte, sieh dich ruhig um, mein Freund!")
talkEntry:addConsequence(consequence_trade(tradingNPC))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hello")
talkEntry:addTrigger("Greet")
talkEntry:addTrigger("Hail")
talkEntry:addTrigger("Good day")
talkEntry:addTrigger("Good morning")
talkEntry:addTrigger("Good evening")
talkEntry:addTrigger("Good night")
talkEntry:addResponse("Be greeted, my friend. How are you today?")
talkEntry:addResponse("Greetings my friend. Did you come here to take a look at my wares?")
talkEntry:addResponse("#me smiles, 'Greetings, my friend.'")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Grüß")
talkEntry:addTrigger("Gruß")
talkEntry:addTrigger("Grüss")
talkEntry:addTrigger("Gruss")
talkEntry:addTrigger("Guten Morgen")
talkEntry:addTrigger("Guten Tag")
talkEntry:addTrigger("Guten Abend")
talkEntry:addTrigger("Gute Nacht")
talkEntry:addTrigger("Mahlzeit")
talkEntry:addTrigger("Tach")
talkEntry:addTrigger("Moin")
talkEntry:addTrigger("Mohltied")
talkEntry:addResponse("Seid Gegrüßt mein Freund. Wie geht es dir heute?")
talkEntry:addResponse("Grüße, mein Freund. Bist du gekommen um meine Ware zu bewundern?")
talkEntry:addResponse("#me lächelt 'Grüße, mein Freund.'")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Hiho")
talkEntry:addTrigger("Hallo")
talkEntry:addTrigger("Hey")
talkEntry:addTrigger("Greeb")
talkEntry:addResponse("Be greeted, my friend. How are you today?")
talkEntry:addResponse("Greetings my friend. Did you come here to take a look at my wares?")
talkEntry:addResponse("#me smiles, 'Greetings, my friend.'")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hiho")
talkEntry:addTrigger("Hallo")
talkEntry:addTrigger("Hey")
talkEntry:addTrigger("Greeb")
talkEntry:addResponse("Seid Gegrüßt mein Freund. Wie geht es dir heute?")
talkEntry:addResponse("Grüße, mein Freund. Bist du gekommen um meine Ware zu bewundern?")
talkEntry:addResponse("#me lächelt 'Grüße, mein Freund.'")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Farewell")
talkEntry:addTrigger("Bye")
talkEntry:addTrigger("Fare well")
talkEntry:addTrigger("See you")
talkEntry:addResponse("Farewell, my friend.")
talkEntry:addResponse("Stay safe, my friend!")
talkEntry:addResponse("May the Gods protect you, my friend!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Tschüß")
talkEntry:addTrigger("Tschüss")
talkEntry:addTrigger("Wiedersehen")
talkEntry:addTrigger("Gehab wohl")
talkEntry:addResponse("Lebt wohl, mein Freund.")
talkEntry:addResponse("Pass auf dich auf, mein Freund.")
talkEntry:addResponse("Mögen die Götter dich beschützen, mein Freund.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Ciao")
talkEntry:addTrigger("Adieu")
talkEntry:addTrigger("Au revoir")
talkEntry:addTrigger("Farebba")
talkEntry:addResponse("Farewell, my friend.")
talkEntry:addResponse("Stay safe, my friend!")
talkEntry:addResponse("May the Gods protect you, my friend!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Ciao")
talkEntry:addTrigger("Adieu")
talkEntry:addTrigger("Au revoir")
talkEntry:addTrigger("Farebba")
talkEntry:addResponse("Lebt wohl, mein Freund.")
talkEntry:addResponse("Pass auf dich auf, mein Freund.")
talkEntry:addResponse("Mögen die Götter dich beschützen, mein Freund.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("How are you")
talkEntry:addTrigger("How feel")
talkEntry:addTrigger("How do you do")
talkEntry:addResponse("Thank you for asking, my friend. I feel fine, and you?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Wie geht")
talkEntry:addTrigger("Wie fühlst")
talkEntry:addTrigger("Wie ist es ergangen")
talkEntry:addTrigger("Wie Befind")
talkEntry:addResponse("Danke der Nachfrage, mein Freund. Ich fühle mich gut. Und du?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("your name")
talkEntry:addTrigger("who are you")
talkEntry:addTrigger("who art thou")
talkEntry:addConsequence(consequence_talkstate("end"))
talkEntry:addResponse("My name is Laramir Silverwood, my friend.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("ihr name")
talkEntry:addTrigger("dein name")
talkEntry:addTrigger("wer bist du")
talkEntry:addTrigger("wer seid ihr")
talkEntry:addTrigger("wie heißt")
talkEntry:addTrigger("wie heisst")
talkEntry:addResponse("Mein Freund, ich heiße Laramir Silverwood.")
talkEntry:addResponse("Mein Name ist Laramir Silverwood, mein Freund.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_talkstate("end"))
talkEntry:addResponse("My friend there is nothing I could ask you to do, but I'm thankful for your concern.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Mein Freund, es gibt nichts um was ich dich bitten könnte. Aber ich bin dankbar für deine Sorge.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_talkstate("end"))
talkEntry:addResponse("My friend there is nothing I could ask you to do, but I'm thankful for your concern.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addResponse("Mein Freund, es gibt nichts um was ich dich bitten könnte. Aber ich bin dankbar für deine Sorge.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("profession")
talkEntry:addResponse("I'm an elven trader, my friend.")
talkEntry:addResponse("I'm an elven carpenter, my friend.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("beruf")
talkEntry:addResponse("Ich bin ein elfischer Händler, mein Freund.")
talkEntry:addResponse("Ich bin ein elfischer Schreiner, mein Freund.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("job")
talkEntry:addResponse("I'm an elven trader, my friend.")
talkEntry:addResponse("I'm an elven carpenter, my friend.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("job")
talkEntry:addResponse("Ich bin ein elfischer Händler, mein Freund.")
talkEntry:addResponse("Ich bin ein elfischer Schreiner, mein Freund.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("tell something")
talkEntry:addResponse("Do you like nice conversations, my friend? We have to learn how to talk with others from young age.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("erzähl was")
talkEntry:addResponse("Magst du nette Plaudereinen, mein Freund? Wir müssen von klein auf lernen mit anderen zu reden.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Gobaith")
talkEntry:addTrigger("Gobiath")
talkEntry:addResponse("Hmm... ask someone else if you want know about it.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Gobaith")
talkEntry:addTrigger("Gobiath")
talkEntry:addResponse("Hmm... fragt jemand anderen bezüglich dieses Ortes.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("my name")
talkEntry:addResponse("What a fine name, my friend.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("mein Name")
talkEntry:addResponse("Was für ein schöner Name, mein Freund.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Laramir")
talkEntry:addTrigger("Silverwood")
talkEntry:addResponse("Yes, that is my name.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Laramir")
talkEntry:addTrigger("Silverwood")
talkEntry:addResponse("Ja, das ist mein Name.")
talkingNPC:addTalkingEntry(talkEntry)
end
talkingNPC:addCycleText("#me gähnt.", "#me yawns.")
talkingNPC:addCycleText("#me blickt herum mit geschlossenen Augen.", "#me looks around with closed eyes.")
talkingNPC:addCycleText("#me untersucht seine Kleidung.", "#me examines his clothes.")
talkingNPC:addCycleText("#me kämmt sein Haar.", "#me combs his hair.")
talkingNPC:addCycleText("#me isst einen Apfel.", "#me eats an apple.")
talkingNPC:addCycleText("#me prüft seine Waren.", "#me examines his wares.")
talkingNPC:addCycleText("#me summt etwas vor sich hin.", "#me hums to himself.")
talkingNPC:addCycleText("#me streicht sein Hemd glatt.", "#me smoothes down his shirt.")
talkingNPC:addCycleText("Ich fürchte den Beginn von Mas.", "I dread the coming of Mas.")
tradingNPC:addItem(trade.tradeNPCItem(2752,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2715,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(9,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(312,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(74,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(64,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(237,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(445,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1045,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2664,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(230,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1521,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(231,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1522,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2737,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1044,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(226,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(65,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1531,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2646,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2714,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2708,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(70,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2525,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2530,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2548,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2572,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2584,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2528,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2541,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2561,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2566,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2567,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2570,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2585,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2527,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2544,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2549,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2573,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(90,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(532,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(533,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(335,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(333,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2185,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(391,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2717,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2719,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2744,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1059,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(374,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2445,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(17,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(18,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(917,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(19,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(20,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(186,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2388,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1046,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1038,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1047,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1049,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1040,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1048,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(77,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1042,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1090,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(39,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(40,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1528,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(57,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1529,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(76,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2031,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2935,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2952,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(51,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(72,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(118,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(121,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(227,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(258,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(312,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(429,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(734,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2781,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(4820,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(323,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(545,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(546,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2543,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2716,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(56,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(3,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(543,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(544,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2560,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(3786,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(314,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(463,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(64,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(237,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(322,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(445,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1045,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2664,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(230,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1521,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(231,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1522,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2737,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1044,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(226,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1523,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1041,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1043,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1052,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(65,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1531,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2646,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2714,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2708,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(70,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2685,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2780,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2718,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2727,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2525,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2530,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2548,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2572,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2584,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2528,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2541,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2561,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2566,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2567,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2570,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2585,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2527,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2544,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2549,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2573,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(90,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(532,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(533,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(335,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(332,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(333,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2185,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(391,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2717,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2719,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2744,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1059,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(374,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2445,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(17,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(18,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(917,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(19,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(20,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(186,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2388,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2448,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(95,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(96,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(916,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2284,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2447,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2439,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1046,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1038,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1047,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1049,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1040,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1048,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(77,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1042,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1053,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1039,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1050,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1051,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1090,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(39,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(40,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1528,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(57,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1529,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(76,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(209,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(207,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(208,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1530,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2031,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2935,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2952,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(293,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(51,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(72,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(118,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(121,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(227,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(258,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(312,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(429,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(734,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2781,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(4820,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(323,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2782,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2783,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2784,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2785,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(3608,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(545,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(546,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2543,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2716,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(56,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(3,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(543,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(544,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2560,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(3786,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(314,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(463,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(4618,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(4617,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(4620,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(4619,"buySecondary"))
tradingNPC:addNotEnoughMoneyMsg("Mein Freund, ich glaube du hast deine Münzen nicht gezählt.", "My friend, I think you forgot to count your coins.")
tradingNPC:addDialogClosedMsg("Komm wieder, mein Freund.", "Please come again, my friend.")
tradingNPC:addDialogClosedNoTradeMsg("Bis zum nächsten mal, mein Freund.", "Hope to see you again, my friend!")
tradingNPC:addWrongItemMsg("Mein Freund, was soll ich mit diesem Gegenstand?", "My friend, what shall I use this thing for?")
mainNPC:addLanguage(0)
mainNPC:addLanguage(3)
mainNPC:setDefaultLanguage(0)
mainNPC:setLookat("Dieser NPC ist Laramir Silverwood der Schreiner.", "This NPC is Laramir Silverwood the carpenter.")
mainNPC:setUseMessage("Fasst mich nicht an!", "Do not touch me!")
mainNPC:setConfusedMessage("#me lächelt und zuckt mit den Schultern.", "#me smilies and shrugs his shoulders.")
mainNPC:setEquipment(1, 0)
mainNPC:setEquipment(3, 364)
mainNPC:setEquipment(11, 196)
mainNPC:setEquipment(5, 335)
mainNPC:setEquipment(6, 0)
mainNPC:setEquipment(4, 48)
mainNPC:setEquipment(9, 183)
mainNPC:setEquipment(10, 369)
mainNPC:setAutoIntroduceMode(true)

mainNPC:initDone()
return mainNPC
end
local mNPC = initNpc()
initNpc = nil
local M = {}
function M.receiveText(npcChar, texttype, message, speaker) mNPC:receiveText(npcChar, texttype, speaker, message) end
function M.nextCycle(npcChar) mNPC:nextCycle(npcChar) end
function M.lookAtNpc(npcChar, char, mode) mNPC:lookAt(npcChar, char, mode) end
function M.useNPC(npcChar, char, counter, param) mNPC:use(npcChar, char) end
return M
