local consequence_item = require("npc.base.consequence.item")
local condition_item = require("npc.base.condition.item")
local consequence_quest = require("npc.base.consequence.quest")
local condition_skill = require("npc.base.condition.skill")
local condition_language = require("npc.base.condition.language")
local consequence_deleteitem = require("npc.base.consequence.deleteitem")
local basic = require("npc.base.basic")
local condition_town = require("npc.base.condition.town")
local talk = require("npc.base.talk")
local consequence_money = require("npc.base.consequence.money")
local condition_quest = require("npc.base.condition.quest")
local consequence_inform = require("npc.base.consequence.inform")
local function initNpc()
local mainNPC = basic()
mainNPC:setAffiliation(1)
local talkingNPC = talk(mainNPC)
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Help")
talkEntry:addConsequence(consequence_inform("[Game Help] This NPC is Lilli Gallfing the tailor. Keywords: Hello, Quest, Tailoring."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hilfe")
talkEntry:addConsequence(consequence_inform("[Spielhilfe] Dieser NPC ist Lilli Gallfing die Schneiderin. Schlüsselwörter: Hallo, Quest, Schneidern."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hello")
talkEntry:addTrigger("Greet")
talkEntry:addTrigger("Hail")
talkEntry:addTrigger("Good day")
talkEntry:addTrigger("Good morning")
talkEntry:addTrigger("Good Evening")
talkEntry:addResponse("So nice of you to visit me. What can I do for you on this lovely day?")
talkEntry:addResponse("I like talking to people like you. So, what shall we talk about?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Grüß")
talkEntry:addTrigger("Gruß")
talkEntry:addTrigger("Grüss")
talkEntry:addTrigger("Gruss")
talkEntry:addTrigger("Guten Morgen")
talkEntry:addTrigger("Guten Tag")
talkEntry:addTrigger("Guten Abend")
talkEntry:addTrigger("Gute Nacht")
talkEntry:addTrigger("Mahlzeit")
talkEntry:addTrigger("Tach")
talkEntry:addTrigger("Moin")
talkEntry:addTrigger("Mohltied")
talkEntry:addResponse("Das ist ja nett von dir, mich zu besuchen. Was kann ich an diesem schönen Tag für dich tun?")
talkEntry:addResponse("Ich mag es, mit Leuten wir dir zu reden. Also, über was wollen wir uns unterhalten?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Hiho")
talkEntry:addTrigger("Hallo")
talkEntry:addTrigger("Hey")
talkEntry:addTrigger("Greeb")
talkEntry:addResponse("So nice of you to visit me. What can I do for you on this lovely day?")
talkEntry:addResponse("I like talking to people like you. So, what shall we talk about?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hiho")
talkEntry:addTrigger("Hallo")
talkEntry:addTrigger("Hey")
talkEntry:addTrigger("Greeb")
talkEntry:addResponse("Das ist ja nett von dir, mich zu besuchen. Was kann ich an diesem schönen Tag für dich tun?")
talkEntry:addResponse("Ich mag es, mit Leuten wir dir zu reden. Also, über was wollen wir uns unterhalten?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Farewell")
talkEntry:addTrigger("Bye")
talkEntry:addTrigger("Fare well")
talkEntry:addTrigger("See you")
talkEntry:addResponse("Thank you and see you soon. Visit me again.")
talkEntry:addResponse("See you later.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Tschüß")
talkEntry:addTrigger("Tschüss")
talkEntry:addTrigger("Wiedersehen")
talkEntry:addResponse("Danke und auf Wiedersehen. Schau bald mal wieder rein.")
talkEntry:addResponse("Bis bald!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Ciao")
talkEntry:addTrigger("Adieu")
talkEntry:addTrigger("Au revoir")
talkEntry:addTrigger("Farebba")
talkEntry:addResponse("Thank you and see you soon. Visit me again.")
talkEntry:addResponse("See you later.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Ciao")
talkEntry:addTrigger("Adieu")
talkEntry:addTrigger("Au revoir")
talkEntry:addTrigger("Farebba")
talkEntry:addResponse("Danke und auf Wiedersehen. Schau bald mal wieder rein.")
talkEntry:addResponse("Bis bald!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("How are you")
talkEntry:addTrigger("How feel")
talkEntry:addTrigger("How do you do")
talkEntry:addResponse("All is fine, as usual. Why should I complain, anyway?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Wie geht")
talkEntry:addTrigger("Wie fühlst")
talkEntry:addTrigger("Wie ist es ergangen")
talkEntry:addTrigger("Wie Befind")
talkEntry:addResponse("Alles bestens, wie immer. Warum sollte ich auch klagen?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("your name")
talkEntry:addTrigger("who are you")
talkEntry:addTrigger("who art thou")
talkEntry:addResponse("I'm Lilli Gallfing, but you can also call me Miss Moonshine. I provide her Majesty with her gowns.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("ihr name")
talkEntry:addTrigger("dein name")
talkEntry:addTrigger("wer bist du")
talkEntry:addTrigger("wer seid ihr")
talkEntry:addTrigger("wie heißt")
talkEntry:addTrigger("wie heisst")
talkEntry:addResponse("Ich bin Lilli Gallfing, aber du kannst mich auch Fräulein Mondschein nennen. Ich versorge ihre Majestät mit Gewändern.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("sell")
talkEntry:addTrigger("buy")
talkEntry:addTrigger("wares")
talkEntry:addTrigger("price")
talkEntry:addTrigger("trade")
talkEntry:addTrigger("purchase")
talkEntry:addResponse("I am not a trader. But I can teach you how to tailor.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("kauf")
talkEntry:addTrigger("waren")
talkEntry:addTrigger("preis")
talkEntry:addTrigger("Handel")
talkEntry:addTrigger("veräußer")
talkEntry:addTrigger("veräusser")
talkEntry:addTrigger("erwerb")
talkEntry:addResponse("Ich bin keine Marktfrau. Aber ich kann dir das Schneiderhandwerk beibringen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("profession")
talkEntry:addResponse("Tailoring is my passion. To craft marvellous robes that cover beautiful bodies is just amazing, isn't it?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("beruf")
talkEntry:addResponse("Schneidern ist meine Leidenschaft. Wunderbare Roben zu nähen, die schöne Körper umschmeicheln, ist das nicht klasse?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("job")
talkEntry:addResponse("Tailoring is my passion. To craft marvellous robes that cover beautiful bodies is just amazing, isn't it?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("job")
talkEntry:addResponse("Schneidern ist meine Leidenschaft. Wunderbare Roben zu nähen, die schöne Körper umschmeicheln, ist das nicht klasse?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("tailor")
talkEntry:addTrigger("craft")
talkEntry:addResponse("So you think tailoring just takes a needle and some practice? Ha! You need various tools and a lot of experience in different actions to get anywhere. Scissors for cutting, a dye rod for dyeing and do not forget the razor blade for tanning.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Schneider")
talkEntry:addTrigger("Handwerk")
talkEntry:addResponse("Du denkst also, dass man für das Schneidern nur eine Nadel und etwas Übung braucht? Ha! Du wirst viele Werkzeuge und viel Erfahrung brauchen, um irgendetwas zu erreichen. Du brauchst eine Schere fürs Zuschneiden, einen Färberstab zum Einfärben und vergiss nicht die das Rasiermesser fürs Gerben.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(705, "=", 0))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_item(6, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 1))
talkEntry:addResponse("Oh, you want to join the Royal Tailors? Well, let's start with something simple. Collect twenty bales of wool. You can find sheep if you leave the city and follow the road to the west. You can have my old scissors to collect the wool.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Royal Tailors of Cadomyr I. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(705, "=", 0))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_item(6, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 1))
talkEntry:addResponse("Oh, you want to join the Royal Tailors? Well, let's start with something simple. Collect twenty bales of wool. You can find sheep if you leave the city and follow the road to the west. You can have my old scissors to collect the wool.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Royal Tailors of Cadomyr I. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(705, "=", 0))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addConsequence(consequence_item(6, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 1))
talkEntry:addResponse("Oh, du willst den königlichen Schneidern beitreten? Nun gut, fangen wir mit etwas Einfachem an. Bringt mir doch bitte zwanzig Wollballen. Schafe solltest du finden, wenn du die Stadt verlässt und nach Westen gehst. Hier noch eine Schere, um die Schafe zu scheren.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Die königlichen Schneider von Cadomyr I. Detaillierte Informationen findest du im Questlog (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(705, "=", 1))
talkEntry:addCondition(condition_item(170, "all", ">", 19, nil))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_quest(705, "=", 2))
talkEntry:addResponse("Ah, so you have found the sheep, well done. Keep the bales of wool for your next task.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Ask Lilli Gallfing for your next task."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(705, "=", 1))
talkEntry:addCondition(condition_item(170, "all", ">", 19, nil))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("wool")
talkEntry:addConsequence(consequence_quest(705, "=", 2))
talkEntry:addResponse("Ah, so you have found the sheep, well done. Keep the bales of wool for your next task.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Ask Lilli Gallfing for your next task."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(705, "=", 1))
talkEntry:addCondition(condition_item(170, "all", ">", 19, nil))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Woll")
talkEntry:addConsequence(consequence_quest(705, "=", 2))
talkEntry:addResponse("Ah, also hast du die Schafe gefunden, gut gemacht. Behalte die Wollballen für die nächste Aufgabe.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Frage Lilli Gallfing nach deiner nächsten Aufgaben."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(705, "=", 1))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("That isn't twenty bales of wool yet. Please come back once you've finished this task.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(705, "=", 1))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("wool")
talkEntry:addResponse("That isn't twenty bales of wool yet. Please come back once you've finished this task.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(705, "=", 1))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Woll")
talkEntry:addResponse("Das sind noch keine zwanzig Wollballen. Komm wieder, wenn du die Aufgabe erledigt hast.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(705, "=", 2))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_quest(705, "=", 3))
talkEntry:addResponse("You want to learn more? Alright, please go to the loom behind me and weave ten bolts of grey cloth. Furthermore, go to the spinning wheel over there and produce ten spools of thread from the remaining wool.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Royal Tailors of Cadomyr II. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(705, "=", 2))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_quest(705, "=", 3))
talkEntry:addResponse("You want to learn more? Alright, please go to the loom behind me and weave ten bolts of grey cloth. Furthermore, go to the spinning wheel over there and produce ten spools of thread from the remaining wool.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Royal Tailors of Cadomyr II. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(705, "=", 2))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addConsequence(consequence_quest(705, "=", 3))
talkEntry:addResponse("Du willst mehr lernen? Bitte geh zum Webstuhl hinter mir und webe zehn Bahnen grauen Stoff und aus der restlichen Wolle beim Spinnrad da vorne zehn Spulen Garn.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Die königlichen Schneider von Cadomyr II. Detaillierte Informationen findest du im Questlog (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(705, "=", 3))
talkEntry:addCondition(condition_item(176, "all", ">", 9, nil))
talkEntry:addCondition(condition_item(50, "all", ">", 9, nil))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_quest(705, "=", 4))
talkEntry:addResponse("I see you made great progress. Now you have everything for your final task. Upon completion, I can accept in the ranks of the Royal Tailors.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Ask Lilli Gallfing for your next task."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(705, "=", 3))
talkEntry:addCondition(condition_item(176, "all", ">", 9, nil))
talkEntry:addCondition(condition_item(50, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("cloth")
talkEntry:addTrigger("thread")
talkEntry:addConsequence(consequence_quest(705, "=", 4))
talkEntry:addResponse("I see you made great progress. Now you have everything for your final task. Upon completion, I can accept in the ranks of the Royal Tailors.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Ask Lilli Gallfing for your next task."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(705, "=", 3))
talkEntry:addCondition(condition_item(176, "all", ">", 9, nil))
talkEntry:addCondition(condition_item(50, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Stoff")
talkEntry:addTrigger("Garn")
talkEntry:addConsequence(consequence_quest(705, "=", 4))
talkEntry:addResponse("Wie ich sehe, hast du gute Fortschritte gemacht. Du hast nun alles für deine letzte Aufgabe. Wenn du sie erledigt hast, kann ich dich bei den königlichen Schneider willkommen heißen.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Frage Lilli Gallfing nach deiner nächsten Aufgaben."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(705, "=", 3))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Thread and cloth is the minimum you need to become a successful tailor.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(705, "=", 3))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("cloth")
talkEntry:addTrigger("thread")
talkEntry:addResponse("Thread and cloth is the minimum you need to become a successful tailor.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(705, "=", 3))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Stoff")
talkEntry:addTrigger("Garn")
talkEntry:addResponse("Garn und Stoff ist das Mindeste, was du brauchst, um ein erfolgreicher Schneider zu werden.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(705, "=", 4))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_item(47, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 5))
talkEntry:addResponse("I think you are ready for real tailoring work, aren't you? Take this needle and sew ten pairs of grey cloth gloves. They are fairly easy to make but you'll see once you go to the tailoring table.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Royal Tailors of Cadomyr III. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(705, "=", 4))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_item(47, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 5))
talkEntry:addResponse("I think you are ready for real tailoring work, aren't you? Take this needle and sew ten pairs of grey cloth gloves. They are fairly easy to make but you'll see once you go to the tailoring table.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Royal Tailors of Cadomyr III. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(705, "=", 4))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addConsequence(consequence_item(47, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 5))
talkEntry:addResponse("Ich denke, du bist bereit für echte Schneiderarbeit, richtig? Nimm diese Nadel und nähe zehn Paar graue Stoffhandschuhe. Sind recht einfach herzustellen, aber das wirst du schon am Schneidertisch selbst herausfinden.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Die königlichen Schneider von Cadomyr III. Detaillierte Informationen findest du im Questlog (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(705, "=", 5))
talkEntry:addCondition(condition_item(1447, "all", ">", 9, nil))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Layman with the Royal Tailors of Cadomyr. You are awarded twenty silver coins."))
talkEntry:addConsequence(consequence_deleteitem(1447, 10, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 6))
talkEntry:addConsequence(consequence_money("+", 2000))
talkEntry:addResponse("You are now a valuable member of the Royal Tailors of Cadomyr. For advanced products, you'll have to learn dyeing. But I am sure you can manage that without my help. I'll have a little something for you when you improved your skills.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(705, "=", 5))
talkEntry:addCondition(condition_item(1447, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("cloth")
talkEntry:addTrigger("glove")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Layman with the Royal Tailors of Cadomyr. You are awarded twenty silver coins."))
talkEntry:addConsequence(consequence_deleteitem(1447, 10, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 6))
talkEntry:addConsequence(consequence_money("+", 2000))
talkEntry:addResponse("You are now a valuable member of the Royal Tailors of Cadomyr. For advanced products, you'll have to learn dyeing. But I am sure you can manage that without my help. I'll have a little something for you when you improved your skills.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(705, "=", 5))
talkEntry:addCondition(condition_item(1447, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Stoff")
talkEntry:addTrigger("Handschuh")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die königlichen Schneider von Cadomyr erheben dich in den Rang eines Laiens. Du erhältst zwanzig Silberstücke."))
talkEntry:addConsequence(consequence_deleteitem(1447, 10, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 6))
talkEntry:addConsequence(consequence_money("+", 2000))
talkEntry:addResponse("Du bist nun ein geschätztes Mitglied der königlichen Schneider. Für fortgeschrittene Produkte wirst du Färben lernen müssen. Aber das bekommst du auch ohne meine Hilfe hin. Ich habe eine kleine Überraschung für dich, sobald du deine Fertigkeiten verbessert hast.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(705, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Do you have any problems sewing ten pairs of cloth gloves? If you need any more resources, just shear some more wool and spin thread or weave cloth. Thomas Dalenus also sells all you need - at a price.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(705, "=", 5))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("cloth")
talkEntry:addTrigger("glove")
talkEntry:addResponse("Do you have any problems sewing ten pairs of cloth gloves? If you need any more resources, just shear some more wool and spin thread or weave cloth. Thomas Dalenus also sells all you need - at a price.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(705, "=", 5))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Stoff")
talkEntry:addTrigger("Handschuh")
talkEntry:addResponse("Gibt es Probleme beim Nähen von zehn Paaren Stoffhandschuhe? Wenn du mehr Material brauchst, schere etwas mehr Wolle und spinne Garn oder webe Stoff. Thomas Dalenus verkauft auch alles, was du benötigst - aber nicht gerade günstig.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, ">", 9))
talkEntry:addCondition(condition_quest(705, "=", 6))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Novice with the Royal Tailors of Cadomyr. You are awarded ten bales of wool."))
talkEntry:addConsequence(consequence_item(170, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 7))
talkEntry:addResponse("I am so excited about you making progress. The Royal Tailors sponsor you with some wool. Once you learned more, just come back to me.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, ">", 9))
talkEntry:addCondition(condition_quest(705, "=", 6))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Novice with the Royal Tailors of Cadomyr. You are awarded ten bales of wool."))
talkEntry:addConsequence(consequence_item(170, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 7))
talkEntry:addResponse("I am so excited about you making progress. The Royal Tailors sponsor you with some wool. Once you learned more, just come back to me.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, ">", 9))
talkEntry:addCondition(condition_quest(705, "=", 6))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die königlichen Schneider von Cadomyr erheben dich in den Rang eines Anfängers. Du erhältst zehn Ballen Wolle."))
talkEntry:addConsequence(consequence_item(170, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 7))
talkEntry:addResponse("Ich freue mich so zu sehen, dass du Fortschritte gemacht hast. Die königlichen Schneider geben dir etwas Wolle. Wenn du etwas dazugelernt hast, schau doch mal wieder vorbei.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, "<", 10))
talkEntry:addCondition(condition_quest(705, "=", 6))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("I am sorry but to advance in the ranks of the Royal Tailors, you have to become more experienced. Your current rank is Layman.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 10 in tailoring to advance in the ranks of the Royal Tailors."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, "<", 10))
talkEntry:addCondition(condition_quest(705, "=", 6))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("I am sorry but to advance in the ranks of the Royal Tailors, you have to become more experienced. Your current rank is Layman.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 10 in tailoring to advance in the ranks of the Royal Tailors."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, "<", 10))
talkEntry:addCondition(condition_quest(705, "=", 6))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Es tut mir leid, aber um bei den königlichen Schneidern aufzusteigen, musst du noch Erfahrung sammeln. Du wirst im Rang eines Laiens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 10 in Schneidern um bei den königlichen Schneider aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, ">", 19))
talkEntry:addCondition(condition_quest(705, "=", 7))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Apprentice with the Royal Tailors of Cadomyr. You are awarded twenty hides of raw leather."))
talkEntry:addConsequence(consequence_item(69, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 8))
talkEntry:addResponse("I am so excited about you making progress. The Royal Tailors sponsor you with some raw leather. Once you learned more, just come back to me.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, ">", 19))
talkEntry:addCondition(condition_quest(705, "=", 7))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Apprentice with the Royal Tailors of Cadomyr. You are awarded twenty hides of raw leather."))
talkEntry:addConsequence(consequence_item(69, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 8))
talkEntry:addResponse("I am so excited about you making progress. The Royal Tailors sponsor you with some raw leather. Once you learned more, just come back to me.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, ">", 19))
talkEntry:addCondition(condition_quest(705, "=", 7))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die königlichen Schneider von Cadomyr erheben dich in den Rang eines Lehrlings. Du erhältst zwanzig Häute Rohleder."))
talkEntry:addConsequence(consequence_item(69, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 8))
talkEntry:addResponse("Ich freue mich so zu sehen, dass du Fortschritte gemacht hast. Die königlichen Schneider geben dir etwas Rohleder. Wenn du etwas dazugelernt hast, schau doch mal wieder vorbei.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, "<", 20))
talkEntry:addCondition(condition_quest(705, "=", 7))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("I am sorry but to advance in the ranks of the Royal Tailors, you have to become more experienced. Your current rank is Novice.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 20 in tailoring to advance in the ranks of the Royal Tailors."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, "<", 20))
talkEntry:addCondition(condition_quest(705, "=", 7))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("I am sorry but to advance in the ranks of the Royal Tailors, you have to become more experienced. Your current rank is Novice.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 20 in tailoring to advance in the ranks of the Royal Tailors."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, "<", 20))
talkEntry:addCondition(condition_quest(705, "=", 7))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Es tut mir leid, aber um bei den königlichen Schneidern aufzusteigen, musst du noch Erfahrung sammeln. Du wirst im Rang eines Anfängers geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 20 in Schneidern um bei den königlichen Schneider aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, ">", 29))
talkEntry:addCondition(condition_quest(705, "=", 8))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Initiate with the Royal Tailors of Cadomyr. You are awarded ten spools of thread."))
talkEntry:addConsequence(consequence_item(50, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 9))
talkEntry:addResponse("I am so excited about you making progress. The Royal Tailors sponsor you with some thread. Once you learned more, just come back to me.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, ">", 29))
talkEntry:addCondition(condition_quest(705, "=", 8))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Initiate with the Royal Tailors of Cadomyr. You are awarded spools of thread."))
talkEntry:addConsequence(consequence_item(50, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 9))
talkEntry:addResponse("I am so excited about you making progress. The Royal Tailors sponsor you with some thread. Once you learned more, just come back to me.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, ">", 29))
talkEntry:addCondition(condition_quest(705, "=", 8))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die königlichen Schneider von Cadomyr erheben dich in den Rang eines Initiatens. Du erhältst zehn Spulen Garn."))
talkEntry:addConsequence(consequence_item(50, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 9))
talkEntry:addResponse("Ich freue mich so zu sehen, dass du Fortschritte gemacht hast. Die königlichen Schneider geben dir etwas Garn. Wenn du etwas dazugelernt hast, schau doch mal wieder vorbei.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, "<", 30))
talkEntry:addCondition(condition_quest(705, "=", 8))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("I am sorry but to advance in the ranks of the Royal Tailors, you have to become more experienced. Your current rank is Apprentice.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 30 in tailoring to advance in the ranks of the Royal Tailors."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, "<", 30))
talkEntry:addCondition(condition_quest(705, "=", 8))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("I am sorry but to advance in the ranks of the Royal Tailors, you have to become more experienced. Your current rank is Apprentice.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 30 in tailoring to advance in the ranks of the Royal Tailors."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, "<", 30))
talkEntry:addCondition(condition_quest(705, "=", 8))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Es tut mir leid, aber um bei den königlichen Schneidern aufzusteigen, musst du noch Erfahrung sammeln. Du wirst im Rang eines Lehrlings geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 30 in Schneidern um bei den königlichen Schneider aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, ">", 39))
talkEntry:addCondition(condition_quest(705, "=", 9))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Journeyman with the Royal Tailors of Cadomyr. You are awarded twenty hides of leather and a journeyman's certificate."))
talkEntry:addConsequence(consequence_item(2547, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 10))
talkEntry:addResponse("I am so excited about you making progress. The Royal Tailors sponsor you with some leather. Once you learned more, just come back to me.")
talkEntry:addConsequence(consequence_item(3109, 1, 333, {["descriptionEn"] = "The owner of this certificate has successfully passed the examination as Journeyman. Lilli Gallfing - Royal Tailors of Cadomyr", ["descriptionDe"] = "Der Inhaber dieses Gesellenbriefes hat erfolgreich das Examen zum Gesellen bestanden. Lilli Gallfing - Die königlichen Schneider von Cadomyr", ["nameDe"] = "Gesellenbrief", ["nameEn"] = "Journeyman's Certificate", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, ">", 39))
talkEntry:addCondition(condition_quest(705, "=", 9))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Journeyman with the Royal Tailors of Cadomyr. You are awarded twenty hides of leather and a journeyman's certificate."))
talkEntry:addConsequence(consequence_item(2547, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 10))
talkEntry:addResponse("I am so excited about you making progress. The Royal Tailors sponsor you with some leather. Once you learned more, just come back to me.")
talkEntry:addConsequence(consequence_item(3109, 1, 333, {["descriptionEn"] = "The owner of this certificate has successfully passed the examination as Journeyman. Lilli Gallfing - Royal Tailors of Cadomyr", ["descriptionDe"] = "Der Inhaber dieses Gesellenbriefes hat erfolgreich das Examen zum Gesellen bestanden. Lilli Gallfing - Die königlichen Schneider von Cadomyr", ["nameDe"] = "Gesellenbrief", ["nameEn"] = "Journeyman's Certificate", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, ">", 39))
talkEntry:addCondition(condition_quest(705, "=", 9))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die königlichen Schneider von Cadomyr erheben dich in den Rang eines Gesellens. Du erhältst zwanzig Lederhäute und einen Gesellenbrief."))
talkEntry:addConsequence(consequence_item(2547, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 10))
talkEntry:addResponse("Ich freue mich so zu sehen, dass du Fortschritte gemacht hast. Die königlichen Schneider geben dir etwas Leder. Wenn du etwas dazugelernt hast, schau doch mal wieder vorbei.")
talkEntry:addConsequence(consequence_item(3109, 1, 333, {["descriptionEn"] = "The owner of this certificate has successfully passed the examination as Journeyman. Lilli Gallfing - Royal Tailors of Cadomyr", ["descriptionDe"] = "Der Inhaber dieses Gesellenbriefes hat erfolgreich das Examen zum Gesellen bestanden. Lilli Gallfing - Die königlichen Schneider von Cadomyr", ["nameDe"] = "Gesellenbrief", ["nameEn"] = "Journeyman's Certificate", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, "<", 40))
talkEntry:addCondition(condition_quest(705, "=", 9))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("I am sorry but to advance in the ranks of the Royal Tailors, you have to become more experienced. Your current rank is Initiate.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 40 in tailoring to advance in the ranks of the Royal Tailors."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, "<", 40))
talkEntry:addCondition(condition_quest(705, "=", 9))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("I am sorry but to advance in the ranks of the Royal Tailors, you have to become more experienced. Your current rank is Initiate.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 40 in tailoring to advance in the ranks of the Royal Tailors."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, "<", 40))
talkEntry:addCondition(condition_quest(705, "=", 9))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Es tut mir leid, aber um bei den königlichen Schneidern aufzusteigen, musst du noch Erfahrung sammeln. Du wirst im Rang eines Initiatens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 40 in Schneidern um bei den königlichen Schneider aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, ">", 49))
talkEntry:addCondition(condition_quest(705, "=", 10))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Specialist with the Royal Tailors of Cadomyr. You are awarded ten bales of red cloth."))
talkEntry:addConsequence(consequence_item(174, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 11))
talkEntry:addResponse("I am so excited about you making progress. The Royal Tailors sponsor you with some red cloth. Once you learned more, just come back to me.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, ">", 49))
talkEntry:addCondition(condition_quest(705, "=", 10))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Specialist with the Royal Tailors of Cadomyr. You are awarded ten bales of red cloth."))
talkEntry:addConsequence(consequence_item(174, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 11))
talkEntry:addResponse("I am so excited about you making progress. The Royal Tailors sponsor you with some red cloth. Once you learned more, just come back to me.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, ">", 49))
talkEntry:addCondition(condition_quest(705, "=", 10))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die königlichen Schneider von Cadomyr erheben dich in den Rang eines Spezialistens. Du erhältst zehn Ballen roter Stoff."))
talkEntry:addConsequence(consequence_item(174, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 11))
talkEntry:addResponse("Ich freue mich so zu sehen, dass du Fortschritte gemacht hast. Die königlichen Schneider geben dir etwas roten Stoff. Wenn du etwas dazugelernt hast, schau doch mal wieder vorbei.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, "<", 50))
talkEntry:addCondition(condition_quest(705, "=", 10))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("I am sorry but to advance in the ranks of the Royal Tailors, you have to become more experienced. Your current rank is Journeyman.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 50 in tailoring to advance in the ranks of the Royal Tailors."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, "<", 50))
talkEntry:addCondition(condition_quest(705, "=", 10))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("I am sorry but to advance in the ranks of the Royal Tailors, you have to become more experienced. Your current rank is Journeyman.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 50 in tailoring to advance in the ranks of the Royal Tailors."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, "<", 50))
talkEntry:addCondition(condition_quest(705, "=", 10))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Es tut mir leid, aber um bei den königlichen Schneidern aufzusteigen, musst du noch Erfahrung sammeln. Du wirst im Rang eines Gesellens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 50 in Schneidern um bei den königlichen Schneider aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, ">", 59))
talkEntry:addCondition(condition_quest(705, "=", 11))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Expert with the Royal Tailors of Cadomyr. You are awarded twenty bales of blue cloth."))
talkEntry:addConsequence(consequence_item(179, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 12))
talkEntry:addResponse("I am so excited about you making progress. The Royal Tailors sponsor you with some blue cloth. Once you learned more, just come back to me.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, ">", 59))
talkEntry:addCondition(condition_quest(705, "=", 11))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Expert with the Royal Tailors of Cadomyr. You are awarded twenty bales of blue cloth."))
talkEntry:addConsequence(consequence_item(179, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 12))
talkEntry:addResponse("I am so excited about you making progress. The Royal Tailors sponsor you with some blue cloth. Once you learned more, just come back to me.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, ">", 59))
talkEntry:addCondition(condition_quest(705, "=", 11))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die königlichen Schneider von Cadomyr erheben dich in den Rang eines Expertens. Du erhältst zwanzig Ballen blauer Stoff."))
talkEntry:addConsequence(consequence_item(179, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 12))
talkEntry:addResponse("Ich freue mich so zu sehen, dass du Fortschritte gemacht hast. Die königlichen Schneider geben dir etwas blauen Stoff. Wenn du etwas dazugelernt hast, schau doch mal wieder vorbei.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, "<", 60))
talkEntry:addCondition(condition_quest(705, "=", 11))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("I am sorry but to advance in the ranks of the Royal Tailors, you have to become more experienced. Your current rank is Specialist.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 60 in tailoring to advance in the ranks of the Royal Tailors."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, "<", 60))
talkEntry:addCondition(condition_quest(705, "=", 11))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("I am sorry but to advance in the ranks of the Royal Tailors, you have to become more experienced. Your current rank is Specialist.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 60 in tailoring to advance in the ranks of the Royal Tailors."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, "<", 60))
talkEntry:addCondition(condition_quest(705, "=", 11))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Es tut mir leid, aber um bei den königlichen Schneidern aufzusteigen, musst du noch Erfahrung sammeln. Du wirst im Rang eines Spezialistens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 60 in Schneidern um bei den königlichen Schneider aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, ">", 69))
talkEntry:addCondition(condition_quest(705, "=", 12))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Adept with the Royal Tailors of Cadomyr. You are awarded five bales of silk."))
talkEntry:addConsequence(consequence_item(3787, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 13))
talkEntry:addResponse("I am so excited about you making progress. The Royal Tailors sponsor you with some silk. Once you learned more, just come back to me.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, ">", 69))
talkEntry:addCondition(condition_quest(705, "=", 12))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Adept with the Royal Tailors of Cadomyr. You are awarded five bales of silk."))
talkEntry:addConsequence(consequence_item(3787, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 13))
talkEntry:addResponse("I am so excited about you making progress. The Royal Tailors sponsor you with some silk. Once you learned more, just come back to me.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, ">", 69))
talkEntry:addCondition(condition_quest(705, "=", 12))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die königlichen Schneider von Cadomyr erheben dich in den Rang eines Adeptens. Du erhältst fünf Ballen Seide."))
talkEntry:addConsequence(consequence_item(3787, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 13))
talkEntry:addResponse("Ich freue mich so zu sehen, dass du Fortschritte gemacht hast. Die königlichen Schneider geben dir etwas Seide. Wenn du etwas dazugelernt hast, schau doch mal wieder vorbei.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, "<", 70))
talkEntry:addCondition(condition_quest(705, "=", 12))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("I am sorry but to advance in the ranks of the Royal Tailors, you have to become more experienced. Your current rank is Expert.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 70 in tailoring to advance in the ranks of the Royal Tailors."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, "<", 70))
talkEntry:addCondition(condition_quest(705, "=", 12))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("I am sorry but to advance in the ranks of the Royal Tailors, you have to become more experienced. Your current rank is Expert.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 70 in tailoring to advance in the ranks of the Royal Tailors."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, "<", 70))
talkEntry:addCondition(condition_quest(705, "=", 12))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Es tut mir leid, aber um bei den königlichen Schneidern aufzusteigen, musst du noch Erfahrung sammeln. Du wirst im Rang eines Expertens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 70 in Schneidern um bei den königlichen Schneider aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, ">", 79))
talkEntry:addCondition(condition_quest(705, "=", 13))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Artisan with the Royal Tailors of Cadomyr. You are awarded ten bales of silk."))
talkEntry:addConsequence(consequence_item(3787, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 14))
talkEntry:addResponse("I am so excited about you making progress. The Royal Tailors sponsor you with some silk. Once you learned more, just come back to me.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, ">", 79))
talkEntry:addCondition(condition_quest(705, "=", 13))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Artisan with the Royal Tailors of Cadomyr. You are awarded ten bales of silk."))
talkEntry:addConsequence(consequence_item(3787, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 14))
talkEntry:addResponse("I am so excited about you making progress. The Royal Tailors sponsor you with some silk. Once you learned more, just come back to me.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, ">", 79))
talkEntry:addCondition(condition_quest(705, "=", 13))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die königlichen Schneider von Cadomyr erheben dich in den Rang eines Artisanens. Du erhältst zehn Ballen Seide."))
talkEntry:addConsequence(consequence_item(3787, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 14))
talkEntry:addResponse("Ich freue mich so zu sehen, dass du Fortschritte gemacht hast. Die königlichen Schneider geben dir etwas Seide. Wenn du etwas dazugelernt hast, schau doch mal wieder vorbei.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, "<", 80))
talkEntry:addCondition(condition_quest(705, "=", 13))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("I am sorry but to advance in the ranks of the Royal Tailors, you have to become more experienced. Your current rank is Adept.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 80 in tailoring to advance in the ranks of the Royal Tailors."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, "<", 80))
talkEntry:addCondition(condition_quest(705, "=", 13))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("I am sorry but to advance in the ranks of the Royal Tailors, you have to become more experienced. Your current rank is Adept.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 80 in tailoring to advance in the ranks of the Royal Tailors."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, "<", 80))
talkEntry:addCondition(condition_quest(705, "=", 13))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Es tut mir leid, aber um bei den königlichen Schneidern aufzusteigen, musst du noch Erfahrung sammeln. Du wirst im Rang eines Adeptens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 80 in Schneidern um bei den königlichen Schneider aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, ">", 89))
talkEntry:addCondition(condition_quest(705, "=", 14))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Master with the Royal Tailors of Cadomyr. You are awarded five pieces of pure spirit and a special tool."))
talkEntry:addConsequence(consequence_item(3607, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 15))
talkEntry:addResponse("I am so excited about you making progress. The Royal Tailors sponsor you with some pure spirit. Once you learned more, just come back to me.")
talkEntry:addConsequence(consequence_item(47, 1, 999, {["descriptionEn"] = "Master of the Royal Tailors of Cadomyr", ["descriptionDe"] = "Meister der königlichen Schneider von Cadomyr", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, ">", 89))
talkEntry:addCondition(condition_quest(705, "=", 14))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Master with the Royal Tailors of Cadomyr. You are awarded five pieces of pure spirit and a special tool."))
talkEntry:addConsequence(consequence_item(3607, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 15))
talkEntry:addResponse("I am so excited about you making progress. The Royal Tailors sponsor you with some pure spirit. Once you learned more, just come back to me.")
talkEntry:addConsequence(consequence_item(47, 1, 999, {["descriptionEn"] = "Master of the Royal Tailors of Cadomyr", ["descriptionDe"] = "Meister der königlichen Schneider von Cadomyr", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, ">", 89))
talkEntry:addCondition(condition_quest(705, "=", 14))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die königlichen Schneider von Cadomyr erheben dich in den Rang eines Meisters. Du erhältst fünf Stück reiner Geist und ein besonderes Werkzeug."))
talkEntry:addConsequence(consequence_item(3607, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 15))
talkEntry:addResponse("Ich freue mich so zu sehen, dass du Fortschritte gemacht hast. Die königlichen Schneider geben dir etwas reinen Geist. Wenn du etwas dazugelernt hast, schau doch mal wieder vorbei.")
talkEntry:addConsequence(consequence_item(47, 1, 999, {["descriptionEn"] = "Master of the Royal Tailors of Cadomyr", ["descriptionDe"] = "Meister der königlichen Schneider von Cadomyr", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, "<", 90))
talkEntry:addCondition(condition_quest(705, "=", 14))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("I am sorry but to advance in the ranks of the Royal Tailors, you have to become more experienced. Your current rank is Artisan.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 90 in tailoring to advance in the ranks of the Royal Tailors."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, "<", 90))
talkEntry:addCondition(condition_quest(705, "=", 14))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("I am sorry but to advance in the ranks of the Royal Tailors, you have to become more experienced. Your current rank is Artisan.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 90 in tailoring to advance in the ranks of the Royal Tailors."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, "<", 90))
talkEntry:addCondition(condition_quest(705, "=", 14))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Es tut mir leid, aber um bei den königlichen Schneidern aufzusteigen, musst du noch Erfahrung sammeln. Du wirst im Rang eines Artisanens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 90 in Schneidern um bei den königlichen Schneider aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, ">", 99))
talkEntry:addCondition(condition_quest(705, "=", 15))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Grandmaster with the Royal Tailors of Cadomyr. You are awarded ten pieces of pure air and a grandmaster's medal."))
talkEntry:addConsequence(consequence_item(2551, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 16))
talkEntry:addResponse("Hooray! You are now a Grandmaster of the Royal Tailors of Cadomyr. Tailor the finest robes for her Majesty with this pure air.")
talkEntry:addConsequence(consequence_item(3535, 1, 999, {["descriptionEn"] = "Grandmaster of the Royal Tailors of Cadomyr", ["descriptionDe"] = "Großmeister der königlichen Schneider von Cadomyr", ["nameDe"] = "Großmeistermedallie", ["nameEn"] = "Grandmaster's Medal", ["rareness"] = "2"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, ">", 99))
talkEntry:addCondition(condition_quest(705, "=", 15))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Grandmaster with the Royal Tailors of Cadomyr. You are awarded ten pieces of pure air and a grandmaster's medal."))
talkEntry:addConsequence(consequence_item(2551, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 16))
talkEntry:addResponse("Hooray! You are now a Grandmaster of the Royal Tailors of Cadomyr. Tailor the finest robes for her Majesty with this pure air.")
talkEntry:addConsequence(consequence_item(3535, 1, 999, {["descriptionEn"] = "Grandmaster of the Royal Tailors of Cadomyr", ["descriptionDe"] = "Großmeister der königlichen Schneider von Cadomyr", ["nameDe"] = "Großmeistermedallie", ["nameEn"] = "Grandmaster's Medal", ["rareness"] = "2"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, ">", 99))
talkEntry:addCondition(condition_quest(705, "=", 15))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die königlichen Schneider von Cadomyr erheben dich in den Rang eines Großmeisters. Du erhältst zehn Stück reiner Luft und eine Großmeistermedallie."))
talkEntry:addConsequence(consequence_item(2551, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(705, "=", 16))
talkEntry:addResponse("Hurra! Du bist nun Großmeister der königlichen Schneider von Cadomyr. Nähe die feinsten Roben für Ihre Majestät mit dieser reinen Luft.")
talkEntry:addConsequence(consequence_item(3535, 1, 999, {["descriptionEn"] = "Grandmaster of the Royal Tailors of Cadomyr", ["descriptionDe"] = "Großmeister der königlichen Schneider von Cadomyr", ["nameDe"] = "Großmeistermedallie", ["nameEn"] = "Grandmaster's Medal", ["rareness"] = "2"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, "<", 100))
talkEntry:addCondition(condition_quest(705, "=", 15))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("I am sorry but to advance in the ranks of the Royal Tailors, you have to become more experienced. Your current rank is Master.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 100 in tailoring to advance in the ranks of the Royal Tailors."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, "<", 100))
talkEntry:addCondition(condition_quest(705, "=", 15))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("I am sorry but to advance in the ranks of the Royal Tailors, you have to become more experienced. Your current rank is Master.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 100 in tailoring to advance in the ranks of the Royal Tailors."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.tailoring, "<", 100))
talkEntry:addCondition(condition_quest(705, "=", 15))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Es tut mir leid, aber um bei den königlichen Schneidern aufzusteigen, musst du noch Erfahrung sammeln. Du wirst im Rang eines Meisters geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 100 in Schneidern um bei den königlichen Schneider aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(705, "=", 16))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Grandmaster %CHARNAME. Sounds good, doesn't it? The Royal Tailors salut you.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(705, "=", 16))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addResponse("Grandmaster %CHARNAME. Sounds good, doesn't it? The Royal Tailors salut you.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(705, "=", 16))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addResponse("Großmeister %CHARNAME. Klingt klasse, oder? Die königlichen Schneider grüßen dich.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Have you ever seen Cadomyrians wearing non-cadomyrian gowns? No? The Royal Tailors are all Cadomyrians!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addResponse("Have you ever seen Cadomyrians wearing non-cadomyrian gowns? No? The Royal Tailors are all Cadomyrians!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addResponse("Hast du schon mal einen Bürger Cadomyrs in einem Gewand gesehen, welches nicht aus Cadomyr stammt? Nein? Die königlichen Schneider sind alle aus Cadomyr.")
talkingNPC:addTalkingEntry(talkEntry)
end
talkingNPC:addCycleText("#me begutachtet die Qualität eines Stoffstückes.", "#me examines a piece of cloth for quality.")
talkingNPC:addCycleText("#me bestickt eine Robe mit einem Symbol.", "#me embroiders an emblem on a robe.")
talkingNPC:addCycleText("#me entfernt einen Fadenrest von ihrem Hemd.", "#me pulls a stray thread from her shirt.")
talkingNPC:addCycleText("Morgen mache ich ein Kleid für eine sehr wichtige Person.", "Tomorrow I am going to make a dress for a very important person!")
talkingNPC:addCycleText("Ich kenne mich aus mit feinsten Gewändern.", "I know everything about finest garments.")
talkingNPC:addCycleText("#me rollt eine Spule Garn auf.", "#me rolls up a clew of yarn.")
talkingNPC:addCycleText("#me legt bunte Hemden zusammen.", "#me folds coloured shirts.")
talkingNPC:addCycleText("#me pfeift eine fröhliche Melodie, während sie ein Kleid bestickt.", "#me whistles a merry melody as she embroiders a dress.")
mainNPC:addLanguage(0)
mainNPC:addLanguage(1)
mainNPC:setDefaultLanguage(0)
mainNPC:setLookat("Dieser NPC ist Lilli Gallfing die Schneiderin.", "This NPC is Lilli Gallfing the tailor.")
mainNPC:setUseMessage("Fass mich nicht an!", "Hands off!")
mainNPC:setConfusedMessage("#me schaut dich verwirrt an.", "#me looks at you confused.")
mainNPC:setEquipment(1, 0)
mainNPC:setEquipment(3, 834)
mainNPC:setEquipment(11, 0)
mainNPC:setEquipment(5, 0)
mainNPC:setEquipment(6, 0)
mainNPC:setEquipment(4, 0)
mainNPC:setEquipment(9, 0)
mainNPC:setEquipment(10, 369)
mainNPC:setAutoIntroduceMode(true)

mainNPC:initDone()
return mainNPC
end
local mNPC = initNpc()
initNpc = nil
local M = {}
function M.receiveText(npcChar, texttype, message, speaker) mNPC:receiveText(npcChar, texttype, speaker, message) end
function M.nextCycle(npcChar) mNPC:nextCycle(npcChar) end
function M.lookAtNpc(npcChar, char, mode) mNPC:lookAt(npcChar, char, mode) end
function M.useNPC(npcChar, char, counter, param) mNPC:use(npcChar, char) end
return M
