local consequence_item = require("npc.base.consequence.item")
local condition_item = require("npc.base.condition.item")
local consequence_quest = require("npc.base.consequence.quest")
local condition_skill = require("npc.base.condition.skill")
local condition_language = require("npc.base.condition.language")
local consequence_deleteitem = require("npc.base.consequence.deleteitem")
local basic = require("npc.base.basic")
local condition_town = require("npc.base.condition.town")
local talk = require("npc.base.talk")
local consequence_money = require("npc.base.consequence.money")
local condition_quest = require("npc.base.condition.quest")
local consequence_inform = require("npc.base.consequence.inform")
local function initNpc()
local mainNPC = basic()
mainNPC:setAffiliation(1)
local talkingNPC = talk(mainNPC)
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Help")
talkEntry:addConsequence(consequence_inform("[Game Help] This NPC is Nadime the glass blower. Keywords: Hello, quest, glass blowing."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hilfe")
talkEntry:addConsequence(consequence_inform("[Spielhilfe] Dieser NPC ist Nadime die Glasbläserin. Schlüsselwörter: Hallo, Quest, Glasblasen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hello")
talkEntry:addTrigger("Greet")
talkEntry:addTrigger("Hail")
talkEntry:addTrigger("Good day")
talkEntry:addTrigger("Good morning")
talkEntry:addTrigger("Good evening")
talkEntry:addTrigger("Good night")
talkEntry:addResponse("Nadime greets you.")
talkEntry:addResponse("Greetings, Greetings.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Grüß")
talkEntry:addTrigger("Gruß")
talkEntry:addTrigger("Guten Morgen")
talkEntry:addTrigger("Guten Tag")
talkEntry:addTrigger("Guten Abend")
talkEntry:addTrigger("Gute Nacht")
talkEntry:addTrigger("Mahlzeit")
talkEntry:addTrigger("Tach")
talkEntry:addTrigger("Moin")
talkEntry:addTrigger("Mohltied")
talkEntry:addResponse("Nadime grüßt dich.")
talkEntry:addResponse("Grüße, Grüße.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Hiho")
talkEntry:addTrigger("Hallo")
talkEntry:addTrigger("Hey")
talkEntry:addTrigger("Greeb")
talkEntry:addResponse("Nadime greets you.")
talkEntry:addResponse("Greetings, Greetings.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hiho")
talkEntry:addTrigger("Hallo")
talkEntry:addTrigger("Hey")
talkEntry:addTrigger("Greeb")
talkEntry:addResponse("Nadime grüßt dich.")
talkEntry:addResponse("Grüße, Grüße.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Farewell")
talkEntry:addTrigger("Bye")
talkEntry:addTrigger("Fare well")
talkEntry:addTrigger("See you")
talkEntry:addResponse("Revisit Nadime again.")
talkEntry:addResponse("Bye, Bye.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Tschüß")
talkEntry:addTrigger("Tschüss")
talkEntry:addTrigger("Wiedersehen")
talkEntry:addTrigger("Gehab wohl")
talkEntry:addResponse("Besuch Nadime bald wieder.")
talkEntry:addResponse("Bis bald.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Ciao")
talkEntry:addTrigger("Adieu")
talkEntry:addTrigger("Au revoir")
talkEntry:addResponse("Visit Nadime again.")
talkEntry:addResponse("Bye, Bye.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Ciao")
talkEntry:addTrigger("Adieu")
talkEntry:addTrigger("Au revoir")
talkEntry:addResponse("Besuch Nadime bald wieder.")
talkEntry:addResponse("Bis bald.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("How are you")
talkEntry:addTrigger("How feel")
talkEntry:addTrigger("How do you do")
talkEntry:addResponse("Great, it's warm enough here.")
talkEntry:addResponse("Good, good.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Wie geht")
talkEntry:addTrigger("Wie fühlst")
talkEntry:addTrigger("Wie ist es ergangen")
talkEntry:addResponse("Toll, alles schön warm hier.")
talkEntry:addResponse("Gut, gut.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("your name")
talkEntry:addTrigger("who are you")
talkEntry:addTrigger("who art thou")
talkEntry:addResponse("I'm Nadime. Nadime is a glass blower.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("ihr name")
talkEntry:addTrigger("dein name")
talkEntry:addTrigger("wer bist du")
talkEntry:addTrigger("wer seid ihr")
talkEntry:addTrigger("wie heißt")
talkEntry:addResponse("Ich bin Nadime. Nadime ist die Glasbläserin hier.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("sell")
talkEntry:addTrigger("buy")
talkEntry:addTrigger("wares")
talkEntry:addTrigger("price")
talkEntry:addTrigger("trade")
talkEntry:addTrigger("purchase")
talkEntry:addResponse("I am not a trader.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("kauf")
talkEntry:addTrigger("waren")
talkEntry:addTrigger("preis")
talkEntry:addTrigger("Handel")
talkEntry:addTrigger("veräußer")
talkEntry:addTrigger("veräusser")
talkEntry:addTrigger("erwerb")
talkEntry:addResponse("Ich bin kein Händler.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("profession")
talkEntry:addResponse("Nadime melts glass. Nadime forms glass into wonderful things.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("beruf")
talkEntry:addResponse("Nadime schmelzt Glas. Nadime formt schöne Glasdinge.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("job")
talkEntry:addResponse("Nadime melts glass. Nadime forms glass into wonderful things.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("job")
talkEntry:addResponse("Nadime schmilzt Glas. Nadime formt schöne Glasdinge.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("rosalie")
talkEntry:addTrigger("edwards")
talkEntry:addResponse("Rosalie Edwards is Queen of Cadomyr and patron of our guild.")
talkEntry:addResponse("I'm proud to serve the Queen as a craftsmen.")
talkEntry:addResponse("Long burns the fire in our Queen!")
talkEntry:addResponse("All the glass wares in the palace were made by our guild.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("queen")
talkEntry:addResponse("Rosalie Edwards is Queen of Cadomyr and patron of our guild.")
talkEntry:addResponse("I'm proud to serve the Queen as a craftsmen.")
talkEntry:addResponse("Long burns the fire in our Queen!")
talkEntry:addResponse("All the glass wares in the palace were made by our guild.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("rosalie")
talkEntry:addTrigger("edwards")
talkEntry:addTrigger("König")
talkEntry:addResponse("Rosalie Edwards ist Königin Cadomyrs und Schutzherrin unsere Zünfte.")
talkEntry:addResponse("Ich bin stolz der Königin als Handwerker zu dienen.")
talkEntry:addResponse("Lang brenne das Feuer in der Königin!")
talkEntry:addResponse("Alle Glaswaren im Palast stammen von unserer Zunft.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("sand")
talkEntry:addResponse("Sand ist eine wichtige Grundlage für das Glasblasen.")
talkEntry:addResponse("Nadime besorgt ihren Sand aus den Gruben um Cadomyr herum.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("sand")
talkEntry:addResponse("Sand is an important base for glass blowing.")
talkEntry:addResponse("Nadime finds her sand around Cadomyr.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Asche")
talkEntry:addResponse("Asche ist eine wichtige Grundlage für das Glasblasen, ja ist es.")
talkEntry:addResponse("Nadime nutzt besondere Asche, Nadime weiß, wie sie sie herstellt.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("ash")
talkEntry:addResponse("Ash is an important base for glass blowing.")
talkEntry:addResponse("Nadime uses special ash. Nadime knows how to produce it.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("imp")
talkEntry:addResponse("Most fire imps live isolated in warm volcanoes. They don't like other people there.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("imp")
talkEntry:addTrigger("kobold")
talkEntry:addResponse("Die meisten Feuerkobolde leben abgeschieden in schön warmen Vulkanen. Dort mögen sie keine Eindringlinge.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("god")
talkEntry:addResponse("Nadime only knows the Fire Father.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Gott")
talkEntry:addTrigger("Götter")
talkEntry:addResponse("Nadime kennt nur den Feuervater.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Bragon")
talkEntry:addTrigger("Brágon")
talkEntry:addResponse("The Fire Father makes big fires. He is very important for Nadime and her glass blowing.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Bragon")
talkEntry:addTrigger("Brágon")
talkEntry:addTrigger("Feuervater")
talkEntry:addResponse("Der Feuervater macht große und heiße Feuer. Sehr wichtig für Nadime und das Glasblasen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("glass")
talkEntry:addTrigger("blowing")
talkEntry:addTrigger("craft")
talkEntry:addResponse("Glass blowing is done at an oven with a glass blowing pipe. Mind that you first need glas ingots, cast into a mould.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Glasblasen")
talkEntry:addTrigger("handwerk")
talkEntry:addResponse("Glasblasen wird an einem Ofen mit einem Glasblasrohr ausgeübt. Bedenke, dass du zunächst Glasbarren in eine Form gießen musst.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(717, "=", 0))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_item(24, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 1))
talkEntry:addResponse("The Glassblowing Guild is proud to guide you on your apprenticeship. But honour comes from hard work. Take this shovel and collect ten shovels of sand from the sand pits in front of the gate.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Glassblowing Guild of Cadomyr I. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(717, "=", 0))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_item(24, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 1))
talkEntry:addResponse("The Glassblowing Guild is proud to guide you on your apprenticeship. But honour comes from hard work. Take this shovel and collect ten shovels of sand from the sand pits in front of the gate.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Glassblowing Guild of Cadomyr I. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(717, "=", 0))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addConsequence(consequence_item(24, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 1))
talkEntry:addResponse("Die Glasbläserzunft ist stolz, deine Ausbildung zu begleiten. Ehre zu erringen ist harte Arbeit. Nimm diese Schaufel und hole zehn Haufen Sand aus den Sandgruben vor den Toren der Stadt.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Die Glasbäserzunft von Cadomyr I. Detaillierte Informationen findest du im Questlog (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(717, "=", 1))
talkEntry:addCondition(condition_item(726, "all", ">", 9, nil))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_quest(717, "=", 2))
talkEntry:addResponse("Alright, you got the sand. But it takes more to become a real glass blower. Keep the sand for the next part of your apprenticeship.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Ask Nadime for your next task."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(717, "=", 1))
talkEntry:addCondition(condition_item(726, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("sand")
talkEntry:addConsequence(consequence_quest(717, "=", 2))
talkEntry:addResponse("Alright, you got the sand. But it takes more to become a real glass blower. Keep the sand for the next part of your apprenticeship.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Ask Nadime for your next task."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(717, "=", 1))
talkEntry:addCondition(condition_item(726, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("sand")
talkEntry:addConsequence(consequence_quest(717, "=", 2))
talkEntry:addResponse("Schön, du hast den Sand. Aber es erfordert schon noch etwas mehr, um ein Glasbläser zu werden. Behalte den Sand für den nächsten Schritt in deiner Ausbildung.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Frage Nadime nach deiner nächsten Aufgaben."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(717, "=", 1))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("This can't be happening. Am I surrounded by fools? As your master, I'll repeat my order: Get sand from the sandpits in front of the gates.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(717, "=", 1))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("sand")
talkEntry:addResponse("This can't be happening. Am I surrounded by fools? As your master, I'll repeat my order: Get sand from the sandpits in front of the gates.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(717, "=", 1))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Sand")
talkEntry:addResponse("Das kann doch nicht sein. Bin ich denn nur von Dummköpfen umgeben. Als dein Meister werde ich meine Anordnung noch einmal wiederholen: Hole Sand von den Sandgruben vor den Toren der Stadt!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(717, "=", 2))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_item(2710, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 3))
talkEntry:addResponse("I'm proud to introduce you into the real art. Let's melt glass. I'll give you an old mould and you bring back ten glass ingots. You will need potash and sand. But you better carefully sieve the sand in advance. I want to see your glass as clear as the diamonds in our queens crown.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Glassblowing Guild of Cadomyr II. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(717, "=", 2))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_item(2710, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 3))
talkEntry:addResponse("I'm proud to introduce you into the real art. Let's melt glass. I'll give you an old mould and you bring back ten glass ingots. You will need  potash and sand. But you better carefully sieve the sand in advance. I want to see your glass as clear as the diamonds in our queens crown.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Glassblowing Guild of Cadomyr II. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(717, "=", 2))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addConsequence(consequence_item(2710, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 3))
talkEntry:addResponse("Es ist mir eine Ehre, dich jetzt in die wahre Kunst einzuweisen. Wir werden Glas schmelzen. Ich gebe dir eine alte Gussform und du bringst mir zehn Glasblöcke zurück. Du brauchst Pottasche und Sand. Und siebe den Sand vorher sorgfältig. Ich will Glas sehen, das so rein ist wie die Diamanten in der Krone unserer Königin.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Die Glasbäserzunft von Cadomyr II. Detaillierte Informationen findest du im Questlog (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(717, "=", 3))
talkEntry:addCondition(condition_item(41, "all", ">", 9, nil))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_quest(717, "=", 4))
talkEntry:addResponse("You are able to make glass ingots. Wonderful. You'll need them for the next part of your apprenticeship.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Ask Nadime for your next task."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(717, "=", 3))
talkEntry:addCondition(condition_item(41, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("ingot")
talkEntry:addConsequence(consequence_quest(717, "=", 4))
talkEntry:addResponse("You are able to make glass ingots. Wonderful. You'll need them for the next part of your apprenticeship.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Ask Nadime for your next task."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(717, "=", 3))
talkEntry:addCondition(condition_item(41, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Barren")
talkEntry:addConsequence(consequence_quest(717, "=", 4))
talkEntry:addResponse("Du bist in der Lage, Glasbarren herzustellen. Wunderbar, du wirst sie für den nächsten Teil deiner Ausbildung benötigen.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Frage Nadime nach deiner nächsten Aufgaben."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(717, "=", 3))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Your task is to produce ten glass ingots in the glass melting oven. It would be honourable if you don't waste my time with unfinished tasks.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(717, "=", 3))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("ingot")
talkEntry:addResponse("Your task is to produce ten glass ingots in the glass melting oven. It would be honourable if you don't waste my time with unfinished tasks.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(717, "=", 3))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Barren")
talkEntry:addResponse("Deine Aufgabe ist es, zehn Glasbarren im Glasschmelzofen herzustellen. Es sollte dir eine Ehre sein, mich nicht mit unfertigen Aufgaben zu belästigen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(717, "=", 4))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_item(311, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 5))
talkEntry:addResponse("Well, it is about time I tell you how to manufacture bottles. Have this glass blow pipe and go to the glass melting oven. For starters, craft ten large empty bottles. It is not too difficult!")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Glassblowing Guild of Cadomyr III. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(717, "=", 4))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_item(311, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 5))
talkEntry:addResponse("Well, it is about time I tell you how to manufacture bottles. Have this glass blow pipe and go to the glass melting oven. For starters, craft ten large empty bottles. It is not too difficult!")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Glassblowing Guild of Cadomyr III. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(717, "=", 4))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addConsequence(consequence_item(311, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 5))
talkEntry:addResponse("Nun, ich glaube es ist an der Zeit, dir beizubringen, wie man Flaschen bläst. Nimm dieses Glasblasrohr und gehe zum Glasschmelzofen. Für den Anfang reicht es, wenn du zehn große leere Flaschen herstellst.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Die Glasbäserzunft von Cadomyr III. Detaillierte Informationen findest du im Questlog (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(717, "=", 5))
talkEntry:addCondition(condition_item(2498, "all", ">", 9, nil))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Layman with the Glassblowing Guild of Cadomyr. You are awarded thirty silver coins."))
talkEntry:addConsequence(consequence_deleteitem(2498, 10, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 6))
talkEntry:addConsequence(consequence_money("+", 3000))
talkEntry:addResponse("The Glassblowing Guild of Cadomyr is proud to have a new member. Here is some money to get you started. And come back once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(717, "=", 5))
talkEntry:addCondition(condition_item(2498, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("bottle")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Layman with the Glassblowing Guild of Cadomyr. You are awarded thirty silver coins."))
talkEntry:addConsequence(consequence_deleteitem(2498, 10, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 6))
talkEntry:addConsequence(consequence_money("+", 3000))
talkEntry:addResponse("The Glassblowing Guild of Cadomyr is proud to have a new member. Here is some money to get you started. And come back once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(717, "=", 5))
talkEntry:addCondition(condition_item(2498, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Flasche")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Glasbläserzunft von Cadomyr erhebt dich in den Rang eines Laiens. Du erhältst dreißig Silberstücke."))
talkEntry:addConsequence(consequence_deleteitem(2498, 10, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 6))
talkEntry:addConsequence(consequence_money("+", 3000))
talkEntry:addResponse("Die Glasbläserzunft von Cadomyr ist stolz, dich als neues Mitglied aufnehmen zu können. Hier ist etwas monetäre Starthilfe. Und komm zu mir zurück, sobald du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(717, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Please blame yourself. It's hard not to produce ten big empty bottles at the glass melting oven.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(717, "=", 5))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addResponse("Please blame yourself. It's hard not to produce ten big empty bottles at the glass melting oven.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(717, "=", 5))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addResponse("Blamier dich nicht. So schwer ist es doch nicht, zehn große leere Flaschen am Glasschmelzofen herzustellen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, ">", 9))
talkEntry:addCondition(condition_quest(717, "=", 6))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Novice with the Glassblowing Guild of Cadomyr. You are awarded ten logs of conifer wood."))
talkEntry:addConsequence(consequence_item(3, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 7))
talkEntry:addResponse("You honour yourself with your hard work, well done. The Glassblowing Guild of Cadomyr supports your efforts with some wood. Come back once you can tell me you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, ">", 9))
talkEntry:addCondition(condition_quest(717, "=", 6))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Novice with the Glassblowing Guild of Cadomyr. You are awarded ten logs of conifer wood."))
talkEntry:addConsequence(consequence_item(3, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 7))
talkEntry:addResponse("You honour yourself with your hard work, well done. The Glassblowing Guild of Cadomyr supports your efforts with some wood. Come back once you can tell me you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, ">", 9))
talkEntry:addCondition(condition_quest(717, "=", 6))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Glasbläserzunft von Cadomyr erhebt dich in den Rang eines Anfängers. Du erhältst zehn Nadelholzscheite."))
talkEntry:addConsequence(consequence_item(3, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 7))
talkEntry:addResponse("Du ehrst dich selber mit deiner harten Arbeit. Die Glasbläserzunft von Cadomyr unterstützt deine Bemühungen mit etwas Holz. Komm erneut zu mir, wenn du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, "<", 10))
talkEntry:addCondition(condition_quest(717, "=", 6))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("You haven't spent enough time at the glass melting oven to get the honour of a promotion. Your current rank is Layman.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 10 in glassblowing to advance in the ranks of the Glassblowing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, "<", 10))
talkEntry:addCondition(condition_quest(717, "=", 6))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("You haven't spent enough time at the glass melting oven to get the honour of a promotion. Your current rank is Layman.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 10 in glassblowing to advance in the ranks of the Glassblowing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, "<", 10))
talkEntry:addCondition(condition_quest(717, "=", 6))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Du hast nicht ausreichend Zeit am Glasschmelzofen verbracht, um in die Ehre einer Beförderung zu kommen. Du wirst im Rang eines Laiens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 10 in Glasblasen um in der Glasbläserzunft aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, ">", 19))
talkEntry:addCondition(condition_quest(717, "=", 7))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Apprentice with the Glassblowing Guild of Cadomyr. You are awarded twenty piles of coarse sand."))
talkEntry:addConsequence(consequence_item(726, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 8))
talkEntry:addResponse("You honour yourself with your hard work, well done. The Glassblowing Guild of Cadomyr supports your efforts with some coarse sand. Come back once you can tell me you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, ">", 19))
talkEntry:addCondition(condition_quest(717, "=", 7))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Apprentice with the Glassblowing Guild of Cadomyr. You are awarded twenty piles of coarse sand."))
talkEntry:addConsequence(consequence_item(726, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 8))
talkEntry:addResponse("You honour yourself with your hard work, well done. The Glassblowing Guild of Cadomyr supports your efforts with some wood. Come back once you can tell me you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, ">", 19))
talkEntry:addCondition(condition_quest(717, "=", 7))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Glasbläserzunft von Cadomyr erhebt dich in den Rang eines Lehrlings. Du erhältst zwanzig Haufen groben Sand."))
talkEntry:addConsequence(consequence_item(726, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 8))
talkEntry:addResponse("Du ehrst dich selber mit deiner harten Arbeit. Die Glasbläserzunft von Cadomyr unterstützt deine Bemühungen mit etwas grobem Sand. Komm erneut zu mir, wenn du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, "<", 20))
talkEntry:addCondition(condition_quest(717, "=", 7))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("You haven't spent enough time at the glass melting oven to get the honour of a promotion. Your current rank is Novice.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 20 in glassblowing to advance in the ranks of the Glassblowing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, "<", 20))
talkEntry:addCondition(condition_quest(717, "=", 7))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("You haven't spent enough time at the glass melting oven to get the honour of a promotion. Your current rank is Novice.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 20 in glassblowing to advance in the ranks of the Glassblowing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, "<", 20))
talkEntry:addCondition(condition_quest(717, "=", 7))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Du hast nicht ausreichend Zeit am Glasschmelzofen verbracht, um in die Ehre einer Beförderung zu kommen. Du wirst im Rang eines Anfängers geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 20 in Glasblasen um in der Glasbläserzunft aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, ">", 29))
talkEntry:addCondition(condition_quest(717, "=", 8))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Initiate with the Glassblowing Guild of Cadomyr. You are awarded ten piles of pot ash."))
talkEntry:addConsequence(consequence_item(314, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 9))
talkEntry:addResponse("You honour yourself with your hard work, well done. The Glassblowing Guild of Cadomyr supports your efforts with some pot ash. Come back once you can tell me you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, ">", 29))
talkEntry:addCondition(condition_quest(717, "=", 8))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Initiate with the Glassblowing Guild of Cadomyr. You are awarded ten piles of pot ash."))
talkEntry:addConsequence(consequence_item(314, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 9))
talkEntry:addResponse("You honour yourself with your hard work, well done. The Glassblowing Guild of Cadomyr supports your efforts with some pot ash. Come back once you can tell me you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, ">", 29))
talkEntry:addCondition(condition_quest(717, "=", 8))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Glasbläserzunft von Cadomyr erhebt dich in den Rang eines Initiatens. Du erhältst zehn Haufen Pottasche."))
talkEntry:addConsequence(consequence_item(314, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 9))
talkEntry:addResponse("Du ehrst dich selber mit deiner harten Arbeit. Die Glasbläserzunft von Cadomyr unterstützt deine Bemühungen mit etwas Pottasche. Komm erneut zu mir, wenn du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, "<", 30))
talkEntry:addCondition(condition_quest(717, "=", 8))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("You haven't spent enough time at the glass melting oven to get the honour of a promotion. Your current rank is Apprentice.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 30 in glassblowing to advance in the ranks of the Glassblowing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, "<", 30))
talkEntry:addCondition(condition_quest(717, "=", 8))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("You haven't spent enough time at the glass melting oven to get the honour of a promotion. Your current rank is Apprentice.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 30 in glassblowing to advance in the ranks of the Glassblowing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, "<", 30))
talkEntry:addCondition(condition_quest(717, "=", 8))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Du hast nicht ausreichend Zeit am Glasschmelzofen verbracht, um in die Ehre einer Beförderung zu kommen. Du wirst im Rang eines Lehrlings geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 30 in Glasblasen um in der Glasbläserzunft aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, ">", 39))
talkEntry:addCondition(condition_quest(717, "=", 9))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Journeyman with the Glassblowing Guild of Cadomyr. You are awarded twenty glass ingots and a journeyman's certificate."))
talkEntry:addConsequence(consequence_item(41, 20, 333, nil))
talkEntry:addConsequence(consequence_item(3109, 1, 333, {["descriptionEn"] = "The owner of this certificate has successfully passed the examination as Journeyman. Nadime - Glassblowing Guild of Cadomyr", ["descriptionDe"] = "Der Inhaber dieses Gesellenbriefes hat erfolgreich das Examen zum Gesellen bestanden. Nadime - Glasblaeserzunft von Cadomyr", ["nameDe"] = "Gesellenbrief", ["nameEn"] = "Journeyman's Certificate", ["rareness"] = "1"}))
talkEntry:addConsequence(consequence_quest(717, "=", 10))
talkEntry:addResponse("The fire glows brighter today for a new Journeyman. The Glassblowing Guild of Cadomyr supports your efforts with some glass ingots. Come back once you can tell me you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, ">", 39))
talkEntry:addCondition(condition_quest(717, "=", 9))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Journeyman with the Glassblowing Guild of Cadomyr. You are awarded twenty glass ingots and a journeyman's certificate."))
talkEntry:addConsequence(consequence_item(41, 20, 333, nil))
talkEntry:addConsequence(consequence_item(3109, 1, 333, {["descriptionEn"] = "The owner of this certificate has successfully passed the examination as Journeyman. Nadime - Glassblowing Guild of Cadomyr", ["descriptionDe"] = "Der Inhaber dieses Gesellenbriefes hat erfolgreich das Examen zum Gesellen bestanden. Nadime - Glasblaeserzunft von Cadomyr", ["nameDe"] = "Gesellenbrief", ["nameEn"] = "Journeyman's Certificate", ["rareness"] = "1"}))
talkEntry:addConsequence(consequence_quest(717, "=", 10))
talkEntry:addResponse("The fire glows brighter today for a new Journeyman. The Glassblowing Guild of Cadomyr supports your efforts with some glass ingots. Come back once you can tell me you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, ">", 39))
talkEntry:addCondition(condition_quest(717, "=", 9))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Glasbläserzunft von Cadomyr erhebt dich in den Rang eines Gesellens. Du erhältst zwanzig Glasbarren und einen Gesellenbrief."))
talkEntry:addConsequence(consequence_item(41, 20, 333, nil))
talkEntry:addConsequence(consequence_item(3109, 1, 333, {["descriptionEn"] = "The owner of this certificate has successfully passed the examination as Journeyman. Nadime - Glassblowing Guild of Cadomyr", ["descriptionDe"] = "Der Inhaber dieses Gesellenbriefes hat erfolgreich das Examen zum Gesellen bestanden. Nadime - Glasblaeserzunft von Cadomyr", ["nameDe"] = "Gesellenbrief", ["nameEn"] = "Journeyman's Certificate", ["rareness"] = "1"}))
talkEntry:addConsequence(consequence_quest(717, "=", 10))
talkEntry:addResponse("Das Feuer glüht heute heller für einen neuen Gesellen. Die Glasbläserzunft von Cadomyr unterstützt deine Bemühungen mit einigen Glasbarren. Komm erneut zu mir, wenn du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, "<", 40))
talkEntry:addCondition(condition_quest(717, "=", 9))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("You haven't spent enough time at the glass melting oven to get the honour of a promotion. Your current rank is Initiate.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 40 in glassblowing to advance in the ranks of the Glassblowing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, "<", 40))
talkEntry:addCondition(condition_quest(717, "=", 9))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("You haven't spent enough time at the glass melting oven to get the honour of a promotion. Your current rank is Initiate.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 40 in glassblowing to advance in the ranks of the Glassblowing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, "<", 40))
talkEntry:addCondition(condition_quest(717, "=", 9))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Du hast nicht ausreichend Zeit am Glasschmelzofen verbracht, um in die Ehre einer Beförderung zu kommen. Du wirst im Rang eines Initiatens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 40 in Glasblasen um in der Glasbläserzunft aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, ">", 49))
talkEntry:addCondition(condition_quest(717, "=", 10))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Specialist with the Glassblowing Guild of Cadomyr. You are awarded ten piles of sapphire powder."))
talkEntry:addConsequence(consequence_item(446, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 11))
talkEntry:addResponse("You honour yourself with your hard work, well done. The Glassblowing Guild of Cadomyr supports your efforts with some sapphire powder. Come back once you can tell me you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, ">", 49))
talkEntry:addCondition(condition_quest(717, "=", 10))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Specialist with the Glassblowing Guild of Cadomyr. You are awarded ten piles of sapphire powder."))
talkEntry:addConsequence(consequence_item(446, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 11))
talkEntry:addResponse("You honour yourself with your hard work, well done. The Glassblowing Guild of Cadomyr supports your efforts with some sapphire powder. Come back once you can tell me you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, ">", 49))
talkEntry:addCondition(condition_quest(717, "=", 10))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Glasbläserzunft von Cadomyr erhebt dich in den Rang eines Spezialistens. Du erhältst zehn Haufen Saphirstaub."))
talkEntry:addConsequence(consequence_item(446, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 11))
talkEntry:addResponse("Du ehrst dich selber mit deiner harten Arbeit. Die Glasbläserzunft von Cadomyr unterstützt deine Bemühungen mit etwas Saphirstaub. Komm erneut zu mir, wenn du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, "<", 50))
talkEntry:addCondition(condition_quest(717, "=", 10))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("You haven't spent enough time at the glass melting oven to get the honour of a promotion. Your current rank is Journeyman.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 50 in glassblowing to advance in the ranks of the Glassblowing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, "<", 50))
talkEntry:addCondition(condition_quest(717, "=", 10))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("You haven't spent enough time at the glass melting oven to get the honour of a promotion. Your current rank is Journeyman.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 50 in glassblowing to advance in the ranks of the Glassblowing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, "<", 50))
talkEntry:addCondition(condition_quest(717, "=", 10))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Du hast nicht ausreichend Zeit am Glasschmelzofen verbracht, um in die Ehre einer Beförderung zu kommen. Du wirst im Rang eines Gesellens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 50 in Glasblasen um in der Glasbläserzunft aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, ">", 59))
talkEntry:addCondition(condition_quest(717, "=", 11))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Expert with the Glassblowing Guild of Cadomyr. You are awarded twenty piles of obsidian powder."))
talkEntry:addConsequence(consequence_item(449, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 12))
talkEntry:addResponse("You honour yourself with your hard work, well done. The Glassblowing Guild of Cadomyr supports your efforts with some obsidian powder. Come back once you can tell me you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, ">", 59))
talkEntry:addCondition(condition_quest(717, "=", 11))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Expert with the Glassblowing Guild of Cadomyr. You are awarded twenty piles of obsidian powder."))
talkEntry:addConsequence(consequence_item(449, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 12))
talkEntry:addResponse("You honour yourself with your hard work, well done. The Glassblowing Guild of Cadomyr supports your efforts with some obsidian powder. Come back once you can tell me you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, ">", 59))
talkEntry:addCondition(condition_quest(717, "=", 11))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Glasbläserzunft von Cadomyr erhebt dich in den Rang eines Expertens. Du erhältst zwanzig Haufen Obsidianstaub."))
talkEntry:addConsequence(consequence_item(449, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 12))
talkEntry:addResponse("Du ehrst dich selber mit deiner harten Arbeit. Die Glasbläserzunft von Cadomyr unterstützt deine Bemühungen mit etwas Obsidianstaub. Komm erneut zu mir, wenn du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, "<", 60))
talkEntry:addCondition(condition_quest(717, "=", 11))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("You haven't spent enough time at the glass melting oven to get the honour of a promotion. Your current rank is Specialist.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 60 in glassblowing to advance in the ranks of the Glassblowing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, "<", 60))
talkEntry:addCondition(condition_quest(717, "=", 11))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("You haven't spent enough time at the glass melting oven to get the honour of a promotion. Your current rank is Specialist.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 60 in glassblowing to advance in the ranks of the Glassblowing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, "<", 60))
talkEntry:addCondition(condition_quest(717, "=", 11))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Du hast nicht ausreichend Zeit am Glasschmelzofen verbracht, um in die Ehre einer Beförderung zu kommen. Du wirst im Rang eines Spezialistens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 60 in Glasblasen um in der Glasbläserzunft aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, ">", 69))
talkEntry:addCondition(condition_quest(717, "=", 12))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Adept with the Glassblowing Guild of Cadomyr. You are awarded ten piles of topaz powder."))
talkEntry:addConsequence(consequence_item(451, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 13))
talkEntry:addResponse("You honour yourself with your hard work, well done. The Glassblowing Guild of Cadomyr supports your efforts with some topaz powder. Come back once you can tell me you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, ">", 69))
talkEntry:addCondition(condition_quest(717, "=", 12))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Adept with the Glassblowing Guild of Cadomyr. You are awarded ten piles of topaz powder."))
talkEntry:addConsequence(consequence_item(451, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 13))
talkEntry:addResponse("You honour yourself with your hard work, well done. The Glassblowing Guild of Cadomyr supports your efforts with some topaz powder. Come back once you can tell me you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, ">", 69))
talkEntry:addCondition(condition_quest(717, "=", 12))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Glasbläserzunft von Cadomyr erhebt dich in den Rang eines Adeptens. Du erhältst zehn Haufen Topasstaub."))
talkEntry:addConsequence(consequence_item(451, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 13))
talkEntry:addResponse("Du ehrst dich selber mit deiner harten Arbeit. Die Glasbläserzunft von Cadomyr unterstützt deine Bemühungen mit etwas Topasstaub. Komm erneut zu mir, wenn du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, "<", 70))
talkEntry:addCondition(condition_quest(717, "=", 12))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("You haven't spent enough time at the glass melting oven to get the honour of a promotion. Your current rank is Expert.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 70 in glassblowing to advance in the ranks of the Glassblowing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, "<", 70))
talkEntry:addCondition(condition_quest(717, "=", 12))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("You haven't spent enough time at the glass melting oven to get the honour of a promotion. Your current rank is Expert.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 70 in glassblowing to advance in the ranks of the Glassblowing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, "<", 70))
talkEntry:addCondition(condition_quest(717, "=", 12))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Du hast nicht ausreichend Zeit am Glasschmelzofen verbracht, um in die Ehre einer Beförderung zu kommen. Du wirst im Rang eines Expertens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 70 in Glasblasen um in der Glasbläserzunft aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, ">", 79))
talkEntry:addCondition(condition_quest(717, "=", 13))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Artisan with the Glassblowing Guild of Cadomyr. You are awarded twenty piles of amethyst powder."))
talkEntry:addConsequence(consequence_item(450, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 14))
talkEntry:addResponse("You honour yourself with your hard work, well done. The Glassblowing Guild of Cadomyr supports your efforts with some amethyst powder. Come back once you can tell me you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, ">", 79))
talkEntry:addCondition(condition_quest(717, "=", 13))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Artisan with the Glassblowing Guild of Cadomyr. You are awarded twenty piles of amethyst powder."))
talkEntry:addConsequence(consequence_item(450, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 14))
talkEntry:addResponse("You honour yourself with your hard work, well done. The Glassblowing Guild of Cadomyr supports your efforts with some amethyst powder. Come back once you can tell me you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, ">", 79))
talkEntry:addCondition(condition_quest(717, "=", 13))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Glasbläserzunft von Cadomyr erhebt dich in den Rang eines Artisanens. Du erhältst zwanzig Haufen Amethyststaub."))
talkEntry:addConsequence(consequence_item(450, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 14))
talkEntry:addResponse("Du ehrst dich selber mit deiner harten Arbeit. Die Glasbläserzunft von Cadomyr unterstützt deine Bemühungen mit etwas Amethyststaub. Komm erneut zu mir, wenn du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, "<", 80))
talkEntry:addCondition(condition_quest(717, "=", 13))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("The highest honour is hard work. I know that Adept.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 80 in glassblowing to advance in the ranks of the Glassblowing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, "<", 80))
talkEntry:addCondition(condition_quest(717, "=", 13))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("The highest honour is hard work. I know that Adept.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 80 in glassblowing to advance in the ranks of the Glassblowing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, "<", 80))
talkEntry:addCondition(condition_quest(717, "=", 13))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Die höchste Ehre ist nur durch harte Arbeit zu erringen. Wer weiß das besser als ihr Adept.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 80 in Glasblasen um in der Glasbläserzunft aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, ">", 89))
talkEntry:addCondition(condition_quest(717, "=", 14))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Master with the Glassblowing Guild of Cadomyr. You are awarded five pieces of pure water and a special tool."))
talkEntry:addConsequence(consequence_item(2554, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 15))
talkEntry:addResponse("You honour yourself with your hard work, well done. The Glassblowing Guild of Cadomyr supports your efforts with some pure water and this special tool. Come back once you can tell me you are more experienced.")
talkEntry:addConsequence(consequence_item(311, 1, 999, {["descriptionEn"] = "Master of the Glassblowing Guild of Cadomyr", ["descriptionDe"] = "Meister der Glasblaeserzunft von Cadomyr", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, ">", 89))
talkEntry:addCondition(condition_quest(717, "=", 14))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Master with the Glassblowing Guild of Cadomyr. You are awarded five pieces of pure water and a special tool."))
talkEntry:addConsequence(consequence_item(2554, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 15))
talkEntry:addResponse("You honour yourself with your hard work, well done. The Glassblowing Guild of Cadomyr supports your efforts with some pure water and this special tool. Come back once you can tell me you are more experienced.")
talkEntry:addConsequence(consequence_item(311, 1, 999, {["descriptionEn"] = "Master of the Glassblowing Guild of Cadomyr", ["descriptionDe"] = "Meister der Glasblaeserzunft von Cadomyr", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, ">", 89))
talkEntry:addCondition(condition_quest(717, "=", 14))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Glasbläserzunft von Cadomyr erhebt dich in den Rang eines Meisters. Du erhältst fünf Stück reinem Wassers und ein besonderes Werkzeug."))
talkEntry:addConsequence(consequence_item(2554, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 15))
talkEntry:addResponse("Du ehrst dich selber mit deiner harten Arbeit. Die Glasbläserzunft von Cadomyr unterstützt deine Bemühungen mit etwas reinem Wasser und diesem besonderen Glasblasrohr. Komm erneut zu mir, wenn du erfahrener bist.")
talkEntry:addConsequence(consequence_item(311, 1, 999, {["descriptionEn"] = "Master of the Glassblowing Guild of Cadomyr", ["descriptionDe"] = "Meister der Glasblaeserzunft von Cadomyr", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, "<", 90))
talkEntry:addCondition(condition_quest(717, "=", 14))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("The highest honour is hard work. I know that Artisan.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 90 in glassblowing to advance in the ranks of the Glassblowing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, "<", 90))
talkEntry:addCondition(condition_quest(717, "=", 14))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("The highest honour is hard work. I know that Artisan.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 90 in glassblowing to advance in the ranks of the Glassblowing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, "<", 90))
talkEntry:addCondition(condition_quest(717, "=", 14))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Die höchste Ehre ist nur durch harte Arbeit zu erringen. Wer weiß das besser als ihr Artisan.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 90 in Glasblasen um in der Glasbläserzunft aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, ">", 99))
talkEntry:addCondition(condition_quest(717, "=", 15))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Grandmaster with the Glassblowing Guild of Cadomyr. You are awarded ten pieces of pure earth and a grandmaster's medal."))
talkEntry:addConsequence(consequence_item(2552, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 16))
talkEntry:addResponse("What a glorious honour. I bow to the new Grandmaster of the Glassblowing Guild of Cadomyr. With this pure earth, you shall help create the most valuable goods of Illarion.")
talkEntry:addConsequence(consequence_item(3535, 1, 999, {["descriptionEn"] = "Grandmaster of the Glassblowing Guild of Cadomyr", ["descriptionDe"] = "Großmeister der Glasblaeserzunft von Cadomyr", ["nameDe"] = "Großmeistermedallie", ["nameEn"] = "Grandmaster's Medal", ["rareness"] = "2"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, ">", 99))
talkEntry:addCondition(condition_quest(717, "=", 15))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Grandmaster with the Glassblowing Guild of Cadomyr. You are awarded ten pieces of pure earth and a grandmaster's medal."))
talkEntry:addConsequence(consequence_item(2552, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 16))
talkEntry:addResponse("What a glorious honour. I bow to the new Grandmaster of the Glassblowing Guild of Cadomyr. With this pure earth, you shall help create the most valuable goods of Illarion.")
talkEntry:addConsequence(consequence_item(3535, 1, 999, {["descriptionEn"] = "Grandmaster of the Glassblowing Guild of Cadomyr", ["descriptionDe"] = "Großmeister der Glasblaeserzunft von Cadomyr", ["nameDe"] = "Großmeistermedallie", ["nameEn"] = "Grandmaster's Medal", ["rareness"] = "2"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, ">", 99))
talkEntry:addCondition(condition_quest(717, "=", 15))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Glasbläserzunft von Cadomyr erhebt dich in den Rang eines Großmeisters. Du erhältst zehn Stück reiner Erde und eine Großmeistermedallie."))
talkEntry:addConsequence(consequence_item(2552, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(717, "=", 16))
talkEntry:addResponse("Welch große Ehre. Ich verneige mich vor einem neuen Großmeister der Glasbläserzunft von Cadomyr. Mit dieser reinen Erde wirst du die teuersten Waren Illarions herstellen.")
talkEntry:addConsequence(consequence_item(3535, 1, 999, {["descriptionEn"] = "Grandmaster of the Glassblowing Guild of Cadomyr", ["descriptionDe"] = "Großmeister der Glasblaeserzunft von Cadomyr", ["nameDe"] = "Großmeistermedallie", ["nameEn"] = "Grandmaster's Medal", ["rareness"] = "2"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, "<", 100))
talkEntry:addCondition(condition_quest(717, "=", 15))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("The highest honour is hard work. I know that, Master.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 100 in glassblowing to advance in the ranks of the Glassblowing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, "<", 100))
talkEntry:addCondition(condition_quest(717, "=", 15))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("The highest honour is hard work. I know that, Master.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 100 in glassblowing to advance in the ranks of the Glassblowing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.glassBlowing, "<", 100))
talkEntry:addCondition(condition_quest(717, "=", 15))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Die höchste Ehre ist nur durch harte Arbeit zu erringen. Wer weiß das besser als ihr, Meister.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 100 in Glasblasen um in der Glasbläserzunft aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(717, "=", 16))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("The Glassblowing Guild of Cadomyr honours its Grandmaster %CHARNAME.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(717, "=", 16))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addResponse("The Glassblowing Guild of Cadomyr honours its Grandmaster %CHARNAME.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(717, "=", 16))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addResponse("Die Glasbläserzunft von Cadomyr ehrt ihren Großmeister %CHARNAME.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("The Glassblowing Guild is restricted to Cadomyr's citizens.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addResponse("The Glassblowing Guild is restricted to Cadomyr's citizens.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addResponse("Die Glasbläserzunft steht nur Bürgern Cadomyrs offen.")
talkingNPC:addTalkingEntry(talkEntry)
end
talkingNPC:addCycleText("Feuer, Feuer, Flamme!", "Fire, fire, flame!")
talkingNPC:addCycleText("Nadime kann dich viel über das Glasblasen lehren.", "Nadime can teach you glass blowing.")
talkingNPC:addCycleText("Möge das Feuer, das du in deinem Ofen schürst, nie verlöschen!", "May the fire that you poke in your oven never go out!")
talkingNPC:addCycleText("#mes Augen scheinen zu glühen.", "#me's eyes seem to glow.")
talkingNPC:addCycleText("#me hüpft grinsend um den Ofen.", "#me jumps around the oven grinning.")
talkingNPC:addCycleText("#me formt ein komplexen Kolben aus Glas.", "#me shapes a complex piece of glass.")
talkingNPC:addCycleText("#me läst ein paar Funken fliegen.", "#me lets some sparks fly.")
talkingNPC:addCycleText("Ziemlich heiß hier, nicht wahr?", "Pretty hot, isn't it?")
mainNPC:addLanguage(0)
mainNPC:addLanguage(10)
mainNPC:setDefaultLanguage(0)
mainNPC:setLookat("Dieser NPC ist Nadime die Glasbläserin.", "This NPC is Nadime the glass blower.")
mainNPC:setUseMessage("Verbrenn dir nicht die Finger!", "Don't burn your fingers!")
mainNPC:setConfusedMessage("#me schaut dich verwirrt an.", "#me looks at you confused.")
mainNPC:setEquipment(1, 0)
mainNPC:setEquipment(3, 804)
mainNPC:setEquipment(11, 0)
mainNPC:setEquipment(5, 47)
mainNPC:setEquipment(6, 0)
mainNPC:setEquipment(4, 0)
mainNPC:setEquipment(9, 0)
mainNPC:setEquipment(10, 1500)
mainNPC:setAutoIntroduceMode(true)

mainNPC:initDone()
return mainNPC
end
local mNPC = initNpc()
initNpc = nil
local M = {}
function M.receiveText(npcChar, texttype, message, speaker) mNPC:receiveText(npcChar, texttype, speaker, message) end
function M.nextCycle(npcChar) mNPC:nextCycle(npcChar) end
function M.lookAtNpc(npcChar, char, mode) mNPC:lookAt(npcChar, char, mode) end
function M.useNPC(npcChar, char, counter, param) mNPC:use(npcChar, char) end
return M
