local consequence_item = require("npc.base.consequence.item")
local condition_item = require("npc.base.condition.item")
local consequence_quest = require("npc.base.consequence.quest")
local condition_skill = require("npc.base.condition.skill")
local condition_language = require("npc.base.condition.language")
local consequence_deleteitem = require("npc.base.consequence.deleteitem")
local basic = require("npc.base.basic")
local condition_town = require("npc.base.condition.town")
local talk = require("npc.base.talk")
local consequence_money = require("npc.base.consequence.money")
local condition_quest = require("npc.base.condition.quest")
local consequence_inform = require("npc.base.consequence.inform")
local function initNpc()
local mainNPC = basic()
mainNPC:setAffiliation(3)
local talkingNPC = talk(mainNPC)
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Help")
talkEntry:addConsequence(consequence_inform("[Game Help] This NPC is Seleseth the armourer. Keywords: Hello, quest, armourer."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hilfe")
talkEntry:addConsequence(consequence_inform("[Spielhilfe] Dieser NPC ist Seleseth der Rüstschmied. Schlüsselwörter: Hallo, Quest, Rüstschmied."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hello")
talkEntry:addTrigger("Greet")
talkEntry:addTrigger("Hail")
talkEntry:addTrigger("Good day")
talkEntry:addTrigger("Good morning")
talkEntry:addTrigger("Good evening")
talkEntry:addTrigger("Good night")
talkEntry:addResponse("Greetingsss to you.")
talkEntry:addResponse("Yess, greetingsss.")
talkEntry:addResponse("Blessingsss of the Mother upon you, greetingsss")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Grüß")
talkEntry:addTrigger("Gruß")
talkEntry:addTrigger("Grüss")
talkEntry:addTrigger("Gruss")
talkEntry:addTrigger("Guten Morgen")
talkEntry:addTrigger("Guten Tag")
talkEntry:addTrigger("Guten Abend")
talkEntry:addTrigger("Gute Nacht")
talkEntry:addTrigger("Mahlzeit")
talkEntry:addTrigger("Tach")
talkEntry:addTrigger("Moin")
talkEntry:addTrigger("Mohltied")
talkEntry:addResponse("Grüßsse dir.")
talkEntry:addResponse("Ja, Grüße.")
talkEntry:addResponse("Grüße.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Hiho")
talkEntry:addTrigger("Hallo")
talkEntry:addTrigger("Hey")
talkEntry:addTrigger("Greeb")
talkEntry:addResponse("Greetingsss to you.")
talkEntry:addResponse("Yess, greetingss.")
talkEntry:addResponse("Greetsss.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hiho")
talkEntry:addTrigger("Hallo")
talkEntry:addTrigger("Hey")
talkEntry:addTrigger("Greeb")
talkEntry:addResponse("Grüßsse dir.")
talkEntry:addResponse("Ja, Grüßsse.")
talkEntry:addResponse("Grüßsse.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Farewell")
talkEntry:addTrigger("Bye")
talkEntry:addTrigger("Fare well")
talkEntry:addTrigger("See you")
talkEntry:addResponse("May the rainsss be heavy and frequent.")
talkEntry:addResponse("May the sssea-Mother watch your path.")
talkEntry:addResponse("Farewell, zsss.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Tschüß")
talkEntry:addTrigger("Tschüss")
talkEntry:addTrigger("Wiedersehen")
talkEntry:addTrigger("Gehab wohl")
talkEntry:addResponse("Mögenss Regen häufig und ssstark sssein.")
talkEntry:addResponse("Mögenss die Meermutter dein Pfad leitenss.")
talkEntry:addResponse("Abschied, zsss.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Ciao")
talkEntry:addTrigger("Adieu")
talkEntry:addTrigger("Au revoir")
talkEntry:addResponse("Goodbye")
talkEntry:addResponse("Farewell")
talkEntry:addResponse("#me nods slowly, 'Goodbye'.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Ciao")
talkEntry:addTrigger("Adieu")
talkEntry:addTrigger("Au revoir")
talkEntry:addResponse("Gut wiedersehensss.")
talkEntry:addResponse("Abschied.")
talkEntry:addResponse("#me nickt langsam: 'Auf Wiedersehensss'.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("How are you")
talkEntry:addTrigger("How feel")
talkEntry:addTrigger("How do you do")
talkEntry:addResponse("Ssseleseth isss fine, yesss.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Wie geht")
talkEntry:addTrigger("Wie fühlst")
talkEntry:addTrigger("Wie ist es ergangen")
talkEntry:addResponse("Ssseleseth isss gut, ja..")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("your name")
talkEntry:addTrigger("who are you")
talkEntry:addTrigger("who art thou")
talkEntry:addResponse("I be Ssseleseth, would you like to do a job for me?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("ihr name")
talkEntry:addTrigger("dein name")
talkEntry:addTrigger("wer bist du")
talkEntry:addTrigger("wer seid ihr")
talkEntry:addTrigger("wie heißt")
talkEntry:addTrigger("wie heisst")
talkEntry:addResponse("Ich sindss Ssseleseth, machenss du Aufgabe für michse?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("sell")
talkEntry:addTrigger("buy")
talkEntry:addTrigger("wares")
talkEntry:addTrigger("price")
talkEntry:addTrigger("trade")
talkEntry:addTrigger("purchase")
talkEntry:addResponse("I am not a trader.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("kauf")
talkEntry:addTrigger("waren")
talkEntry:addTrigger("preis")
talkEntry:addTrigger("Handel")
talkEntry:addTrigger("veräußer")
talkEntry:addTrigger("veräusser")
talkEntry:addTrigger("erwerb")
talkEntry:addResponse("Ich bin kein Händler.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("job")
talkEntry:addResponse("I'm a gem armourer, do you wantsss to help Ssseleseth?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("profession")
talkEntry:addResponse("I'm a armourer, do you wantsss to help Ssseleseth?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("beruf")
talkEntry:addTrigger("job")
talkEntry:addResponse("Ich binss Rüstssschmied, wollen du michssz helfen?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("armourer")
talkEntry:addTrigger("craft")
talkEntry:addResponse("Armourersss are the best smithsss! We have our very own hammer, ssso everyone makesss room for usss at the anvil.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Rüstschmied")
talkEntry:addTrigger("handwerk")
talkEntry:addResponse("Rüstssschmiede sssind die besssten Ssschmiede! Wir haben unssseren ganzss ssspezssiellen Hammer, jeder macht unsss Platzss am Ambosss.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(709, "=", 0))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_item(2763, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 1))
talkEntry:addResponse("The Armourer Guild takess you as an apprentice. Wealth comesss from work, sssz. Take thisss pick-axe and collect ten piles of iron ore from the Malachite mine sssouth of the city.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Armourer Guild of Galmair I. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(709, "=", 0))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_item(2763, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 1))
talkEntry:addResponse("The Armourer Guild takess you as an apprentice. Wealth comesss from work, sssz. Take thisss pick-axe and collect ten piles of iron ore from the Malachite mine sssouth of the city.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Armourer Guild of Galmair I. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(709, "=", 0))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addConsequence(consequence_item(2763, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 1))
talkEntry:addResponse("Du kannst deine Lehre in der Zunft der Rüstschmiede anfangen. Vor dem Reichtum sssteht Arbeit an. Nimm diese Ssspitzhacke und sssammle zehn Eisenerzbrocken in der Malachitmine im Sssüden der Stadt, sssz.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Die Zunft der Rüstschmiede von Galmair I. Detaillierte Informationen findest du im Questlog (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(709, "=", 1))
talkEntry:addCondition(condition_item(22, "all", ">", 9, nil))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_quest(709, "=", 2))
talkEntry:addResponse("Rich ore, but it takesss more to become a real armourer. I'll not sssteal what you worked hard for. Keep it for your next exercise, sssz.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Ask Seleseth for your next task."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(709, "=", 1))
talkEntry:addCondition(condition_item(22, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("iron")
talkEntry:addTrigger("ore")
talkEntry:addConsequence(consequence_quest(709, "=", 2))
talkEntry:addResponse("Rich ore, but it takesss more to become a real armourer. I'll not sssteal what you worked hard for. Keep it for your next exercise, sssz.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Ask Seleseth for your next task."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(709, "=", 1))
talkEntry:addCondition(condition_item(22, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Eisen")
talkEntry:addTrigger("Erz")
talkEntry:addConsequence(consequence_quest(709, "=", 2))
talkEntry:addResponse("Ein reichhaliges Erzss. Aber esss isss mehr sszu tun, um ein Rüstschmied zu werden, sssz. Ich werd dir nicht die Früchte deiner harten Arbeit stehlen. Behalte sie für weitere Übungen, sssz.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Frage Seleseth nach deiner nächsten Aufgaben."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(709, "=", 1))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Wealth doesn't come on in sssleep. Asss your master, I'll repeat my order: Get iron ore.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(709, "=", 1))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("iron")
talkEntry:addTrigger("ore")
talkEntry:addResponse("Wealth doesn't come on in sssleep. Asss your master, I'll repeat my order: Get iron ore.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(709, "=", 1))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Eisen")
talkEntry:addTrigger("Erz")
talkEntry:addResponse("Wohlstand findest du nicht im Schlaf, sssz. Alsss dein Meister werde ich meine Anordnung noch einmal wiederholen: Besorge Eisenerz!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(709, "=", 2))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_item(2751, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 3))
talkEntry:addResponse("Iron holdsss the world together. Iron ingotsss are a good basement of a filled purse, sssz. Make ten of them from the collected ore at the bloomery, sssz. Here isss a rusty crucible-pincers, don't get rusty yourself. Don't forget you need coal as well, sssz!")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Armourer Guild of Galmair II. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(709, "=", 2))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_item(2751, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 3))
talkEntry:addResponse("Iron holdsss the world together. Iron ingotsss are a good basement of a filled purse, sssz. Make ten of them from the collected ore at the bloomery, sssz. Here isss a rusty crucible-pincers, don't get rusty yourself. Don't forget you need coal as well, sssz!")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Armourer Guild of Galmair II. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(709, "=", 2))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addConsequence(consequence_item(2751, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 3))
talkEntry:addResponse("Eisen hält die Welt zusammen, sssz. Eisenbarren sind eine gute Basis für eine volle Geldkatze, sssz. Schmelze bitte am Rennofen zehn aus dem Erz, welches du gesammelt hast, sssz. Hier isss eine rostige Tiegelzange, sssz. Nicht rasten, sssonst rostest du. Vergissss nicht, du brauchst auch Kohle!")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Die Zunft der Rüstschmiede von Galmair II. Detaillierte Informationen findest du im Questlog (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(709, "=", 3))
talkEntry:addCondition(condition_item(2535, "all", ">", 9, nil))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_quest(709, "=", 4))
talkEntry:addResponse("You are able to melt iron, sssz. I'll let you keep them for the next part of your apprenticeship, sssz. Wasss new too, long time ago, and know it'sss hard, sssz.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Ask Seleseth for your next task."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(709, "=", 3))
talkEntry:addCondition(condition_item(2535, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("iron")
talkEntry:addTrigger("ingot")
talkEntry:addConsequence(consequence_quest(709, "=", 4))
talkEntry:addResponse("You are able to melt iron, sssz. I'll let you keep them for the next part of your apprenticeship, sssz. Wasss new too, long time ago, and know it'sss hard, sssz.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Ask Seleseth for your next task."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(709, "=", 3))
talkEntry:addCondition(condition_item(2535, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Eisen")
talkEntry:addTrigger("Barren")
talkEntry:addConsequence(consequence_quest(709, "=", 4))
talkEntry:addResponse("Du bist in der Lage, Eisen zu schmelzen, sssz. Sssehr schön, behalte esss für den nächsten Teil deiner Ausbildung. Ich war auch mal neu und weissss dass isss hart, sssz.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Frage Seleseth nach deiner nächsten Aufgaben."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(709, "=", 3))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Melting ten iron ingotsss isss your task. Without iron, I cannot show you how to produce more expensive itemsss.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(709, "=", 3))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("iron")
talkEntry:addTrigger("ingot")
talkEntry:addResponse("Melting ten iron ingotsss isss your task. Without iron, I cannot show you how to produce more expensive itemsss.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(709, "=", 3))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Eisen")
talkEntry:addTrigger("Barren")
talkEntry:addResponse("Zehn Eisenbarren zu schmelzen isss deine Aufgabe. Ohne diese kann ich dir nicht ssszeigen, wie man wertvollere Dinge herstellt, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(709, "=", 4))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_item(2709, 1, 333, nil))
talkEntry:addConsequence(consequence_item(2537, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 5))
talkEntry:addResponse("Now the real work begins. Armour sssmithing. I'll give you an old armourer's hammer and sssome iron platesss and you try your luck with some sssteel capsss. I do not want to sssee you leaving the anvil before you are done, sssz.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Armourer Guild of Galmair III. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(709, "=", 4))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_item(2709, 1, 333, nil))
talkEntry:addConsequence(consequence_item(2537, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 5))
talkEntry:addResponse("Now the real work begins. Armour sssmithing. I'll give you an old armourer's hammer and sssome iron platesss and you try your luck with some sssteel capsss. I do not want to sssee you leaving the anvil before you are done, sssz.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Armourer Guild of Galmair III. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(709, "=", 4))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addConsequence(consequence_item(2709, 1, 333, nil))
talkEntry:addConsequence(consequence_item(2537, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 5))
talkEntry:addResponse("Jetzt wird es anstrengend. Schmieden, sssz. Ich gebe dir einen alten Hammer des Rüstschmiedesss und einige Eisenplatten und du versuchst dich an einigen Stahlkappen, sssz. Und verlassss ja nicht den Ambossssz, bisss du fertig damit bist, sssz.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Die Zunft der Rüstschmiede von Galmair III. Detaillierte Informationen findest du im Questlog (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(709, "=", 5))
talkEntry:addCondition(condition_item(202, "all", ">", 9, nil))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Layman with the Armourer Guild of Galmair. You are awarded forty five silver coins."))
talkEntry:addConsequence(consequence_deleteitem(202, 10, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 6))
talkEntry:addConsequence(consequence_money("+", 4500))
talkEntry:addResponse("The Armourer Guild of Galmair acceptsss you asss a new member. Here isss sssome money as a first ssstep on you way to wealth. I recommend you buy a normal hammer from it, sssz. Come back once you are more experienced, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(709, "=", 5))
talkEntry:addCondition(condition_item(202, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("steel")
talkEntry:addTrigger("cap")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Layman with the Armourer Guild of Galmair. You are awarded forty five silver coins."))
talkEntry:addConsequence(consequence_deleteitem(202, 10, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 6))
talkEntry:addConsequence(consequence_money("+", 4500))
talkEntry:addResponse("The Armourer Guild of Galmair acceptsss you asss a new member. Here isss sssome money as a first ssstep on you way to wealth. I recommend you buy a normal hammer from it, sssz. Come back once you are more experienced, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(709, "=", 5))
talkEntry:addCondition(condition_item(202, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Stahl")
talkEntry:addTrigger("Kappe")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Zunft der Rüstschmiede von Galmair erhebt dich in den Rang eines Laiens. Du erhältst fünfundvierzig Silberstücke."))
talkEntry:addConsequence(consequence_deleteitem(202, 10, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 6))
talkEntry:addConsequence(consequence_money("+", 4500))
talkEntry:addResponse("Die Zunft der Rüstschmiede von Galmair nimmt dich alsss neues Mitglied auf, sssz. Hier ist etwas Geld, ein kleiner Schritt auf deinem Weg zu Wohlstand, sssz. Mein Vorschlag wäre esss, dassss du davon einen einfachen Hammer kaufst, sssz. Und komm zu mir zurück, sssobald du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(709, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("That doesn't looks like steel capsss. Try once more, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(709, "=", 5))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("steel")
talkEntry:addTrigger("cap")
talkEntry:addResponse("That doesn't looks like steel capsss. Try once more, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(709, "=", 5))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Axt")
talkEntry:addTrigger("Griff")
talkEntry:addResponse("Das sssieht nicht ausss wie Stahlkappen. Versuchsss noch mal.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, ">", 9))
talkEntry:addCondition(condition_quest(709, "=", 6))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Novice with the Armourer Guild of Galmair. You are awarded ten piles of iron ore."))
talkEntry:addConsequence(consequence_item(22, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 7))
talkEntry:addResponse("That looks good, sssz. Another ssstep to wealth isss done. From our ssstocksss, the Armourer Guild of Galmair sssupportsss you with sssome iron ore. Work hard, earn coinss and come back to me once your are more experienced, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, ">", 9))
talkEntry:addCondition(condition_quest(709, "=", 6))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Novice with the Armourer Guild of Galmair. You are awarded ten piles of iron ore."))
talkEntry:addConsequence(consequence_item(22, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 7))
talkEntry:addResponse("That looks good, sssz. Another ssstep to wealth isss done. From our ssstocksss, the Armourer Guild of Galmair sssupportsss you with sssome iron ore. Work hard, earn coinss and come back to me once your are more experienced, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, ">", 9))
talkEntry:addCondition(condition_quest(709, "=", 6))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Zunft der Rüstschmiede von Galmair erhebt dich in den Rang eines Anfängers. Du erhältst zehn Eisenerzbrocken."))
talkEntry:addConsequence(consequence_item(22, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 7))
talkEntry:addResponse("Dass sssieht gut ausss. Harte Arbeit für gute Ware, sssz. Ausss unserem Fundusss gibt dir die Zunft der Rüstschmiede von Galmair etwas Eisenerz alsss Unterstützung, sssz. Arbeite weiter und komm wieder sszu mir, wenn du erfahrener bist, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, "<", 10))
talkEntry:addCondition(condition_quest(709, "=", 6))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Wealth doesn't come on it'sss own, sssz. Sssee you spend more time at the anvil and your ssskill improvesss. Your current rank isss Layman.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 10 in armourer to advance in the ranks of the Armourer Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, "<", 10))
talkEntry:addCondition(condition_quest(709, "=", 6))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Wealth doesn't come on it'sss own, sssz. Sssee you spend more time at the anvil and your ssskill improvesss. Your current rank isss Layman.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 10 in armourer to advance in the ranks of the Armourer Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, "<", 10))
talkEntry:addCondition(condition_quest(709, "=", 6))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Wohlstand kommt nicht von alleine, sssz. Steh öfter am Ambossss und du wirst merken, um wieviel bessssser du den Hammer führen kast, sssz. Du bist jetzt ein Laie.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 10 in Rüstschmieden um in der Zunft der Rüstschmiede aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, ">", 19))
talkEntry:addCondition(condition_quest(709, "=", 7))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Apprentice with the Armourer Guild of Galmair. You are awarded twenty piles of coal."))
talkEntry:addConsequence(consequence_item(21, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 8))
talkEntry:addResponse("That looks good, sssz. Another ssstep to wealth isss done. From our ssstocksss, the Armourer Guild of Galmair sssupportsss you with sssome coal. Work hard, earn coinss and come back to me once your are more experienced, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, ">", 19))
talkEntry:addCondition(condition_quest(709, "=", 7))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Apprentice with the Armourer Guild of Galmair. You are awarded twenty piles of coal."))
talkEntry:addConsequence(consequence_item(21, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 8))
talkEntry:addResponse("That looks good, sssz. Another ssstep to wealth isss done. From our ssstocksss, the Armourer Guild of Galmair sssupportsss you with sssome coal. Work hard, earn coinss and come back to me once your are more experienced, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, ">", 19))
talkEntry:addCondition(condition_quest(709, "=", 7))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Zunft der Rüstschmiede von Galmair erhebt dich in den Rang eines Lehrlings. Du erhältst zwanzig Brocken Kohle."))
talkEntry:addConsequence(consequence_item(21, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 8))
talkEntry:addResponse("Dass sssieht gut ausss. Harte Arbeit für gute Ware, sssz. Ausss unserem Fundus gibt dir die Zunft der Rüstschmiede von Galmair etwas Kohle alsss Unterstützung, sssz. Arbeite weiter und komm wieder sszu mir, wenn du erfahrener bist, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, "<", 20))
talkEntry:addCondition(condition_quest(709, "=", 7))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Wealth doesn't come on it'sss own, sssz. Sssee you spend more time at the anvil and your ssskill improvesss. Your current rank isss Novice.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 20 in armourer to advance in the ranks of the Armourer Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, "<", 20))
talkEntry:addCondition(condition_quest(709, "=", 7))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Wealth doesn't come on it'sss own, sssz. Sssee you spend more time at the anvil and your ssskill improvesss. Your current rank isss Novice.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 20 in armourer to advance in the ranks of the Armourer Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, "<", 20))
talkEntry:addCondition(condition_quest(709, "=", 7))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Wohlstand kommt nicht von alleine, sssz. Steh öfter am Ambossss und du wirst merken, um wieviel bessssser du den Hammer führen kast, sssz. Du bist jetzt ein Anfänger.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 20 in Rüstschmieden um in der Zunft der Rüstschmiede aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, ">", 29))
talkEntry:addCondition(condition_quest(709, "=", 8))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Initiate with the Armourer Guild of Galmair. You are awarded ten iron ingots."))
talkEntry:addConsequence(consequence_item(2535, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 9))
talkEntry:addResponse("That looks good, sssz. Another ssstep to wealth isss done. From our ssstocksss, the Armourer Guild of Galmair sssupportsss you with sssome iron ingots. Work hard, earn coinss and come back to me once your are more experienced, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, ">", 29))
talkEntry:addCondition(condition_quest(709, "=", 8))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Initiate with the Armourer Guild of Galmair. You are awarded ten iron ingots."))
talkEntry:addConsequence(consequence_item(2535, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 9))
talkEntry:addResponse("That looks good, sssz. Another ssstep to wealth isss done. From our ssstocksss, the Armourer Guild of Galmair sssupportsss you with sssome iron ingots. Work hard, earn coinss and come back to me once your are more experienced, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, ">", 29))
talkEntry:addCondition(condition_quest(709, "=", 8))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Zunft der Rüstschmiede von Galmair erhebt dich in den Rang eines Initiatens. Du erhältst zehn Eisenbarren."))
talkEntry:addConsequence(consequence_item(2535, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 9))
talkEntry:addResponse("Dass sssieht gut ausss. Harte Arbeit für gute Ware, sssz. Ausss unserem Fundus gibt dir die Zunft der Rüstschmiede von Galmair einige Eisenbarren alsss Unterstützung, sssz. Arbeite weiter und komm wieder sszu mir, wenn du erfahrener bist, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, "<", 30))
talkEntry:addCondition(condition_quest(709, "=", 8))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Wealth doesn't come on it'sss own, sssz. Sssee you spend more time at the anvil and your ssskill improvesss. Your current rank isss Apprentice.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 30 in armourer to advance in the ranks of the Armourer Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, "<", 30))
talkEntry:addCondition(condition_quest(709, "=", 8))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Wealth doesn't come on it'sss own, sssz. Sssee you spend more time at the anvil and your ssskill improvesss. Your current rank isss Apprentice.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 30 in armourer to advance in the ranks of the Armourer Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, "<", 30))
talkEntry:addCondition(condition_quest(709, "=", 8))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Wohlstand kommt nicht von alleine, sssz. Steh öfter am Ambossss und du wirst merken, um wieviel bessssser du den Hammer führen kast, sssz. Du bist jetzt ein Lehrling.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 30 in Rüstschmieden um in der Zunft der Rüstschmiede aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, ">", 39))
talkEntry:addCondition(condition_quest(709, "=", 9))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Journeyman with the Armourer Guild of Galmair. You are awarded twenty leather hides and a journeyman's certificate."))
talkEntry:addConsequence(consequence_item(2547, 20, 333, nil))
talkEntry:addConsequence(consequence_item(3109, 1, 333, {["descriptionEn"] = "The owner of this certificate has successfully passed the examination as Journeyman. Seleseth - Armourer Guild of Galmair", ["descriptionDe"] = "Der Inhaber dieses Gesellenbriefes hat erfolgreich das Examen zum Gesellen bestanden. Seleseth - Zunft der Ruestungsschmiede von Galmair", ["nameDe"] = "Gesellenbrief", ["nameEn"] = "Journeyman's Certificate", ["rareness"] = "1"}))
talkEntry:addConsequence(consequence_quest(709, "=", 10))
talkEntry:addResponse("A new Journeyman wasss born. From our ssstocksss, the Armourer Guild of Galmair sssupportsss you with sssome leather. Work hard, earn coinss and come back to me once your are more experienced, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, ">", 39))
talkEntry:addCondition(condition_quest(709, "=", 9))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Journeyman with the Armourer Guild of Galmair. You are awarded twenty leather hides and a journeyman's certificate."))
talkEntry:addConsequence(consequence_item(2547, 20, 333, nil))
talkEntry:addConsequence(consequence_item(3109, 1, 333, {["descriptionEn"] = "The owner of this certificate has successfully passed the examination as Journeyman. Seleseth - Armourer Guild of Galmair", ["descriptionDe"] = "Der Inhaber dieses Gesellenbriefes hat erfolgreich das Examen zum Gesellen bestanden. Seleseth - Zunft der Ruestungsschmiede von Galmair", ["nameDe"] = "Gesellenbrief", ["nameEn"] = "Journeyman's Certificate", ["rareness"] = "1"}))
talkEntry:addConsequence(consequence_quest(709, "=", 10))
talkEntry:addResponse("A new Journeyman wasss born. From our ssstocksss, the Armourer Guild of Galmair sssupportsss you with sssome leather. Work hard, earn coinss and come back to me once your are more experienced, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, ">", 39))
talkEntry:addCondition(condition_quest(709, "=", 9))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Zunft der Rüstschmiede von Galmair erhebt dich in den Rang eines Gesellens. Du erhältst zwanzig Lederhäute und einen Gesellenbrief."))
talkEntry:addConsequence(consequence_item(2547, 20, 333, nil))
talkEntry:addConsequence(consequence_item(3109, 1, 333, {["descriptionEn"] = "The owner of this certificate has successfully passed the examination as Journeyman. Seleseth - Armourer Guild of Galmair", ["descriptionDe"] = "Der Inhaber dieses Gesellenbriefes hat erfolgreich das Examen zum Gesellen bestanden. Seleseth - Zunft der Ruestungsschmiede von Galmair", ["nameDe"] = "Gesellenbrief", ["nameEn"] = "Journeyman's Certificate", ["rareness"] = "1"}))
talkEntry:addConsequence(consequence_quest(709, "=", 10))
talkEntry:addResponse("Ein neuer Geselle wurde verbrieft, sssz. Ausss unserem Fundus gibt dir die Zunft der Rüstschmiede von Galmair etwas Leder alsss Unterstützung, sssz. Arbeite weiter und komm wieder sszu mir, wenn du erfahrener bist, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, "<", 40))
talkEntry:addCondition(condition_quest(709, "=", 9))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Wealth doesn't come on it'sss own, sssz. Sssee you spend more time at the anvil and your ssskill improvesss. Your current rank isss Initiate.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 40 in armourer to advance in the ranks of the Armourer Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, "<", 40))
talkEntry:addCondition(condition_quest(709, "=", 9))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Wealth doesn't come on it'sss own, sssz. Sssee you spend more time at the anvil and your ssskill improvesss. Your current rank isss Initiate.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 40 in armourer to advance in the ranks of the Armourer Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, "<", 40))
talkEntry:addCondition(condition_quest(709, "=", 9))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Wohlstand kommt nicht von alleine, sssz. Steh öfter am Ambossss und du wirst merken, um wieviel bessssser du den Hammer führen kast, sssz. Du bist jetzt ein Initiat.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 40 in Rüstschmieden um in der Zunft der Rüstschmiede aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, ">", 49))
talkEntry:addCondition(condition_quest(709, "=", 10))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Specialist with the Armourer Guild of Galmair. You are awarded ten iron plates."))
talkEntry:addConsequence(consequence_item(2537, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 11))
talkEntry:addResponse("That looks good, sssz. Another ssstep to wealth isss done. From our ssstocksss, the Armourer Guild of Galmair sssupportsss you with sssome iron plates. Work hard, earn coinss and come back to me once your are more experienced, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, ">", 49))
talkEntry:addCondition(condition_quest(709, "=", 10))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Specialist with the Armourer Guild of Galmair. You are awarded ten iron plates."))
talkEntry:addConsequence(consequence_item(2537, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 11))
talkEntry:addResponse("That looks good, sssz. Another ssstep to wealth isss done. From our ssstocksss, the Armourer Guild of Galmair sssupportsss you with sssome iron plates. Work hard, earn coinss and come back to me once your are more experienced, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, ">", 49))
talkEntry:addCondition(condition_quest(709, "=", 10))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Zunft der Rüstschmiede von Galmair erhebt dich in den Rang eines Spezialistens. Du erhältst zehn Eisenplatten."))
talkEntry:addConsequence(consequence_item(2537, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 11))
talkEntry:addResponse("Dass sssieht gut ausss. Harte Arbeit für gute Ware, sssz. Ausss unserem Fundus gibt dir die Zunft der Rüstschmiede von Galmair einige Eisenplatten alsss Unterstützung, sssz. Arbeite weiter und komm wieder sszu mir, wenn du erfahrener bist, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, "<", 50))
talkEntry:addCondition(condition_quest(709, "=", 10))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Wealth doesn't come on it'sss own, sssz. Sssee you spend more time at the anvil and your ssskill improvesss. Your current rank isss Journeyman.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 50 in armourer to advance in the ranks of the Armourer Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, "<", 50))
talkEntry:addCondition(condition_quest(709, "=", 10))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Wealth doesn't come on it'sss own, sssz. Sssee you spend more time at the anvil and your ssskill improvesss. Your current rank isss Journeyman.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 50 in armourer to advance in the ranks of the Armourer Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, "<", 50))
talkEntry:addCondition(condition_quest(709, "=", 10))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Wohlstand kommt nicht von alleine, sssz. Steh öfter am Ambossss und du wirst merken, um wieviel bessssser du den Hammer führen kast, sssz. Du bist jetzt ein Gesellen.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 50 in Rüstschmieden um in der Zunft der Rüstschmiede aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, ">", 59))
talkEntry:addCondition(condition_quest(709, "=", 11))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Expert with the Armourer Guild of Galmair. You are awarded twenty gold ingots."))
talkEntry:addConsequence(consequence_item(236, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 12))
talkEntry:addResponse("That looks good, sssz. Another ssstep to wealth isss done. From our ssstocksss, the Armourer Guild of Galmair sssupportsss you with sssome gold ingots. Work hard, earn coinss and come back to me once your are more experienced, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, ">", 59))
talkEntry:addCondition(condition_quest(709, "=", 11))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Expert with the Armourer Guild of Galmair. You are awarded twenty gold ingots."))
talkEntry:addConsequence(consequence_item(236, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 12))
talkEntry:addResponse("That looks good, sssz. Another ssstep to wealth isss done. From our ssstocksss, the Armourer Guild of Galmair sssupportsss you with sssome gold ingots. Work hard, earn coinss and come back to me once your are more experienced, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, ">", 59))
talkEntry:addCondition(condition_quest(709, "=", 11))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Zunft der Rüstschmiede von Galmair erhebt dich in den Rang eines Expertens. Du erhältst zwanzig Goldbarren."))
talkEntry:addConsequence(consequence_item(236, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 12))
talkEntry:addResponse("Dass sssieht gut ausss. Harte Arbeit für gute Ware, sssz. Ausss unserem Fundus gibt dir die Zunft der Rüstschmiede von Galmair einige Goldbarren alsss Unterstützung, sssz. Arbeite weiter und komm wieder sszu mir, wenn du erfahrener bist, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, "<", 60))
talkEntry:addCondition(condition_quest(709, "=", 11))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Wealth doesn't come on it'sss own, sssz. Sssee you spend more time at the anvil and your ssskill improvesss. Your current rank isss Specialist.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 60 in armourer to advance in the ranks of the Armourer Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, "<", 60))
talkEntry:addCondition(condition_quest(709, "=", 11))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Wealth doesn't come on it'sss own, sssz. Sssee you spend more time at the anvil and your ssskill improvesss. Your current rank isss Specialist.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 60 in armourer to advance in the ranks of the Armourer Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, "<", 60))
talkEntry:addCondition(condition_quest(709, "=", 11))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Wohlstand kommt nicht von alleine, sssz. Steh öfter am Ambossss und du wirst merken, um wieviel bessssser du den Hammer führen kast, sssz. Du bist jetzt ein Spezialisten.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 60 in Rüstschmieden um in der Zunft der Rüstschmiede aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, ">", 69))
talkEntry:addCondition(condition_quest(709, "=", 12))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Adept with the Armourer Guild of Galmair. You are awarded five obsidians."))
talkEntry:addConsequence(consequence_item(283, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 13))
talkEntry:addResponse("That looks good, sssz. Another ssstep to wealth isss done. From our ssstocksss, the Armourer Guild of Galmair sssupportsss you with sssome obsidians. Work hard, earn coinss and come back to me once your are more experienced, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, ">", 69))
talkEntry:addCondition(condition_quest(709, "=", 12))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Adept with the Armourer Guild of Galmair. You are awarded five obsidians."))
talkEntry:addConsequence(consequence_item(283, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 13))
talkEntry:addResponse("That looks good, sssz. Another ssstep to wealth isss done. From our ssstocksss, the Armourer Guild of Galmair sssupportsss you with sssome obsidians. Work hard, earn coinss and come back to me once your are more experienced, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, ">", 69))
talkEntry:addCondition(condition_quest(709, "=", 12))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Zunft der Rüstschmiede von Galmair erhebt dich in den Rang eines Adeptens. Du erhältst fünf Obsidiane."))
talkEntry:addConsequence(consequence_item(283, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 13))
talkEntry:addResponse("Dass sssieht gut ausss. Harte Arbeit für gute Ware, sssz. Ausss unserem Fundus gibt dir die Zunft der Rüstschmiede von Galmair einige Obsidiane alsss Unterstützung, sssz. Arbeite weiter und komm wieder sszu mir, wenn du erfahrener bist, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, "<", 70))
talkEntry:addCondition(condition_quest(709, "=", 12))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Wealth doesn't come on it'sss own, sssz. Sssee you spend more time at the anvil and your ssskill improvesss. Your current rank isss Expert.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 70 in armourer to advance in the ranks of the Armourer Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, "<", 70))
talkEntry:addCondition(condition_quest(709, "=", 12))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Wealth doesn't come on it'sss own, sssz. Sssee you spend more time at the anvil and your ssskill improvesss. Your current rank isss Expert.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 70 in armourer to advance in the ranks of the Armourer Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, "<", 70))
talkEntry:addCondition(condition_quest(709, "=", 12))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Wohlstand kommt nicht von alleine, sssz. Steh öfter am Ambossss und du wirst merken, um wieviel bessssser du den Hammer führen kast, sssz. Du bist jetzt ein Experten.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 10 in Rüstschmieden um in der Zunft der Rüstschmiede aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, ">", 79))
talkEntry:addCondition(condition_quest(709, "=", 13))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Artisan with the Armourer Guild of Galmair. You are awarded ten merinium ingots."))
talkEntry:addConsequence(consequence_item(2571, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 14))
talkEntry:addResponse("That looks good, sssz. Another ssstep to wealth isss done. From our ssstocksss, the Armourer Guild of Galmair sssupportsss you with sssome merinium ingots. Work hard, earn coinss and come back to me once your are more experienced, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, ">", 79))
talkEntry:addCondition(condition_quest(709, "=", 13))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Artisan with the Armourer Guild of Galmair. You are awarded ten merinium ingots."))
talkEntry:addConsequence(consequence_item(2571, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 14))
talkEntry:addResponse("That looks good, sssz. Another ssstep to wealth isss done. From our ssstocksss, the Armourer Guild of Galmair sssupportsss you with sssome merinium ingots. Work hard, earn coinss and come back to me once your are more experienced, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, ">", 79))
talkEntry:addCondition(condition_quest(709, "=", 13))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Zunft der Rüstschmiede von Galmair erhebt dich in den Rang eines Artisanens. Du erhältst zehn Meriniumbarren."))
talkEntry:addConsequence(consequence_item(2571, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 14))
talkEntry:addResponse("Dass sssieht gut ausss. Harte Arbeit für gute Ware, sssz. Ausss unserem Fundus gibt dir die Zunft der Rüstschmiede von Galmair einige Meriniumbarren alsss Unterstützung, sssz. Arbeite weiter und komm wieder sszu mir, wenn du erfahrener bist, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, "<", 80))
talkEntry:addCondition(condition_quest(709, "=", 13))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("If it wasss easy, everyone would be rich. It'sss a long hard way to master our craft, sssz. You are already an Adept.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 80 in armourer to advance in the ranks of the Armourer Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, "<", 80))
talkEntry:addCondition(condition_quest(709, "=", 13))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("If it wasss easy, everyone would be rich. It'sss a long hard way to master our craft, sssz. You are already an Adept.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 80 in armourer to advance in the ranks of the Armourer Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, "<", 80))
talkEntry:addCondition(condition_quest(709, "=", 13))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Wennsss einfach wär, wär jeder reich, sssz. Esss isss verdammt viel Arbeit unser Handwerk zu meistern. Aber du bisss bereitsss ein Adept.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 80 in Rüstschmieden um in der Zunft der Rüstschmiede aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, ">", 89))
talkEntry:addCondition(condition_quest(709, "=", 14))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Master with the Armourer Guild of Galmair. You are awarded five pieces of pure earth and a special tool."))
talkEntry:addConsequence(consequence_item(2552, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 15))
talkEntry:addResponse("That looks good, sssz. Another ssstep to wealth isss done. From our ssstocksss, the Armourer Guild of Galmair sssupportsss you with sssome pure earth. Take this valuable tool and come back to me once your are more experienced, sssz.")
talkEntry:addConsequence(consequence_item(2709, 1, 999, {["descriptionEn"] = "Master of the Armourer Guild of Galmair", ["descriptionDe"] = "Meister der Zunft der Ruestungsschmiede von Galmair", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, ">", 89))
talkEntry:addCondition(condition_quest(709, "=", 14))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Master with the Armourer Guild of Galmair. You are awarded five pieces of pure earth and a special tool."))
talkEntry:addConsequence(consequence_item(2552, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 15))
talkEntry:addResponse("That looks good, sssz. Another ssstep to wealth isss done. From our ssstocksss, the Armourer Guild of Galmair sssupportsss you with sssome pure earth. Take this valuable tool and come back to me once your are more experienced, sssz.")
talkEntry:addConsequence(consequence_item(2709, 1, 999, {["descriptionEn"] = "Master of the Armourer Guild of Galmair", ["descriptionDe"] = "Meister der Zunft der Ruestungsschmiede von Galmair", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, ">", 89))
talkEntry:addCondition(condition_quest(709, "=", 14))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Zunft der Rüstschmiede von Galmair erhebt dich in den Rang eines Meisters. Du erhältst fünf Stück reiner Erde und ein besonderes Werkzeug."))
talkEntry:addConsequence(consequence_item(2552, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 15))
talkEntry:addResponse("Dass sssieht gut ausss. Harte Arbeit für gute Ware, sssz. Ausss unserem Fundus gibt dir die Zunft der Rüstschmiede von Galmair etwas reiner Erde alsss Unterstützung, sssz. Nimm auch dieses wertvolle Werkzeug und komm wieder sszu mir, wenn du erfahrener bist, sssz.")
talkEntry:addConsequence(consequence_item(2709, 1, 999, {["descriptionEn"] = "Master of the Armourer Guild of Galmair", ["descriptionDe"] = "Meister der Zunft der Ruestungsschmiede von Galmair", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, "<", 90))
talkEntry:addCondition(condition_quest(709, "=", 14))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("If it wasss easy, everyone would be rich. It'sss a long hard way to master our craft, sssz. You are already an Artisan.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 90 in armourer to advance in the ranks of the Armourer Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, "<", 90))
talkEntry:addCondition(condition_quest(709, "=", 14))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("If it wasss easy, everyone would be rich. It'sss a long hard way to master our craft, sssz. You are already an Artisan.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 90 in armourer to advance in the ranks of the Armourer Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, "<", 90))
talkEntry:addCondition(condition_quest(709, "=", 14))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Wennsss einfach wär, wär jeder reich, sssz. Esss isss verdammt viel Arbeit unser Handwerk zu meistern. Aber du bisss bereitsss ein Artisan.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 90 in Rüstschmieden um in der Zunft der Rüstschmiede aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, ">", 99))
talkEntry:addCondition(condition_quest(709, "=", 15))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Grandmaster with the Armourer Guild of Galmair. You are awarded ten pieces of pure water and a grandmaster's medal."))
talkEntry:addConsequence(consequence_item(2554, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 16))
talkEntry:addResponse("Wasss about time. I bow to a new Grandmaster of the Armourer Guild of Galmair, sssz. With thisss pure water, you shall help sssmith the most valuable goodsss of Illarion.")
talkEntry:addConsequence(consequence_item(3535, 1, 999, {["descriptionEn"] = "Grandmaster of the Armourer Guild of Galmair", ["descriptionDe"] = "Großmeister der Zunft der Rüstschmiede von Galmair", ["nameDe"] = "Großmeistermedallie", ["nameEn"] = "Grandmaster's Medal", ["rareness"] = "2"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, ">", 99))
talkEntry:addCondition(condition_quest(709, "=", 15))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Grandmaster with the Armourer Guild of Galmair. You are awarded ten pieces of pure water and a grandmaster's medal."))
talkEntry:addConsequence(consequence_item(2554, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 16))
talkEntry:addResponse("Wasss about time. I bow to a new Grandmaster of the Armourer Guild of Galmair, sssz. With thisss pure water, you shall help sssmith the most valuable goodsss of Illarion.")
talkEntry:addConsequence(consequence_item(3535, 1, 999, {["descriptionEn"] = "Grandmaster of the Armourer Guild of Galmair", ["descriptionDe"] = "Großmeister der Zunft der Rüstschmiede von Galmair", ["nameDe"] = "Großmeistermedallie", ["nameEn"] = "Grandmaster's Medal", ["rareness"] = "2"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, ">", 99))
talkEntry:addCondition(condition_quest(709, "=", 15))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Zunft der Rüstschmiede von Galmair erhebt dich in den Rang eines Großmeisters. Du erhältst zehn Stück reines Wasser und eine Großmeistermedallie."))
talkEntry:addConsequence(consequence_item(2554, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(709, "=", 16))
talkEntry:addResponse("Seit langer Zeit mal wieder, sssz. Ich verneige mich vor einem neuen Großmeister der Zunft der Rüstschmiede von Galmair, sssz. Mit diesem reinen Wasser wirst du die teuersten Waren Illarionsss herstellen.")
talkEntry:addConsequence(consequence_item(3535, 1, 999, {["descriptionEn"] = "Grandmaster of the Armourer Guild of Galmair", ["descriptionDe"] = "Großmeister der Zunft der Rüstschmiede von Galmair", ["nameDe"] = "Großmeistermedallie", ["nameEn"] = "Grandmaster's Medal", ["rareness"] = "2"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, "<", 100))
talkEntry:addCondition(condition_quest(709, "=", 15))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("If it wasss easy, everyone would be rich. It'sss a long hard way to master our craft, sssz. You are already a Master.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 100 in armourer to advance in the ranks of the Armourer Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, "<", 100))
talkEntry:addCondition(condition_quest(709, "=", 15))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("If it wasss easy, everyone would be rich. It'sss a long hard way to master our craft, sssz. You are already a Master.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 100 in armourer to advance in the ranks of the Armourer Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.armourer, "<", 100))
talkEntry:addCondition(condition_quest(709, "=", 15))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Wennsss einfach wär, wär jeder reich, sssz. Esss isss verdammt viel Arbeit unser Handwerk zu meistern. Aber du bisss bereitsss ein Meister.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 100 in Rüstschmieden um in der Zunft der Rüstschmiede aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(709, "=", 16))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("One day, you will tell your hatchlings about your time with the Armourer Guild of Galmair, Grandmaster %CHARNAME, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(709, "=", 16))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addResponse("One day, you will tell your hatchlings about your time with the Armourer Guild of Galmair, Grandmaster %CHARNAME, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(709, "=", 16))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addResponse("Du wirst noch deinen Schlüpflingen von deiner Zsseit bei der Zunft der Rüstschmiede von Galmair erzählen, Großmeister %CHARNAME, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("The Armourer Guild isss restricted to Galmair's citizensss.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addResponse("The Armourer Guild isss restricted to Galmair's citizensss.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addResponse("Die Zunft der Rüstschmiede steht nur Bürgern Galmairs offen, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("don")
talkEntry:addResponse("The protecting hand of the Don allowssss us to work for our wealth, sssz.")
talkEntry:addResponse("Don Valerio Guilianni personally takessss care our guild prosperssss.")
talkEntry:addResponse("Don Valerio Guilianni wearssss an armoury, made by our guild, yessss.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("don")
talkEntry:addResponse("Die schützende Hand des Donsss ermöglicht unseren Wohlstand, sssz.")
talkEntry:addResponse("Don Valerio Guilianni kümmert sssich persönlich, dassss unsere Zunft gedeiht, sssz.")
talkEntry:addResponse("Die Rüstung von Don Valerio Guilianni wurde von Meistern unserer Zunft geschmiedet, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Zelphia")
talkEntry:addTrigger("Tanora")
talkEntry:addResponse("Zelphia isss mother of childrensss of ssssea.")
talkEntry:addResponse("Seleseth isss child of mother Zelphia.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Zelphia")
talkEntry:addTrigger("Tanora")
talkEntry:addResponse("Zelphia isss Mutter der Kinder der Sssee.")
talkEntry:addResponse("Seleseth isss ein Kind von Mutter Zelphia, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Irmorom")
talkEntry:addResponse("Irmorom and our guild asss well worksss in the sssmithy, that sssaysss all.")
talkEntry:addResponse("Deep in the west of our valley you find Irmorom'sss temple, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Irmorom")
talkEntry:addResponse("Irmorom und auch unsere Zunft arbeiten in der Schmiede, dasss sssagt doch allesss.")
talkEntry:addResponse("Irmoroms Tempel findest du tief im Tal im Westen, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("nargun")
talkEntry:addResponse("Skill and luck we need, don't forget to sacrifice to Nargun.")
talkEntry:addResponse("Nargunsss temple, use the elevator and head westward, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("nargun")
talkEntry:addResponse("Können und Glück isss wasss esss braucht. Vergesss nie auch Nargun zu opfern.")
talkEntry:addResponse("Nargunsss Tempel, fahr mit dem Aufzug und halte dich westlich.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("ronagan")
talkEntry:addResponse("Poor people aren't good for buisinesss. Ronagan may help them, sssz.")
talkEntry:addResponse("Ronagansss temple, use the elevator and head sssoutheast. Take the boat then, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("ronagan")
talkEntry:addResponse("Arme Leute sind nicht gut fürsss Geschäft, sssz. Ronagan möge ihnen beistehen, sssz.")
talkEntry:addResponse("Ronagansss Tempel, fahr mit dem Aufzug und halte dich südöstlich. Nimm einfach dasss Boot.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("god")
talkEntry:addTrigger("temple")
talkEntry:addResponse("Galmair hasss many temples, sssz. Isss Irmorom in west, Ronagan and Nargun in the mountain.")
talkEntry:addResponse("I pray at Zelphiasss altar in the Temple of the Five, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Gott")
talkEntry:addTrigger("Tempel")
talkEntry:addResponse("Galmair hat viele Tempel, sssz. Irmoromssss in Westen, Ronagansss und Nargunsss im Berg.")
talkEntry:addResponse("Ich bete an Zelphias Schrein im Tempel der Fünf, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("fish")
talkEntry:addResponse("I catch my fish fresh from the Malachite Creek, sssz.")
talkEntry:addResponse("Fish tastesss good alwaysss, no matter if raw, roasted or cooked, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("fisch")
talkEntry:addResponse("Ich fang mir meinen Fisch frisch aus dem Malachitbach.")
talkEntry:addResponse("Egal ob roh, gegräuchert oder gekocht, Fisch schmeckt immer, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("malachit")
talkEntry:addResponse("It's not that far sssouth of Galmair to the Malachite Mine.")
talkEntry:addResponse("The deeper you go into the mine, the better the ore, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("ore")
talkEntry:addResponse("It's not that far sssouth of Galmair to the Malachite Mine and the ore.")
talkEntry:addResponse("The deeper you go into the mine, the better the ore, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("malachit")
talkEntry:addTrigger("erz")
talkEntry:addResponse("Ssso weit sssüdlich von Galmair isss die Malachitmine gar nicht, sssz.")
talkEntry:addResponse("Tiefer in der Mine isss Erzss reicher, sssagt man.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("coal")
talkEntry:addTrigger("dark hole")
talkEntry:addResponse("It'sss fine coal we get from the Dark hole Mine, sssz.")
talkEntry:addResponse("Coal would be much more expensive without the Copperhand Tunnel, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Kohle")
talkEntry:addTrigger("Dunkelloch")
talkEntry:addResponse("Esss isss eine gute Kohle, die wir ausss der Dunkellochmine gewinnen, sssz.")
talkEntry:addResponse("Ohne den Copperhand-Tunnel wäre Kohle echt teuer, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
talkingNPC:addCycleText("#me schaut sich gelangweilt um.", "#me looks around bored.")
talkingNPC:addCycleText("#me kratzt sich am Kopf.", "#me scratches his head.")
talkingNPC:addCycleText("Wenns du Hilfe beim Rüstngss machen dann frag michss!", "If yous need any help in ssmithing armours jussst asssk me!")
talkingNPC:addCycleText("Zsss...", "Zsss...")
talkingNPC:addCycleText("Zsss!", "Zsss!")
talkingNPC:addCycleText("Zsss?", "Zsss?")
talkingNPC:addCycleText("#me zischelt.", "#me hisses.")
talkingNPC:addCycleText("Ssss...", "Ssss...")
talkingNPC:addCycleText("Ssss?", "Ssss?")
talkingNPC:addCycleText("Ssss!", "Ssss!")
talkingNPC:addCycleText("Tsss...", "Tsss...")
talkingNPC:addCycleText("#me lässt seinen Schwanz hin und her schnellen.", "#me wags his tail back and forth.")
mainNPC:addLanguage(0)
mainNPC:addLanguage(4)
mainNPC:setDefaultLanguage(0)
mainNPC:setLookat("Dieser NPC ist Seleseth der Rüstschmied.", "This NPC is Seleseth the armourer.")
mainNPC:setUseMessage("Fass mich nicht an!", "Hands off!")
mainNPC:setConfusedMessage("#me schaut dich verwirrt an.", "#me looks at you confused.")
mainNPC:setEquipment(1, 0)
mainNPC:setEquipment(3, 696)
mainNPC:setEquipment(11, 194)
mainNPC:setEquipment(5, 0)
mainNPC:setEquipment(6, 0)
mainNPC:setEquipment(4, 0)
mainNPC:setEquipment(9, 824)
mainNPC:setEquipment(10, 0)
mainNPC:setAutoIntroduceMode(true)

mainNPC:initDone()
return mainNPC
end
local mNPC = initNpc()
initNpc = nil
local M = {}
function M.receiveText(npcChar, texttype, message, speaker) mNPC:receiveText(npcChar, texttype, speaker, message) end
function M.nextCycle(npcChar) mNPC:nextCycle(npcChar) end
function M.lookAtNpc(npcChar, char, mode) mNPC:lookAt(npcChar, char, mode) end
function M.useNPC(npcChar, char, counter, param) mNPC:use(npcChar, char) end
return M
