local consequence_item = require("npc.base.consequence.item")
local condition_item = require("npc.base.condition.item")
local consequence_quest = require("npc.base.consequence.quest")
local consequence_trade = require("npc.base.consequence.trade")
local condition_language = require("npc.base.condition.language")
local basic = require("npc.base.basic")
local talk = require("npc.base.talk")
local trade = require("npc.base.trade")
local condition_quest = require("npc.base.condition.quest")
local consequence_inform = require("npc.base.consequence.inform")
local function initNpc()
local mainNPC = basic()
mainNPC:setAffiliation(0)
local talkingNPC = talk(mainNPC)
local tradingNPC = trade(mainNPC)
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("kauf")
talkEntry:addTrigger("waren")
talkEntry:addTrigger("preis")
talkEntry:addTrigger("Handel")
talkEntry:addTrigger("veräußer")
talkEntry:addTrigger("veräusser")
talkEntry:addResponse("Was? Oh, natürlich kannst du meine Forschung finanzieren!")
talkEntry:addResponse("Kann ich dich an einer Duftkerze interessieren? Uh, zumindest glaube ich, dass sie einen Duft haben. Wachs ist ein Duft, richtig?")
talkEntry:addResponse("Möchtest du einen meiner alten Zauberstäbe haben? Ich kann vielleicht fast sicher garantieren, dass vielleicht nichts explodiert! Hoffentlich...")
talkEntry:addConsequence(consequence_trade(tradingNPC))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("sell")
talkEntry:addTrigger("buy")
talkEntry:addTrigger("wares")
talkEntry:addTrigger("price")
talkEntry:addTrigger("trade")
talkEntry:addTrigger("purchase")
talkEntry:addResponse("What? Oh, sure, I'll let you fund my research.")
talkEntry:addResponse("Can I interest you in some scented candles? Err. At least I think they're scented. Wax is a scent, right?")
talkEntry:addResponse("How about purchasing one of my old wands? Almost certainly assured to maybe not explode on you upon use! Guaranteed, maybe!")
talkEntry:addConsequence(consequence_trade(tradingNPC))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Help")
talkEntry:addConsequence(consequence_inform("[Game Help] This NPC is Terry Ogg, a wandering mage visiting Troll's Haven. Keywords: Magic, Sell, Rune, Glyph, Enchant, Teleport, Spatial"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hilfe")
talkEntry:addConsequence(consequence_inform("[Spielhilfe] Dieser NPC ist Terry Ogg, ein umherziehender Magier der Trolls's Haven besucht. Stichworte: Magie, Kauf, Rune, Glyph, Verzauber, Teleport"))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Hiho")
talkEntry:addTrigger("Hallo")
talkEntry:addTrigger("Hey")
talkEntry:addTrigger("Greeb")
talkEntry:addResponse("Oh, you're back? Or is this our first time meeting?")
talkEntry:addResponse("Hello! Have you seen my wand? Oh, it's right here.")
talkEntry:addResponse("Hello there! Welcome to my... Well, welcome, anyhow.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hello")
talkEntry:addTrigger("Greet")
talkEntry:addTrigger("Hail")
talkEntry:addTrigger("Good day")
talkEntry:addTrigger("Good morning")
talkEntry:addTrigger("Good evening")
talkEntry:addTrigger("Good night")
talkEntry:addResponse("Oh, you're back? Or is this our first time meeting?")
talkEntry:addResponse("Hello! Have you seen my wand? Oh, it's right here.")
talkEntry:addResponse("Hello there! Welcome to my... Well, welcome, anyhow.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hiho")
talkEntry:addTrigger("Hallo")
talkEntry:addTrigger("Hey")
talkEntry:addTrigger("Greeb")
talkEntry:addTrigger("Grüß")
talkEntry:addTrigger("Gruß")
talkEntry:addTrigger("Grüss")
talkEntry:addTrigger("Gruss")
talkEntry:addTrigger("Guten Morgen")
talkEntry:addTrigger("Guten Tag")
talkEntry:addTrigger("Guten Abend")
talkEntry:addTrigger("Gute Nacht")
talkEntry:addTrigger("Mahlzeit")
talkEntry:addTrigger("Tach")
talkEntry:addTrigger("Moin")
talkEntry:addTrigger("Mohltied")
talkEntry:addResponse("Oh du bist zurück? Oder treffen wir uns zum ersten Mal?")
talkEntry:addResponse("Hallo! Hast du meinen Zauberstab gesehen? Oh, da ist er ja.")
talkEntry:addResponse("Guten Tag! Willkommen zu meinem... Also, willkommen halt. ")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Farewell")
talkEntry:addTrigger("Bye")
talkEntry:addTrigger("Fare well")
talkEntry:addTrigger("See you")
talkEntry:addResponse("Carry on then.")
talkEntry:addResponse("Good bye.")
talkEntry:addResponse("Good luck with your... whatever it is.")
talkEntry:addResponse("Safe journey, see you soon.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Tschüß")
talkEntry:addTrigger("Tschüss")
talkEntry:addTrigger("Wiedersehen")
talkEntry:addTrigger("Gehab wohl")
talkEntry:addResponse("Auf Wiedersehen.")
talkEntry:addResponse("Alles Gute mit... was auch immer.")
talkEntry:addResponse("Gute Reise, bis bald.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("How are you")
talkEntry:addTrigger("How do you feel")
talkEntry:addTrigger("How do you do")
talkEntry:addResponse("I'm doing quite splendidly, thank you. I could do with a little more funding though.")
talkEntry:addResponse("Why? Trying to butter me up so I'll teach you magic, are you?")
talkEntry:addResponse("Fine. Now spare me your nonsense and get on with it, I have research to perform.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Wie geht")
talkEntry:addTrigger("Wie fühlst")
talkEntry:addTrigger("Wie ist es ergangen")
talkEntry:addResponse("Mir geht es hervorragend, vielen Dank. Obwohl eine etwas bessere Finanzierung nicht schaden würde.")
talkEntry:addResponse("Wieso fragst du? Willst du mir etwa schmeicheln, sodass ich dich Magie lehre?")
talkEntry:addResponse("Gut. Und nun lass mich mit deinem Blödsinn in Ruhe. Ich muss arbeiten!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("your name")
talkEntry:addTrigger("who are you")
talkEntry:addTrigger("who art thou")
talkEntry:addResponse("Oh, me? Terry Ogg, and that's Ogg, not Egg!")
talkEntry:addResponse("Aha, you wish to know this handsome gentleman's name? I am Terry Ogg, the mighty... What was I doing again?")
talkEntry:addResponse("Who am I? Terry Ogg. Who are you? Wait before you answer that, I don't really care.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("ihr name")
talkEntry:addTrigger("dein name")
talkEntry:addTrigger("wer bist du")
talkEntry:addTrigger("wer seid ihr")
talkEntry:addTrigger("wie heißt")
talkEntry:addTrigger("wie heisst")
talkEntry:addResponse("Wer? Ich? Ich bin Terry Ogg, und es heißt Ogg, nicht Egg!")
talkEntry:addResponse("Ah du willst also den Namen dieses gutausehenden Gentelmans wissen? Ich bin Terry Ogg, der mächtige... was mache ich noch gerade?")
talkEntry:addResponse("Wer ich bin? Terry Ogg. Und wer bist du? Wobei, bevor du das beantwortest... ist mir eigentlich egal.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("my name")
talkEntry:addTrigger("I am called")
talkEntry:addTrigger("I'm called")
talkEntry:addResponse("#me nods half-heartedly, clearly not paying your introduction any mind.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("mein Name")
talkEntry:addTrigger("ich heiße")
talkEntry:addResponse("#me nickt halbherzig und schenkt deiner Vorstellung offensichtlich keine Beachtung. ")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Egg")
talkEntry:addResponse("I told you not to call me that!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(568, "=", 0))
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("rune")
talkEntry:addTrigger("glyph")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("teleport")
talkEntry:addResponse("If you want me to teach you about magic, you have to at least attune to a wand first. Learn how to do so by reading books about magic then try to attune to your wand. You can find these books in any of the realms libraries. After that you may return to me.")
talkEntry:addConsequence(consequence_quest(568, "=", 1))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(568, "=", 0))
talkEntry:addTrigger("magic")
talkEntry:addTrigger("enchant")
talkEntry:addTrigger("wand")
talkEntry:addTrigger("spatial")
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addResponse("If you want me to teach you about magic, you have to at least attune to a wand first. Learn how to do so by reading books about magic then try to attune to your wand. You can find these books in any of the realms libraries. After that you may return to me.")
talkEntry:addConsequence(consequence_quest(568, "=", 1))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(568, "=", 0))
talkEntry:addTrigger("magie")
talkEntry:addTrigger("verzauber")
talkEntry:addTrigger("zauberstab")
talkEntry:addTrigger("teleport")
talkEntry:addTrigger("rune")
talkEntry:addTrigger("glyph")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("auftrag")
talkEntry:addTrigger("aufgabe")
talkEntry:addTrigger("abenteuer")
talkEntry:addResponse("Wenn du willst, dass ich dir etwas über Magie beibringe, musst du dich zumindest auf einen Zauberstab einstimmen. Lerne, wie man das macht, indem du Bücher über Magie liest, und versuche dann dich auf den Zauberstab einzustimmen. Sie können diese Bücher in den Bibliotheken der verschiedenen Reiche finden. Danach kannst du zu mir zurückkehren.")
talkEntry:addConsequence(consequence_quest(568, "=", 1))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(37, "=", 0))
talkEntry:addCondition(condition_quest(568, "=", 1))
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("rune")
talkEntry:addTrigger("glyph")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("teleport")
talkEntry:addResponse("Didn't I tell you to read more books and attune to your wand before you return to me? You can find these books in any of the realms libraries. Now shoo!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(37, "=", 0))
talkEntry:addCondition(condition_quest(568, "=", 1))
talkEntry:addTrigger("magic")
talkEntry:addTrigger("enchant")
talkEntry:addTrigger("wand")
talkEntry:addTrigger("spatial")
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addResponse("Didn't I tell you to read more books and attune to your wand before you return to me? You can find these books in any of the realms libraries. Now shoo!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(37, "=", 0))
talkEntry:addCondition(condition_quest(568, "=", 1))
talkEntry:addTrigger("magie")
talkEntry:addTrigger("verzauber")
talkEntry:addTrigger("zauberstab")
talkEntry:addTrigger("teleport")
talkEntry:addTrigger("rune")
talkEntry:addTrigger("glyph")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("auftrag")
talkEntry:addTrigger("aufgabe")
talkEntry:addTrigger("abenteuer")
talkEntry:addResponse("Habe ich dir nicht gesagt, dass du mehr Bücher lesen musst, und ein besseres Verständnis für deinen Zauberstab entwickeln? Sie können diese Bücher in den Bibliotheken der Reiche finden. Husch husch!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(37, "=", 1))
talkEntry:addCondition(condition_quest(568, "=", 2))
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("rune")
talkEntry:addTrigger("glyph")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("teleport")
talkEntry:addConsequence(consequence_quest(568, "=", 3))
talkEntry:addResponse("Good! I can see you've attuned yourself to a wand! Now what would you like to learn about, enchanting perhaps?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(37, "=", 1))
talkEntry:addCondition(condition_quest(568, "=", 2))
talkEntry:addTrigger("magic")
talkEntry:addTrigger("enchant")
talkEntry:addTrigger("wand")
talkEntry:addTrigger("spatial")
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_quest(568, "=", 3))
talkEntry:addResponse("Good! I can see you've attuned yourself to a wand! Now what would you like to learn about, enchanting perhaps?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(37, "=", 1))
talkEntry:addCondition(condition_quest(568, "=", 2))
talkEntry:addTrigger("magie")
talkEntry:addTrigger("verzauber")
talkEntry:addTrigger("zauberstab")
talkEntry:addTrigger("teleport")
talkEntry:addTrigger("rune")
talkEntry:addTrigger("glyph")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("auftrag")
talkEntry:addTrigger("aufgabe")
talkEntry:addTrigger("abenteuer")
talkEntry:addConsequence(consequence_quest(568, "=", 3))
talkEntry:addResponse("Sehr gut. Du scheinst ein gutes Verständnis für deinen Zauberstab entwickelt zu haben! Was würdest du jetzt gerne lernen? Verzauberungen, vielleicht?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(237, "=", 0))
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("rune")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[New quest] Rune Magic"))
talkEntry:addConsequence(consequence_quest(237, "=", 1))
talkEntry:addResponse("So you want to learn rune magic, eh? First things first, you'll have to learn a rune. My book, right here next to me, will give you a hint to their whereabouts, but beware that a mortal mind can only learn so much within a short timeframe. You may have to wait a week or so after learning each rune or two. Now for your task: go find the location of the primary rune RA, the rune of fire. Learn it, then return to me.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(237, "=", 0))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("magic")
talkEntry:addConsequence(consequence_inform("[New quest] Rune Magic"))
talkEntry:addConsequence(consequence_quest(237, "=", 1))
talkEntry:addResponse("So you want to learn rune magic, eh? First things first, you'll have to learn a rune. My book, right here next to me, will give you a hint to their whereabouts, but beware that a mortal mind can only learn so much within a short timeframe. You may have to wait a week or so after learning each rune or two. Now for your task: go find the location of the primary rune RA, the rune of fire. Learn it, then return to me.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(237, "=", 0))
talkEntry:addTrigger("rune")
talkEntry:addTrigger("verzauber")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("auftrag")
talkEntry:addTrigger("aufgabe")
talkEntry:addTrigger("abenteuer")
talkEntry:addTrigger("magie")
talkEntry:addConsequence(consequence_inform("[Neue Quest] Runenmagie"))
talkEntry:addConsequence(consequence_quest(237, "=", 1))
talkEntry:addResponse("Also, du möchtest Runenmagie lernen, ja? Zuerst musst du eine Rune lernen. Mein Buch, gleich hier neben mir, gibt dir einen Hinweis auf ihren Aufenthaltsort, aber sei gewarnt: Ein sterblicher Geist kann nur so viel in kurzer Zeit aufnehmen. Du musst vielleicht eine Woche oder so warten, nachdem du jede Rune oder zwei gelernt hast. Jetzt zu deiner Aufgabe: Finde den Standort der Primärrune RA, der Rune des Feuers. Lerne sie und kehre dann zu mir zurück.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(237, "=", 1))
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("rune")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("You still haven't found the location of the rune RA. Return to me when you have.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(237, "=", 1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("magic")
talkEntry:addResponse("You still haven't found the location of the rune RA. Return to me when you have.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(237, "=", 1))
talkEntry:addTrigger("rune")
talkEntry:addTrigger("verzauber")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("auftrag")
talkEntry:addTrigger("aufgabe")
talkEntry:addTrigger("abenteuer")
talkEntry:addTrigger("magie")
talkEntry:addResponse("Du hast den Ort der Rune RA immer noch nicht gefunden. Kehre zu mir zurück, wenn du sie gefunden hast.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(237, "=", 2))
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("rune")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_quest(237, "=", 3))
talkEntry:addResponse("Now that you have learned how to use the rune RA, you will want a grimoire to more conveniently store the structure of your spells in. You can purchase a blank book from a tailor of your own choosing to enchant into a grimoire, a process which is done at the magic desk, or you can fund my researching by purchasing one from me directly!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(237, "=", 2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("magic")
talkEntry:addConsequence(consequence_quest(237, "=", 3))
talkEntry:addResponse("Now that you have learned how to use the rune RA, you will want a grimoire to more conveniently store the structure of your spells in. You can purchase a blank book from a tailor of your own choosing to enchant into a grimoire, a process which is done at the magic desk, or you can fund my researching by purchasing one from me directly!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(237, "=", 2))
talkEntry:addTrigger("rune")
talkEntry:addTrigger("verzauber")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("auftrag")
talkEntry:addTrigger("aufgabe")
talkEntry:addTrigger("abenteuer")
talkEntry:addTrigger("magie")
talkEntry:addConsequence(consequence_quest(237, "=", 3))
talkEntry:addResponse("Nun, da du gelernt hast, wie man die Rune RA benutzt, wirst du ein Grimoire haben wollen, um die Struktur deiner Zauber bequemer zu speichern. Du kannst ein leeres Buch von einem Schneider deiner Wahl kaufen, um es in ein Grimoire zu verzaubern ? ein Prozess, der am Magie-Tisch durchgeführt wird ? oder du kannst meine Forschung unterstützen, indem du eines direkt von mir kaufst!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(237, "=", 3))
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("rune")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_quest(237, "=", 4))
talkEntry:addResponse("Next up, go store the structure of the rune RA into your new grimoire. Once you have, you will be able to attune a wand of your choice to the spell for more convenient casting of magic! You will need a quill, of course. You can either buy one from Half-hung Bryan over by the inn or find a carpenter to make you one.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(237, "=", 3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("magic")
talkEntry:addConsequence(consequence_quest(237, "=", 4))
talkEntry:addResponse("Next up, go store the structure of the rune RA into your new grimoire. Once you have, you will be able to attune a wand of your choice to the spell for more convenient casting of magic! You will need a quill, of course. You can either buy one from Half-hung Bryan over by the inn or find a carpenter to make you one.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(237, "=", 3))
talkEntry:addTrigger("rune")
talkEntry:addTrigger("verzauber")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("auftrag")
talkEntry:addTrigger("aufgabe")
talkEntry:addTrigger("abenteuer")
talkEntry:addTrigger("magie")
talkEntry:addConsequence(consequence_quest(237, "=", 4))
talkEntry:addResponse("Als Nächstes speichere die Struktur der Rune RA in dein neues Grimoire. Sobald du das getan hast, kannst du einen Zauberstab deiner Wahl auf den Zauber abstimmen, um die Magie bequemer wirken zu können! Du brauchst natürlich eine Feder. Du kannst entweder eine bei Halb-Aufgehängtem Bryan beim Gasthaus kaufen oder einen Tischler finden, der dir eine anfertigt.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(237, "=", 4))
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("rune")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("You still haven't stored the rune RA as a spell in your grimoire. Return to me when you have.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(237, "=", 4))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("magic")
talkEntry:addResponse("You still haven't stored the rune RA as a spell in your grimoire. Return to me when you have.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(237, "=", 4))
talkEntry:addTrigger("rune")
talkEntry:addTrigger("verzauber")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("auftrag")
talkEntry:addTrigger("aufgabe")
talkEntry:addTrigger("abenteuer")
talkEntry:addTrigger("magie")
talkEntry:addResponse("Du hast den Zauber RA noch immer nicht in deinem Grimoire geschrieben. Kehre zu mir zurück, wenn du ihn niedergeschrieben hast.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(237, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("rune")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_quest(237, "=", 6))
talkEntry:addResponse("Getting there! Now all that remains is casting the spell. You can either use your grimoire to attune your wand to the stored spell, or you can just speak the rune out loud while picturing the result you want in your mind. Go on, cast one before me. Show me what you got.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(237, "=", 5))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("magic")
talkEntry:addConsequence(consequence_quest(237, "=", 6))
talkEntry:addResponse("Getting there! Now all that remains is casting the spell. You can either use your grimoire to attune your wand to the stored spell, or you can just speak the rune out loud while picturing the result you want in your mind. Go on, cast one before me. Show me what you got.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(237, "=", 5))
talkEntry:addTrigger("rune")
talkEntry:addTrigger("verzauber")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("auftrag")
talkEntry:addTrigger("aufgabe")
talkEntry:addTrigger("abenteuer")
talkEntry:addTrigger("magie")
talkEntry:addConsequence(consequence_quest(237, "=", 6))
talkEntry:addResponse("Wir kommen zum Ziel! Jetzt musst du nur noch den Zauberspruch sprechen. Du kannst entweder dein Grimoire benutzen, um deinen Zauberstab auf den hinterlegten Zauberspruch einzustimmen, oder du kannst die Rune laut aussprechen und dir dabei das gewünschte Ergebnis vorstellen. Na los, sprich einen Zauber vor mir. Zeig mir, was du kannst.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(237, "=", 6))
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("rune")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Come on, I don't have all day. Cast RA for me!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(237, "=", 6))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("magic")
talkEntry:addResponse("Come on, I don't have all day. Cast RA for me!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(237, "=", 6))
talkEntry:addTrigger("rune")
talkEntry:addTrigger("verzauber")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("auftrag")
talkEntry:addTrigger("aufgabe")
talkEntry:addTrigger("abenteuer")
talkEntry:addTrigger("magie")
talkEntry:addResponse("Komm schon, ich habe nicht den ganzen Tag Zeit. Nutze den Zauber RA für mich!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(237, "=", 7))
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("rune")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_quest(237, "=", 8))
talkEntry:addResponse("Well done, that is all I can teach you of rune magic! Though there are other kinds of magic I can also teach you about.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(237, "=", 7))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("magic")
talkEntry:addConsequence(consequence_quest(237, "=", 8))
talkEntry:addResponse("Well done, that is all I can teach you of rune magic! Though there are other kinds of magic I can also teach you about.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(237, "=", 7))
talkEntry:addTrigger("rune")
talkEntry:addTrigger("verzauber")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("auftrag")
talkEntry:addTrigger("aufgabe")
talkEntry:addTrigger("abenteuer")
talkEntry:addTrigger("magie")
talkEntry:addConsequence(consequence_quest(237, "=", 8))
talkEntry:addResponse("Gut gemacht! Das ist alles, was ich dir über Runenmagie beibringen kann! Es gibt aber auch andere Arten von Magie, die ich dir beibringen kann.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 0))
talkEntry:addCondition(condition_quest(37, "=", 1))
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("glyph")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_quest(241, "=", 1))
talkEntry:addResponse("So you want to learn about enchanting items through the means of glyphs? Fine, I'll teach you the basics. First of all, you need a shrine to perform the enchantment at. You can use the one I set up over there, or if in the future you find yourself far away, you can use your wand to set up your own based on that. Go have a look at it, then you can return to me for your next task.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 0))
talkEntry:addCondition(condition_quest(37, "=", 1))
talkEntry:addTrigger("enchant")
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("magic")
talkEntry:addConsequence(consequence_quest(241, "=", 1))
talkEntry:addResponse("So you want to learn about enchanting items through the means of glyphs? Fine, I'll teach you the basics. First of all, you need a shrine to perform the enchantment at. You can use the one I set up over there, or if in the future you find yourself far away, you can use your wand to set up your own based on that. Go have a look at it, then you can return to me for your next task.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 0))
talkEntry:addCondition(condition_quest(37, "=", 1))
talkEntry:addTrigger("glyph")
talkEntry:addTrigger("verzauber")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("auftrag")
talkEntry:addTrigger("aufgabe")
talkEntry:addTrigger("abenteuer")
talkEntry:addTrigger("magie")
talkEntry:addConsequence(consequence_quest(241, "=", 1))
talkEntry:addResponse("Du möchtest also etwas über das Verzaubern von Gegenständen mit Glyphen lernen? Na gut, ich bringe dir die Grundlagen bei. Zu allererst brauchst du einen Schrein, an dem du Verzauberungen durchführen kannst. Du kannst entweder den dort drüben nutzen, oder einen eigenen mit deinem Zauberstab erschaffen. Sieh ihn dir mal an und komm dann zu mir zurück.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 1))
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("glyph")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("You still need to examine a glyph ritual shrine. Return to me once you have.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 1))
talkEntry:addTrigger("enchant")
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("magic")
talkEntry:addResponse("You still need to examine a glyph ritual shrine. Return to me once you have.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 1))
talkEntry:addTrigger("glyph")
talkEntry:addTrigger("verzauber")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("auftrag")
talkEntry:addTrigger("aufgabe")
talkEntry:addTrigger("abenteuer")
talkEntry:addTrigger("magie")
talkEntry:addResponse("Du musst noch immer einen Glyphenritualschrein untersuchen. Komm wieder, wenn du das erledigt hast.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 2))
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("glyph")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_quest(241, "=", 3))
talkEntry:addConsequence(consequence_item(43, 2, 333, nil))
talkEntry:addConsequence(consequence_item(399, 2, 333, nil))
talkEntry:addResponse("Good. Now that you've familiarised yourself with where you will be performing the work, we can move on to the next step. Here, take these candles and candlesticks. You'll use them as you channel your mana into the shrine, in a ritual to prepare it for your work. Make sure not to lose them, if you do you'll have to buy your own.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 2))
talkEntry:addTrigger("enchant")
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("magic")
talkEntry:addConsequence(consequence_quest(241, "=", 3))
talkEntry:addConsequence(consequence_item(43, 2, 333, nil))
talkEntry:addConsequence(consequence_item(399, 2, 333, nil))
talkEntry:addResponse("Good. Now that you've familiarised yourself with where you will be performing the work, we can move on to the next step. Here, take these candles and candlesticks. You'll use them as you channel your mana into the shrine, in a ritual to prepare it for your work. Make sure not to lose them, if you do you'll have to buy your own.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 2))
talkEntry:addTrigger("glyph")
talkEntry:addTrigger("verzauber")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("auftrag")
talkEntry:addTrigger("aufgabe")
talkEntry:addTrigger("abenteuer")
talkEntry:addTrigger("magie")
talkEntry:addConsequence(consequence_quest(241, "=", 3))
talkEntry:addConsequence(consequence_item(43, 2, 333, nil))
talkEntry:addConsequence(consequence_item(399, 2, 333, nil))
talkEntry:addResponse("Sehr gut. Jetzt weißt du, wo du arbeiten kannst und wir können zum nächsten Schritt übergehen. Hier, nimm diese Kerzen und Kerzenhalter. Sie werden dafür verwendet, dein Mana in den Schrein zu kanalisieren, um ihn für deine Arbeit vorzubereiten. Verlier sie nicht, sonst musst du dir deine eigenen kaufen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 3))
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("glyph")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("You still need to prepare a ritual at a glyph ritual shrine. Return to me once you have.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 3))
talkEntry:addTrigger("enchant")
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("magic")
talkEntry:addResponse("You still need to prepare a ritual at a glyph ritual shrine. Return to me once you have.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 3))
talkEntry:addTrigger("glyph")
talkEntry:addTrigger("verzauber")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("auftrag")
talkEntry:addTrigger("aufgabe")
talkEntry:addTrigger("abenteuer")
talkEntry:addTrigger("magie")
talkEntry:addResponse("Du musst noch ein Ritual an einem Glyphenritualschrein vorbereiten. Komm wieder, wenn du das erledigt hast.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 4))
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("glyph")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_quest(241, "=", 5))
talkEntry:addConsequence(consequence_item(4184, 1, 333, nil))
talkEntry:addConsequence(consequence_item(4185, 1, 333, nil))
talkEntry:addConsequence(consequence_item(4186, 1, 333, nil))
talkEntry:addConsequence(consequence_item(4187, 1, 333, nil))
talkEntry:addConsequence(consequence_item(4188, 1, 333, nil))
talkEntry:addConsequence(consequence_item(4189, 1, 333, nil))
talkEntry:addConsequence(consequence_item(4190, 1, 333, nil))
talkEntry:addResponse("Good! Now with the shrine set up, you can use it to combine glyph shards you find around the lands of Illarion into a fully fledged glyph. Since I'm so nice, I will provide you with a full set you can use to give it a try.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 4))
talkEntry:addTrigger("enchant")
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("magic")
talkEntry:addConsequence(consequence_quest(241, "=", 5))
talkEntry:addConsequence(consequence_item(4184, 1, 333, nil))
talkEntry:addConsequence(consequence_item(4185, 1, 333, nil))
talkEntry:addConsequence(consequence_item(4186, 1, 333, nil))
talkEntry:addConsequence(consequence_item(4187, 1, 333, nil))
talkEntry:addConsequence(consequence_item(4188, 1, 333, nil))
talkEntry:addConsequence(consequence_item(4189, 1, 333, nil))
talkEntry:addConsequence(consequence_item(4190, 1, 333, nil))
talkEntry:addResponse("Good! Now with the shrine set up, you can use it to combine glyph shards you find around the lands of Illarion into a fully fledged glyph. Since I'm so nice, I will provide you with a full set you can use to give it a try.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 4))
talkEntry:addTrigger("glyph")
talkEntry:addTrigger("verzauber")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("auftrag")
talkEntry:addTrigger("aufgabe")
talkEntry:addTrigger("abenteuer")
talkEntry:addTrigger("magie")
talkEntry:addConsequence(consequence_quest(241, "=", 5))
talkEntry:addConsequence(consequence_item(4184, 1, 333, nil))
talkEntry:addConsequence(consequence_item(4185, 1, 333, nil))
talkEntry:addConsequence(consequence_item(4186, 1, 333, nil))
talkEntry:addConsequence(consequence_item(4187, 1, 333, nil))
talkEntry:addConsequence(consequence_item(4188, 1, 333, nil))
talkEntry:addConsequence(consequence_item(4189, 1, 333, nil))
talkEntry:addConsequence(consequence_item(4190, 1, 333, nil))
talkEntry:addResponse("Ausgezeichnet! Nachdem du jetzt den Schrein vorbereitet hast, kannst du ihn dafür nutzen Glyphscherben, die du überall in Illarion finden kannst, in vollständige Glyphen zu verbinden. Weil ich so nett bin, gebe ich dir ein ganzes Set an Scherben, mit dem du es mal ausprobieren kannst.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("glyph")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("You still need to combine the shards I gave you into a glyph. Return to me once you have. If you lost the shards, you'll have to search the lands of Illarion for new ones as I have no more for you.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 5))
talkEntry:addTrigger("enchant")
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("magic")
talkEntry:addResponse("You still need to combine the shards I gave you into a glyph. Return to me once you have. If you lost the shards, you'll have to search the lands of Illarion for new ones as I have no more for you.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 5))
talkEntry:addTrigger("glyph")
talkEntry:addTrigger("verzauber")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("auftrag")
talkEntry:addTrigger("aufgabe")
talkEntry:addTrigger("abenteuer")
talkEntry:addTrigger("magie")
talkEntry:addResponse("Du musst noch die Scherben, die ich dir gegeben habe, zu einer Glyphe verbinden. Komm wieder, wenn du das erledigt hast. Falls du die Scherben verloren hast, musst du wohl die Länder Illarions nach neuen durchsuchen - ich habe leider keine mehr.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 6))
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("glyph")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_quest(241, "=", 7))
talkEntry:addResponse("Now that you have a glyph, first thing you can do is to inspect it! Simply use your wand to channel your mana into it, and you should be able to learn more about it through feeling your way around!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 6))
talkEntry:addTrigger("enchant")
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("magic")
talkEntry:addConsequence(consequence_quest(241, "=", 7))
talkEntry:addResponse("Now that you have a glyph, first thing you can do is to inspect it! Simply use your wand to channel your mana into it, and you should be able to learn more about it through feeling your way around!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 6))
talkEntry:addTrigger("glyph")
talkEntry:addTrigger("verzauber")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("auftrag")
talkEntry:addTrigger("aufgabe")
talkEntry:addTrigger("abenteuer")
talkEntry:addTrigger("magie")
talkEntry:addConsequence(consequence_quest(241, "=", 7))
talkEntry:addResponse("Nun, da du eine Glyphe hergestellt hast, ist der nächste Schritt sie zu untersuchen! Nutz einfach deinen Zauberstab, um dein Mana in die Glyphe zu kanalisieren und schon solltest du mehr über sie erfahren können.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 7))
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("glyph")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("You still need to inspect the glyph you made. Return to me once you have.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 7))
talkEntry:addTrigger("enchant")
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("magic")
talkEntry:addResponse("You still need to inspect the glyph you made. Return to me once you have.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 7))
talkEntry:addTrigger("glyph")
talkEntry:addTrigger("verzauber")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("auftrag")
talkEntry:addTrigger("aufgabe")
talkEntry:addTrigger("abenteuer")
talkEntry:addTrigger("magie")
talkEntry:addResponse("Du musst noch die Glyphe, die du hergestellt hast, untersuchen. Komm wieder, wenn du das erledigt hast.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 8))
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("glyph")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_quest(241, "=", 9))
talkEntry:addConsequence(consequence_item(3527, 1, 333, nil))
talkEntry:addResponse("Now you know more about the glyph, such as the jewellery type it can be used with. In this case, it requires an amethyst ring. You can use your own, but I have one for you here that you can use. Simply hold both the ring and glyph in your hands, then press the glyph against the ring for them to merge. It is so simple, even a commoner can do it! The magic happens during the forging after all, so you can feel free to sell glyphs to others without socketing a glyph into a piece of jewellery first.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 8))
talkEntry:addTrigger("enchant")
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("magic")
talkEntry:addConsequence(consequence_quest(241, "=", 9))
talkEntry:addConsequence(consequence_item(3527, 1, 333, nil))
talkEntry:addResponse("Now you know more about the glyph, such as the jewellery type it can be used with. In this case, it requires an amethyst ring. You can use your own, but I have one for you here that you can use. Simply hold both the ring and glyph in your hands, then press the glyph against the ring for them to merge. It is so simple, even a commoner can do it! The magic happens during the forging after all, so you can feel free to sell glyphs to others without socketing a glyph into a piece of jewellery first.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 8))
talkEntry:addTrigger("glyph")
talkEntry:addTrigger("verzauber")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("auftrag")
talkEntry:addTrigger("aufgabe")
talkEntry:addTrigger("abenteuer")
talkEntry:addTrigger("magie")
talkEntry:addConsequence(consequence_quest(241, "=", 9))
talkEntry:addConsequence(consequence_item(3527, 1, 333, nil))
talkEntry:addResponse("Jetzt weißt du mehr über die Glyphe - zum Beispiel, in welche Arten von Schmuck sie eingesetzt werden kann. In diesem Fall brauchst du einen Amethystring. Du kannst einen eigenen nutzen, aber sonst kannst du auch diesen hier haben. Halt einfach die Glyphe und den Ring in deinen Händen und press sie zusammen, bis sie verschmelzen. Es ist so einfach, dass selbst normale Leute es machen können! Die Magie findet beim Verbinden der Scherben statt. Du kannst Glyphen also auch einzeln verkaufen, ohne sie in Schmuck einzusetzen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 9))
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("glyph")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("You still need to socket the glyph into a ring. Return to me once you have.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 9))
talkEntry:addTrigger("enchant")
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("magic")
talkEntry:addResponse("You still need to socket the glyph into a ring. Return to me once you have.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 9))
talkEntry:addTrigger("glyph")
talkEntry:addTrigger("verzauber")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("auftrag")
talkEntry:addTrigger("aufgabe")
talkEntry:addTrigger("abenteuer")
talkEntry:addTrigger("magie")
talkEntry:addResponse("Du musst die Glyphe noch in einen Ring einsetzen. Komm wieder, wenn das erledigt ist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 10))
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("glyph")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_quest(241, "=", 11))
talkEntry:addResponse("Good! Now that the glyph has been socketed into the ring, there are two things you can do. You can inspect it, just like you did to the glyph previously. If you're unhappy with it, perhaps having used a low quality metal like copper that is less conductive to magic than silver or gold, you can also use the shrine to break the glyph out of the jewellery. This will however harm the jewellery's durability; you might need to repair it and you won't be able to recover all the shards, or even any if the glyph is too fragile due to seeing too much use! Go on, give it a go.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 10))
talkEntry:addTrigger("enchant")
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("magic")
talkEntry:addConsequence(consequence_quest(241, "=", 11))
talkEntry:addResponse("Good! Now that the glyph has been socketed into the ring, there are two things you can do. You can inspect it, just like you did to the glyph previously. If you're unhappy with it, perhaps having used a low quality metal like copper that is less conductive to magic than silver or gold, you can also use the shrine to break the glyph out of the jewellery. This will however harm the jewellery's durability; you might need to repair it and you won't be able to recover all the shards, or even any if the glyph is too fragile due to seeing too much use! Go on, give it a go.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 10))
talkEntry:addTrigger("glyph")
talkEntry:addTrigger("verzauber")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("auftrag")
talkEntry:addTrigger("aufgabe")
talkEntry:addTrigger("abenteuer")
talkEntry:addTrigger("magie")
talkEntry:addConsequence(consequence_quest(241, "=", 11))
talkEntry:addResponse("Großartig! Mit dem verzauberten Ring kannst du jetzt zwei Dinge tun. Du kannst ihn untersuchen, wie auch die Glyphe zuvor. Wenn du mit dem Ergebnis unzufrieden bist, weil du zum Beispiel ein minderwertiges Metall wie Kupfer genommen hast, welches für Magie nicht so empfänglich ist wie Silber oder Gold, kannst du die Glyphe an einem Schrein wieder aus dem Schmuckstück herausbrechen. Dies beschädigt den Schmuck etwas, so dass du ihn eventuell reparieren musst. Allerdings kannst du lediglich ein paar Scherben wiederverwenden, oder sogar gar keine, falls die Glyphe nur noch wenig geladen ist. Na los, versuch es mal!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 11))
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("glyph")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("You still need to break out the glyph in the ring you socketed previously. Return to me once you have. If you lost the ring, or used up the charges, then any other ring you've socketed will do.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 11))
talkEntry:addTrigger("enchant")
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("magic")
talkEntry:addResponse("You still need to break out the glyph in the ring you socketed previously. Return to me once you have. If you lost the ring, or used up the charges, then any other ring you've socketed will do.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 11))
talkEntry:addTrigger("glyph")
talkEntry:addTrigger("verzauber")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("auftrag")
talkEntry:addTrigger("aufgabe")
talkEntry:addTrigger("abenteuer")
talkEntry:addTrigger("magie")
talkEntry:addResponse("Du musst noch eine Glyphe aus einem Ring entfernen. Komm wieder, wenn du das erledigt hast. Falls du den Ring verloren hast oder alle Ladungen aufgebraucht hast, kannst du auch jeden anderen Ring, den du verzaubert hast, nutzen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 12))
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("glyph")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_quest(241, "=", 13))
talkEntry:addConsequence(consequence_item(43, 4, 333, nil))
talkEntry:addConsequence(consequence_item(399, 4, 333, nil))
talkEntry:addResponse("That's all I have to teach you about enchanting jewellery through the means of glyph forging. Don't feel too down about destroying the glyph you just made, you'll find plenty more of the mystical shards in the wild as they fall bursting with light, a sign of the mana captured within. Here, have these candles and candlesticks as a reward to get you started on your path as an enchanter!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 12))
talkEntry:addTrigger("enchant")
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("magic")
talkEntry:addConsequence(consequence_quest(241, "=", 13))
talkEntry:addConsequence(consequence_item(43, 4, 333, nil))
talkEntry:addConsequence(consequence_item(399, 4, 333, nil))
talkEntry:addResponse("That's all I have to teach you about enchanting jewellery through the means of glyph forging. Don't feel too down about destroying the glyph you just made, you'll find plenty more of the mystical shards in the wild as they fall bursting with light, a sign of the mana captured within. Here, have these candles and candlesticks as a reward to get you started on your path as an enchanter!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(241, "=", 12))
talkEntry:addTrigger("glyph")
talkEntry:addTrigger("verzauber")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("auftrag")
talkEntry:addTrigger("aufgabe")
talkEntry:addTrigger("abenteuer")
talkEntry:addTrigger("magie")
talkEntry:addConsequence(consequence_quest(241, "=", 13))
talkEntry:addConsequence(consequence_item(43, 4, 333, nil))
talkEntry:addConsequence(consequence_item(399, 4, 333, nil))
talkEntry:addResponse("Das ist alles was, was ich dir über das Verzaubern von Schmuck beibringen kann. Sei nicht zu enttäuscht, dass du die Glyphe, die du gerade hergestellt hast, wieder zerstört hast. Du wirst reichlich magische Scherben in der Wildnis finden, die über Illarion niedergegangen sind. Sie schimmern in einem besonderen Licht, welches vom in ihnen eingefangenen Mana stammt. Nimm diese Kerzen und Kerzenhalter als Belohnung, damit du deinen Pfad in der Magie der Verzauberung beschreiten kannst.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(240, "=", 0))
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("teleport")
talkEntry:addConsequence(consequence_inform("[New quest] Spatial Magic"))
talkEntry:addConsequence(consequence_quest(240, "=", 1))
talkEntry:addResponse("So you want to learn about spatial magic, eh? Well first go on and head over to the nearby teleporter and use your wand to attune to it, then return to me once you have succeeded.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(240, "=", 0))
talkEntry:addTrigger("portal")
talkEntry:addTrigger("spatial")
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_inform("[New quest] Spatial Magic"))
talkEntry:addConsequence(consequence_quest(240, "=", 1))
talkEntry:addResponse("So you want to learn about spatial magic, eh? Well first go on and head over to the nearby teleporter and use your wand to attune to it, then return to me once you have succeeded.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(240, "=", 0))
talkEntry:addTrigger("teleport")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("auftrag")
talkEntry:addTrigger("aufgabe")
talkEntry:addTrigger("abenteuer")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_inform("[Neue Quest] Raummagie"))
talkEntry:addConsequence(consequence_quest(240, "=", 1))
talkEntry:addResponse("Also, du willst etwas über Raum-Magie lernen, hm? Geh zuerst zum nahegelegenen Teleporter und benutze deinen Zauberstab, um dich darauf abzustimmen. Kehre dann zu mir zurück, sobald du Erfolg hattest.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(240, "=", 1))
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("teleport")
talkEntry:addResponse("Go on then. Go attune yourself to the teleporter. The incantation is 'Locus Memento'.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(240, "=", 1))
talkEntry:addTrigger("portal")
talkEntry:addTrigger("spatial")
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addResponse("Go on then. Go attune yourself to the teleporter. The incantation is 'Locus Memento'.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(240, "=", 1))
talkEntry:addTrigger("teleport")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("auftrag")
talkEntry:addTrigger("aufgabe")
talkEntry:addTrigger("abenteuer")
talkEntry:addTrigger("order")
talkEntry:addResponse("Na dann los. Geh und stimm dich auf den Teleporter ab. Die Beschwörungsformel lautet 'Locus Memento'.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(240, "=", 2))
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("teleport")
talkEntry:addConsequence(consequence_quest(240, "=", 3))
talkEntry:addResponse("Good, you're attuned to the teleporter! Next up, show me how you teleport to it. The incantation is 'Locus Itinerantur'.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(240, "=", 2))
talkEntry:addTrigger("portal")
talkEntry:addTrigger("spatial")
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_quest(240, "=", 3))
talkEntry:addResponse("Good, you're attuned to the teleporter! Next up, show me how you teleport to it. The incantation is 'Locus Itinerantur'.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(240, "=", 2))
talkEntry:addTrigger("teleport")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("auftrag")
talkEntry:addTrigger("aufgabe")
talkEntry:addTrigger("abenteuer")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_quest(240, "=", 3))
talkEntry:addResponse("Gut, du hast dich auf den Teleporter abgestimmt! Als Nächstes musst du mir zeigen, wie du dich zu ihm teleportierst. Die Beschwörungsformel lautet 'Locus Itinerantur'.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(240, "=", 3))
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("teleport")
talkEntry:addResponse("Well go on then. I want to see you teleport to the nearby teleporter.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(240, "=", 3))
talkEntry:addTrigger("portal")
talkEntry:addTrigger("spatial")
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addResponse("Well go on then. I want to see you teleport to the nearby teleporter.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(240, "=", 3))
talkEntry:addTrigger("teleport")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("auftrag")
talkEntry:addTrigger("aufgabe")
talkEntry:addTrigger("abenteuer")
talkEntry:addTrigger("order")
talkEntry:addResponse("Na dann los. Ich möchte sehen, wie du dich zum nahe gelegenen Teleporter teleportierst.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(240, "=", 4))
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("teleport")
talkEntry:addConsequence(consequence_quest(240, "=", 5))
talkEntry:addResponse("Well done! Next up, I want to see you open a portal to it as well. The incantation is 'Locus Ianua'.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(240, "=", 4))
talkEntry:addTrigger("portal")
talkEntry:addTrigger("spatial")
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_quest(240, "=", 5))
talkEntry:addResponse("Well done! Next up, I want to see you open a portal to it as well. The incantation is 'Locus Ianua'.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(240, "=", 4))
talkEntry:addTrigger("teleport")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("auftrag")
talkEntry:addTrigger("aufgabe")
talkEntry:addTrigger("abenteuer")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_quest(240, "=", 5))
talkEntry:addResponse("Gut gemacht! Als Nächstes möchte ich sehen, wie du auch ein Portal zu ihm öffnest. Die Beschwörungsformel lautet 'Locus Ianua'.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(240, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("teleport")
talkEntry:addResponse("Well go on then. I want to see you open a portal to the nearby teleporter.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(240, "=", 5))
talkEntry:addTrigger("portal")
talkEntry:addTrigger("spatial")
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addResponse("Well go on then. I want to see you open a portal to the nearby teleporter.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(240, "=", 5))
talkEntry:addTrigger("teleport")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("auftrag")
talkEntry:addTrigger("aufgabe")
talkEntry:addTrigger("abenteuer")
talkEntry:addTrigger("order")
talkEntry:addResponse("Na dann los. Ich möchte sehen, wie du ein Portal zum nahen Teleporter öffnest.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(240, "=", 6))
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("teleport")
talkEntry:addConsequence(consequence_quest(240, "=", 7))
talkEntry:addConsequence(consequence_item(4815, 1, 333, nil))
talkEntry:addConsequence(consequence_item(1118, 1, 333, nil))
talkEntry:addResponse("Alright then, you know your way around spatial magic. For your last task, I want you to go over to the magic desk over there and craft me a portal book. Once created, you can use your wand to inspect the quality of your book. Here, have this empty book and bottle of ink to help you along. You'll need to get your own quill, though.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(240, "=", 6))
talkEntry:addTrigger("portal")
talkEntry:addTrigger("spatial")
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_quest(240, "=", 7))
talkEntry:addConsequence(consequence_item(4815, 1, 333, nil))
talkEntry:addConsequence(consequence_item(1118, 1, 333, nil))
talkEntry:addResponse("Alright then, you know your way around spatial magic. For your last task, I want you to go over to the magic desk over there and craft me a portal book. Once created, you can use your wand to inspect the quality of your book. Here, have this empty book and bottle of ink to help you along. You'll need to get your own quill, though.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(240, "=", 6))
talkEntry:addTrigger("teleport")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("auftrag")
talkEntry:addTrigger("aufgabe")
talkEntry:addTrigger("abenteuer")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_quest(240, "=", 7))
talkEntry:addConsequence(consequence_item(4815, 1, 333, nil))
talkEntry:addConsequence(consequence_item(1118, 1, 333, nil))
talkEntry:addResponse("Also gut, du kennst dich mit Raummagie aus. Für deine letzte Aufgabe möchte ich, dass du zum Zauberpult dort drüben gehst und mir ein Portalbuch anfertigst. Sobald es fertig ist, kannst du mit Hilfe deines Zauberstab die Qualität deines Buches überprüfen. Hier, nimm dieses leere Buch und die Tintenflasche, um dir zu helfen. Eine Feder musst du dir allerdings selbst besorgen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(240, "=", 7))
talkEntry:addCondition(condition_item(1061, "all", ">", 0, nil))
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("teleport")
talkEntry:addConsequence(consequence_quest(240, "=", 8))
talkEntry:addResponse("Splendid! You can keep the book. That's all there is that I have to teach you about spatial magic. Though you can always ask me about other types of magic.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(240, "=", 7))
talkEntry:addCondition(condition_item(1061, "all", ">", 0, nil))
talkEntry:addTrigger("portal")
talkEntry:addTrigger("spatial")
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_quest(240, "=", 8))
talkEntry:addResponse("Splendid! You can keep the book. That's all there is that I have to teach you about spatial magic. Though you can always ask me about other types of magic.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(240, "=", 7))
talkEntry:addCondition(condition_item(1061, "all", ">", 0, nil))
talkEntry:addTrigger("teleport")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("auftrag")
talkEntry:addTrigger("aufgabe")
talkEntry:addTrigger("abenteuer")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_quest(240, "=", 8))
talkEntry:addResponse("Prächtig! Du kannst das Buch behalten. Das ist alles, was ich dir über Raummagie beibringen kann. Du kannst mich aber jederzeit über andere Arten von Magie befragen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(240, "=", 7))
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("teleport")
talkEntry:addResponse("Where's my portal book?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(240, "=", 7))
talkEntry:addTrigger("portal")
talkEntry:addTrigger("spatial")
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addResponse("Where's my portal book?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(240, "=", 7))
talkEntry:addTrigger("teleport")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("auftrag")
talkEntry:addTrigger("aufgabe")
talkEntry:addTrigger("abenteuer")
talkEntry:addTrigger("order")
talkEntry:addResponse("Wo ist mein Portalbuch?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("rune")
talkEntry:addTrigger("glyph")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("teleport")
talkEntry:addResponse("There is nothing more I can teach you for now. Once I've had a chance to settle all my things, I may have more for you to learn though.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("magic")
talkEntry:addTrigger("enchant")
talkEntry:addTrigger("wand")
talkEntry:addTrigger("spatial")
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addResponse("There is nothing more I can teach you for now. Once I've had a chance to settle all my things, I may have more for you to learn though.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("magie")
talkEntry:addTrigger("verzauber")
talkEntry:addTrigger("zauberstab")
talkEntry:addTrigger("teleport")
talkEntry:addTrigger("rune")
talkEntry:addTrigger("glyph")
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("auftrag")
talkEntry:addTrigger("aufgabe")
talkEntry:addTrigger("abenteuer")
talkEntry:addResponse("Ich kann dir nichts weiter beibringen. Aber sobald ich mich hier eingelebt habe, kann ich dir vielleicht mehr beibringen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("job")
talkEntry:addResponse("What do I do for a living? Isn't it obvious? I'm a proud almighty magician, darn it! See the hat?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("job")
talkEntry:addResponse("Womit verdiene ich meinen Lebensunterhalt? Ist das nicht offensichtlich? Ich bin ein stolzer, allmächtiger Zauberer, verflixt noch mal! Siehst du den Hut denn nicht?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("profession")
talkEntry:addTrigger("work")
talkEntry:addResponse("What do I do for a living? Isn't it obvious? I'm a proud almighty magician, darn it! See the hat?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("beruf")
talkEntry:addResponse("Womit verdiene ich meinen Lebensunterhalt? Ist das nicht offensichtlich? Ich bin ein stolzer, allmächtiger Zauberer, verflixt noch mal! Siehst du den Hut denn nicht?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Illarion")
talkEntry:addResponse("Illarion. That's what this place is called, isn't it? I go where my research leads me.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Illarion")
talkEntry:addResponse("Illarion. So heißt dieser Ort doch, oder? Ich gehe dorthin, wohin mich meine Forschung führt.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Troll's Haven")
talkEntry:addTrigger("Trolls Haven")
talkEntry:addTrigger("Trollshaven")
talkEntry:addResponse("What? Are you saying I am a troll for taking haven in this place!? Oh. It's the name of this place?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Troll's Haven")
talkEntry:addTrigger("Trolls Haven")
talkEntry:addTrigger("Trollshaven")
talkEntry:addResponse("Wie bitte? Willst du sagen, dass ich ein Troll bin, weil ich hier Zuflucht suche? Oh. Das ist der Name dieses Ortes?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("queen")
talkEntry:addResponse("A queen? You know, I used to serve as the royal archmage in a palace at one point. Then I almost got my head chopped off for sleeping with the... Eh-hem... Moving on.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("königin")
talkEntry:addResponse("Eine Königin? Weißt du, ich habe mal als königlicher Erzmagier in einem Palast gedient. Dann wurde mir fast der Kopf abgehackt, weil ich mit der... Eh-hem... Weiter im Text.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Rosaline")
talkEntry:addTrigger("Edwards")
talkEntry:addResponse("Queen Rosaline Edwards! Now that's a looker, I wouldn't mind... Eh-hem-hem... Moving on.")
talkEntry:addResponse("The queen? Why, did she ask about me?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Rosaline")
talkEntry:addTrigger("Edwards")
talkEntry:addResponse("Königin Rosaline Edwards! Das ist ein Hingucker, ich hätte nichts dagegen... Eh-hem-hem... Weiter geht's.")
talkEntry:addResponse("Die Königin? Warum, hat sie nach mir gefragt?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Cadomyr")
talkEntry:addResponse("#me shudders. 'Sand... sand everywhere. That city is no good.'")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Cadomyr")
talkEntry:addResponse("#me schaudert es. 'Sand... überall Sand. Diese Stadt ist nicht lebenswert.'")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Don")
talkEntry:addResponse("The Don, leader of Galmair? Why DON't we talk about something else instead? He-he.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Don")
talkEntry:addResponse("Der Don, Anführer von Galmair? Warum reden wir nicht lieber über etwas anderes?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Valerio")
talkEntry:addTrigger("Guilianni")
talkEntry:addResponse("Sounds familiar... Wait, that guy owes me money!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Valerio")
talkEntry:addTrigger("Guilianni")
talkEntry:addResponse("Kommt mir bekannt vor... Warte, der Typ schuldet mir Geld!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Galmair")
talkEntry:addResponse("Thieves! Scum! Can you believe they wanted me to PAY for protection!? Me, an almighty archmage!?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Galmair")
talkEntry:addResponse("Diebe! Abschaum! Unglaublich, dass sie von mir Geld für Schutz verlangen!? Ich, ein allmächtiger Erzmagier!?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Archmage")
talkEntry:addResponse("Archmage? Are you gossiping about me, again?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Erzmagier")
talkEntry:addResponse("Erzmagier? Tratschst du schon wieder über mich?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Elvaine")
talkEntry:addTrigger("Morgan")
talkEntry:addResponse("Pfah, that elf in Runewick? I'm clearly a much superior mage.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Elvaine")
talkEntry:addTrigger("Morgan")
talkEntry:addResponse("Pfah, dieser Elf in Runewick? Ich bin eindeutig ein viel überlegenerer Magier.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Runewick")
talkEntry:addResponse("A bunch of losers! No, I was not kicked out of their academy and you can not prove it!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Runewick")
talkEntry:addResponse("Ein Haufen von Verlierern! Nein, ich wurde nicht aus ihrer Akademie rausgeschmissen und du kannst es nicht beweisen!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("god")
talkEntry:addResponse("Gods? Who has time for gods these days, research is taking place! Though come to think of it, Elara isn't all that bad.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Gott")
talkEntry:addTrigger("Götter")
talkEntry:addResponse("Götter? Wer hat heutzutage noch Zeit für Götter. Es wird geforscht! Obwohl, wenn ich so darüber nachdenke, ist Elara gar nicht so schlecht.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Elara")
talkEntry:addResponse("Elara, the goddess of wisdom and knowledge. Truly the only god or goddess worthy of the piety of a grand archmage such as myself... must be quite a looker, too.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Elara")
talkEntry:addResponse("Elara, die Göttin der Weisheit und des Wissens. Wahrlich der einzige Gott oder die einzige Göttin, die der Frömmigkeit eines großen Erzmagiers wie mir würdig ist... Sie muss auch ziemlich gut aussehen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Terry")
talkEntry:addTrigger("Ogg")
talkEntry:addResponse("Yes, what is it? Can't you see I'm busy with my research?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Terry")
talkEntry:addTrigger("Ogg")
talkEntry:addResponse("Was ist denn? Siehst du nicht das ich arbeite?")
talkingNPC:addTalkingEntry(talkEntry)
end
talkingNPC:addCycleText("#me hebt seinen Zauberstab, dann fuchtelt und wedelt er damit.", "#me lifts his wand, giving it a swish and flick.")
talkingNPC:addCycleText("#me murmelt einige unverständliche Worte in seinen Bart.", "#me mutters some unintelligible words under his breath.")
talkingNPC:addCycleText("#me bohrt in der Nase, schaut sich um und wischt seinen Finger dann vorsichtig an der Innenseite seiner Erzmagierrobe ab.", "#me picks his nose, looking around before subtly wiping it off on the inside of his archmage robes.")
talkingNPC:addCycleText("#me gibt ein nachdenkliches Brummen von sich, während er leise in einem Buch liest.", "#me utters a thoughtful hum as he reads silently from a book.")
talkingNPC:addCycleText("Was? Schon wieder kein Forschungsmaterial mehr!?", "What!? Out of research material again!?")
talkingNPC:addCycleText("Huh? Wer... wo war ich?", "Huh? Who... Where was I?")
talkingNPC:addCycleText("Forschen, Forschen, Forschen... Wo ist jetzt mein Essen geblieben?", "Research, research, research... Now where did my dinner go off to?")
talkingNPC:addCycleText("Sie werden es noch bereuen, mich aus der Akademie geworfen zu haben...", "They'll regret kicking me out of the academy, you'll see...")
talkingNPC:addCycleText("Grimoires zu verkaufen! Unterstützt meine Forschung, kauft heute ein Grimoire!", "Grimoires for sale! Come fund my research, buy a Grimoire today!")
tradingNPC:addItem(trade.tradeNPCItem(2619,"sell","Grimoire","Grimoire",18000,1,999,{["magicBook"] = "true"}))
tradingNPC:addItem(trade.tradeNPCItem(105,"sell","Die Enzyklopädie der arkanen Runen","The arcane runes encyclopedia",20000,1,999,{["book"] = "arcane_runes_encyclopedia"}))
tradingNPC:addItem(trade.tradeNPCItem(323,"sell","Terrys alter Zauberstab","Terry's old wand",nil,1,333,{["descriptionEn"] = "An old, worn wand that used to belong to Terry Ogg the wandering mage.", ["descriptionDe"] = "Ein alter, abgegriffener Zauberstab, der einst dem wandernden Magier Terry Ogg gehörte.", ["nameDe"] = "Terrys alter Zauberstab", ["nameEn"] = "Terry's old wand"}))
tradingNPC:addItem(trade.tradeNPCItem(43,"sell",nil,nil,nil,nil,nil,nil))
tradingNPC:addItem(trade.tradeNPCItem(399,"sell",nil,nil,nil,nil,nil,nil))
tradingNPC:addItem(trade.tradeNPCItem(4815,"sell",nil,nil,nil,nil,nil,nil))
tradingNPC:addNotEnoughMoneyMsg("Oh, ich fürchte, das kannst du dir nicht leisten. Wie bedauerlich.", "Oh, I'm afraid you can't afford that. How unfortunate.")
tradingNPC:addDialogClosedMsg("Ah, eine Förderung für meine magische Forschung. Ich danke dir.", "Ah, funding for my magical research. Thank you.")
tradingNPC:addDialogClosedNoTradeMsg("Oh, hast du deine Meinung geändert?", "Oh, changed your mind?")
tradingNPC:addWrongItemMsg("Wenn du deine Waren verkaufen willst, bin ich nicht dein Mann.", "If your intent is to sell your wares, I am not your man.")
mainNPC:addLanguage(0)
mainNPC:addLanguage(1)
mainNPC:setDefaultLanguage(0)
mainNPC:setLookat("Das ist ein NPC dessen Entwickler zu faul war eine Beschreibung einzutragen.", "This is a NPC who's developer was too lazy to type in a description.")
mainNPC:setUseMessage("Fass mich nicht an!", "Do not touch me!")
mainNPC:setConfusedMessage("#me schaut dich verwirrt an.", "#me looks at you in confusion.")
mainNPC:setEquipment(1, 357)
mainNPC:setEquipment(3, 819)
mainNPC:setEquipment(11, 558)
mainNPC:setEquipment(5, 0)
mainNPC:setEquipment(6, 323)
mainNPC:setEquipment(4, 0)
mainNPC:setEquipment(9, 461)
mainNPC:setEquipment(10, 53)
mainNPC:setAutoIntroduceMode(true)

mainNPC:initDone()
return mainNPC
end
local mNPC = initNpc()
initNpc = nil
local M = {}
function M.receiveText(npcChar, texttype, message, speaker) mNPC:receiveText(npcChar, texttype, speaker, message) end
function M.nextCycle(npcChar) mNPC:nextCycle(npcChar) end
function M.lookAtNpc(npcChar, char, mode) mNPC:lookAt(npcChar, char, mode) end
function M.useNPC(npcChar, char, counter, param) mNPC:use(npcChar, char) end
return M
