local consequence_quest = require("npc.base.consequence.quest")
local consequence_trade = require("npc.base.consequence.trade")
local condition_language = require("npc.base.condition.language")
local basic = require("npc.base.basic")
local trade = require("npc.base.trade")
local talk = require("npc.base.talk")
local condition_quest = require("npc.base.condition.quest")
local consequence_inform = require("npc.base.consequence.inform")
local function initNpc()
local mainNPC = basic()
mainNPC:setAffiliation(1)
local talkingNPC = talk(mainNPC)
local tradingNPC = trade(mainNPC)
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Help")
talkEntry:addConsequence(consequence_inform("[Game Help] This NPC is the tailor Thomas Dalenus. Keywords: buy, sell, trade, Hello, tailor, Cadomyr, needle, dye."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hilfe")
talkEntry:addConsequence(consequence_inform("[Spielhilfe] Dieser NPC ist der Schneider Thomas Dalenus. Schlüsselwörter: kaufe, verkaufe, Handel, Hallo, Schneider, Cadomyr, Nadel, Färben."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("sell")
talkEntry:addTrigger("buy")
talkEntry:addTrigger("wares")
talkEntry:addTrigger("price")
talkEntry:addTrigger("trade")
talkEntry:addTrigger("purchase")
talkEntry:addResponse("Robes, dresses, capes, shirts, trousers... what do you need, I have everything.")
talkEntry:addConsequence(consequence_trade(tradingNPC))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("kauf")
talkEntry:addTrigger("waren")
talkEntry:addTrigger("preis")
talkEntry:addTrigger("Handel")
talkEntry:addTrigger("veräußer")
talkEntry:addTrigger("veräusser")
talkEntry:addTrigger("erwerb")
talkEntry:addResponse("Roben, Kleider, Umhänge, Hemden, Hosen,... was braucht ihr, ich habe alles.")
talkEntry:addConsequence(consequence_trade(tradingNPC))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hello")
talkEntry:addTrigger("Greet")
talkEntry:addTrigger("Hail")
talkEntry:addTrigger("Good day")
talkEntry:addTrigger("Good morning")
talkEntry:addTrigger("Good evening")
talkEntry:addTrigger("Good night")
talkEntry:addResponse("Good day. Do you need a coat?")
talkEntry:addResponse("Greetings. How are you?")
talkEntry:addResponse("Hello. I have all kinds of clothes.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Grüß")
talkEntry:addTrigger("Gruß")
talkEntry:addTrigger("Grüss")
talkEntry:addTrigger("Gruss")
talkEntry:addTrigger("Guten Morgen")
talkEntry:addTrigger("Guten Tag")
talkEntry:addTrigger("Guten Abend")
talkEntry:addTrigger("Gute Nacht")
talkEntry:addTrigger("Mahlzeit")
talkEntry:addTrigger("Tach")
talkEntry:addTrigger("Moin")
talkEntry:addTrigger("Mohltied")
talkEntry:addResponse("Guten Tag. Braucht ihr einen Umhang?")
talkEntry:addResponse("Seid gegrüßt. Wie geht es euch?")
talkEntry:addResponse("Hallo. Ich habe vielerlei Stoffe.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Hiho")
talkEntry:addTrigger("Hallo")
talkEntry:addTrigger("Hey")
talkEntry:addTrigger("Greeb")
talkEntry:addResponse("Good day. Do you need a coat?")
talkEntry:addResponse("Greetings. How are you?")
talkEntry:addResponse("Hello. I have all kinds of clothes.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hiho")
talkEntry:addTrigger("Hallo")
talkEntry:addTrigger("Hey")
talkEntry:addTrigger("Greeb")
talkEntry:addResponse("Guten Tag. Braucht ihr einen Umhang?")
talkEntry:addResponse("Seid gegrüßt. Wie geht es euch?")
talkEntry:addResponse("Hallo. Ich habe vielerlei Stoffe.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Farewell")
talkEntry:addTrigger("Bye")
talkEntry:addTrigger("Fare well")
talkEntry:addTrigger("See you")
talkEntry:addResponse("Farewell, go with the gods.")
talkEntry:addResponse("Good bye, my customer.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Tschüß")
talkEntry:addTrigger("Tschüss")
talkEntry:addTrigger("Wiedersehen")
talkEntry:addTrigger("Gehab wohl")
talkEntry:addResponse("Gehabt euch wohl, geht mit den Göttern.")
talkEntry:addResponse("Auf wiedersehen, mein Kunde.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Ciao")
talkEntry:addTrigger("Adieu")
talkEntry:addTrigger("Au revoir")
talkEntry:addResponse("Farewell, go with the gods.")
talkEntry:addResponse("Good bye, my customer.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Ciao")
talkEntry:addTrigger("Adieu")
talkEntry:addTrigger("Au revoir")
talkEntry:addResponse("Gehabt euch wohl, geht mit den Göttern.")
talkEntry:addResponse("Auf wiedersehen, mein Kunde.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("How are you")
talkEntry:addTrigger("How feel")
talkEntry:addTrigger("How do you do")
talkEntry:addResponse("I just finished this robe. Maybe you want to take a look at it?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Wie geht")
talkEntry:addTrigger("Wie fühlst")
talkEntry:addTrigger("Wie ist es ergangen")
talkEntry:addResponse("Ich habe gerade diese Robe fertiggestellt. Wollt ihr sie euch ansehen?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("your name")
talkEntry:addTrigger("who are you")
talkEntry:addTrigger("who art thou")
talkEntry:addResponse("My name is Thomas, Thomas Dalenus. I'm a tailor.")
talkEntry:addResponse("Dalenus' tailored goods - that is my business.")
talkEntry:addResponse("Thomas Dalenus. And do not call me Tom or I'll sting my needle into your eye.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("ihr name")
talkEntry:addTrigger("dein name")
talkEntry:addTrigger("wer bist du")
talkEntry:addTrigger("wer seid ihr")
talkEntry:addTrigger("wie heißt")
talkEntry:addTrigger("wie heisst")
talkEntry:addResponse("Mein Name ist Thomas, Thomas Dalenus. Ich bin ein Schneider.")
talkEntry:addResponse("Dalenus Schneiderwaren - das ist mein Geschäft.")
talkEntry:addResponse("Thomas Dalenus. Und nennt mich nicht Tom, sonst stech ich euch die Augen mit meiner Nadel aus.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("If you are searching for a quest, go to the Oasis of Stars. There are people who need your help.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Wenn ihr nach einem Abenteuer sucht, geht zum der Sternenoase. Dort wird eure Hilfe gebraucht.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addResponse("If you are searching for a quest, go to the Oasis of Stars. There are people who need your help.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addResponse("Wenn ihr nach einem Abenteuer sucht, geht zum der Sternenoase. Dort wird eure Hilfe gebraucht.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(317, "=", 3))
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Mirarie")
talkEntry:addTrigger("Bragolin")
talkEntry:addTrigger("letter")
talkEntry:addTrigger("message")
talkEntry:addConsequence(consequence_quest(317, "=", 4))
talkEntry:addResponse("I'm sorry, I don't have time. I still need to finish that dress. Please tell Lady Bragolin that I'll notify her soon.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(317, "=", 3))
talkEntry:addTrigger("Mirarie")
talkEntry:addTrigger("Bragolin")
talkEntry:addTrigger("Brief")
talkEntry:addTrigger("Nachricht")
talkEntry:addConsequence(consequence_quest(317, "=", 4))
talkEntry:addResponse("Tut mir leid. Ich habe grade keine Zeit, ich muss noch ein Kleid fertig nähen. Sagst doch bitte Fräulein Bragolin, dass ich mich bei ihr melden werde.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("profession")
talkEntry:addResponse("I'm a tailor, I even made a dress for the queen once.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("beruf")
talkEntry:addResponse("Ich bin Schneider, einst habe ich sogar ein Kleid für die Königin geschneidert.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("job")
talkEntry:addResponse("I'm a tailor, I even made a dress for the queen once.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("job")
talkEntry:addResponse("Ich bin Schneider, einst habe ich sogar ein Kleid für die Königin geschneidert.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Gobaith")
talkEntry:addTrigger("Gobiath")
talkEntry:addResponse("Let's not talk about sad things, please.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Gobaith")
talkEntry:addTrigger("Gobiath")
talkEntry:addResponse("Lasst uns doch bitte nicht von traurigen Dingen reden.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("my name")
talkEntry:addResponse("And I am Thomas Dalenus; you could use a new coat if you ask me.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("mein Name")
talkEntry:addResponse("Und ich bin Thomas Dalenus; ihr könntet einen neuen Mantel vertragen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("tailor")
talkEntry:addResponse("When I made the dress of queen Rosaline, I worked all day and night. It was such an honour! Is there anything I can tailor for you?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Schneider")
talkEntry:addResponse("Als ich das Kleid der Königin Rosaline gefertigt habe, hab ich den ganzen Tag und die ganze Nacht gearbeitet. Es war so eine Ehre! Gibt es etwas, was ich für dich schneidern kann?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("trader")
talkEntry:addTrigger("merchant")
talkEntry:addTrigger("collegue")
talkEntry:addTrigger("vendor")
talkEntry:addTrigger("market")
talkEntry:addResponse("The amount of goods on this marketplace is magnificent. We're not a nation of traders by heart, but everyone needs something sometimes.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("händler")
talkEntry:addTrigger("kollege")
talkEntry:addTrigger("höker")
talkEntry:addTrigger("markt")
talkEntry:addResponse("Die Menge an Waren, die auf diesem Markt gehandelt werden, sind schon beeindruckend. Wir sind zwar kein Volk von Händlern, aber jeder braucht mal etwas.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("dye")
talkEntry:addResponse("To dye clothes is tricky. You need various ingredients like herbs. Better buy dyed clothes from me instead of wasting your time.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("färbe")
talkEntry:addTrigger("farbe")
talkEntry:addResponse("Stoffe zu Färben ist aufwändig. Man braucht eine Reihe von Wirkstoffen, so wie Kräuter. Kauft besser gefärbte Stoffe direkt bei mir.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("needle")
talkEntry:addResponse("I can sell you a needle, but be careful, they are pointed.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Nadel")
talkEntry:addResponse("Ich kann euch eine Nadel verkaufen, aber vorsichtig, sie ist spitz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("cloth")
talkEntry:addResponse("I sell any kind of cloth.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Stoff")
talkEntry:addResponse("Ich verkaufe vielerlei Stoffe.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("archmage")
talkEntry:addResponse("You are talking about Elvaine Morgan, the archmage of Runewick? I keep forgetting his name.")
talkEntry:addResponse("Who is that again?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Erzmagier")
talkEntry:addResponse("Ihr redet von Elvaine Morgan, dem Erzmagier von Runewick? Ich vergesse immer wieder seinen Namen.")
talkEntry:addResponse("Wer war das nochmal?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Elvaine")
talkEntry:addTrigger("Morgan")
talkEntry:addResponse("You are talking about Elvaine Morgan, the archmage of Runewick? I keep forgetting his name.")
talkEntry:addResponse("Who is that again?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Elvaine")
talkEntry:addTrigger("Morgan")
talkEntry:addResponse("Ihr redet von Elvaine Morgan, dem Erzmagier von Runewick? Ich vergesse immer wieder seinen Namen.")
talkEntry:addResponse("Wer war das nochmal?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Runewick")
talkEntry:addResponse("I was told they prefer silk in Runewick.")
talkEntry:addResponse("Runewick, well, trading with Runewick takes too long, all this talking.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Runewick")
talkEntry:addResponse("Mir wurde erzählt, dass man in Runewick Seide bevorzugt.")
talkEntry:addResponse("Runewick, nun, ein Handel mit Runewick dauert immer so lange, immer dieses Gelaber.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Valerio")
talkEntry:addTrigger("Guilianni")
talkEntry:addTrigger("Don")
talkEntry:addResponse("The Don once ordered trousers for his ruffians from me. I refused, of course.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Valerio")
talkEntry:addTrigger("Guilianni")
talkEntry:addTrigger("Don")
talkEntry:addResponse("Der Don hat einst Hosen für seine Schlägertrupps bei mir bestellt. Ich hab abgelehnt, wie sich von selbst versteht.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Galmair")
talkEntry:addResponse("I am honest, I do not like Galmair. I prefer to act with honourable men.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Galmair")
talkEntry:addResponse("Ich bin ganz ehrlich; ich mag Galmair nicht. Ich ziehe es vor, mit ehrbaren Leuten zu handeln.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Queen")
talkEntry:addResponse("Did you notice the blue dress the queen wears from time to time? My masterpiece!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Königin")
talkEntry:addResponse("Habt ihr das blaue Kleid bemerkt, welches die Königin manchmal trägt? Mein Meisterwerk!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("rosaline")
talkEntry:addTrigger("edwards")
talkEntry:addResponse("Did you notice the blue dress the queen wears from time to time? My masterpiece!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("rosaline")
talkEntry:addTrigger("edwards")
talkEntry:addResponse("Habt ihr das blaue Kleid bemerkt, welches die Königin manchmal trägt? Mein Meisterwerk!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Cadomyr")
talkEntry:addResponse("I tailor for the queen, I tailor for every noble man of Cadomyr. And for every woman, of course.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Cadomyr")
talkEntry:addResponse("Ich schneidere für die Königin, ich schneider für jeden Edelmann von Cadomyr. Und für jede Dame, wie sich von selbst versteht.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("albar")
talkEntry:addResponse("Once, the lords of Albar ordered a shipment of clothes. But somehow, they never paid me. I suspect Galmairian thugs are behind this!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("albar")
talkEntry:addResponse("Einst bestellten die Herren von Albar eine Ladung Stoffe. Aber irgendwie wurde ich nie entlohnt. Ich vermute, dass Halunken aus Galmair dahinterstecken.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("gynk")
talkEntry:addTrigger("gync")
talkEntry:addResponse("I will never trade again with anyone from Gynk. They never fulfil a contract.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("gync")
talkEntry:addTrigger("gynk")
talkEntry:addResponse("Ich werde niemals mit jemanden aus Gynk handeln. Die halten sich nicht an geschlossene Verträge.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("salkama")
talkEntry:addResponse("The women of Salkamar are too thin, I was told. Who can tailor a dress for a stick figure?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("salkama")
talkEntry:addResponse("Die Damen aus Salkamar sind alle zu dünn, sagt man. Wie soll man für einen Strich in der Landschaft ein Kleid schneidern?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("god")
talkEntry:addResponse("When I don't work, I sometimes pray to Irmorom but with little effects as it seems.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Gott")
talkEntry:addTrigger("Götter")
talkEntry:addResponse("Wenn ich mal nicht arbeite, bete ich manchmal zu Irmorom; viel hats bis jetzt nicht gebracht.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Irmorom")
talkEntry:addResponse("Irmorom guides my hands while stitching. I wonder why I sting myself that often with the needle!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Irmorom")
talkEntry:addResponse("Irmorom führt meine Hand, wenn ich sticke. Ich frag mich, warum ich mich trotzdem so oft mit der Nadel steche.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Malachin")
talkEntry:addTrigger("Malachín")
talkEntry:addResponse("Malachin is the god of battles and hunting. I'd like to fight and hunt, too, but I'm better at tailoring.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Malachin")
talkEntry:addTrigger("Malachín")
talkEntry:addResponse("Malachin ist der Gott der Schlachten und der Jagd. Ich würde auch gerne Kämpfen und Jagen, aber ich bin besser in der Schneiderei.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("tell something")
talkEntry:addResponse("Never trade with Galmair. Just saying.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("erzähl was")
talkEntry:addTrigger("erzähl etwas")
talkEntry:addResponse("Handelt niemals mit Galmair, sage ich.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Thomas")
talkEntry:addTrigger("Dalenus")
talkEntry:addResponse("There are many by the name of Thomas, but few of the name Dalenus. And only one Thomas Dalenus, best tailor of Cadomyr!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Thomas")
talkEntry:addTrigger("Dalenus")
talkEntry:addResponse("Es gibt viele, die Thomas heißen, aber nur wenige namens Dalenus. Und nur einen Thomas Dalenus, den besten Schneider Cadomyrs!")
talkingNPC:addTalkingEntry(talkEntry)
end
talkingNPC:addCycleText("Autsch!", "Ouch!")
talkingNPC:addCycleText("#me zerschneidet einige Stoffbahnen.", "#me cuts some clothes.")
talkingNPC:addCycleText("#me stickt ein Muster in ein Stoffstück.", "#me stitches a pattern into a piece of cloth.")
talkingNPC:addCycleText("Maßgeschneiderte Kleider für die Frau, Hüte für euch und Röcke für die Töchter!", "Tailored dresses for your wife, hats for you and a skirt for your daughter!")
talkingNPC:addCycleText("Kommt herein und findet heraus... was ich anzubieten habe!", "Come in and find out... what I have to offer!")
talkingNPC:addCycleText("Kundschaft!", "Customers!")
talkingNPC:addCycleText("Einmal gekleidet sein wie Königin Rosaline - beste Kleider im Angebot.", "For once, be dressed like Queen Rosaline - I offer best dresses.")
talkingNPC:addCycleText("Thomas Dalenus ist euer Mann, wenn es um Stickereien geht!", "Thomas Dalenus is your man for stitching!")
talkingNPC:addCycleText("Eine Frau ohne Kleid ist meist nur halb so schön.", "A woman without a dress is commonly half as beautiful.")
talkingNPC:addCycleText("#me streicht ein fein gewobenes Kleid glatt.", "#me smoothes down a finely woven dress.")
tradingNPC:addItem(trade.tradeNPCItem(47,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(58,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2781,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(6,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2746,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(4337,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1500,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(369,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1501,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1502,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(53,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1503,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1504,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1447,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2295,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1448,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1449,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1450,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(809,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(813,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(810,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(812,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(811,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(808,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(807,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(802,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(806,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(803,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(804,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1478,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(367,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1479,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1480,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(366,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1481,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1482,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(356,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(830,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1415,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(831,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(832,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(829,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(828,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1416,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(7,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1417,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1418,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1419,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1420,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1453,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(384,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(48,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1454,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(526,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1455,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1456,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(97,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2760,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(89,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(196,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2418,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2421,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(55,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(194,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2378,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2384,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2420,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(547,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2419,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2377,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(195,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(368,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(457,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(182,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(180,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(458,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(181,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(841,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(842,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(844,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(843,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(840,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(839,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1433,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(363,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1434,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2407,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(365,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1435,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1436,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2399,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(823,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(827,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(824,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(183,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(826,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(34,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(459,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(825,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(460,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(816,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(820,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(817,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(819,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(818,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(815,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(814,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(176,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(175,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(179,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(54,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(174,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(178,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(177,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2678,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2680,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2679,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2681,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2683,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2682,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2586,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(69,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2547,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(170,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(50,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(4337,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1500,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(369,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1501,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1502,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(53,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1503,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1504,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(697,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1505,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(698,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1506,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1447,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(2295,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1448,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1449,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1450,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1451,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1452,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(809,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(813,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(810,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(812,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(811,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(808,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(807,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(802,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(806,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(803,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(805,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(800,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(385,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(804,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(801,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(833,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(836,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(835,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(837,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(838,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(834,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(851,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(845,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(846,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(850,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(849,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(852,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(847,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(848,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1478,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(367,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1479,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1480,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(366,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1481,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1482,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(2114,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1483,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(2113,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1484,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(356,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(830,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1415,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(831,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(832,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(829,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(828,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(358,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(357,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3868,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(370,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(3708,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(371,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1416,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(7,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1417,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1418,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1419,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1420,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1421,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1422,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1423,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1424,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1453,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(384,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(48,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1454,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(526,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1455,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1456,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1457,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(527,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1458,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1459,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(2760,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(89,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(196,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(2418,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(2421,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(55,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(194,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(2378,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(2384,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(2420,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(547,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(2419,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(2377,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(195,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(368,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(2416,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(193,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(2380,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(548,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(558,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(457,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(182,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(180,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(458,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(181,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(841,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(842,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(844,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(843,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(840,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(839,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1433,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(363,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1434,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(2407,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(365,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1435,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1436,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(2399,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(2357,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(364,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(362,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(1437,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(823,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(827,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(824,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(183,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(826,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(34,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(459,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(825,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(460,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(822,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(461,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(821,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(816,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(820,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(817,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(819,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(818,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(815,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(814,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(176,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(175,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(179,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(54,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(174,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(178,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(177,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(2678,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(2680,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(2679,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(2681,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(2683,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(2682,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(2586,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(69,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(2547,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(170,"buyPrimary"))
tradingNPC:addItem(trade.tradeNPCItem(50,"buyPrimary"))
tradingNPC:addNotEnoughMoneyMsg("Euer Vermögen reicht hierfür nicht aus.", "You are not wealthy enough for that.")
tradingNPC:addDialogClosedMsg("Das hat sich doch gelohnt.", "That was worth it.")
tradingNPC:addDialogClosedNoTradeMsg("Kommt doch bald wieder.", "Please come again.")
tradingNPC:addWrongItemMsg("So etwas kaufe ich nicht.", "I don't buy that kind of things.")
mainNPC:addLanguage(0)
mainNPC:addLanguage(1)
mainNPC:setDefaultLanguage(0)
mainNPC:setLookat("Dieser NPC ist der Schneider Thomas Dalenus.", "This NPC is the tailor Thomas Dalenus.")
mainNPC:setUseMessage("Fass mich nicht an!", "Do not touch me!")
mainNPC:setConfusedMessage("#me schaut dich verwirrt an.", "#me looks at you confused.")
mainNPC:setEquipment(1, 0)
mainNPC:setEquipment(3, 458)
mainNPC:setEquipment(11, 2421)
mainNPC:setEquipment(5, 0)
mainNPC:setEquipment(6, 0)
mainNPC:setEquipment(4, 2295)
mainNPC:setEquipment(9, 823)
mainNPC:setEquipment(10, 53)
mainNPC:setAutoIntroduceMode(true)

mainNPC:initDone()
return mainNPC
end
local mNPC = initNpc()
initNpc = nil
local M = {}
function M.receiveText(npcChar, texttype, message, speaker) mNPC:receiveText(npcChar, texttype, speaker, message) end
function M.nextCycle(npcChar) mNPC:nextCycle(npcChar) end
function M.lookAtNpc(npcChar, char, mode) mNPC:lookAt(npcChar, char, mode) end
function M.useNPC(npcChar, char, counter, param) mNPC:use(npcChar, char) end
return M
