local consequence_item = require("npc.base.consequence.item")
local condition_item = require("npc.base.condition.item")
local consequence_quest = require("npc.base.consequence.quest")
local condition_skill = require("npc.base.condition.skill")
local condition_language = require("npc.base.condition.language")
local consequence_deleteitem = require("npc.base.consequence.deleteitem")
local basic = require("npc.base.basic")
local condition_town = require("npc.base.condition.town")
local talk = require("npc.base.talk")
local consequence_money = require("npc.base.consequence.money")
local condition_quest = require("npc.base.condition.quest")
local consequence_inform = require("npc.base.consequence.inform")
local function initNpc()
local mainNPC = basic()
mainNPC:setAffiliation(2)
local talkingNPC = talk(mainNPC)
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Help")
talkEntry:addConsequence(consequence_inform("[Game Help] This NPC is Thomas Weste the brewer. Keywords: Hello, quest, brewer."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hilfe")
talkEntry:addConsequence(consequence_inform("[Spielhilfe] Dieser NPC ist Thomas Weste der Brauer. Schlüsselwörter: Hallo, Quest, Brauer."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hello")
talkEntry:addTrigger("Greet")
talkEntry:addTrigger("Hail")
talkEntry:addTrigger("Good day")
talkEntry:addTrigger("Good morning")
talkEntry:addTrigger("Good Evening")
talkEntry:addResponse("Hello, can I help you?")
talkEntry:addResponse("Nice to meet you, I'm Thomas Weste.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Grüß")
talkEntry:addTrigger("Gruß")
talkEntry:addTrigger("Grüss")
talkEntry:addTrigger("Gruss")
talkEntry:addTrigger("Guten Morgen")
talkEntry:addTrigger("Guten Tag")
talkEntry:addTrigger("Guten Abend")
talkEntry:addTrigger("Gute Nacht")
talkEntry:addTrigger("Mahlzeit")
talkEntry:addTrigger("Tach")
talkEntry:addTrigger("Moin")
talkEntry:addTrigger("Mohltied")
talkEntry:addResponse("Hallo, kann ich Euch helfen?")
talkEntry:addResponse("Freut mich, Euch zu treffen. Ich bin Thomas Weste.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Hiho")
talkEntry:addTrigger("Hallo")
talkEntry:addTrigger("Hey")
talkEntry:addTrigger("Greeb")
talkEntry:addResponse("Hello, can I help you?")
talkEntry:addResponse("Nice to meet you, I'm Thomas Weste.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hiho")
talkEntry:addTrigger("Hallo")
talkEntry:addTrigger("Hey")
talkEntry:addTrigger("Greeb")
talkEntry:addResponse("Hallo, kann ich Euch helfen?")
talkEntry:addResponse("Freut mich, Euch zu treffen. Ich bin Thomas Weste")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Farewell")
talkEntry:addTrigger("Bye")
talkEntry:addTrigger("Fare well")
talkEntry:addTrigger("See you")
talkEntry:addResponse("I wish you a nice day.")
talkEntry:addResponse("I hope we meet again, goodbye.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Tschüß")
talkEntry:addTrigger("Tschüss")
talkEntry:addTrigger("Wiedersehen")
talkEntry:addResponse("Ich wünsche Euch noch einen schönen Tag.")
talkEntry:addResponse("Ich hoffe, wir sehen uns wieder, auf bald!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Ciao")
talkEntry:addTrigger("Adieu")
talkEntry:addTrigger("Au revoir")
talkEntry:addTrigger("Farebba")
talkEntry:addResponse("I wish you a nice day.")
talkEntry:addResponse("I hope we meet again, goodbye.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Ciao")
talkEntry:addTrigger("Adieu")
talkEntry:addTrigger("Au revoir")
talkEntry:addTrigger("Farebba")
talkEntry:addResponse("Ich wünsche Euch noch einen schönen Tag.")
talkEntry:addResponse("Ich hoffe, wir sehen uns wieder, auf bald!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("How are you")
talkEntry:addTrigger("How feel")
talkEntry:addTrigger("How do you do")
talkEntry:addResponse("I feel fine, thank you for asking.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Wie geht")
talkEntry:addTrigger("Wie fühlst")
talkEntry:addTrigger("Wie ist es ergangen")
talkEntry:addTrigger("Wie Befind")
talkEntry:addResponse("Mir geht es gut, danke für die Nachfrage.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("your name")
talkEntry:addTrigger("who are you")
talkEntry:addTrigger("who art thou")
talkEntry:addResponse("I'm Thomas Weste, who are you?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("ihr name")
talkEntry:addTrigger("dein name")
talkEntry:addTrigger("wer bist du")
talkEntry:addTrigger("wer seid ihr")
talkEntry:addTrigger("wie heißt")
talkEntry:addTrigger("wie heisst")
talkEntry:addResponse("Ich bin Thomas Weste, wer bist du?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("sell")
talkEntry:addTrigger("buy")
talkEntry:addTrigger("wares")
talkEntry:addTrigger("price")
talkEntry:addTrigger("trade")
talkEntry:addTrigger("purchase")
talkEntry:addResponse("I am not a trader.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("kauf")
talkEntry:addTrigger("waren")
talkEntry:addTrigger("preis")
talkEntry:addTrigger("Handel")
talkEntry:addTrigger("veräußer")
talkEntry:addTrigger("veräusser")
talkEntry:addTrigger("erwerb")
talkEntry:addResponse("Ich bin kein Händler.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("profession")
talkEntry:addResponse("I'm a brewer, I can tell you from own experience everything I make tastes good.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("beruf")
talkEntry:addResponse("Ich bin Brauer. Aus eigener Erfahrung kann ich sagen, dass alles was ich herstelle gut schmeckt.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("job")
talkEntry:addResponse("I'm a brewer, I can tell you from own experience everything I make tastes good.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("job")
talkEntry:addResponse("Ich bin Brauer. Aus eigener Erfahrung kann ich sagen, dass alles was ich herstelle gut schmeckt.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("brewer")
talkEntry:addTrigger("craft")
talkEntry:addResponse("Brewing is fun, isn't it? If not, just drink some of your booze you make with the cooking spoon at the barrel and it will be fun, I promise!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Brauer")
talkEntry:addTrigger("Handwerk")
talkEntry:addResponse("Brauen macht Spaß, nicht wahr? Falls nicht, trink einfach etwas von dem Zeug, welches du mit dem Kochlöffel am Fass herstellst. Dann wird's bestimmt heiter!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(716, "=", 0))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_quest(716, "=", 1))
talkEntry:addResponse("Adron's Brewery School accepts you as an apprentice. To learn what you need you have to stay sober. Go to Yewdale and collect sixty apples.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Adron's Brewery School of Runewick I. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(716, "=", 0))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_quest(716, "=", 1))
talkEntry:addResponse("Adron's Brewery School accepts you as an apprentice. To learn what you need you have to stay sober. Go to Yewdale and collect sixty apples.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Adron's Brewery School of Runewick I. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(716, "=", 0))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addConsequence(consequence_quest(716, "=", 1))
talkEntry:addResponse("Adrons Braukunstschule wird deine Ausbildung übernehmen. Wenn du was lernen willst musst du nüchtern bleiben. Marschier nach Eibenthal und pflücke dort sechzig Äpfel.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Adrons Braukunstschule zu Runewick I. Detaillierte Informationen findest du im Questlog (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(716, "=", 1))
talkEntry:addCondition(condition_item(15, "all", ">", 59, nil))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_quest(716, "=", 2))
talkEntry:addResponse("These are the apples? Fine. Some are bruised, but it doesn't matter if the drinker doesn't know. You will need them for your first bottles.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Ask Thomas Weste for your next task."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(716, "=", 1))
talkEntry:addCondition(condition_item(15, "all", ">", 59, nil))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("apple")
talkEntry:addConsequence(consequence_quest(716, "=", 2))
talkEntry:addResponse("These are the apples? Fine. Some are bruised, but it doesn't matter if the drinker doesn't know. You will need them for your first bottles.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Ask Thomas Weste for your next task."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(716, "=", 1))
talkEntry:addCondition(condition_item(15, "all", ">", 59, nil))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Apfel")
talkEntry:addTrigger("Äpfel")
talkEntry:addConsequence(consequence_quest(716, "=", 2))
talkEntry:addResponse("Das sind die Äpfel? Einige sind zwar schon angeschlagen, aber was solls. Was der Trinker nicht weiß ist ihm egal. Behalte sie für später.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Frage Thomas Weste nach deiner nächsten Aufgaben."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(716, "=", 1))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Can't count properly? As your master, I'll slowly repeat my order: Collect sixty apples.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(716, "=", 1))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("apple")
talkEntry:addResponse("Can't count properly? As your master, I'll slowly repeat my order: Collect sixty apples.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(716, "=", 1))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Apfel")
talkEntry:addTrigger("Äpfel")
talkEntry:addResponse("Zählen ist nicht deine Stärke was? Als dein Meister werde ich meine Anordnung noch einmal langsam wiederholen: Pflücke sechzig Äpfel!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(716, "=", 2))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_item(51, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 3))
talkEntry:addResponse("You can't brew anything without water. Fill these ten buckets with water at the next well. Try not to fall in the well.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Adron's Brewery School of Runewick II. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(716, "=", 2))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_item(51, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 3))
talkEntry:addResponse("You can't brew anything without water. Fill these ten buckets with water at the next well. Try not to fall in the well.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Adron's Brewery School of Runewick II. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(716, "=", 2))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addConsequence(consequence_item(51, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 3))
talkEntry:addResponse("Ohne Wasser wird nicht nur der Wein trocken. Füll diese zehn Eimer mit Wasser. Und fall nicht ins Wasser.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Adrons Braukunstschule zu Runewick II. Detaillierte Informationen findest du im Questlog (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(716, "=", 3))
talkEntry:addCondition(condition_item(52, "all", ">", 9, nil))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_quest(716, "=", 4))
talkEntry:addResponse("Ohh, the water is clear, that's even better for the drinks. But before we continue I have to have a drink.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Ask Thomas Weste for your next task."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(716, "=", 3))
talkEntry:addCondition(condition_item(52, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("water")
talkEntry:addTrigger("bucket")
talkEntry:addConsequence(consequence_quest(716, "=", 4))
talkEntry:addResponse("Ohh, the water is clear, that's even better for the drinks. But before we continue I have to have a drink.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Ask Thomas Weste for your next task."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(716, "=", 3))
talkEntry:addCondition(condition_item(52, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Wasser")
talkEntry:addTrigger("Eimer")
talkEntry:addConsequence(consequence_quest(716, "=", 4))
talkEntry:addResponse("Ohh, das ist ja sogar sauberes Wasser. Aber bevor wir weitermachen, muss ich darauf einen heben.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Frage Thomas Weste nach deiner nächsten Aufgaben."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(716, "=", 3))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Where is the water? Your task was to fill ten buckets of water, not drink it. A brewer never drinks water. Cheers.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(716, "=", 3))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("water")
talkEntry:addTrigger("bucket")
talkEntry:addResponse("Where is the water? Your task was to fill ten buckets of water, not drink it. A brewer never drinks water. Cheers.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(716, "=", 3))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Wasser")
talkEntry:addTrigger("Eimer")
talkEntry:addResponse("Wo hast du das Wasser? Du solltest zehn Eimer mit Wasser füllen und nicht austrinken. Ein Brauer trinkt kein Wasser. Prost.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(716, "=", 4))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_item(227, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 5))
talkEntry:addConsequence(consequence_item(2498, 10, 333, nil))
talkEntry:addResponse("Now we come to the real fun. I'll give you an old cooking spoon and you'll give me ten bottles of apple cider. Pour the cider into the big empty bottles I gave you.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Adron's Brewery School of Runewick III. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(716, "=", 4))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_item(227, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 5))
talkEntry:addConsequence(consequence_item(2498, 10, 333, nil))
talkEntry:addResponse("Now we come to the real fun. I'll give you an old cooking spoon and you'll give me ten bottles of apple cider. Pour the cider into the big empty bottles I gave you.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Adron's Brewery School of Runewick III. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(716, "=", 4))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addConsequence(consequence_item(227, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 5))
talkEntry:addConsequence(consequence_item(2498, 10, 333, nil))
talkEntry:addResponse("Jetzt kommen wir zur Sache. Ich gebe dir einen alten Rührlöffel und du bringst mir zehn Flaschen Apfelcider. Fülle den Cider in die großen leeren Flaschen hier.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Adrons Braukunstschule zu Runewick III. Detaillierte Informationen findest du im Questlog (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(716, "=", 5))
talkEntry:addCondition(condition_item(2499, "all", ">", 9, nil))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Layman with Adron's Brewery School of Runewick. You are awarded forty five silver coins."))
talkEntry:addConsequence(consequence_deleteitem(2499, 10, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 6))
talkEntry:addConsequence(consequence_money("+", 4500))
talkEntry:addResponse("Adron's Brewery School of Runewick is glad to have a new person willing to learn in it's rows. Here is some money to get you started. I recommend you don't buy drinks but buckets with it. And, come back once you improved your knowledge.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(716, "=", 5))
talkEntry:addCondition(condition_item(2499, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Layman with Adron's Brewery School of Runewick. You are awarded forty five silver coins."))
talkEntry:addConsequence(consequence_deleteitem(2499, 10, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 6))
talkEntry:addConsequence(consequence_money("+", 4500))
talkEntry:addResponse("Adron's Brewery School of Runewick is glad to have a new person willing to learn in it's rows. Here is some money to get you started. I recommend you don't buy drinks but buckets with it. And, come back once you improved your knowledge.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(716, "=", 5))
talkEntry:addCondition(condition_item(2499, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Adrons Braukunstschule zu Runewick erhebt dich in den Rang eines Laiens. Du erhältst fünfundvierzig Silberstücke."))
talkEntry:addConsequence(consequence_deleteitem(2499, 10, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 6))
talkEntry:addConsequence(consequence_money("+", 4500))
talkEntry:addResponse("Adrons Braukunstschule zu Runewick freut sich ein neues lernwilliges Mitglied zu begrüßen. Hier hast du Geld. Mein Vorschlag wäre, dass du es nicht versäufst und davon Eimer kaufst. Und komm zu mir zurück, wenn du deine Kenntnisse erweitert hast.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(716, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("First the water and apples in the barrel, then stir. I'll taste the results, ten bottles of cider.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(716, "=", 5))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addResponse("First the water and apples in the barrel, then stir. I'll taste the results, ten bottles of cider.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(716, "=", 5))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addResponse("Erst Wasser ud Äpfel in den Bottich, dann rühren. Ich teste dann das Ergebnis, zehn Flaschen Cider.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, ">", 9))
talkEntry:addCondition(condition_quest(716, "=", 6))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Novice with Adron's Brewery School of Runewick. You are awarded ten honeycombs."))
talkEntry:addConsequence(consequence_item(2529, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 7))
talkEntry:addResponse("Cheers. You not only know how to drink, you know how to make drinks. Adron's Brewery School of Runewick wants to ease your path with some honeycombs. Come back to me once you have brewed new drinks that I can taste.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, ">", 9))
talkEntry:addCondition(condition_quest(716, "=", 6))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Novice with Adron's Brewery School of Runewick. You are awarded ten honeycombs."))
talkEntry:addConsequence(consequence_item(2529, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 7))
talkEntry:addResponse("Cheers. You not only know how to drink, you know how to make drinks. Adron's Brewery School of Runewick wants to ease your path with some honeycombs. Come back to me once you have brewed new drinks that I can taste.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, ">", 9))
talkEntry:addCondition(condition_quest(716, "=", 6))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Adrons Braukunstschule zu Runewick erhebt dich in den Rang eines Anfängers. Du erhältst zehn Honigwaben."))
talkEntry:addConsequence(consequence_item(2529, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 7))
talkEntry:addResponse("Prost. Du kannst ja nicht nur trinken sondern auch Tränke. Adrons Braukunstschule zu Runewick gibt dir gerne einige Honigwaben. Komm erneut zu mir, wenn ich mehr probieren kann.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, "<", 10))
talkEntry:addCondition(condition_quest(716, "=", 6))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Drinking is fine. But from time to time you have to stir a brew in the barrel too to be eligible for a promotion. Your current rank is Layman.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 10 in brewing to advance in the ranks of Adron's Brewery School."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, "<", 10))
talkEntry:addCondition(condition_quest(716, "=", 6))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Drinking is fine. But from time to time you have to stir a brew in the barrel too to be eligible for a promotion. Your current rank is Layman.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 10 in brewing to advance in the ranks of Adron's Brewery School."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, "<", 10))
talkEntry:addCondition(condition_quest(716, "=", 6))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Selber trinken ist schon in Ordnung. Aber hin und wieder musst du auch mal einen Sud rühren, wenn du befördert werden willst. Du wirst im Rang eines Laiens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 10 in Brauen um in Adrons Braukunstschule aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, ">", 19))
talkEntry:addCondition(condition_quest(716, "=", 7))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Apprentice with Adron's Brewery School of Runewick. You are awarded twenty bags of hops."))
talkEntry:addConsequence(consequence_item(154, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 8))
talkEntry:addResponse("Cheers. You not only know how to drink, you know how to make drinks. Adron's Brewery School of Runewick wants to ease your path with some hops. Come back to me once you have brewed new drinks that I can taste.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, ">", 19))
talkEntry:addCondition(condition_quest(716, "=", 7))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Apprentice with Adron's Brewery School of Runewick. You are awarded twenty hops."))
talkEntry:addConsequence(consequence_item(154, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 8))
talkEntry:addResponse("Cheers. You not only know how to drink, you know how to make drinks. Adron's Brewery School of Runewick wants to ease your path with some hops. Come back to me once you have brewed new drinks that I can taste.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, ">", 19))
talkEntry:addCondition(condition_quest(716, "=", 7))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Adrons Braukunstschule zu Runewick erhebt dich in den Rang eines Lehrlings. Du erhältst zwanzig Hopfendolden."))
talkEntry:addConsequence(consequence_item(154, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 8))
talkEntry:addResponse("Prost. Du kannst ja nicht nur trinken sondern auch Tränke. Adrons Braukunstschule zu Runewick gibt dir gerne etwas Hopfen. Komm erneut zu mir, wenn ich mehr probieren kann.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, "<", 20))
talkEntry:addCondition(condition_quest(716, "=", 7))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Drinking is fine. But from time to time you have to stir a brew in the barrel too to be eligible for a promotion. Your current rank is Novice.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 20 in brewing to advance in the ranks of Adron's Brewery School."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, "<", 20))
talkEntry:addCondition(condition_quest(716, "=", 7))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Drinking is fine. But from time to time you have to stir a brew in the barrel too to be eligible for a promotion. Your current rank is Novice.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 20 in brewing to advance in the ranks of Adron's Brewery School."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, "<", 20))
talkEntry:addCondition(condition_quest(716, "=", 7))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Selber trinken ist schon in Ordnung. Aber hin und wieder musst du auch mal einen Sud rühren, wenn du befördert werden willst. Du wirst im Rang eines Anfängers geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 20 in Brauen um in Adrons Braukunstschule aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, ">", 29))
talkEntry:addCondition(condition_quest(716, "=", 8))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Initiate with Adron's Brewery School of Runewick. You are awarded ten berry juice bottles."))
talkEntry:addConsequence(consequence_item(790, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 9))
talkEntry:addResponse("Cheers. You not only know how to drink, you know how to make drinks. Adron's Brewery School of Runewick wants to ease your path with some berry juice bottles. Come back to me once you have brewed new drinks that I can taste.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, ">", 29))
talkEntry:addCondition(condition_quest(716, "=", 8))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Initiate with Adron's Brewery School of Runewick. You are awarded ten berry juice bottles."))
talkEntry:addConsequence(consequence_item(790, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 9))
talkEntry:addResponse("Cheers. You not only know how to drink, you know how to make drinks. Adron's Brewery School of Runewick wants to ease your path with some berry juice bottles. Come back to me once have brewed new drinks that I can taste.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, ">", 29))
talkEntry:addCondition(condition_quest(716, "=", 8))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Adrons Braukunstschule zu Runewick erhebt dich in den Rang eines Initiatens. Du erhältst zehn Beerensaftflaschen."))
talkEntry:addConsequence(consequence_item(790, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 9))
talkEntry:addResponse("Prost. Du kannst ja nicht nur trinken sondern auch Tränke. Adrons Braukunstschule zu Runewick gibt dir gerne einige Beerensaftflaschen. Komm erneut zu mir, wenn ich mehr probieren kann.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, "<", 30))
talkEntry:addCondition(condition_quest(716, "=", 8))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Drinking is fine. But from time to time you have to stir a brew in the barrel too to be eligible for a promotion. Your current rank is Apprentice.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 30 in brewing to advance in the ranks of Adron's Brewery School."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, "<", 30))
talkEntry:addCondition(condition_quest(716, "=", 8))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Drinking is fine. But from time to time you have to stir a brew in the barrel too to be eligible for a promotion. Your current rank is Apprentice.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 30 in brewing to advance in the ranks of Adron's Brewery School."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, "<", 30))
talkEntry:addCondition(condition_quest(716, "=", 8))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Selber trinken ist schon in Ordnung. Aber hin und wieder musst du auch mal einen Sud rühren, wenn du befördert werden willst. Du wirst im Rang eines Lehrlings geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 30 in Brauen um in Adrons Braukunstschule aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, ">", 39))
talkEntry:addCondition(condition_quest(716, "=", 9))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Journeyman with Adron's Brewery School of Runewick. You are awarded twenty bags of sugar cane and a journeyman's certificate."))
talkEntry:addConsequence(consequence_item(778, 20, 333, nil))
talkEntry:addConsequence(consequence_item(3109, 1, 333, {["descriptionEn"] = "The owner of this certificate has successfully passed the examination as Journeyman. Thomas Weste - Adron's Brewery School of Runewick", ["descriptionDe"] = "Der Inhaber dieses Gesellenbriefes hat erfolgreich das Examen zum Gesellen bestanden. Thomas Weste - Adrons Braukunstschule zu Runewick", ["nameDe"] = "Gesellenbrief", ["nameEn"] = "Journeyman's Certificate", ["rareness"] = "1"}))
talkEntry:addConsequence(consequence_quest(716, "=", 10))
talkEntry:addResponse("I'm glad to drink with a new Journeyman in our rows. Adron's Brewery School of Runewick wants to ease your path with some sugar cane. Come back to me once you have brewed new drinks that I can taste.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, ">", 39))
talkEntry:addCondition(condition_quest(716, "=", 9))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Journeyman with Adron's Brewery School of Runewick. You are awarded twenty bags of sugar cane and a journeyman's certificate."))
talkEntry:addConsequence(consequence_item(778, 20, 333, nil))
talkEntry:addConsequence(consequence_item(3109, 1, 333, {["descriptionEn"] = "The owner of this certificate has successfully passed the examination as Journeyman. Thomas Weste - Adron's Brewery School of Runewick", ["descriptionDe"] = "Der Inhaber dieses Gesellenbriefes hat erfolgreich das Examen zum Gesellen bestanden. Thomas Weste - Adrons Braukunstschule zu Runewick", ["nameDe"] = "Gesellenbrief", ["nameEn"] = "Journeyman's Certificate", ["rareness"] = "1"}))
talkEntry:addConsequence(consequence_quest(716, "=", 10))
talkEntry:addResponse("I'm glad to drink with a new Journeyman in our rows. Adron's Brewery School of Runewick wants to ease your path with some sugar cane. Come back to me once you have brewed new drinks that I can taste.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, ">", 39))
talkEntry:addCondition(condition_quest(716, "=", 9))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Adrons Braukunstschule zu Runewick erhebt dich in den Rang eines Gesellens. Du erhältst zwanzig Stangen Zuckerrohr und einen Gesellenbrief."))
talkEntry:addConsequence(consequence_item(778, 20, 333, nil))
talkEntry:addConsequence(consequence_item(3109, 1, 333, {["descriptionEn"] = "The owner of this certificate has successfully passed the examination as Journeyman. Thomas Weste - Adron's Brewery School of Runewick", ["descriptionDe"] = "Der Inhaber dieses Gesellenbriefes hat erfolgreich das Examen zum Gesellen bestanden. Thomas Weste - Adrons Braukunstschule zu Runewick", ["nameDe"] = "Gesellenbrief", ["nameEn"] = "Journeyman's Certificate", ["rareness"] = "1"}))
talkEntry:addConsequence(consequence_quest(716, "=", 10))
talkEntry:addResponse("Ich freu mich von einem neuen Gesellen zu einen Umtrunk eingeladen zu werden. Adrons Braukunstschule zu Runewick gibt dir gerne einige Stangen Zuckerrohr. Komm erneut zu mir, wenn ich mehr probieren kann.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, "<", 40))
talkEntry:addCondition(condition_quest(716, "=", 9))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Drinking is fine. But from time to time you have to stir a brew in the barrel too to be eligible for a promotion. Your current rank is Initiate.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 40 in brewing to advance in the ranks of Adron's Brewery School."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, "<", 40))
talkEntry:addCondition(condition_quest(716, "=", 9))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Drinking is fine. But from time to time you have to stir a brew in the barrel too to be eligible for a promotion. Your current rank is Initiate.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 40 in brewing to advance in the ranks of Adron's Brewery School."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, "<", 40))
talkEntry:addCondition(condition_quest(716, "=", 9))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Selber trinken ist schon in Ordnung. Aber hin und wieder musst du auch mal einen Sud rühren, wenn du befördert werden willst. Du wirst im Rang eines Initiatens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 40 in Brauen um in Adrons Braukunstschule aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, ">", 49))
talkEntry:addCondition(condition_quest(716, "=", 10))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Specialist with Adron's Brewery School of Runewick. You are awarded ten liquor bottles."))
talkEntry:addConsequence(consequence_item(1317, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 11))
talkEntry:addResponse("Cheers. You not only know how to drink, you know how to make drinks. Adron's Brewery School of Runewick wants to ease your path with some liquor bottles. Come back to me once you have brewed new drinks that I can taste.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, ">", 49))
talkEntry:addCondition(condition_quest(716, "=", 10))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Specialist with Adron's Brewery School of Runewick. You are awarded ten liquor bottles."))
talkEntry:addConsequence(consequence_item(1317, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 11))
talkEntry:addResponse("Cheers. You not only know how to drink, you know how to make drinks. Adron's Brewery School of Runewick wants to ease your path with some liquor bottles. Come back to me once you have brewed new drinks that I can taste.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, ">", 49))
talkEntry:addCondition(condition_quest(716, "=", 10))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Adrons Braukunstschule zu Runewick erhebt dich in den Rang eines Spezialistens. Du erhältst zehn Likörflaschen."))
talkEntry:addConsequence(consequence_item(1317, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 11))
talkEntry:addResponse("Prost. Du kannst ja nicht nur trinken sondern auch Tränke. Adrons Braukunstschule zu Runewick gibt dir gerne einige Likörflaschen. Komm erneut zu mir, wenn ich mehr probieren kann.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, "<", 50))
talkEntry:addCondition(condition_quest(716, "=", 10))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Drinking is fine. But from time to time you have to stir a brew in the barrel too to be eligible for a promotion. Your current rank is Journeyman.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 50 in brewing to advance in the ranks of Adron's Brewery School."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, "<", 50))
talkEntry:addCondition(condition_quest(716, "=", 10))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Drinking is fine. But from time to time you have to stir a brew in the barrel too to be eligible for a promotion. Your current rank is Journeyman.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 50 in brewing to advance in the ranks of Adron's Brewery School."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, "<", 50))
talkEntry:addCondition(condition_quest(716, "=", 10))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Selber trinken ist schon in Ordnung. Aber hin und wieder musst du auch mal einen Sud rühren, wenn du befördert werden willst. Du wirst im Rang eines Gesellens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 50 in Brauen um in Adrons Braukunstschule aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, ">", 59))
talkEntry:addCondition(condition_quest(716, "=", 11))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Expert with Adron's Brewery School of Runewick. You are awarded twenty berry juice bottles."))
talkEntry:addConsequence(consequence_item(790, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 12))
talkEntry:addResponse("Cheers. You not only know how to drink, you know how to make drinks. Adron's Brewery School of Runewick wants to ease your path with some berry juice bottles. Come back to me once you have brewed new drinks that I can taste.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, ">", 59))
talkEntry:addCondition(condition_quest(716, "=", 11))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Expert with Adron's Brewery School of Runewick. You are awarded berry twenty juice bottles."))
talkEntry:addConsequence(consequence_item(790, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 12))
talkEntry:addResponse("Cheers. You not only know how to drink, you know how to make drinks. Adron's Brewery School of Runewick wants to ease your path with some berry juice bottles. Come back to me once you have brewed new drinks that I can taste.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, ">", 59))
talkEntry:addCondition(condition_quest(716, "=", 11))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Adrons Braukunstschule zu Runewick erhebt dich in den Rang eines Expertens. Du erhältst zwanzig Beerensaftflaschen."))
talkEntry:addConsequence(consequence_item(790, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 12))
talkEntry:addResponse("Prost. Du kannst ja nicht nur trinken sondern auch Tränke. Adrons Braukunstschule zu Runewick gibt dir gerne einige Beerensaftflaschen. Komm erneut zu mir, wenn ich mehr probieren kann.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, "<", 60))
talkEntry:addCondition(condition_quest(716, "=", 11))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Drinking is fine. But from time to time you have to stir a brew in the barrel too to be eligible for a promotion. Your current rank is Specialist.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 60 in brewing to advance in the ranks of Adron's Brewery School."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, "<", 60))
talkEntry:addCondition(condition_quest(716, "=", 11))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Drinking is fine. But from time to time you have to stir a brew in the barrel too to be eligible for a promotion. Your current rank is Specialist.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 60 in brewing to advance in the ranks of Adron's Brewery School."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, "<", 60))
talkEntry:addCondition(condition_quest(716, "=", 11))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Selber trinken ist schon in Ordnung. Aber hin und wieder musst du auch mal einen Sud rühren, wenn du befördert werden willst. Du wirst im Rang eines Spezialistens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 60 in Brauen um in Adrons Braukunstschule aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, ">", 69))
talkEntry:addCondition(condition_quest(716, "=", 12))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Adept with Adron's Brewery School of Runewick. You are awarded ten liquor bottles."))
talkEntry:addConsequence(consequence_item(1317, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 13))
talkEntry:addResponse("Cheers. You not only know how to drink, you know how to make drinks. Adron's Brewery School of Runewick wants to ease your path with some liquor bottles. Come back to me once you have brewed new drinks that I can taste.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, ">", 69))
talkEntry:addCondition(condition_quest(716, "=", 12))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Adept with Adron's Brewery School of Runewick. You are awarded ten liquor bottles."))
talkEntry:addConsequence(consequence_item(1317, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 13))
talkEntry:addResponse("Cheers. You not only know how to drink, you know how to make drinks. Adron's Brewery School of Runewick wants to ease your path with some liquor bottles. Come back to me once have brewed new drinks that I can taste.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, ">", 69))
talkEntry:addCondition(condition_quest(716, "=", 12))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Adrons Braukunstschule zu Runewick erhebt dich in den Rang eines Adeptens. Du erhältst zehn Likörflaschen."))
talkEntry:addConsequence(consequence_item(1317, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 13))
talkEntry:addResponse("Prost. Du kannst ja nicht nur trinken sondern auch Tränke. Adrons Braukunstschule zu Runewick gibt dir gerne einige Likörflaschen. Komm erneut zu mir, wenn ich mehr probieren kann.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, "<", 70))
talkEntry:addCondition(condition_quest(716, "=", 12))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Drinking is fine. But from time to time you have to stir a brew in the barrel too to be eligible for a promotion. Your current rank is Expert.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 70 in brewing to advance in the ranks of Adron's Brewery School."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, "<", 70))
talkEntry:addCondition(condition_quest(716, "=", 12))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Drinking is fine. But from time to time you have to stir a brew in the barrel too to be eligible for a promotion. Your current rank is Expert.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 70 in brewing to advance in the ranks of Adron's Brewery School."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, "<", 70))
talkEntry:addCondition(condition_quest(716, "=", 12))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Selber trinken ist schon in Ordnung. Aber hin und wieder musst du auch mal einen Sud rühren, wenn du befördert werden willst. Du wirst im Rang eines Expertens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 70 in Brauen um in Adrons Braukunstschule aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, ">", 79))
talkEntry:addCondition(condition_quest(716, "=", 13))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Artisan with Adron's Brewery School of Runewick. You are awarded twenty sandberries."))
talkEntry:addConsequence(consequence_item(142, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 14))
talkEntry:addResponse("Cheers. You not only know how to drink, you know how to make drinks. Adron's Brewery School of Runewick wants to ease your path with some sandberries. Come back to me once you have brewed new drinks that I can taste.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, ">", 79))
talkEntry:addCondition(condition_quest(716, "=", 13))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Artisan with Adron's Brewery School of Runewick. You are awarded twenty sandberries."))
talkEntry:addConsequence(consequence_item(142, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 14))
talkEntry:addResponse("Cheers. You not only know how to drink, you know how to make drinks. Adron's Brewery School of Runewick wants to ease your path with some sandberries. Come back to me once you have brewed new drinks that I can taste.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, ">", 79))
talkEntry:addCondition(condition_quest(716, "=", 13))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Adrons Braukunstschule zu Runewick erhebt dich in den Rang eines Artisanens. Du erhältst zwanzig Sandbeeren."))
talkEntry:addConsequence(consequence_item(142, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 14))
talkEntry:addResponse("Prost. Du kannst ja nicht nur trinken sondern auch Tränke. Adrons Braukunstschule zu Runewick gibt dir gerne einige Sandbeeren. Komm erneut zu mir, wenn ich mehr probieren kann.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, "<", 80))
talkEntry:addCondition(condition_quest(716, "=", 13))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Drinking alone isn't wise and there's a lot of work for the best drinks. Cheers Adept.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 80 in brewing to advance in the ranks of Adron's Brewery School."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, "<", 80))
talkEntry:addCondition(condition_quest(716, "=", 13))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Drinking alone isn't wise and there's a lot of work for the best drinks. Cheers Adept.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 80 in brewing to advance in the ranks of Adron's Brewery School."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, "<", 80))
talkEntry:addCondition(condition_quest(716, "=", 13))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Alleine trinken ist nicht weise. Und du brauchst mir nicht zu erklären wie viel Arbeit es ist, hervorragende Tränke zu brauen. Prost Adept.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 80 in Brauen um in Adrons Braukunstschule aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, ">", 89))
talkEntry:addCondition(condition_quest(716, "=", 14))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Master with Adron's Brewery School of Runewick. You are awarded five pieces of pure water and a special tool."))
talkEntry:addConsequence(consequence_item(2554, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 15))
talkEntry:addResponse("Cheers. You not only know how to drink, you know how to make drinks. Adron's Brewery School of Runewick wants to ease your path with some drops pure water and this engraved spoon. Come back to me once you know have brewed new drinks that I can taste.")
talkEntry:addConsequence(consequence_item(227, 1, 999, {["descriptionEn"] = "Master of Adron's Brewery School of Runewick", ["descriptionDe"] = "Meister an Adrons Braukunstschule zu Runewick", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, ">", 89))
talkEntry:addCondition(condition_quest(716, "=", 14))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Master with Adron's Brewery School of Runewick. You are awarded five pieces of pure water and a special tool."))
talkEntry:addConsequence(consequence_item(2554, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 15))
talkEntry:addResponse("Cheers. You not only know how to drink, you know how to make drinks. Adron's Brewery School of Runewick wants to ease your path with some drops pure water and this engraved spoon. Come back to me once you have brewed new drinks that I can taste.")
talkEntry:addConsequence(consequence_item(227, 1, 999, {["descriptionEn"] = "Master of Adron's Brewery School of Runewick", ["descriptionDe"] = "Meister an Adrons Braukunstschule zu Runewick", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, ">", 89))
talkEntry:addCondition(condition_quest(716, "=", 14))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Adrons Braukunstschule zu Runewick erhebt dich in den Rang eines Meisters. Du erhältst fünf Tropfen reines Wasser und ein besonderes Werkzeug."))
talkEntry:addConsequence(consequence_item(2554, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 15))
talkEntry:addResponse("Prost. Du kannst ja nicht nur trinken sondern auch Tränke. Adrons Braukunstschule zu Runewick gibt dir gerne etwas reines Wasser und diesem besonderen Kochlöffel. Komm erneut zu mir, wenn ich mehr probieren kann.")
talkEntry:addConsequence(consequence_item(227, 1, 999, {["descriptionEn"] = "Master of Adron's Brewery School of Runewick", ["descriptionDe"] = "Meister an Adrons Braukunstschule zu Runewick", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, "<", 90))
talkEntry:addCondition(condition_quest(716, "=", 14))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Drinking alone isn't wise and there's a lot of work for the best drinks. Cheers Artisan.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 90 in brewing to advance in the ranks of Adron's Brewery School."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, "<", 90))
talkEntry:addCondition(condition_quest(716, "=", 14))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Drinking alone isn't wise and there's a lot of work for the best drinks. Cheers Artisan.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 90 in brewing to advance in the ranks of Adron's Brewery School."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, "<", 90))
talkEntry:addCondition(condition_quest(716, "=", 14))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Alleine trinken ist nicht weise. Und du brauchst mir nicht zu erklären wie viel Arbeit es ist, hervorragende Tränke zu brauen. Prost Artisan.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 90 in Brauen um in Adrons Braukunstschule aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, ">", 99))
talkEntry:addCondition(condition_quest(716, "=", 15))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Grandmaster with Adron's Brewery School of Runewick. You are awarded ten pieces of pure spirit and a grandmaster's medal."))
talkEntry:addConsequence(consequence_item(3607, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 16))
talkEntry:addResponse("Unbelieveable. I cheer to a new Grandmaster of Adron's Brewery School of Runewick. With this pure spirit... erm what's it for? Let's clink our glasses.")
talkEntry:addConsequence(consequence_item(3535, 1, 999, {["descriptionEn"] = "Grandmaster of Adron's Brewery School of Runewick", ["descriptionDe"] = "Großmeister von Adrons Braukunstschule zu Runewick", ["nameDe"] = "Großmeistermedallie", ["nameEn"] = "Grandmaster's Medal", ["rareness"] = "2"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, ">", 99))
talkEntry:addCondition(condition_quest(716, "=", 15))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Grandmaster with Adron's Brewery School of Runewick. You are awarded ten pieces of pure fire and a grandmaster's medal."))
talkEntry:addConsequence(consequence_item(3607, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 16))
talkEntry:addResponse("Unbelieveable. I cheer to a new Grandmaster of Adron's Brewery School of Runewick. With this pure spirit... erm what's it for? Let's clink our glasses.")
talkEntry:addConsequence(consequence_item(3535, 1, 999, {["descriptionEn"] = "Grandmaster of Adron's Brewery School of Runewick", ["descriptionDe"] = "Großmeister von Adrons Braukunstschule zu Runewick", ["nameDe"] = "Großmeistermedallie", ["nameEn"] = "Grandmaster's Medal", ["rareness"] = "2"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, ">", 99))
talkEntry:addCondition(condition_quest(716, "=", 15))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Adrons Braukunstschule zu Runewick erhebt dich in den Rang eines Großmeisters. Du erhältst zehn Stück reinen Geist und eine Großmeistermedallie."))
talkEntry:addConsequence(consequence_item(3607, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(716, "=", 16))
talkEntry:addResponse("Unglaublich. Ich erhebe mein Glas auf einen neuen Großmeister von Adrons Braukunstschule zu Runewick. Mit diesem reinen Geist wirst du... erm ja was wirst du? Lasst uns anstoßen.")
talkEntry:addConsequence(consequence_item(3535, 1, 999, {["descriptionEn"] = "Grandmaster of Adron's Brewery School of Runewick", ["descriptionDe"] = "Großmeister von Adrons Braukunstschule zu Runewick", ["nameDe"] = "Großmeistermedallie", ["nameEn"] = "Grandmaster's Medal", ["rareness"] = "2"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, "<", 100))
talkEntry:addCondition(condition_quest(716, "=", 15))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Drinking alone isn't wise and there's a lot of work for the best drinks. Cheers Master.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 100 in brewing to advance in the ranks of Adron's Brewery School."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, "<", 100))
talkEntry:addCondition(condition_quest(716, "=", 15))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Drinking alone isn't wise and there's a lot of work for the best drinks. Cheers Master.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 100 in brewing to advance in the ranks of Adron's Brewery School."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.brewing, "<", 100))
talkEntry:addCondition(condition_quest(716, "=", 15))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Alleine trinken ist nicht weise. Und du brauchst mir nicht zu erklären wie viel Arbeit es ist, hervorragende Tränke zu brauen. Prost Meister.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 100 in Brauen um in Adrons Braukunstschule aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(716, "=", 16))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Your apprenticeship with Adron's Brewery School of Runewick is over. For you are now one of its Grandmasters, %CHARNAME.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(716, "=", 16))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addResponse("Your apprenticeship with Adron's Brewery School of Runewick is over. For you are now one of its Grandmasters, %CHARNAME.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(716, "=", 16))
talkEntry:addCondition(condition_town(2))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addResponse("Deine Lehre bei Adrons Braukunstschule zu Runewick ist nun vorrüber. Denn du bist einer ihrer Großmeister, %CHARNAME.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Adron's Brewery School is restricted to Runewick's citizens.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addResponse("Adron's Brewery School is restricted to Runewick's citizens.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addResponse("Adrons Braukunstschule steht nur Bürgern Runewicks offen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("elvaine")
talkEntry:addTrigger("morgan")
talkEntry:addResponse("The Archmage Elvaine Morgan patrons everybody who is willing to learn. That includes our school.")
talkEntry:addResponse("I wish I could understand everything Elvaine Morgan writes.")
talkEntry:addResponse("Yesterday, I was able to serve the Archmage a special drink.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Archmage")
talkEntry:addResponse("The Archmage Elvaine Morgan patrons everybody who is willing to learn. That includes our school.")
talkEntry:addResponse("I wish I could understand everything Elvaine Morgan writes.")
talkEntry:addResponse("Yesterday, I was able to serve the Archmage a special drink.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Erzmagier")
talkEntry:addTrigger("elvaine")
talkEntry:addTrigger("morgan")
talkEntry:addResponse("Der Erzmagier behütet jeden, der gewillt ist zu lernen. Auch unsere Schule.")
talkEntry:addResponse("Ich wünschte ich könnte verstehen, was Elvaine Morgan alles geschrieben hat.")
talkEntry:addResponse("Gestern durfte ich dem Erzmagier ein besondern Trank kredenzen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("farm")
talkEntry:addTrigger("field")
talkEntry:addTrigger("vegetable")
talkEntry:addTrigger("grain")
talkEntry:addResponse("I buy the food for my drinks from the farmers of our city.")
talkEntry:addResponse("On the fields in front of the city almost everything a good brewer needs grows.")
talkEntry:addResponse("You could plant everything yourself, but the farmers also want to sell something.")
talkEntry:addResponse("I put fresh sugar cane only in the barrel.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("landwirt")
talkEntry:addTrigger("feld")
talkEntry:addTrigger("Zucker")
talkEntry:addTrigger("getreide")
talkEntry:addResponse("Die Lebensmittel für meine Getränke kaufe ich bei den Landwirten unserer Stadt.")
talkEntry:addResponse("Auf den Feldern vor der Stadt wächst fast alles was ein guter Braumeister braucht.")
talkEntry:addResponse("Man könnte ja alles selber anpflanzen, aber die Landwirte wollen ja auch was verkaufen.")
talkEntry:addResponse("Mir kommt nur frisches Zuckerrohr in den Topf.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("honey")
talkEntry:addResponse("Mmmm... Mead!")
talkEntry:addResponse("Mead, the drink of the north... and south, and west and east.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Honig")
talkEntry:addResponse("Mmmm.. Honig!")
talkEntry:addResponse("Meet, der Trank des Nordens... und Südens und Westens und Ostens.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Adron")
talkEntry:addResponse("Right in the tavern you find his altar.")
talkEntry:addResponse("The best brewers always worshipped Adron.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Adron")
talkEntry:addResponse("Direkt in der Taverne findet man seinen Altar")
talkEntry:addResponse("Die besten Brauer waren Anhänger Adrons.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("god")
talkEntry:addTrigger("temple")
talkEntry:addResponse("Many Gods have a temple in Runewick: Adron in the tavern, Ushara on the isle of earth, Tanora near the harbour, Bragon on the isle of fire, Oldra in Yewdale, Elara in the library, Eldan on the isle of the Archmage and Findari here on the isle of air.")
talkEntry:addResponse("You may find temples of the Old and the Younger Gods in Runewick.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Gott")
talkEntry:addTrigger("Tempel")
talkEntry:addResponse("Viele Götter haben einen Tempel in Runewick. Adron in der Taverne, Ushara auf der Insel der Erde, Tanora in der Nähe des Hafens, Bragon auf der Insel des Feuers, Oldra in Eibenthal, Elara in der Bücherei, Eldan auf der Insel der Erzmagiers und Findari hier bei uns auf der Insel der Luft")
talkEntry:addResponse("Hier in Runewick findest du Tempel der alten und der jungen Götter.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("cheers")
talkEntry:addResponse("Cheers!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("prost")
talkEntry:addResponse("Prost!")
talkingNPC:addTalkingEntry(talkEntry)
end
talkingNPC:addCycleText("#me verstaut eine Flasche in seinem Beutel.", "#me stores a bottle in his bag.")
talkingNPC:addCycleText("#me kratzt sich am Kopf.", "#me scratches his head.")
talkingNPC:addCycleText("Wenn ihr Hilfe beim Brauen braucht dann fragt nur mich!", "If you need any help with brewing, just ask me!")
talkingNPC:addCycleText("#me gähnt verhalten.", "#me yawns restrained.")
talkingNPC:addCycleText("#me schaut sich kurz um und kratzt sich anschließend an seinem Hintern.", "#me looks around briefly and scratches his bum.")
talkingNPC:addCycleText("Im Adras rutschen einem die Getränke nur so die Kehle herunter.", "In Adras the drinks flow freely.")
talkingNPC:addCycleText("#me schaut sich gereizt um.", "#me looks about crankily.")
talkingNPC:addCycleText("#me isst einen Apfel.", "#me eats an apple.")
talkingNPC:addCycleText("#me schreibt einen Brief.", "#me writes a letter.")
talkingNPC:addCycleText("#me reinigt sich seine Nägel mit einem Dolch.", "#me cleans his finger nails with a dagger.")
talkingNPC:addCycleText("Prost", "Cheers")
mainNPC:addLanguage(0)
mainNPC:addLanguage(1)
mainNPC:setDefaultLanguage(0)
mainNPC:setLookat("Dieser NPC ist Thomas Weste der Brauer.", "This NPC is Thomas Weste the brewer.")
mainNPC:setUseMessage("Fass mich nicht an!", "Hands off!")
mainNPC:setConfusedMessage("#me schaut dich verwirrt an.", "#me looks at you confused.")
mainNPC:setEquipment(1, 0)
mainNPC:setEquipment(3, 182)
mainNPC:setEquipment(11, 193)
mainNPC:setEquipment(5, 0)
mainNPC:setEquipment(6, 0)
mainNPC:setEquipment(4, 0)
mainNPC:setEquipment(9, 461)
mainNPC:setEquipment(10, 53)
mainNPC:setAutoIntroduceMode(true)

mainNPC:initDone()
return mainNPC
end
local mNPC = initNpc()
initNpc = nil
local M = {}
function M.receiveText(npcChar, texttype, message, speaker) mNPC:receiveText(npcChar, texttype, speaker, message) end
function M.nextCycle(npcChar) mNPC:nextCycle(npcChar) end
function M.lookAtNpc(npcChar, char, mode) mNPC:lookAt(npcChar, char, mode) end
function M.useNPC(npcChar, char, counter, param) mNPC:use(npcChar, char) end
return M
