local consequence_item = require("npc.base.consequence.item")
local condition_item = require("npc.base.condition.item")
local consequence_quest = require("npc.base.consequence.quest")
local condition_skill = require("npc.base.condition.skill")
local condition_language = require("npc.base.condition.language")
local consequence_deleteitem = require("npc.base.consequence.deleteitem")
local basic = require("npc.base.basic")
local condition_town = require("npc.base.condition.town")
local talk = require("npc.base.talk")
local consequence_money = require("npc.base.consequence.money")
local condition_quest = require("npc.base.condition.quest")
local consequence_inform = require("npc.base.consequence.inform")
local function initNpc()
local mainNPC = basic()
mainNPC:setAffiliation(3)
local talkingNPC = talk(mainNPC)
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Help")
talkEntry:addConsequence(consequence_inform("[Game Help] This NPC is Thorgrem Silverbeard the blacksmith. Keywords: Hello, Quest, blacksmithing."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hilfe")
talkEntry:addConsequence(consequence_inform("[Spielhilfe] Dieser NPC ist Thorgrem Silverbeard der Schmied. Schlüsselwörter: Hallo, Quest, Schmieden."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hello")
talkEntry:addTrigger("Greet")
talkEntry:addTrigger("Hail")
talkEntry:addTrigger("Good day")
talkEntry:addTrigger("Good morning")
talkEntry:addTrigger("Good Evening")
talkEntry:addResponse("Now what, do I need to help you?")
talkEntry:addResponse("Not sure it is nice to meet you but I'm Thorgrem Silverbeard.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Grüß")
talkEntry:addTrigger("Gruß")
talkEntry:addTrigger("Grüss")
talkEntry:addTrigger("Gruss")
talkEntry:addTrigger("Guten Morgen")
talkEntry:addTrigger("Guten Tag")
talkEntry:addTrigger("Guten Abend")
talkEntry:addTrigger("Gute Nacht")
talkEntry:addTrigger("Mahlzeit")
talkEntry:addTrigger("Tach")
talkEntry:addTrigger("Moin")
talkEntry:addTrigger("Mohltied")
talkEntry:addResponse("Hallo, muss ich dir jetzt helfen?")
talkEntry:addResponse("Sollte ich mich freuen, dich kennenzulernen? Egal, ich bin Thorgrem Silverbeard.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Hiho")
talkEntry:addTrigger("Hallo")
talkEntry:addTrigger("Hey")
talkEntry:addTrigger("Greeb")
talkEntry:addResponse("Now what, do I need to help you?")
talkEntry:addResponse("Not sure it is nice to meet you but I'm Thorgrem Silverbeard.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hiho")
talkEntry:addTrigger("Hallo")
talkEntry:addTrigger("Hey")
talkEntry:addTrigger("Greeb")
talkEntry:addResponse("Hallo, muss ich dir jetzt helfen?")
talkEntry:addResponse("Sollte ich mich freuen, dich kennenzulernen? Egal, ich bin Thorgrem Silverbeard.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Farewell")
talkEntry:addTrigger("Bye")
talkEntry:addTrigger("Fare well")
talkEntry:addTrigger("See you")
talkEntry:addResponse("I wish you a day. Nice, bad, your call.")
talkEntry:addResponse("I hope we meet again. Or not.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Tschüß")
talkEntry:addTrigger("Tschüss")
talkEntry:addTrigger("Wiedersehen")
talkEntry:addResponse("Ich wünsche noch einen Tag. Obs ein schöner wird, liegt an dir.")
talkEntry:addResponse("Ich hoffe wir sehen uns wieder. Oder auch nicht.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Ciao")
talkEntry:addTrigger("Adieu")
talkEntry:addTrigger("Au revoir")
talkEntry:addTrigger("Farebba")
talkEntry:addResponse("I wish you a day. Nice, bad, your call.")
talkEntry:addResponse("I hope we meet again. Or not.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Ciao")
talkEntry:addTrigger("Adieu")
talkEntry:addTrigger("Au revoir")
talkEntry:addTrigger("Farebba")
talkEntry:addResponse("Ich wünsche noch einen Tag. Obs ein schöner wird, liegt an dir.")
talkEntry:addResponse("Ich hoffe wir sehen uns wieder. Oder auch nicht.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("How are you")
talkEntry:addTrigger("How feel")
talkEntry:addTrigger("How do you do")
talkEntry:addResponse("How am I supposed to feel?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Wie geht")
talkEntry:addTrigger("Wie fühlst")
talkEntry:addTrigger("Wie ist es ergangen")
talkEntry:addTrigger("Wie Befind")
talkEntry:addResponse("Wie soll's mir schon gehen?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("your name")
talkEntry:addTrigger("who are you")
talkEntry:addTrigger("who art thou")
talkEntry:addResponse("I'm Thorgrem Silverbeard. That matters.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("ihr name")
talkEntry:addTrigger("dein name")
talkEntry:addTrigger("wer bist du")
talkEntry:addTrigger("wer seid ihr")
talkEntry:addTrigger("wie heißt")
talkEntry:addTrigger("wie heisst")
talkEntry:addResponse("Ich bin Thorgrem Silverbeard. Das ist wichtig.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("sell")
talkEntry:addTrigger("buy")
talkEntry:addTrigger("wares")
talkEntry:addTrigger("price")
talkEntry:addTrigger("trade")
talkEntry:addTrigger("purchase")
talkEntry:addResponse("I am not a trader. Not at all.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("kauf")
talkEntry:addTrigger("waren")
talkEntry:addTrigger("preis")
talkEntry:addTrigger("Handel")
talkEntry:addTrigger("veräußer")
talkEntry:addTrigger("veräusser")
talkEntry:addTrigger("erwerb")
talkEntry:addResponse("Ich bin doch kein Händler!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("profession")
talkEntry:addResponse("Short legs, long beard; what do you think I am? A blacksmith of course!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("beruf")
talkEntry:addResponse("Kurze Beine, langer Bart; was denkst du wohl, bin ich? Ein Schmied natürlich!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("job")
talkEntry:addResponse("Short legs, long beard; what do you think I am? A blacksmith of course!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("job")
talkEntry:addResponse("Kurze Beine, langer Bart; was denkst du wohl, bin ich? Ein Schmied natürlich!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("smith")
talkEntry:addTrigger("craft")
talkEntry:addResponse("If you want to smith you need ingots and a hammer of course. Blacksmiths need a normal hammer, finesmiths need a finesmithing hammer, though. Armourers have their own hammer, too.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("schmied")
talkEntry:addTrigger("handwerk")
talkEntry:addResponse("Wenn du schmieden willt, dann brauchst du Barren und natürlich einen Hammer. Schmiede benutzen einen gewöhnlichen Hammer, Goldschmiede dagegen brauchen einen Feinschmiedehammer. Und Rüstschmiede haben auch ihren eigenen Hammer.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(708, "=", 0))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_item(2763, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 1))
talkEntry:addResponse("Let's get started. To become a real blacksmith, you'll need iron ore and coal. Get ten pieces of iron ore from the Malachite Mine and also ten lumps of coal from the Dark Hole Mine. If you leave the workshop to the south, and follow the street south, you will get to the Malachite Mine. The Dark Hole Mine is outside the city, you can find it if you go north west from the main gate. I'll give you my old pick-axe to mine the ore.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Blacksmithing Guild of Galmair I. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(708, "=", 0))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_item(2763, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 1))
talkEntry:addResponse("Let's get started. To become a real blacksmith, you'll need iron ore and coal. Get ten pieces of iron ore from the Malachite Mine and also ten lumps of coal from the Dark Hole Mine. If you leave the workshop to the south, and follow the street south, you will get to the Malachite Mine. The Dark Hole Mine is outside the city, you can find it if you go north west from the main gate. I'll give you my old pick-axe to mine the ore.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Blacksmithing Guild of Galmair I. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(708, "=", 0))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addConsequence(consequence_item(2763, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 1))
talkEntry:addResponse("Dann mal los. Um ein echter Schmied zu werden, brauchst du Eisenerz und Kohle. Besorg zehn Brocken Eisenerz aus der Malachitmine und noch zehn Klumpen Kohle aus der Dunkellochmine. Verlasse die Werkstatt und folg der Straße die nach Süden führt, um zur Malachitmine zu gelangen. Die Dunkellochmine ist außerhalb der Stadt im Nordwesten. Hier, ich gebe dir meine alte Spitzhacke, um das Erz abzubauen.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Die Schmiedegilde von Galmair I. Detaillierte Informationen findest du im Questlog (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(708, "=", 1))
talkEntry:addCondition(condition_item(21, "all", ">", 9, nil))
talkEntry:addCondition(condition_item(22, "all", ">", 9, nil))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_quest(708, "=", 2))
talkEntry:addResponse("So, now you know how to get raw materials for smithing. Keep the stuff for your next task.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Ask Thorgrem Silverbeard for your next task."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(708, "=", 1))
talkEntry:addCondition(condition_item(21, "all", ">", 9, nil))
talkEntry:addCondition(condition_item(22, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("coal")
talkEntry:addTrigger("iron")
talkEntry:addConsequence(consequence_quest(708, "=", 2))
talkEntry:addResponse("So, now you know how to get raw materials for smithing. Keep the stuff for your next task.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Ask Thorgrem Silverbeard for your next task."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(708, "=", 1))
talkEntry:addCondition(condition_item(21, "all", ">", 9, nil))
talkEntry:addCondition(condition_item(22, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("kohle")
talkEntry:addTrigger("eisen")
talkEntry:addConsequence(consequence_quest(708, "=", 2))
talkEntry:addResponse("So, nun weißt du, wie man sich Ressourcen für das Schmieden besorgt. Behalt den Kram für deine nächste Aufgabe.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Frage Thorgrem Silverbeard nach deiner nächsten Aufgaben."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(708, "=", 1))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Ten pieces of iron ore and ten lumps of coal. Is that too difficult for you?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(708, "=", 1))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("coal")
talkEntry:addTrigger("iron")
talkEntry:addResponse("Ten pieces of iron ore and ten lumps of coal. Is that too difficult for you?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(708, "=", 1))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("kohle")
talkEntry:addTrigger("eisen")
talkEntry:addResponse("Zehn Stück Eisenerz und zehn Haufen Kohle. Ist das etwa zu schwer für dich?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(708, "=", 2))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_item(2751, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 3))
talkEntry:addResponse("Let's go on. Smelt ten iron ingots at the bloomery over there. Here, I'll even give you crucible-pincers for smelting the ore.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Blacksmithing Guild of Galmair II. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(708, "=", 2))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_item(2751, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 3))
talkEntry:addResponse("Let's go on. Smelt ten iron ingots at the bloomery over there. Here, I'll even give you crucible-pincers for smelting the ore.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Blacksmithing Guild of Galmair II. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(708, "=", 2))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addConsequence(consequence_item(2751, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 3))
talkEntry:addResponse("Lass uns weitermachen. Erschmelze zehn Eisenbarren in dem Rennofen neben mir. Hier, ich gebe dir sogar eine Tiegelzange.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Die Schmiedegilde von Galmair II. Detaillierte Informationen findest du im Questlog (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(708, "=", 3))
talkEntry:addCondition(condition_item(2535, "all", ">", 9, nil))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_quest(708, "=", 4))
talkEntry:addResponse("Not bad I must admit. Keep the iron ingots for your next task.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Ask Thorgrem Silverbeard for your next task."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(708, "=", 3))
talkEntry:addCondition(condition_item(2535, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("iron")
talkEntry:addTrigger("ingot")
talkEntry:addConsequence(consequence_quest(708, "=", 4))
talkEntry:addResponse("Not bad I must admit. Keep the iron ingots for your next task.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Ask Thorgrem Silverbeard for your next task."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(708, "=", 3))
talkEntry:addCondition(condition_item(2535, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Eisen")
talkEntry:addTrigger("Barren")
talkEntry:addConsequence(consequence_quest(708, "=", 4))
talkEntry:addResponse("Sieht gar nicht mal schlecht aus. Behalte die Eisenbarren für deine nächste Aufgabe.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Frage Thorgrem Silverbeard nach deiner nächsten Aufgaben."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(708, "=", 3))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("That's not ten iron ingots yet. Please come back later when you've finished the task.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(708, "=", 3))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("iron")
talkEntry:addTrigger("ingot")
talkEntry:addResponse("That's not ten iron ingots yet. Please come back later when you've finished the task.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(708, "=", 3))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Eisen")
talkEntry:addTrigger("Barren")
talkEntry:addResponse("Das sind noch keine zehn Eisenbarren. Komm wieder, wenn du die Aufgabe erledigt hast.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(708, "=", 4))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_item(23, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 5))
talkEntry:addResponse("You want another task? Well, alright. Smith ten pins to show me you know how to forge iron. Have this hammer - don't mix it up with the armourer's hammer and the finesmithing hammer.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Blacksmithing Guild of Galmair III. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(708, "=", 4))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_item(23, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 5))
talkEntry:addResponse("You want another task? Well, alright. Smith ten pins to show me you know how to forge iron. Have this hammer - don't mix it up with the armourer's hammer and the finesmithing hammer.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Blacksmithing Guild of Galmair III. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(708, "=", 4))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addConsequence(consequence_item(23, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 5))
talkEntry:addResponse("Du willst noch eine Aufgabe? Na gut, meinetwegen. Schmiede zehn Nägel um zu beweisen, dass du begriffen hast, wie man Eisen in Form schmiedet. Nimm diesen Hammer - Verwechsle ihn nicht mit dem Feinschmiedehammer und dem Hammer des Rüstschmieds.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Die Schmiedegilde von Galmair III. Detaillierte Informationen findest du im Questlog (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(708, "=", 5))
talkEntry:addCondition(condition_item(2738, "all", ">", 9, nil))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Layman with the Blacksmithing Guild of Galmair. You are awarded twenty silver coins."))
talkEntry:addConsequence(consequence_deleteitem(2738, 10, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 6))
talkEntry:addConsequence(consequence_money("+", 2000))
talkEntry:addResponse("Well done, thanks for the pins. I make you an official member of the Blacksmithing Guild of Galmair. Here is some money that will help you to set up your business. Come back once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(708, "=", 5))
talkEntry:addCondition(condition_item(2738, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("pin")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Layman with the Blacksmithing Guild of Galmair. You are awarded twenty silver coins."))
talkEntry:addConsequence(consequence_deleteitem(2738, 10, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 6))
talkEntry:addConsequence(consequence_money("+", 2000))
talkEntry:addResponse("Well done. I make you an official member of the Blacksmithing Guild of Galmair. Here is some money that will help you to set up your business. Come back once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(708, "=", 5))
talkEntry:addCondition(condition_item(2738, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Nägel")
talkEntry:addTrigger("Nagel")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Schmiedegilde von Galmair erhebt dich in den Rang eines Laiens. Du erhältst zwanzig Silberstücke."))
talkEntry:addConsequence(consequence_deleteitem(2738, 10, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 6))
talkEntry:addConsequence(consequence_money("+", 2000))
talkEntry:addResponse("Gut gemacht, danke für die Nägel. Du bist nun ein offizielles Mitglied der Schmiedegilde von Galmair. Hier ist etwas Geld, welches dir helfen wird, deine Geschäfte auszubauen. Komm erneut zu mir, wenn du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(708, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("You haven't solved the task yet. Please come back again when you have ten pins.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(708, "=", 5))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("pin")
talkEntry:addResponse("You haven't solved the task yet. Please come back again when you have ten pins.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(708, "=", 5))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Nägel")
talkEntry:addTrigger("Nagel")
talkEntry:addResponse("Wie ich sehe, hast du hast die Aufgabe noch nicht erfüllt. Bitte bring mir zehn Nägel.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, ">", 9))
talkEntry:addCondition(condition_quest(708, "=", 6))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Novice with the Blacksmithing Guild of Galmair. You are awarded ten lumps of coal."))
talkEntry:addConsequence(consequence_item(21, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 7))
talkEntry:addResponse("The Blacksmithing Guild of Galmair authorised me to promote you. Have some coal for further working shifts. Come back once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, ">", 9))
talkEntry:addCondition(condition_quest(708, "=", 6))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Novice with the Blacksmithing Guild of Galmair. You are awarded ten lumps of coal."))
talkEntry:addConsequence(consequence_item(21, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 7))
talkEntry:addResponse("The Blacksmithing Guild of Galmair authorised me to promote you. Have some coal for further working shifts. Come back once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, ">", 9))
talkEntry:addCondition(condition_quest(708, "=", 6))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Schmiedegilde von Galmair erhebt dich in den Rang eines Anfängers. Du erhältst zehn Klumpen Kohle."))
talkEntry:addConsequence(consequence_item(21, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 7))
talkEntry:addResponse("Die Schmiedegilde von Galmair hat mich angewiesen, dich zu befördern. Nimm diese Kohlen für weitere Arbeitsschichten. Komm erneut zu mir, wenn du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, "<", 10))
talkEntry:addCondition(condition_quest(708, "=", 6))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("You are not experienced enough for a promotion with the Blacksmithing Guild of Galmair. Your current rank is Layman.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 10 in blacksmithing to advance in the ranks of the Blacksmithing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, "<", 10))
talkEntry:addCondition(condition_quest(708, "=", 6))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("You are not experienced enough for a promotion with the Blacksmithing Guild of Galmair. Your current rank is Layman.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 10 in blacksmithing to advance in the ranks of the Blacksmithing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, "<", 10))
talkEntry:addCondition(condition_quest(708, "=", 6))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Du bist noch nicht erfahren genug, um in der Schmiedegilde von Galmair aufzusteigen. Du hast derzeit den Rang eines Laiens inne.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 10 in Schmieden um in der Schmiedegilde aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, ">", 19))
talkEntry:addCondition(condition_quest(708, "=", 7))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Apprentice with the Blacksmithing Guild of Galmair. You are awarded twenty pieces of iron ore."))
talkEntry:addConsequence(consequence_item(22, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 8))
talkEntry:addResponse("The Blacksmithing Guild of Galmair authorised me to promote you. Have some iron ore for further working shifts. Come back once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, ">", 19))
talkEntry:addCondition(condition_quest(708, "=", 7))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Apprentice with the Blacksmithing Guild of Galmair. You are awarded twenty pieces of iron ore."))
talkEntry:addConsequence(consequence_item(22, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 8))
talkEntry:addResponse("The Blacksmithing Guild of Galmair authorised me to promote you. Have some iron ore for further working shifts. Come back once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, ">", 19))
talkEntry:addCondition(condition_quest(708, "=", 7))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Schmiedegilde von Galmair erhebt dich in den Rang eines Lehrlings. Du erhältst zwanzig Stücke Eisenerz."))
talkEntry:addConsequence(consequence_item(22, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 8))
talkEntry:addResponse("Die Schmiedegilde von Galmair hat mich angewiesen, dich zu befördern. Nimm dieses Eisenerz für weitere Arbeitsschichten. Komm erneut zu mir, wenn du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, "<", 20))
talkEntry:addCondition(condition_quest(708, "=", 7))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("You are not experienced enough for a promotion with the Blacksmithing Guild of Galmair. Your current rank is Novice.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 20 in blacksmithing to advance in the ranks of the Blacksmithing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, "<", 20))
talkEntry:addCondition(condition_quest(708, "=", 7))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("You are not experienced enough for a promotion with the Blacksmithing Guild of Galmair. Your current rank is Novice.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 20 in blacksmithing to advance in the ranks of the Blacksmithing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, "<", 20))
talkEntry:addCondition(condition_quest(708, "=", 7))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Du bist noch nicht erfahren genug, um in der Schmiedegilde von Galmair aufzusteigen. Du hast derzeit den Rang eines Anfängers inne.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 20 in Schmieden um in der Schmiedegilde aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, ">", 29))
talkEntry:addCondition(condition_quest(708, "=", 8))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Initiate with the Blacksmithing Guild of Galmair. You are awarded ten iron ingots."))
talkEntry:addConsequence(consequence_item(2535, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 9))
talkEntry:addResponse("The Blacksmithing Guild of Galmair authorised me to promote you. Have some iron ingots for further working shifts. Come back once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, ">", 29))
talkEntry:addCondition(condition_quest(708, "=", 8))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Initiate with the Blacksmithing Guild of Galmair. You are awarded ten iron ingots."))
talkEntry:addConsequence(consequence_item(2535, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 9))
talkEntry:addResponse("The Blacksmithing Guild of Galmair authorised me to promote you. Have some iron ingots for further working shifts. Come back once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, ">", 29))
talkEntry:addCondition(condition_quest(708, "=", 8))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Schmiedegilde von Galmair erhebt dich in den Rang eines Initiatens. Du erhältst zehn Eisenbarren."))
talkEntry:addConsequence(consequence_item(2535, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 9))
talkEntry:addResponse("Die Schmiedegilde von Galmair hat mich angewiesen, dich zu befördern. Nimm diese Eisenbarren für weitere Arbeitsschichten. Komm erneut zu mir, wenn du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, "<", 30))
talkEntry:addCondition(condition_quest(708, "=", 8))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("You are not experienced enough for a promotion with the Blacksmithing Guild of Galmair. Your current rank is Apprentice.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 30 in blacksmithing to advance in the ranks of the Blacksmithing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, "<", 30))
talkEntry:addCondition(condition_quest(708, "=", 8))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("You are not experienced enough for a promotion with the Blacksmithing Guild of Galmair. Your current rank is Apprentice.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 30 in blacksmithing to advance in the ranks of the Blacksmithing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, "<", 30))
talkEntry:addCondition(condition_quest(708, "=", 8))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Du bist noch nicht erfahren genug, um in der Schmiedegilde von Galmair aufzusteigen. Du hast derzeit den Rang eines Lehrlings inne.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 30 in Schmieden um in der Schmiedegilde aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, ">", 39))
talkEntry:addCondition(condition_quest(708, "=", 9))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Journeyman with the Blacksmithing Guild of Galmair. You are awarded twenty iron plates and a journeyman's certificate."))
talkEntry:addConsequence(consequence_item(2537, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 10))
talkEntry:addResponse("The Blacksmithing Guild of Galmair authorised me to promote you. Have some iron plates for further working shifts. Come back once you are more experienced.")
talkEntry:addConsequence(consequence_item(3109, 1, 333, {["descriptionEn"] = "The owner of this certificate has successfully passed the examination as Journeyman. Thorgrem Silverbeard - Blacksmithing Guild of Galmair", ["descriptionDe"] = "Der Inhaber dieses Gesellenbriefes hat erfolgreich das Examen zum Gesellen bestanden. Thorgrem Silverbeard - Schmiedegilde von Galmair", ["nameDe"] = "Gesellenbrief", ["nameEn"] = "Journeyman's Certificate", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, ">", 39))
talkEntry:addCondition(condition_quest(708, "=", 9))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Journeyman with the Blacksmithing Guild of Galmair. You are awarded twenty iron plates and a journeyman's certificate."))
talkEntry:addConsequence(consequence_item(2537, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 10))
talkEntry:addResponse("The Blacksmithing Guild of Galmair authorised me to promote you. Have some iron plates for further working shifts. Come back once you are more experienced.")
talkEntry:addConsequence(consequence_item(3109, 1, 333, {["descriptionEn"] = "The owner of this certificate has successfully passed the examination as Journeyman. Thorgrem Silverbeard - Blacksmithing Guild of Galmair", ["descriptionDe"] = "Der Inhaber dieses Gesellenbriefes hat erfolgreich das Examen zum Gesellen bestanden. Thorgrem Silverbeard - Schmiedegilde von Galmair", ["nameDe"] = "Gesellenbrief", ["nameEn"] = "Journeyman's Certificate", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, ">", 39))
talkEntry:addCondition(condition_quest(708, "=", 9))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Schmiedegilde von Galmair erhebt dich in den Rang eines Gesellens. Du erhältst zwanzig Eisenplatten und einen Gesellenbrief."))
talkEntry:addConsequence(consequence_item(2537, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 10))
talkEntry:addResponse("Die Schmiedegilde von Galmair hat mich angewiesen, dich zu befördern. Nimm diese Eisenplatten für weitere Arbeitsschichten. Komm erneut zu mir, wenn du erfahrener bist.")
talkEntry:addConsequence(consequence_item(3109, 1, 333, {["descriptionEn"] = "The owner of this certificate has successfully passed the examination as Journeyman. Thorgrem Silverbeard - Blacksmithing Guild of Galmair", ["descriptionDe"] = "Der Inhaber dieses Gesellenbriefes hat erfolgreich das Examen zum Gesellen bestanden. Thorgrem Silverbeard - Schmiedegilde von Galmair", ["nameDe"] = "Gesellenbrief", ["nameEn"] = "Journeyman's Certificate", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, "<", 40))
talkEntry:addCondition(condition_quest(708, "=", 9))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("You are not experienced enough for a promotion with the Blacksmithing Guild of Galmair. Your current rank is Initiate.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 40 in blacksmithing to advance in the ranks of the Blacksmithing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, "<", 40))
talkEntry:addCondition(condition_quest(708, "=", 9))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("You are not experienced enough for a promotion with the Blacksmithing Guild of Galmair. Your current rank is Initiate.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 40 in blacksmithing to advance in the ranks of the Blacksmithing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, "<", 40))
talkEntry:addCondition(condition_quest(708, "=", 9))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Du bist noch nicht erfahren genug, um in der Schmiedegilde von Galmair aufzusteigen. Du hast derzeit den Rang eines Initiatens inne.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 40 in Schmieden um in der Schmiedegilde aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, ">", 49))
talkEntry:addCondition(condition_quest(708, "=", 10))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Specialist with the Blacksmithing Guild of Galmair. You are awarded ten axe handles."))
talkEntry:addConsequence(consequence_item(2525, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 11))
talkEntry:addResponse("The Blacksmithing Guild of Galmair authorised me to promote you. Have some axe handles for further working shifts. Come back once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, ">", 49))
talkEntry:addCondition(condition_quest(708, "=", 10))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Specialist with the Blacksmithing Guild of Galmair. You are awarded ten axe handles."))
talkEntry:addConsequence(consequence_item(2525, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 11))
talkEntry:addResponse("The Blacksmithing Guild of Galmair authorised me to promote you. Have some axe handles for further working shifts. Come back once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, ">", 49))
talkEntry:addCondition(condition_quest(708, "=", 10))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Schmiedegilde von Galmair erhebt dich in den Rang eines Spezialistens. Du erhältst zehn Axtgriffe."))
talkEntry:addConsequence(consequence_item(2525, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 11))
talkEntry:addResponse("Die Schmiedegilde von Galmair hat mich angewiesen, dich zu befördern. Nimm diese Axtgriffe für weitere Arbeitsschichten. Komm erneut zu mir, wenn du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, "<", 50))
talkEntry:addCondition(condition_quest(708, "=", 10))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("You are not experienced enough for a promotion with the Blacksmithing Guild of Galmair. Your current rank is Journeyman.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 50 in blacksmithing to advance in the ranks of the Blacksmithing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, "<", 50))
talkEntry:addCondition(condition_quest(708, "=", 10))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("You are not experienced enough for a promotion with the Blacksmithing Guild of Galmair. Your current rank is Journeyman.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 50 in blacksmithing to advance in the ranks of the Blacksmithing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, "<", 50))
talkEntry:addCondition(condition_quest(708, "=", 10))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Du bist noch nicht erfahren genug, um in der Schmiedegilde von Galmair aufzusteigen. Du hast derzeit den Rang eines Gesellens inne.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 50 in Schmieden um in der Schmiedegilde aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, ">", 59))
talkEntry:addCondition(condition_quest(708, "=", 11))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Expert with the Blacksmithing Guild of Galmair. You are awarded twenty sword handles."))
talkEntry:addConsequence(consequence_item(2584, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 12))
talkEntry:addResponse("The Blacksmithing Guild of Galmair authorised me to promote you. Have some sword handles for further working shifts. Come back once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, ">", 59))
talkEntry:addCondition(condition_quest(708, "=", 11))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Expert with the Blacksmithing Guild of Galmair. You are awarded twenty sword handles."))
talkEntry:addConsequence(consequence_item(2584, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 12))
talkEntry:addResponse("The Blacksmithing Guild of Galmair authorised me to promote you. Have some sword handles for further working shifts. Come back once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, ">", 59))
talkEntry:addCondition(condition_quest(708, "=", 11))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Schmiedegilde von Galmair erhebt dich in den Rang eines Expertens. Du erhältst zwanzig Schwertgriffe."))
talkEntry:addConsequence(consequence_item(2584, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 12))
talkEntry:addResponse("Die Schmiedegilde von Galmair hat mich angewiesen, dich zu befördern. Nimm diese Schwertgriffe für weitere Arbeitsschichten. Komm erneut zu mir, wenn du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, "<", 60))
talkEntry:addCondition(condition_quest(708, "=", 11))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("You are not experienced enough for a promotion with the Blacksmithing Guild of Galmair. Your current rank is Specialist.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 60 in blacksmithing to advance in the ranks of the Blacksmithing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, "<", 60))
talkEntry:addCondition(condition_quest(708, "=", 11))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("You are not experienced enough for a promotion with the Blacksmithing Guild of Galmair. Your current rank is Specialist.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 60 in blacksmithing to advance in the ranks of the Blacksmithing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, "<", 60))
talkEntry:addCondition(condition_quest(708, "=", 11))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Du bist noch nicht erfahren genug, um in der Schmiedegilde von Galmair aufzusteigen. Du hast derzeit den Rang eines Spezialistens inne.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 60 in Schmieden um in der Schmiedegilde aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, ">", 69))
talkEntry:addCondition(condition_quest(708, "=", 12))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Adept with the Blacksmithing Guild of Galmair. You are awarded five pieces of merinium ore."))
talkEntry:addConsequence(consequence_item(2534, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 13))
talkEntry:addResponse("The Blacksmithing Guild of Galmair authorised me to promote you. Have some merinium ore for further working shifts. Come back once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, ">", 69))
talkEntry:addCondition(condition_quest(708, "=", 12))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Adept with the Blacksmithing Guild of Galmair. You are awarded five pieces of merinium ore."))
talkEntry:addConsequence(consequence_item(2534, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 13))
talkEntry:addResponse("The Blacksmithing Guild of Galmair authorised me to promote you. Have some merinium ore for further working shifts. Come back once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, ">", 69))
talkEntry:addCondition(condition_quest(708, "=", 12))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Schmiedegilde von Galmair erhebt dich in den Rang eines Adeptens. Du erhältst fünf Stück Meriniumerz."))
talkEntry:addConsequence(consequence_item(2534, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 13))
talkEntry:addResponse("Die Schmiedegilde von Galmair hat mich angewiesen, dich zu befördern. Nimm dieses Meriniumerz für weitere Arbeitsschichten. Komm erneut zu mir, wenn du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, "<", 70))
talkEntry:addCondition(condition_quest(708, "=", 12))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("You are not experienced enough for a promotion with the Blacksmithing Guild of Galmair. Your current rank is Expert.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 70 in blacksmithing to advance in the ranks of the Blacksmithing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, "<", 70))
talkEntry:addCondition(condition_quest(708, "=", 12))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("You are not experienced enough for a promotion with the Blacksmithing Guild of Galmair. Your current rank is Expert.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 70 in blacksmithing to advance in the ranks of the Blacksmithing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, "<", 70))
talkEntry:addCondition(condition_quest(708, "=", 12))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Du bist noch nicht erfahren genug, um in der Schmiedegilde von Galmair aufzusteigen. Du hast derzeit den Rang eines Expertens inne.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 70 in Schmieden um in der Schmiedegilde aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, ">", 79))
talkEntry:addCondition(condition_quest(708, "=", 13))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Artisan with the Blacksmithing Guild of Galmair. You are awarded ten merinium ingots."))
talkEntry:addConsequence(consequence_item(2571, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 14))
talkEntry:addResponse("The Blacksmithing Guild of Galmair authorised me to promote you. Have some merinium ingots for further working shifts. Come back once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, ">", 79))
talkEntry:addCondition(condition_quest(708, "=", 13))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Artisan with the Blacksmithing Guild of Galmair. You are awarded ten merinium ingots."))
talkEntry:addConsequence(consequence_item(2571, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 14))
talkEntry:addResponse("The Blacksmithing Guild of Galmair authorised me to promote you. Have some merinium ingots for further working shifts. Come back once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, ">", 79))
talkEntry:addCondition(condition_quest(708, "=", 13))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Schmiedegilde von Galmair erhebt dich in den Rang eines Artisanens. Du erhältst zehn Meriniumbarren."))
talkEntry:addConsequence(consequence_item(2571, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 14))
talkEntry:addResponse("Die Schmiedegilde von Galmair hat mich angewiesen, dich zu befördern. Nimm diese Meriniumbarren für weitere Arbeitsschichten. Komm erneut zu mir, wenn du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, "<", 80))
talkEntry:addCondition(condition_quest(708, "=", 13))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("You are not experienced enough for a promotion with the Blacksmithing Guild of Galmair. Your current rank is Adept.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 80 in blacksmithing to advance in the ranks of the Blacksmithing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, "<", 80))
talkEntry:addCondition(condition_quest(708, "=", 13))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("You are not experienced enough for a promotion with the Blacksmithing Guild of Galmair. Your current rank is Adept.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 80 in blacksmithing to advance in the ranks of the Blacksmithing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, "<", 80))
talkEntry:addCondition(condition_quest(708, "=", 13))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Du bist noch nicht erfahren genug, um in der Schmiedegilde von Galmair aufzusteigen. Du hast derzeit den Rang eines Adeptens inne.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 80 in Schmieden um in der Schmiedegilde aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, ">", 89))
talkEntry:addCondition(condition_quest(708, "=", 14))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Master with the Blacksmithing Guild of Galmair. You are awarded five pieces of pure air and a special tool."))
talkEntry:addConsequence(consequence_item(2551, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 15))
talkEntry:addResponse("The Blacksmithing Guild of Galmair authorised me to promote you. Have some pure air for further working shifts. Come back once you are more experienced.")
talkEntry:addConsequence(consequence_item(23, 1, 999, {["descriptionEn"] = "Master of the Blacksmithing Guild of Galmair", ["descriptionDe"] = "Meister der Schmiedegilde von Galmair", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, ">", 89))
talkEntry:addCondition(condition_quest(708, "=", 14))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Master with the Blacksmithing Guild of Galmair. You are awarded five pieces of pure air and a special tool."))
talkEntry:addConsequence(consequence_item(2551, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 15))
talkEntry:addResponse("The Blacksmithing Guild of Galmair authorised me to promote you. Have some pure air for further working shifts. Come back once you are more experienced.")
talkEntry:addConsequence(consequence_item(23, 1, 999, {["descriptionEn"] = "Master of the Blacksmithing Guild of Galmair", ["descriptionDe"] = "Meister der Schmiedegilde von Galmair", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, ">", 89))
talkEntry:addCondition(condition_quest(708, "=", 14))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Schmiedegilde von Galmair erhebt dich in den Rang eines Meisters. Du erhältst fünf Stück reine Luft und ein besonderes Werkzeug."))
talkEntry:addConsequence(consequence_item(2551, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 15))
talkEntry:addResponse("Die Schmiedegilde von Galmair hat mich angewiesen, dich zu befördern. Nimm diese reine Luft für weitere Arbeitsschichten. Komm erneut zu mir, wenn du erfahrener bist.")
talkEntry:addConsequence(consequence_item(23, 1, 999, {["descriptionEn"] = "Master of the Blacksmithing Guild of Galmair", ["descriptionDe"] = "Meister der Schmiedegilde von Galmair", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, "<", 90))
talkEntry:addCondition(condition_quest(708, "=", 14))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("You are not experienced enough for a promotion with the Blacksmithing Guild of Galmair. Your current rank is Artisan.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 90 in blacksmithing to advance in the ranks of the Blacksmithing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, "<", 90))
talkEntry:addCondition(condition_quest(708, "=", 14))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("You are not experienced enough for a promotion with the Blacksmithing Guild of Galmair. Your current rank is Artisan.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 90 in blacksmithing to advance in the ranks of the Blacksmithing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, "<", 90))
talkEntry:addCondition(condition_quest(708, "=", 14))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Du bist noch nicht erfahren genug, um in der Schmiedegilde von Galmair aufzusteigen. Du hast derzeit den Rang eines Artisanens inne.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 90 in Schmieden um in der Schmiedegilde aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, ">", 99))
talkEntry:addCondition(condition_quest(708, "=", 15))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Grandmaster with the Blacksmithing Guild of Galmair. You are awarded ten pieces of pure fire and a grandmaster's medal."))
talkEntry:addConsequence(consequence_item(2553, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 16))
talkEntry:addResponse("Congratulations, you are now a true Grandmaster of the Blacksmithing Guild of Galmair. This pure fire shall help you to manufacture the best goods of Illarion.")
talkEntry:addConsequence(consequence_item(3535, 1, 999, {["descriptionEn"] = "Grandmaster of the Blacksmithing Guild of Galmair", ["descriptionDe"] = "Großmeister der Schmiedegilde von Galmair", ["nameDe"] = "Großmeistermedallie", ["nameEn"] = "Grandmaster's Medal", ["rareness"] = "2"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, ">", 99))
talkEntry:addCondition(condition_quest(708, "=", 15))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Grandmaster with the Blacksmithing Guild of Galmair. You are awarded ten pieces of pure fire and a grandmaster's medal."))
talkEntry:addConsequence(consequence_item(2553, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 16))
talkEntry:addResponse("Congratulations, you are now a true Grandmaster of the Blacksmithing Guild of Galmair. This pure fire shall help you to manufacture the best goods of Illarion.")
talkEntry:addConsequence(consequence_item(3535, 1, 999, {["descriptionEn"] = "Grandmaster of the Blacksmithing Guild of Galmair", ["descriptionDe"] = "Großmeister der Schmiedegilde von Galmair", ["nameDe"] = "Großmeistermedallie", ["nameEn"] = "Grandmaster's Medal", ["rareness"] = "2"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, ">", 99))
talkEntry:addCondition(condition_quest(708, "=", 15))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Schmiedegilde von Galmair erhebt dich in den Rang eines Großmeisters. Du erhältst zehn Stück reines Feuer und eine Großmeistermedallie."))
talkEntry:addConsequence(consequence_item(2553, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(708, "=", 16))
talkEntry:addResponse("Gratulation, du bist nun ein echter Großmeister der Schmiedegilde von Galmair. Dieses reine Feuer soll dir helfen, die besten Waren ganz Illarions herzustellen.")
talkEntry:addConsequence(consequence_item(3535, 1, 999, {["descriptionEn"] = "Grandmaster of the Blacksmithing Guild of Galmair", ["descriptionDe"] = "Großmeister der Schmiedegilde von Galmair", ["nameDe"] = "Großmeistermedallie", ["nameEn"] = "Grandmaster's Medal", ["rareness"] = "2"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, "<", 100))
talkEntry:addCondition(condition_quest(708, "=", 15))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("You are not experienced enough for a promotion with the Blacksmithing Guild of Galmair. Your current rank is Master.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 100 in blacksmithing to advance in the ranks of the Blacksmithing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, "<", 100))
talkEntry:addCondition(condition_quest(708, "=", 15))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("You are not experienced enough for a promotion with the Blacksmithing Guild of Galmair. Your current rank is Master.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 100 in blacksmithing to advance in the ranks of the Blacksmithing Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.blacksmithing, "<", 100))
talkEntry:addCondition(condition_quest(708, "=", 15))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Du bist noch nicht erfahren genug, um in der Schmiedegilde von Galmair aufzusteigen. Du hast derzeit den Rang eines Meisters inne.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 100 in Schmieden um in der Schmiedegilde aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(708, "=", 16))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("All hail Grandmaster %CHARNAME!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(708, "=", 16))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addResponse("All hail Grandmaster %CHARNAME!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(708, "=", 16))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addResponse("Ein Hoch auf Großmeister %CHARNAME!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Get lost. Galmair first!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addResponse("Get lost. Galmair first!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addResponse("Scher dich vom Acker. Galmair zuerst!")
talkingNPC:addTalkingEntry(talkEntry)
end
talkingNPC:addCycleText("#me schaut sich gereizt um.", "#me looks about crankily.")
talkingNPC:addCycleText("#me streicht sich über seinen Bart.", "#me runs a hand over his beard.")
talkingNPC:addCycleText("#me gähnt verhalten.", "#me yawns restrained.")
talkingNPC:addCycleText("Ein Bier! Bringt mir ein Bier!", "A beer, bring me a beer!")
talkingNPC:addCycleText("#me grummelt.", "#me grumbles.")
talkingNPC:addCycleText("#me wirft den Hammer weg und blickt auf den Amboß.", "#me tosses a hammer to the ground and looks at the anvil.")
talkingNPC:addCycleText("Arr! Es gibt nichts Besseres als Schmieden.", "Arrr! There isn't anything better than blacksmithing.")
talkingNPC:addCycleText("#me untersucht die Qualität eines Eisenbarrens.", "#me examines the quality of an iron ingot.")
talkingNPC:addCycleText("#mes Kleidung ist voller Metallspäne.", "#me's clothes are covered in metal shards.")
talkingNPC:addCycleText("Mit diesem Hammer kann ich alles schmieden.", "With this hammer I can make anything.")
talkingNPC:addCycleText("Tritt der Schmiedegilde von Galmair bei!", "Join the blacksmithing guild of Galmair!")
mainNPC:addLanguage(0)
mainNPC:addLanguage(2)
mainNPC:setDefaultLanguage(0)
mainNPC:setLookat("Dieser NPC ist Thorgrem Silverbeard der Schmied.", "This NPC is Thorgrem Silverbeard the blacksmith.")
mainNPC:setUseMessage("Fass mich nicht an!", "Hands off!")
mainNPC:setConfusedMessage("#me schaut dich verwirrt an.", "#me looks at you confused.")
mainNPC:setEquipment(1, 358)
mainNPC:setEquipment(3, 2360)
mainNPC:setEquipment(11, 0)
mainNPC:setEquipment(5, 23)
mainNPC:setEquipment(6, 0)
mainNPC:setEquipment(4, 0)
mainNPC:setEquipment(9, 825)
mainNPC:setEquipment(10, 698)
mainNPC:setAutoIntroduceMode(true)

mainNPC:initDone()
return mainNPC
end
local mNPC = initNpc()
initNpc = nil
local M = {}
function M.receiveText(npcChar, texttype, message, speaker) mNPC:receiveText(npcChar, texttype, speaker, message) end
function M.nextCycle(npcChar) mNPC:nextCycle(npcChar) end
function M.lookAtNpc(npcChar, char, mode) mNPC:lookAt(npcChar, char, mode) end
function M.useNPC(npcChar, char, counter, param) mNPC:use(npcChar, char) end
return M
