local consequence_trade = require("npc.base.consequence.trade")
local condition_language = require("npc.base.condition.language")
local basic = require("npc.base.basic")
local trade = require("npc.base.trade")
local talk = require("npc.base.talk")
local consequence_inform = require("npc.base.consequence.inform")
local function initNpc()
local mainNPC = basic()
mainNPC:setAffiliation(2)
local talkingNPC = talk(mainNPC)
local tradingNPC = trade(mainNPC)
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Help")
talkEntry:addConsequence(consequence_inform("[Game Help] This NPC is the tailor Timotheus. Keywords: sell, buy, trade, Hello, tailor."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hilfe")
talkEntry:addConsequence(consequence_inform("[Spielhilfe] Dieser NPC ist der Schneider Timotheus. Schlüsselwörter: kaufe, verkaufe, Handel, Hallo, Schneider."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("sell")
talkEntry:addTrigger("buy")
talkEntry:addTrigger("wares")
talkEntry:addTrigger("price")
talkEntry:addTrigger("trade")
talkEntry:addTrigger("purchase")
talkEntry:addResponse("Best tailored goods.")
talkEntry:addResponse("Take your time to chose what you like.")
talkEntry:addConsequence(consequence_trade(tradingNPC))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("kauf")
talkEntry:addTrigger("waren")
talkEntry:addTrigger("preis")
talkEntry:addTrigger("Handel")
talkEntry:addTrigger("veräußer")
talkEntry:addTrigger("veräusser")
talkEntry:addTrigger("erwerb")
talkEntry:addResponse("Beste Schneiderwaren.")
talkEntry:addResponse("Sucht euch einfach etwas aus.")
talkEntry:addConsequence(consequence_trade(tradingNPC))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hello")
talkEntry:addTrigger("Greet")
talkEntry:addTrigger("Hail")
talkEntry:addTrigger("Good day")
talkEntry:addTrigger("Good morning")
talkEntry:addTrigger("Good evening")
talkEntry:addTrigger("Good night")
talkEntry:addResponse("Welcome wise one.")
talkEntry:addResponse("Why, greetings to you!")
talkEntry:addResponse("Greetings elevated one.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Grüß")
talkEntry:addTrigger("Gruß")
talkEntry:addTrigger("Grüss")
talkEntry:addTrigger("Gruss")
talkEntry:addTrigger("Guten Morgen")
talkEntry:addTrigger("Guten Tag")
talkEntry:addTrigger("Guten Abend")
talkEntry:addTrigger("Gute Nacht")
talkEntry:addTrigger("Mahlzeit")
talkEntry:addTrigger("Tach")
talkEntry:addTrigger("Moin")
talkEntry:addTrigger("Mohltied")
talkEntry:addResponse("Willkommen, mein weiser Freund.")
talkEntry:addResponse("Wie jetzt, seid gegrüßt!")
talkEntry:addResponse("Grüße, mein Großer.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Hiho")
talkEntry:addTrigger("Hallo")
talkEntry:addTrigger("Hey")
talkEntry:addTrigger("Greeb")
talkEntry:addResponse("Please don't be so informal!")
talkEntry:addResponse("Well... Greetings.")
talkEntry:addResponse("Is that the way people talk on the street nowadays?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hiho")
talkEntry:addTrigger("Hallo")
talkEntry:addTrigger("Hey")
talkEntry:addTrigger("Greeb")
talkEntry:addResponse("Na, nicht so schnodderig.")
talkEntry:addResponse("Nun... seid gegrüßt.")
talkEntry:addResponse("Redet man heutzutage so auf der Straße?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Farewell")
talkEntry:addTrigger("Bye")
talkEntry:addTrigger("Fare well")
talkEntry:addTrigger("See you")
talkEntry:addResponse("May Elara protect your knowledge!")
talkEntry:addResponse("Insightful journey to you!")
talkEntry:addResponse("Farewell now!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Tschüß")
talkEntry:addTrigger("Tschüss")
talkEntry:addTrigger("Wiedersehen")
talkEntry:addTrigger("Gehab wohl")
talkEntry:addResponse("Möge Elara eure Weisheit bewahren.")
talkEntry:addResponse("Eine aufschlussreiche Reise wünsche ich.")
talkEntry:addResponse("Gehabt euch wohl.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Ciao")
talkEntry:addTrigger("Adieu")
talkEntry:addTrigger("Au revoir")
talkEntry:addResponse("Trying to charming me, eh? Farewell then!")
talkEntry:addResponse("The courtesies certainly haven't left you!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Ciao")
talkEntry:addTrigger("Adieu")
talkEntry:addTrigger("Au revoir")
talkEntry:addResponse("Ihr wollt mir wohl schmeicheln. Gute Reise!")
talkEntry:addResponse("Eure Anstandsformen haben euch offensichtlich noch nicht verlassen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("How are you")
talkEntry:addTrigger("How feel")
talkEntry:addTrigger("How do you do")
talkEntry:addResponse("I'm feeling wonderful, thank you.")
talkEntry:addResponse("Great! Did you know the library has books about famous tailors? Amazing literature.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Wie geht")
talkEntry:addTrigger("Wie fühlst")
talkEntry:addTrigger("Wie ist es ergangen")
talkEntry:addResponse("Mir geht es wunderbar, danke.")
talkEntry:addResponse("Großartig! Wußtet ihr, dass es in der Bibliothek Bücher über berühmte Schneider gibt? Spannende Lektüre, muss ich sagen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("your name")
talkEntry:addTrigger("who are you")
talkEntry:addTrigger("who art thou")
talkEntry:addResponse("I am Timotheus.")
talkEntry:addResponse("Why, Timotheus of course!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("ihr name")
talkEntry:addTrigger("dein name")
talkEntry:addTrigger("wer bist du")
talkEntry:addTrigger("wer seid ihr")
talkEntry:addTrigger("wie heißt")
talkEntry:addTrigger("wie heisst")
talkEntry:addResponse("Ich bin Timotheus.")
talkEntry:addResponse("Wie jetzt, Timotheus natürlich!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("quest")
talkEntry:addResponse("I only sell goods, my apologies. Quests are for the courageous and the empty headed.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("quest")
talkEntry:addResponse("Ich bin nur ein Händler, entschuldigt. Abenteuer sind für die mutigen und törichten.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addResponse("Adventures? I'm pretty happy with my robes thank you.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addResponse("Abenteuer? Ich bin ziemlich glücklich mit meinen Roben, danke.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("profession")
talkEntry:addResponse("I am a tailor. I sell tailor goods, and even make some myself!")
talkEntry:addResponse("Profession, my life, whatever you prefer, it's tailoring!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("beruf")
talkEntry:addResponse("Ich bin ein Schneider. Ich verkaufe Schneiderwaren und mache auch welche für mich selbst.")
talkEntry:addResponse("Mein Beruf, ja, mein Leben, das ist die Schneiderei.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("job")
talkEntry:addResponse("I am a tailor. I sell tailor goods, and even make some myself!")
talkEntry:addResponse("Profession, my life, whatever you prefer, it's tailoring!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("job")
talkEntry:addResponse("Ich bin ein Schneider. Ich verkaufe Schneiderwaren und mache auch welche für mich selbst.")
talkEntry:addResponse("Mein Beruf, ja, mein Leben, das ist die Schneiderei.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Gobaith")
talkEntry:addTrigger("Gobiath")
talkEntry:addResponse("Gobaith? No one goes there anymore man! It's a shadow of it's former glory.")
talkEntry:addResponse("Ah that's right! All these Gobaithian refugees...")
talkEntry:addResponse("That good old island isn't much anymore is it?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Gobaith")
talkEntry:addTrigger("Gobiath")
talkEntry:addResponse("Gobaith? Da wagt sich niemand mehr hin. Es ist nur noch ein Schatten längst vergangenen Ruhmes.")
talkEntry:addResponse("Ja, genau! All diese Flüchtlinge aus Gobaith...")
talkEntry:addResponse("Die gute alte Insel gibt es nicht mehr, richtig?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("my name")
talkEntry:addResponse("And I am Timotheus. Ti-mo-the-us.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("mein Name")
talkEntry:addResponse("Und ich bin Timotheus. Ti-mo-the-us.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("tailor")
talkEntry:addResponse("Tailoring is an underestimated craft. A robe can tell a tale, of great adventures and wisdom.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Schneider")
talkEntry:addResponse("Die Schneiderei ist ein unterschätztes Handwerk. Eine Robe kann eine ganze Geschichte von Abenteuern und Weisheit erzählen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("location")
talkEntry:addResponse("Why, you are in Runewick of course, where else.")
talkEntry:addResponse("The place to be in Runewick, at the tailor!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Ort")
talkEntry:addResponse("Wie jetzt, ihr seid natürlich in Runewick.")
talkEntry:addResponse("Der Platz schlechthin, Runewick beim Schneider.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("trader")
talkEntry:addTrigger("merchant")
talkEntry:addTrigger("collegue")
talkEntry:addTrigger("vendor")
talkEntry:addTrigger("market")
talkEntry:addResponse("Well of course there is Francois. He sells the goods all the farmers have been working for on the fields.")
talkEntry:addResponse("Wise old William, he sells all the goods for your studies late at night.")
talkEntry:addResponse("Alysa over there is the finest cook there has been in a long time.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("händler")
talkEntry:addTrigger("kollege")
talkEntry:addTrigger("höker")
talkEntry:addTrigger("markt")
talkEntry:addResponse("Nun, da gibt es Francois. Er handelt mit all dem, was Bauern auf den Feldern bestellt haben.")
talkEntry:addResponse("Der alte, weise William wird euch alles verkaufen, was ihr bei nächtlichen Studien benötigt.")
talkEntry:addResponse("Alysa dort drüben ist der beste Köchin weit und breit.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Timmy")
talkEntry:addResponse("I am not living a lie!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Timmy")
talkEntry:addResponse("Ich lebe keine Lüge!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Archmage")
talkEntry:addResponse("He is a brilliant, BRILLIANT man.")
talkEntry:addResponse("If he wasn't here... I just wouldn't know what would happen with Runewick. Runewick wouldn't flourish like it does today.")
talkEntry:addResponse("Rather restrained, isn't he?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Erzmagier")
talkEntry:addResponse("Er ist ein brillianter, ich sage, brillianter Mann.")
talkEntry:addResponse("Wenn es ihn nicht gäbe... Ich kann mir gar nicht ausmalen, was dann aus Runewick werden würde. Es würde nicht so florieren wie heute, so viel ist sicher.")
talkEntry:addResponse("Er wirkt ziemlich reserviert, nicht wahr?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Elvaine")
talkEntry:addTrigger("Morgan")
talkEntry:addResponse("He is a brilliant, BRILLIANT man.")
talkEntry:addResponse("If he wasn't here... I just wouldn't know what would happen with Runewick. Runewick wouldn't flourish like it does today.")
talkEntry:addResponse("Rather restrained, isn't he?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Elvaine")
talkEntry:addTrigger("Morgan")
talkEntry:addResponse("Er ist ein brillianter, ich sage, brillianter Mann.")
talkEntry:addResponse("Wenn es ihn nicht gäbe... Ich kann mir gar nicht ausmalen, was dann aus Runewick werden würde. Es würde nicht so florieren wie heute, so viel ist sicher.")
talkEntry:addResponse("Er wirkt ziemlich reserviert, nicht wahr?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Runewick")
talkEntry:addResponse("The finest city in the land, that's for sure.")
talkEntry:addResponse("Power through knowledge, that's the motto!")
talkEntry:addResponse("The south-eastern jewel, that's what it is.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Runewick")
talkEntry:addResponse("Die beste Stadt weit und weit, so viel steht fest.")
talkEntry:addResponse("Wissen ist Macht, das ist das Motto!")
talkEntry:addResponse("Das Juwel des Südwesten, das ist es.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Don")
talkEntry:addTrigger("Valerio")
talkEntry:addTrigger("Guilianni")
talkEntry:addResponse("I'm not sure what to think of him. His morals are certainly on the wrong side of a pig.")
talkEntry:addResponse("Money money money, that's all I hear in my head when I hear that name.")
talkEntry:addResponse("Valerio Pighead is his name if you ask me.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Don")
talkEntry:addTrigger("Valerio")
talkEntry:addTrigger("Guilianni")
talkEntry:addResponse("Ich weiß nicht recht, was ich von ihm halten soll. Seine Moralvorstellungen ähneln dem Hinterteil eines Schweines.")
talkEntry:addResponse("Geld, Geld, Geld, das ist alles, was mir bei dem Namen in den Kopf kommt.")
talkEntry:addResponse("Valerio Schweinskopf ist sein Name, wenn ihr mich fragt.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Galmair")
talkEntry:addResponse("About as bad as it's rules I guess.")
talkEntry:addResponse("Built upon the corpses of those with fewer financial reserves.")
talkEntry:addResponse("I heard Galmair is ruled by merchants. I say: Ruled by pigs!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Galmair")
talkEntry:addResponse("Es ist genauso schlecht dort wie die dortigen Regeln.")
talkEntry:addResponse("Gebaut auf den Leichen derer, die über kein ausreichendes Finanzpolster verfügen.")
talkEntry:addResponse("Ich habe gehört, Galmair wird von Händlern dominiert. Ich sage: Es wird von Schweinen beherrscht.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("queen")
talkEntry:addResponse("Queen Rosaline, queen Rosaline. Honourable woman, but not the smartest in her class.")
talkEntry:addResponse("She should spend more time reading books instead of boasting.")
talkEntry:addResponse("The archmage is right to distrust her.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Königin")
talkEntry:addResponse("Queen Rosaline, queen Rosaline. Honourable woman, but not the smartest in her class.")
talkEntry:addResponse("She should spend more time reading books instead of boasting.")
talkEntry:addResponse("The archmage is right to distrust her.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Rosaline")
talkEntry:addTrigger("Edwards")
talkEntry:addResponse("Queen Rosaline, queen Rosaline. Honourable woman, but not the smartest in her class.")
talkEntry:addResponse("She should spend more time reading books instead of boasting.")
talkEntry:addResponse("The archmage is right to distrust her.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Rosaline")
talkEntry:addTrigger("Edwards")
talkEntry:addResponse("Königin Rosaline, Königin Rosaline. Eine ehrbare Frau, aber nicht gerade die schlauste ihrer Art.")
talkEntry:addResponse("Sie sollte mal mehr Zeit mit Büchern als mit ihren Prahlereien verbringen.")
talkEntry:addResponse("Ich denke, der Erzmagier tut gut daran, ihr nicht zu trauen.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Cadomyr")
talkEntry:addResponse("Beautiful city I guess, too bad the inhabitants are airheads.")
talkEntry:addResponse("I bet they have awfully empty libraries.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Cadomyr")
talkEntry:addResponse("Eine schöne Stadt, so denke ich, aber ihre Einwohner sind hirnverbrannt.")
talkEntry:addResponse("Ich schätze, sie haben dort eine schrecklich leere Bibliothek.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("albar")
talkEntry:addResponse("Sir Reginald of Cadomyr owned land in Albar I believe.")
talkEntry:addResponse("Strange customs, those albarians.")
talkEntry:addResponse("Isn't that somewhere at the end of the Aramon mountains?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("albar")
talkEntry:addResponse("Ich glaube zu wissen, dass Sir Reginald von Cadomyr Land in Albar besessen hat.")
talkEntry:addResponse("Merkwürdige Sitten haben sie, die Albarier.")
talkEntry:addResponse("Ist das nicht irgendwo am Ende der Aramonberge?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("gynk")
talkEntry:addTrigger("gync")
talkEntry:addResponse("Lawless pigs, that's what they are.")
talkEntry:addResponse("Surrounded by pirate islands. Doesn't surprise me!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("gync")
talkEntry:addTrigger("gynk")
talkEntry:addResponse("Ruchlose Schweine, das sind sie.")
talkEntry:addResponse("Umgeben von Pirateninseln, mich überrascht gar nichts mehr.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("salkama")
talkEntry:addResponse("Above the Middle Mountains. Beautiful city, truely it is!")
talkEntry:addResponse("Archmage Morgan came from Salkamar, did you know that?")
talkEntry:addResponse("Oh how I long for it's streets.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("salkama")
talkEntry:addResponse("Oberhalb der Mittelberge - eine schöne Stadt, das ist es wahrhaftig.")
talkEntry:addResponse("Erzmagier Morgan stammt aus Salkamar, wußtet ihr das?")
talkEntry:addResponse("Oh, wie ich mich nach den Gassen von Salkamar sehne.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("god")
talkEntry:addResponse("I worship Irmorom and Elara - two gods are enough for one halfling!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Gott")
talkEntry:addTrigger("Götter")
talkEntry:addResponse("Ich bete zu Irmorom und Elara - zwei Götter müssen für einen Halbling reichen!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Elara")
talkEntry:addResponse("Elara brings us all knowledge. At least, that is what I believe.")
talkEntry:addResponse("Elara's blessings elevated one.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Elara")
talkEntry:addResponse("Elara gewährt uns all unser Wissen - daran glaube ich fest.")
talkEntry:addResponse("Elaras Segen, mein Großer.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Irmorom")
talkEntry:addResponse("Only dwarves really pray to Irmorom. Everyone else takes what he grants for granted, as it seems.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Irmorom")
talkEntry:addResponse("Nur Zwerge beten wirklich zu Irmorom. Anscheinend nimmt Jedermann seine Gaben als selbstverständlich hin.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("tell something")
talkEntry:addResponse("Did you know only we from Runewick have such marvellous clothing? I wonder what rags the people of Galmair wear.")
talkEntry:addResponse("My robes are the finest in the land!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("erzähl was")
talkEntry:addTrigger("erzähl etwas")
talkEntry:addResponse("Wußtet ihr, dass nur wir in Runewick hier so feine Kleidung haben? Ich frage mich, in was für Lumpen die Leute in Galmair rumrennen.")
talkEntry:addResponse("Meine Roben sind die besten im ganzen Land.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Timotheus")
talkEntry:addResponse("Yes, I am Timotheus. Ti-mo-the-us.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Timotheus")
talkEntry:addResponse("Ja, ich bin Timotheus. Ti-mo-the-us.")
talkingNPC:addTalkingEntry(talkEntry)
end
talkingNPC:addCycleText("Die feinsten Roben, Westen und Hemden! Niemals mehr wie ein Landstreicher herumlaufen!", "The finest robes, vests, shirts! Never be deemed a tramp again!")
talkingNPC:addCycleText("#me streicht seine blaue Satinrobe glatt. Orangene Stickereien zieren die Ärmel.", "#me straightens his blue satin robes. They are adorned with orange filigree on each sleeve.")
talkingNPC:addCycleText("#me schaut sich kurz um und wendet sich dann wieder einem Buch zu.", "#me looks around for a moment before returning to his book.")
talkingNPC:addCycleText("#me blättert eine Seite seines Buches um.", "#me turns a page of his book.")
talkingNPC:addCycleText("#me kichert auf einmal: 'Oh, entschuldigt. Der Mann, der dies hier schrieb, ist einfach brilliant.", "#me suddenly giggles: 'Oh, my apologies. The man who wrote this is simply brilliant.'")
talkingNPC:addCycleText("#me murmelt vor sich hin: '...und so verließ Mesha Gobblesworth den Rat nach seinem Wutanfall. Er würde nicht mehr sehen, wie...'. Er verstummt anschließend.", "#me begins to mumble: '...and so Mesha Gobblesworth left the council after an outburst of aggression. He wouldn't see...'. He turns silent again.")
talkingNPC:addCycleText("Heda! Eure Kleidung sieht schäbig aus, ich hätte da was passenderes.", "You! Your outfit looks terrible! I have something more fitting for you.")
talkingNPC:addCycleText("Ich habe die besten Umhänge weit und breit. Kauft oder gebt der Hässlichkeit das Ja-Wort!", "I have the best cloaks around. Buy them or say Yes to ugliness , it is up to you!")
talkingNPC:addCycleText("Satin! Brokat! Seide! Leinen!", "Satin! Brocade! Silk! Linen!")
talkingNPC:addCycleText("Ihr da! Einer meiner Hüte würde eurem Kopf gut tun. Schlimmer kanns ja nicht mehr werden...", "You! A hat of mine would suit your head particularly well. Can't get any worse than now...")
tradingNPC:addItem(trade.tradeNPCItem(47,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(58,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2781,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(6,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2746,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(4337,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1500,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(369,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1501,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1502,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(53,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1503,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1504,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1447,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2295,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1448,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1449,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1450,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(809,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(813,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(810,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(812,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(811,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(808,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(807,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(802,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(806,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(803,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(804,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1478,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(367,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1479,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1480,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(366,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1481,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1482,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(356,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(830,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1415,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(831,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(832,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(829,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(828,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1416,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(7,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1417,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1418,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1419,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1420,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1453,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(384,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(48,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1454,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(526,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1455,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1456,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(97,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2760,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(89,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(196,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2418,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2421,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(55,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(194,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2378,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2384,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2420,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(547,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2419,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2377,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(195,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(368,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(457,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(182,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(180,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(458,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(181,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(841,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(842,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(844,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(843,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(840,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(839,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1433,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(363,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1434,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2407,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(365,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1435,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(1436,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2399,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(823,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(827,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(824,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(183,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(826,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(34,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(459,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(825,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(460,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(816,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(820,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(817,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(819,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(818,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(815,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(814,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(176,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(175,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(179,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(54,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(174,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(178,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(177,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2678,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2680,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2679,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2681,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2683,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2682,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2586,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(69,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(2547,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(170,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(50,"sell"))
tradingNPC:addItem(trade.tradeNPCItem(4337,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1500,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(369,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1501,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1502,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(53,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1503,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1504,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(697,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1505,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(698,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1506,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1447,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2295,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1448,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1449,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1450,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1451,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1452,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(809,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(813,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(810,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(812,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(811,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(808,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(807,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(802,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(806,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(803,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(805,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(800,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(385,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(804,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(801,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(833,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(836,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(835,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(837,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(838,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(834,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(851,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(845,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(846,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(850,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(849,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(852,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(847,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(848,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1478,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(367,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1479,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1480,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(366,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1481,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1482,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2114,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1483,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2113,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1484,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(356,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(830,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1415,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(831,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(832,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(829,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(828,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(358,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(357,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(3868,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(370,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(3708,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(371,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1416,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(7,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1417,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1418,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1419,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1420,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1421,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1422,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1423,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1424,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1453,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(384,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(48,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1454,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(526,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1455,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1456,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1457,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(527,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1458,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1459,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2760,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(89,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(196,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2418,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2421,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(55,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(194,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2378,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2384,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2420,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(547,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2419,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2377,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(195,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(368,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2416,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(193,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2380,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(548,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(558,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(457,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(182,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(180,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(458,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(181,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(841,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(842,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(844,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(843,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(840,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(839,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1433,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(363,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1434,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2407,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(365,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1435,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1436,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2399,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2357,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(364,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(362,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(1437,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(823,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(827,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(824,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(183,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(826,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(34,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(459,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(825,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(460,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(822,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(461,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(821,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(816,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(820,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(817,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(819,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(818,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(815,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(814,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(176,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(175,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(179,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(54,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(174,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(178,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(177,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2678,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2680,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2679,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2681,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2683,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2682,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2586,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(69,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(2547,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(170,"buySecondary"))
tradingNPC:addItem(trade.tradeNPCItem(50,"buySecondary"))
tradingNPC:addNotEnoughMoneyMsg("Ich verkaufe nur gegen Geld.", "I only sell goods for money.")
tradingNPC:addDialogClosedMsg("Das hat sich doch gelohnt.", "That was worth it.")
tradingNPC:addDialogClosedNoTradeMsg("Och menno.", "C'mon!")
tradingNPC:addWrongItemMsg("Das kaufe ich nicht.", "I won't buy that.")
mainNPC:addLanguage(0)
mainNPC:addLanguage(6)
mainNPC:setDefaultLanguage(0)
mainNPC:setLookat("Dieser NPC ist der Schneider Timotheus.", "This NPC is the tailor Timotheus.")
mainNPC:setUseMessage("Fass mich nicht an!", "Do not touch me!")
mainNPC:setConfusedMessage("#me schaut dich verwirrt an.", "#me looks at you confused.")
mainNPC:setEquipment(1, 0)
mainNPC:setEquipment(3, 811)
mainNPC:setEquipment(11, 193)
mainNPC:setEquipment(5, 47)
mainNPC:setEquipment(6, 0)
mainNPC:setEquipment(4, 2295)
mainNPC:setEquipment(9, 367)
mainNPC:setEquipment(10, 369)
mainNPC:setAutoIntroduceMode(true)

mainNPC:initDone()
return mainNPC
end
local mNPC = initNpc()
initNpc = nil
local M = {}
function M.receiveText(npcChar, texttype, message, speaker) mNPC:receiveText(npcChar, texttype, speaker, message) end
function M.nextCycle(npcChar) mNPC:nextCycle(npcChar) end
function M.lookAtNpc(npcChar, char, mode) mNPC:lookAt(npcChar, char, mode) end
function M.useNPC(npcChar, char, counter, param) mNPC:use(npcChar, char) end
return M
