local consequence_item = require("npc.base.consequence.item")
local condition_item = require("npc.base.condition.item")
local consequence_quest = require("npc.base.consequence.quest")
local condition_skill = require("npc.base.condition.skill")
local condition_language = require("npc.base.condition.language")
local consequence_deleteitem = require("npc.base.consequence.deleteitem")
local basic = require("npc.base.basic")
local condition_town = require("npc.base.condition.town")
local talk = require("npc.base.talk")
local consequence_money = require("npc.base.consequence.money")
local condition_quest = require("npc.base.condition.quest")
local consequence_inform = require("npc.base.consequence.inform")
local function initNpc()
local mainNPC = basic()
mainNPC:setAffiliation(3)
local talkingNPC = talk(mainNPC)
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Help")
talkEntry:addConsequence(consequence_inform("[Game Help] This NPC is Tony Spirotelli the finesmith. Keywords: Hello, quest, finesmithing."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hilfe")
talkEntry:addConsequence(consequence_inform("[Spielhilfe] Dieser NPC ist Tony Spirotelli der Feinschmied. Schlüsselwörter: Hallo, Quest, Feinschmieden."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hello")
talkEntry:addTrigger("Greet")
talkEntry:addTrigger("Hail")
talkEntry:addTrigger("Good day")
talkEntry:addTrigger("Good morning")
talkEntry:addTrigger("Good Evening")
talkEntry:addResponse("Hello, what do you need?")
talkEntry:addResponse("Good day, what do you need?")
talkEntry:addResponse("I'm Tony Spirotelli, what can I do for you?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Grüß")
talkEntry:addTrigger("Gruß")
talkEntry:addTrigger("Grüss")
talkEntry:addTrigger("Gruss")
talkEntry:addTrigger("Guten Morgen")
talkEntry:addTrigger("Guten Tag")
talkEntry:addTrigger("Guten Abend")
talkEntry:addTrigger("Gute Nacht")
talkEntry:addTrigger("Mahlzeit")
talkEntry:addTrigger("Tach")
talkEntry:addTrigger("Moin")
talkEntry:addTrigger("Mohltied")
talkEntry:addResponse("Hallo, was brauchst du?")
talkEntry:addResponse("Guten Tag, was willst du?")
talkEntry:addResponse("Ich bin Tony Spirotelli, was kann ich für dich tun?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Hiho")
talkEntry:addTrigger("Hallo")
talkEntry:addTrigger("Hey")
talkEntry:addTrigger("Greeb")
talkEntry:addResponse("Hello, what do you need?")
talkEntry:addResponse("Good day, what do you need?")
talkEntry:addResponse("I'm Tony Spirotelli, what can I do for you?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hiho")
talkEntry:addTrigger("Hallo")
talkEntry:addTrigger("Hey")
talkEntry:addTrigger("Greeb")
talkEntry:addResponse("Hallo, was brauchst du?")
talkEntry:addResponse("Guten Tag, was willst du?")
talkEntry:addResponse("Ich bin Tony Spirotelli, was kann ich für dich tun?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Farewell")
talkEntry:addTrigger("Bye")
talkEntry:addTrigger("Fare well")
talkEntry:addTrigger("See you")
talkEntry:addResponse("#me chuckles, 'I'll be seeing you again I hope.'")
talkEntry:addResponse("Aye... another time.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Tschüß")
talkEntry:addTrigger("Tschüss")
talkEntry:addTrigger("Wiedersehen")
talkEntry:addResponse("#me lacht: 'Wir werden uns wiedersehen, da bin ich mir sicher.'")
talkEntry:addResponse("Ja, bis zum nächsten mal.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Ciao")
talkEntry:addTrigger("Adieu")
talkEntry:addTrigger("Au revoir")
talkEntry:addTrigger("Farebba")
talkEntry:addResponse("#me chuckles, 'I'll be seeing you again I hope.'")
talkEntry:addResponse("Aye... another time.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Ciao")
talkEntry:addTrigger("Adieu")
talkEntry:addTrigger("Au revoir")
talkEntry:addTrigger("Farebba")
talkEntry:addResponse("#me lacht: 'Wir werden uns wiedersehen, da bin ich mir sicher.'")
talkEntry:addResponse("Ja, bis zum nächsten mal.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("How are you")
talkEntry:addTrigger("How feel")
talkEntry:addTrigger("How do you do")
talkEntry:addResponse("I feel fine, I'm a finemsmith. Funny, eh?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Wie geht")
talkEntry:addTrigger("Wie fühlst")
talkEntry:addTrigger("Wie ist es ergangen")
talkEntry:addTrigger("Wie Befind")
talkEntry:addResponse("Mir geht es fein, denn ich bin ein Feinschmied. Lustig, oder?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("your name")
talkEntry:addTrigger("who are you")
talkEntry:addTrigger("who art thou")
talkEntry:addResponse("I'm Tony Spirotelli, who are you?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("ihr name")
talkEntry:addTrigger("dein name")
talkEntry:addTrigger("wer bist du")
talkEntry:addTrigger("wer seid ihr")
talkEntry:addTrigger("wie heißt")
talkEntry:addTrigger("wie heisst")
talkEntry:addResponse("Ich bin Tony Spirotelli, wer bist du?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("sell")
talkEntry:addTrigger("buy")
talkEntry:addTrigger("wares")
talkEntry:addTrigger("price")
talkEntry:addTrigger("trade")
talkEntry:addTrigger("purchase")
talkEntry:addResponse("I am not a trader.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("kauf")
talkEntry:addTrigger("waren")
talkEntry:addTrigger("preis")
talkEntry:addTrigger("Handel")
talkEntry:addTrigger("veräußer")
talkEntry:addTrigger("veräusser")
talkEntry:addTrigger("erwerb")
talkEntry:addResponse("Ich bin doch kein Händler.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("profession")
talkEntry:addResponse("I am an important member of the Finesmithing Syndicate.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("beruf")
talkEntry:addResponse("Ich bin ein wichtiges Mitglied des Feinschmiedesyndikates.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("job")
talkEntry:addResponse("I am an important member of the Finesmithing Syndicate.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("job")
talkEntry:addResponse("Ich bin ein wichtiges Mitglied des Feinschmiedesyndikates.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("smith")
talkEntry:addTrigger("craft")
talkEntry:addResponse("For finesmithing, you'll need noble metal ingots and a finesmithing hammer. Don't use the hammer of a blacksmith or an armourer.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("schmied")
talkEntry:addTrigger("Handwerk")
talkEntry:addResponse("Zum Feinschmieden wirst du Edelmetallbarren und einen Feinschmiedehammer brauchen. Benutz bloß nicht den Hammer eines ordinären Schmiedes oder eines Rüstschmiedes.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(710, "=", 0))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_item(2763, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 1))
talkEntry:addResponse("So you fancy a career with the Finemsmithing Syndicate? Let's have a deal, you get this rusty pick-axe and you show me you are worth my time. Get ten lumps of coal and ten pieces of copper ore from the local mines and I'll teach you the ropes.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Finesmithing Syndicate of Galmair I. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(710, "=", 0))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_item(2763, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 1))
talkEntry:addResponse("So you fancy a career with the Finemsmithing Syndicate? Let's have a deal, you get this rusty pick-axe and you show me you are worth my time. Get ten lumps of coal and ten pieces of copper ore from the local mines and I'll teach you the ropes.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Finesmithing Syndicate of Galmair I. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(710, "=", 0))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addConsequence(consequence_item(2763, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 1))
talkEntry:addResponse("So, du denkst also, du kannst eine große Nummer im Feinschmiedesyndikat werden? Hier ist der Deal: Du kriegst diese rostige Spitzhacke und zeigst mir, dass du meine Zeit wert bist. Besorge zehn Klumpen Kohle und zehn Stück Eisenerz aus den nahegelegenen Minen und ich zeig dir, wo der Hase langläuft.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Das Feinschmiedesyndikat von Galmair I. Detaillierte Informationen findest du im Questlog (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(710, "=", 1))
talkEntry:addCondition(condition_item(21, "all", ">", 9, nil))
talkEntry:addCondition(condition_item(2536, "all", ">", 9, nil))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_quest(710, "=", 2))
talkEntry:addResponse("Very well, looks like you can tell rocks and copper ore apart. You'll need the resources for your next task.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Ask Tony Spirotelli for your next task."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(710, "=", 1))
talkEntry:addCondition(condition_item(21, "all", ">", 9, nil))
talkEntry:addCondition(condition_item(2536, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("coal")
talkEntry:addTrigger("copper")
talkEntry:addConsequence(consequence_quest(710, "=", 2))
talkEntry:addResponse("Very well, looks like you can tell rocks and copper ore apart. You'll need the resources for your next task.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Ask Tony Spirotelli for your next task."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(710, "=", 1))
talkEntry:addCondition(condition_item(21, "all", ">", 9, nil))
talkEntry:addCondition(condition_item(2536, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("kohle")
talkEntry:addTrigger("Kupfer")
talkEntry:addConsequence(consequence_quest(710, "=", 2))
talkEntry:addResponse("Bestens, du kannst Kupfererz von Steinen unterscheiden. Du wirst die Ressourcen für deine nächste Aufgabe brauchen.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Frage Tony Spirotelli nach deiner nächsten Aufgaben."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(710, "=", 1))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Without copper ore and coal, you won't get anywhere with the Finesmithing Syndicate.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(710, "=", 1))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("coal")
talkEntry:addTrigger("copper")
talkEntry:addResponse("Without copper ore and coal, you won't get anywhere with the Finesmithing Syndicate.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(710, "=", 1))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("kohle")
talkEntry:addTrigger("Kupfer")
talkEntry:addResponse("Ohne Kupfererz und Kohle wird's nichts mit dir und dem Feinschmiedesyndikat.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(710, "=", 2))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_item(2751, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 3))
talkEntry:addResponse("Ore is not all you need. To cast ingots, light the bloomery with coal and smelt the copper ore. You'll need crucible-pincers and I happen to have a spare pair.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Finesmithing Syndicate of Galmair II. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(710, "=", 2))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_item(2751, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 3))
talkEntry:addResponse("Ore is not all you need. To cast ingots, light the bloomery with coal and smelt the copper ore. You'll need crucible-pincers and I happen to have a spare pair.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Finesmithing Syndicate of Galmair II. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(710, "=", 2))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addConsequence(consequence_item(2751, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 3))
talkEntry:addResponse("Erz ist eigentlich nicht das, was du brauchst. Um Barren zu gießen, befeuere den Rennofen mit Kohle. Du wirst eine Tiegelzange brauchen, glücklicherweise habe ich noch eine Ersatzzange für dich.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Das Feinschmiedesyndikat von Galmair II. Detaillierte Informationen findest du im Questlog (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(710, "=", 3))
talkEntry:addCondition(condition_item(2550, "all", ">", 9, nil))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_quest(710, "=", 4))
talkEntry:addResponse("Are you sure these ingots don't contain blowholes? We'll see during your next task.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Ask Tony Spirotelli for your next task."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(710, "=", 3))
talkEntry:addCondition(condition_item(2550, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("copper")
talkEntry:addTrigger("ingot")
talkEntry:addConsequence(consequence_quest(710, "=", 4))
talkEntry:addResponse("Are you sure these ingots don't contain blowholes? We'll see during your next task.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Ask Tony Spirotelli for your next task."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(710, "=", 3))
talkEntry:addCondition(condition_item(2550, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Kupfer")
talkEntry:addTrigger("Barren")
talkEntry:addConsequence(consequence_quest(710, "=", 4))
talkEntry:addResponse("Bist du sicher, dass keine Lunker in den Barren sind? Wir werden es bei deiner nächsten Aufgabe herausfinden.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Frage Tony Spirotelli nach deiner nächsten Aufgaben."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(710, "=", 3))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Casting ingots is something you need to learn before you can become a good finesmith. Please cast ten copper ingots.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(710, "=", 3))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("copper")
talkEntry:addTrigger("ingot")
talkEntry:addResponse("Casting ingots is something you need to learn before you can become a good finesmith. Please cast ten copper ingots.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(710, "=", 3))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Kupfer")
talkEntry:addTrigger("Barren")
talkEntry:addResponse("Wer ein guter Feinschmied werden will, der muss zunächst das Gießen von Barren erlernen. Gieße zehn Kupferbarren, bitte.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(710, "=", 4))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_item(122, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 5))
talkEntry:addResponse("I think you are ready to start production. Begin with ten copper amulets, they are fairly easy to make. Here, have this finesmithing hammer.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Finesmithing Syndicate of Galmair III. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(710, "=", 4))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_item(122, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 5))
talkEntry:addResponse("I think you are ready to start production. Begin with ten copper amulets, they are fairly easy to make. Here, have this finesmithing hammer.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Finesmithing Syndicate of Galmair III. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(710, "=", 4))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addConsequence(consequence_item(122, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 5))
talkEntry:addResponse("Ich denke, du bist bereit, die Fertigung einzuleiten. Beginne mit zehn Kupferamuletten, die sind recht einfach herzustellen. Hier, nimm diesen Feinschmiedehammer.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Das Feinschmiedesyndikat von Galmair III. Detaillierte Informationen findest du im Questlog (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(710, "=", 5))
talkEntry:addCondition(condition_item(3558, "all", ">", 9, nil))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("amulet")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Layman with the Finesmithing Syndicate of Galmair. You are awarded sixty five silver coins."))
talkEntry:addConsequence(consequence_deleteitem(3558, 10, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 6))
talkEntry:addConsequence(consequence_money("+", 6500))
talkEntry:addResponse("You have proven worthy to join the Finesmithing Syndicate of Galmair. For the amulets, I'll give you some first revenue. Use it wisely. Come back once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(710, "=", 5))
talkEntry:addCondition(condition_item(3558, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Layman with the Finesmithing Syndicate of Galmair. You are awarded sixty five silver coins."))
talkEntry:addConsequence(consequence_deleteitem(3558, 10, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 6))
talkEntry:addConsequence(consequence_money("+", 6500))
talkEntry:addResponse("You have proven worthy to join the Finesmithing Syndicate of Galmair. For the amulets, I'll give you some first revenue. Use it wisely. Come back once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(710, "=", 5))
talkEntry:addCondition(condition_item(3558, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Das Feinschmiedesyndikat von Galmair erhebt dich in den Rang eines Laiens. Du erhältst fünfundsechzig Silberstücke."))
talkEntry:addConsequence(consequence_deleteitem(3558, 10, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 6))
talkEntry:addConsequence(consequence_money("+", 6500))
talkEntry:addResponse("Du hast dich als würdig erwiesen, ein Mitglied des Feinschmiedesyndikates von Galmair zu werden. Für die Amulette erhältst du deinen ersten Gewinn. Verwende ihn weise. Komm erneut zu mir, wenn du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(710, "=", 5))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("amulet")
talkEntry:addResponse("Any problems manufacturing ten copper amulets? Just swing your finesmithing hammer.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(710, "=", 5))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addResponse("Any problems manufacturing ten copper amulets? Just swing your finesmithing hammer.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(710, "=", 5))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addResponse("Gibt es Probleme bei der Herstellung der zehn Kupferamulette? Schwing deinen Feinschmiedehammer!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, ">", 9))
talkEntry:addCondition(condition_quest(710, "=", 6))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Novice with the Finesmithing Syndicate of Galmair. You are awarded ten lumps of coal."))
talkEntry:addConsequence(consequence_item(21, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 7))
talkEntry:addResponse("I acknowledge your progress and the Finesmithing Syndicate of Galmair has decided to support your business with some coal. Please return to me once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, ">", 9))
talkEntry:addCondition(condition_quest(710, "=", 6))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Novice with the Finesmithing Syndicate of Galmair. You are awarded ten lumps of coal."))
talkEntry:addConsequence(consequence_item(21, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 7))
talkEntry:addResponse("I acknowledge your progress and the Finesmithing Syndicate of Galmair has decided to support your business with some coal. Please return to me once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, ">", 9))
talkEntry:addCondition(condition_quest(710, "=", 6))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Das Feinschmiedesyndikat von Galmair erhebt dich in den Rang eines Anfängers. Du erhältst zehn Klumpen Kohle."))
talkEntry:addConsequence(consequence_item(21, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 7))
talkEntry:addResponse("Ich erkenne deinen Fortschritt an. Das Feinschmiedesyndikat von Galmair hat beschlossen, dein Geschäft mit diese Kohlen zu fördern. Bitte suche mich erneut auf, wenn du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, "<", 10))
talkEntry:addCondition(condition_quest(710, "=", 6))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Please improve your finesmithing skills. The Finesmithing Syndicate of Galmair cannot promote you beyond your current rank Layman.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 10 in finesmithing to advance in the ranks of the Finesmithing Syndicate of Galmair."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, "<", 10))
talkEntry:addCondition(condition_quest(710, "=", 6))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Please improve your finesmithing skills. The Finesmithing Syndicate of Galmair cannot promote you beyond your current rank Layman.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 10 in finesmithing to advance in the ranks of the Finesmithing Syndicate of Galmair."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, "<", 10))
talkEntry:addCondition(condition_quest(710, "=", 6))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Verbessere bitte deine Feinschmiedefertigkeit. Das Feinschmiedesyndikat von Galmair kann dich so nicht befördern. Du wirst im Rang eines Laiens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 10 in Feinschmieden um im Feinschmiedesyndikat von Galmair aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, ">", 19))
talkEntry:addCondition(condition_quest(710, "=", 7))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Apprentice with the Finesmithing Syndicate of Galmair. You are awarded twenty pieces of copper ore."))
talkEntry:addConsequence(consequence_item(2536, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 8))
talkEntry:addResponse("I acknowledge your progress and the Finesmithing Syndicate of Galmair has decided to support your business with some copper ore. Please return to me once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, ">", 19))
talkEntry:addCondition(condition_quest(710, "=", 7))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Apprentice with the Finesmithing Syndicate of Galmair. You are awarded twenty pieces of copper ore."))
talkEntry:addConsequence(consequence_item(2536, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 8))
talkEntry:addResponse("I acknowledge your progress and the Finesmithing Syndicate of Galmair has decided to support your business with some copper ore. Please return to me once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, ">", 19))
talkEntry:addCondition(condition_quest(710, "=", 7))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Das Feinschmiedesyndikat von Galmair erhebt dich in den Rang eines Lehrlings. Du erhältst zwanzig Stücke Kupfererz."))
talkEntry:addConsequence(consequence_item(2536, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 8))
talkEntry:addResponse("Ich erkenne deinen Fortschritt an. Das Feinschmiedesyndikat von Galmair hat beschlossen, dein Geschäft mit diesem Kupfererz zu fördern. Bitte suche mich erneut auf, wenn du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, "<", 20))
talkEntry:addCondition(condition_quest(710, "=", 7))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Please improve your finesmithing skills. The Finesmithing Syndicate of Galmair cannot promote you beyond your current rank Novice.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 20 in finesmithing to advance in the ranks of the Finesmithing Syndicate of Galmair."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, "<", 20))
talkEntry:addCondition(condition_quest(710, "=", 7))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Please improve your finesmithing skills. The Finesmithing Syndicate of Galmair cannot promote you beyond your current rank Novice.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 20 in finesmithing to advance in the ranks of the Finesmithing Syndicate of Galmair."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, "<", 20))
talkEntry:addCondition(condition_quest(710, "=", 7))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Verbessere bitte deine Feinschmiedefertigkeit. Das Feinschmiedesyndikat von Galmair kann dich so nicht befördern. Du wirst im Rang eines Anfängers geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 20 in Feinschmieden um im Feinschmiedesyndikat von Galmair aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, ">", 29))
talkEntry:addCondition(condition_quest(710, "=", 8))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Initiate with the Finesmithing Syndicate of Galmair. You are awarded ten copper ingots."))
talkEntry:addConsequence(consequence_item(2550, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 9))
talkEntry:addResponse("I acknowledge your progress and the Finesmithing Syndicate of Galmair has decided to support your business with some copper ingots. Please return to me once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, ">", 29))
talkEntry:addCondition(condition_quest(710, "=", 8))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Initiate with the Finesmithing Syndicate of Galmair. You are awarded ten copper ingots."))
talkEntry:addConsequence(consequence_item(2550, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 9))
talkEntry:addResponse("I acknowledge your progress and the Finesmithing Syndicate of Galmair has decided to support your business with some copper ingots. Please return to me once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, ">", 29))
talkEntry:addCondition(condition_quest(710, "=", 8))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Das Feinschmiedesyndikat von Galmair erhebt dich in den Rang eines Initiatens. Du erhältst zehn Kupferbarren."))
talkEntry:addConsequence(consequence_item(2550, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 9))
talkEntry:addResponse("Ich erkenne deinen Fortschritt an. Das Feinschmiedesyndikat von Galmair hat beschlossen, dein Geschäft mit diesen Kupferbarren zu fördern. Bitte suche mich erneut auf, wenn du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, "<", 30))
talkEntry:addCondition(condition_quest(710, "=", 8))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Please improve your finesmithing skills. The Finesmithing Syndicate of Galmair cannot promote you beyond your current rank Apprentice.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 30 in finesmithing to advance in the ranks of the Finesmithing Syndicate of Galmair."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, "<", 30))
talkEntry:addCondition(condition_quest(710, "=", 8))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Please improve your finesmithing skills. The Finesmithing Syndicate of Galmair cannot promote you beyond your current rank Apprentice.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 30 in finesmithing to advance in the ranks of the Finesmithing Syndicate of Galmair."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, "<", 30))
talkEntry:addCondition(condition_quest(710, "=", 8))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Verbessere bitte deine Feinschmiedefertigkeit. Das Feinschmiedesyndikat von Galmair kann dich so nicht befördern. Du wirst im Rang eines Lehrlings geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 30 in Feinschmieden um im Feinschmiedesyndikat von Galmair aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, ">", 39))
talkEntry:addCondition(condition_quest(710, "=", 9))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Journeyman with the Finesmithing Syndicate of Galmair. You are awarded twenty silver ingots and a journeyman's certificate."))
talkEntry:addConsequence(consequence_item(104, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 10))
talkEntry:addResponse("I acknowledge your progress and the Finesmithing Syndicate of Galmair has decided to support your business with some silver ingots. Please return to me once you are more experienced.")
talkEntry:addConsequence(consequence_item(3109, 1, 333, {["descriptionEn"] = "The owner of this certificate has successfully passed the examination as Journeyman. Tony Spirotelli - Finesmithing Syndicate of Galmair", ["descriptionDe"] = "Der Inhaber dieses Gesellenbriefes hat erfolgreich das Examen zum Gesellen bestanden. Tony Spirotelli - Feinschmiedesyndikat von Galmair", ["nameDe"] = "Gesellenbrief", ["nameEn"] = "Journeyman's Certificate", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, ">", 39))
talkEntry:addCondition(condition_quest(710, "=", 9))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Journeyman with the Finesmithing Syndicate of Galmair. You are awarded twenty silver ingots and a journeyman's certificate."))
talkEntry:addConsequence(consequence_item(104, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 10))
talkEntry:addResponse("I acknowledge your progress and the Finesmithing Syndicate of Galmair has decided to support your business with some silver ingots. Please return to me once you are more experienced.")
talkEntry:addConsequence(consequence_item(3109, 1, 333, {["descriptionEn"] = "The owner of this certificate has successfully passed the examination as Journeyman. Tony Spirotelli - Finesmithing Syndicate of Galmair", ["descriptionDe"] = "Der Inhaber dieses Gesellenbriefes hat erfolgreich das Examen zum Gesellen bestanden. Tony Spirotelli - Feinschmiedesyndikat von Galmair", ["nameDe"] = "Gesellenbrief", ["nameEn"] = "Journeyman's Certificate", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, ">", 39))
talkEntry:addCondition(condition_quest(710, "=", 9))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Das Feinschmiedesyndikat von Galmair erhebt dich in den Rang eines Gesellens. Du erhältst zwanzig Silberbarren und einen Gesellenbrief."))
talkEntry:addConsequence(consequence_item(104, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 10))
talkEntry:addResponse("Ich erkenne deinen Fortschritt an. Das Feinschmiedesyndikat von Galmair hat beschlossen, dein Geschäft mit diesen Silberbarren zu fördern. Bitte suche mich erneut auf, wenn du erfahrener bist.")
talkEntry:addConsequence(consequence_item(3109, 1, 333, {["descriptionEn"] = "The owner of this certificate has successfully passed the examination as Journeyman. Tony Spirotelli - Finesmithing Syndicate of Galmair", ["descriptionDe"] = "Der Inhaber dieses Gesellenbriefes hat erfolgreich das Examen zum Gesellen bestanden. Tony Spirotelli - Feinschmiedesyndikat von Galmair", ["nameDe"] = "Gesellenbrief", ["nameEn"] = "Journeyman's Certificate", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, "<", 40))
talkEntry:addCondition(condition_quest(710, "=", 9))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Please improve your finesmithing skills. The Finesmithing Syndicate of Galmair cannot promote you beyond your current rank Initiate.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 40 in finesmithing to advance in the ranks of the Finesmithing Syndicate of Galmair."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, "<", 40))
talkEntry:addCondition(condition_quest(710, "=", 9))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Please improve your finesmithing skills. The Finesmithing Syndicate of Galmair cannot promote you beyond your current rank Initiate.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 40 in finesmithing to advance in the ranks of the Finesmithing Syndicate of Galmair."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, "<", 40))
talkEntry:addCondition(condition_quest(710, "=", 9))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Verbessere bitte deine Feinschmiedefertigkeit. Das Feinschmiedesyndikat von Galmair kann dich so nicht befördern. Du wirst im Rang eines Initiatens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 40 in Feinschmieden um im Feinschmiedesyndikat von Galmair aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, ">", 49))
talkEntry:addCondition(condition_quest(710, "=", 10))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Specialist with the Finesmithing Syndicate of Galmair. You are awarded ten sapphires."))
talkEntry:addConsequence(consequence_item(284, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 11))
talkEntry:addResponse("I acknowledge your progress and the Finesmithing Syndicate of Galmair has decided to support your business with some sapphires. Please return to me once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, ">", 49))
talkEntry:addCondition(condition_quest(710, "=", 10))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Specialist with the Finesmithing Syndicate of Galmair. You are awarded ten sapphires."))
talkEntry:addConsequence(consequence_item(284, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 11))
talkEntry:addResponse("I acknowledge your progress and the Finesmithing Syndicate of Galmair has decided to support your business with some sapphires. Please return to me once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, ">", 49))
talkEntry:addCondition(condition_quest(710, "=", 10))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Das Feinschmiedesyndikat von Galmair erhebt dich in den Rang eines Spezialistens. Du erhältst zehn Saphire."))
talkEntry:addConsequence(consequence_item(284, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 11))
talkEntry:addResponse("Ich erkenne deinen Fortschritt an. Das Feinschmiedesyndikat von Galmair hat beschlossen, dein Geschäft mit diesen Saphiren zu fördern. Bitte suche mich erneut auf, wenn du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, "<", 50))
talkEntry:addCondition(condition_quest(710, "=", 10))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Please improve your finesmithing skills. The Finesmithing Syndicate of Galmair cannot promote you beyond your current rank Journeyman.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 50 in finesmithing to advance in the ranks of the Finesmithing Syndicate of Galmair."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, "<", 50))
talkEntry:addCondition(condition_quest(710, "=", 10))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Please improve your finesmithing skills. The Finesmithing Syndicate of Galmair cannot promote you beyond your current rank Journeyman.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 50 in finesmithing to advance in the ranks of the Finesmithing Syndicate of Galmair."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, "<", 50))
talkEntry:addCondition(condition_quest(710, "=", 10))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Verbessere bitte deine Feinschmiedefertigkeit. Das Feinschmiedesyndikat von Galmair kann dich so nicht befördern. Du wirst im Rang eines Gesellens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 50 in Feinschmieden um im Feinschmiedesyndikat von Galmair aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, ">", 59))
talkEntry:addCondition(condition_quest(710, "=", 11))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Expert with the Finesmithing Syndicate of Galmair. You are awarded twenty emeralds."))
talkEntry:addConsequence(consequence_item(45, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 12))
talkEntry:addResponse("I acknowledge your progress and the Finesmithing Syndicate of Galmair has decided to support your business with some emeralds. Please return to me once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, ">", 59))
talkEntry:addCondition(condition_quest(710, "=", 11))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Expert with the Finesmithing Syndicate of Galmair. You are awarded twenty emeralds."))
talkEntry:addConsequence(consequence_item(45, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 12))
talkEntry:addResponse("I acknowledge your progress and the Finesmithing Syndicate of Galmair has decided to support your business with some emeralds. Please return to me once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, ">", 59))
talkEntry:addCondition(condition_quest(710, "=", 11))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Das Feinschmiedesyndikat von Galmair erhebt dich in den Rang eines Expertens. Du erhältst zwanzig Smaragde."))
talkEntry:addConsequence(consequence_item(45, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 12))
talkEntry:addResponse("Ich erkenne deinen Fortschritt an. Das Feinschmiedesyndikat von Galmair hat beschlossen, dein Geschäft mit diesen Smaragden zu fördern. Bitte suche mich erneut auf, wenn du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, "<", 60))
talkEntry:addCondition(condition_quest(710, "=", 11))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Please improve your finesmithing skills. The Finesmithing Syndicate of Galmair cannot promote you beyond your current rank Specialist.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 60 in finesmithing to advance in the ranks of the Finesmithing Syndicate of Galmair."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, "<", 60))
talkEntry:addCondition(condition_quest(710, "=", 11))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Please improve your finesmithing skills. The Finesmithing Syndicate of Galmair cannot promote you beyond your current rank Specialist.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 60 in finesmithing to advance in the ranks of the Finesmithing Syndicate of Galmair."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, "<", 60))
talkEntry:addCondition(condition_quest(710, "=", 11))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Verbessere bitte deine Feinschmiedefertigkeit. Das Feinschmiedesyndikat von Galmair kann dich so nicht befördern. Du wirst im Rang eines Spezialistens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 60 in Feinschmieden um im Feinschmiedesyndikat von Galmair aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, ">", 69))
talkEntry:addCondition(condition_quest(710, "=", 12))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Adept with the Finesmithing Syndicate of Galmair. You are awarded five bags of emerald powder."))
talkEntry:addConsequence(consequence_item(448, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 13))
talkEntry:addResponse("I acknowledge your progress and the Finesmithing Syndicate of Galmair has decided to support your business with some emerald powder. Please return to me once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, ">", 69))
talkEntry:addCondition(condition_quest(710, "=", 12))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Adept with the Finesmithing Syndicate of Galmair. You are awarded five bags of emerald powder."))
talkEntry:addConsequence(consequence_item(448, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 13))
talkEntry:addResponse("I acknowledge your progress and the Finesmithing Syndicate of Galmair has decided to support your business with some emerald powder. Please return to me once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, ">", 69))
talkEntry:addCondition(condition_quest(710, "=", 12))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Das Feinschmiedesyndikat von Galmair erhebt dich in den Rang eines Adeptens. Du erhältst fünf Sack Smaragdstaub."))
talkEntry:addConsequence(consequence_item(448, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 13))
talkEntry:addResponse("Ich erkenne deinen Fortschritt an. Das Feinschmiedesyndikat von Galmair hat beschlossen, dein Geschäft mit diesem Smaragdstaub zu fördern. Bitte suche mich erneut auf, wenn du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, "<", 70))
talkEntry:addCondition(condition_quest(710, "=", 12))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Please improve your finesmithing skills. The Finesmithing Syndicate of Galmair cannot promote you beyond your current rank Expert.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 70 in finesmithing to advance in the ranks of the Finesmithing Syndicate of Galmair."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, "<", 70))
talkEntry:addCondition(condition_quest(710, "=", 12))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Please improve your finesmithing skills. The Finesmithing Syndicate of Galmair cannot promote you beyond your current rank Expert.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 70 in finesmithing to advance in the ranks of the Finesmithing Syndicate of Galmair."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, "<", 70))
talkEntry:addCondition(condition_quest(710, "=", 12))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Verbessere bitte deine Feinschmiedefertigkeit. Das Feinschmiedesyndikat von Galmair kann dich so nicht befördern. Du wirst im Rang eines Expertens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 70 in Feinschmieden um im Feinschmiedesyndikat von Galmair aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, ">", 79))
talkEntry:addCondition(condition_quest(710, "=", 13))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Artisan with the Finesmithing Syndicate of Galmair. You are awarded ten bags of diamond powder."))
talkEntry:addConsequence(consequence_item(452, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 14))
talkEntry:addResponse("I acknowledge your progress and the Finesmithing Syndicate of Galmair has decided to support your business with some diamond powder. Please return to me once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, ">", 79))
talkEntry:addCondition(condition_quest(710, "=", 13))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Artisan with the Finesmithing Syndicate of Galmair. You are awarded ten bags of diamond powder."))
talkEntry:addConsequence(consequence_item(452, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 14))
talkEntry:addResponse("I acknowledge your progress and the Finesmithing Syndicate of Galmair has decided to support your business with some diamond powder. Please return to me once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, ">", 79))
talkEntry:addCondition(condition_quest(710, "=", 13))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Das Feinschmiedesyndikat von Galmair erhebt dich in den Rang eines Artisanens. Du erhältst zehn Sack Diamantstaub."))
talkEntry:addConsequence(consequence_item(452, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 14))
talkEntry:addResponse("Ich erkenne deinen Fortschritt an. Das Feinschmiedesyndikat von Galmair hat beschlossen, dein Geschäft mit diesem Diamantstaub zu fördern. Bitte suche mich erneut auf, wenn du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, "<", 80))
talkEntry:addCondition(condition_quest(710, "=", 13))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Please improve your finesmithing skills. The Finesmithing Syndicate of Galmair cannot promote you beyond your current rank Adept.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 80 in finesmithing to advance in the ranks of the Finesmithing Syndicate of Galmair."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, "<", 80))
talkEntry:addCondition(condition_quest(710, "=", 13))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Please improve your finesmithing skills. The Finesmithing Syndicate of Galmair cannot promote you beyond your current rank Adept.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 80 in finesmithing to advance in the ranks of the Finesmithing Syndicate of Galmair."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, "<", 80))
talkEntry:addCondition(condition_quest(710, "=", 13))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Verbessere bitte deine Feinschmiedefertigkeit. Das Feinschmiedesyndikat von Galmair kann dich so nicht befördern. Du wirst im Rang eines Adeptens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 80 in Feinschmieden um im Feinschmiedesyndikat von Galmair aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, ">", 89))
talkEntry:addCondition(condition_quest(710, "=", 14))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Master with the Finesmithing Syndicate of Galmair. You are awarded five drops of pure water and a special tool."))
talkEntry:addConsequence(consequence_item(2554, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 15))
talkEntry:addResponse("I acknowledge your progress and the Finesmithing Syndicate of Galmair has decided to support your business with some pure water. Please return to me once you are more experienced.")
talkEntry:addConsequence(consequence_item(122, 1, 999, {["descriptionEn"] = "Master of the Finesmithing Syndicate of Galmair", ["descriptionDe"] = "Meister des Feinschmiedesyndikates von Galmair", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, ">", 89))
talkEntry:addCondition(condition_quest(710, "=", 14))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Master with the Finesmithing Syndicate of Galmair. You are awarded five drops of pure water and a special tool."))
talkEntry:addConsequence(consequence_item(2554, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 15))
talkEntry:addResponse("I acknowledge your progress and the Finesmithing Syndicate of Galmair has decided to support your business with some pure water. Please return to me once you are more experienced.")
talkEntry:addConsequence(consequence_item(122, 1, 999, {["descriptionEn"] = "Master of the Finesmithing Syndicate of Galmair", ["descriptionDe"] = "Meister des Feinschmiedesyndikates von Galmair", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, ">", 89))
talkEntry:addCondition(condition_quest(710, "=", 14))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Das Feinschmiedesyndikat von Galmair erhebt dich in den Rang eines Meisters. Du erhältst fünf Tropfen reines Wasser und ein besonderes Werkzeug."))
talkEntry:addConsequence(consequence_item(2554, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 15))
talkEntry:addResponse("Ich erkenne deinen Fortschritt an. Das Feinschmiedesyndikat von Galmair hat beschlossen, dein Geschäft mit diesem reinen Wasser zu fördern. Bitte suche mich erneut auf, wenn du erfahrener bist.")
talkEntry:addConsequence(consequence_item(122, 1, 999, {["descriptionEn"] = "Master of the Finesmithing Syndicate of Galmair", ["descriptionDe"] = "Meister des Feinschmiedesyndikates von Galmair", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, "<", 90))
talkEntry:addCondition(condition_quest(710, "=", 14))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Please improve your finesmithing skills. The Finesmithing Syndicate of Galmair cannot promote you beyond your current rank Artisan.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 90 in finesmithing to advance in the ranks of the Finesmithing Syndicate of Galmair."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, "<", 90))
talkEntry:addCondition(condition_quest(710, "=", 14))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Please improve your finesmithing skills. The Finesmithing Syndicate of Galmair cannot promote you beyond your current rank Artisan.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 90 in finesmithing to advance in the ranks of the Finesmithing Syndicate of Galmair."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, "<", 90))
talkEntry:addCondition(condition_quest(710, "=", 14))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Verbessere bitte deine Feinschmiedefertigkeit. Das Feinschmiedesyndikat von Galmair kann dich so nicht befördern. Du wirst im Rang eines Artisanens geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 90 in Feinschmieden um im Feinschmiedesyndikat von Galmair aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, ">", 99))
talkEntry:addCondition(condition_quest(710, "=", 15))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Grandmaster with the Finesmithing Syndicate of Galmair. You are awarded ten pieces of pure spirit and a grandmaster's medal."))
talkEntry:addConsequence(consequence_item(3607, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 16))
talkEntry:addResponse("Congratulations, you are now a true Grandmaster of the Finesmithing Syndicate of Galmair. This pure spirit shall help you to manufacture the best goods of Illarion.")
talkEntry:addConsequence(consequence_item(3535, 1, 999, {["descriptionEn"] = "Grandmaster of the Finesmithing Syndicate of Galmair", ["descriptionDe"] = "Großmeister des Feinschmiedesyndikats von Galmair", ["nameDe"] = "Großmeistermedallie", ["nameEn"] = "Grandmaster's Medal", ["rareness"] = "2"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, ">", 99))
talkEntry:addCondition(condition_quest(710, "=", 15))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Grandmaster with the Finesmithing Syndicate of Galmair. You are awarded ten pieces of pure spirit and a grandmaster's medal."))
talkEntry:addConsequence(consequence_item(3607, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 16))
talkEntry:addResponse("Congratulations, you are now a true Grandmaster of the Finesmithing Syndicate of Galmair. This pure spirit shall help you to manufacture the best goods of Illarion.")
talkEntry:addConsequence(consequence_item(3535, 1, 999, {["descriptionEn"] = "Grandmaster of the Finesmithing Syndicate of Galmair", ["descriptionDe"] = "Großmeister des Feinschmiedesyndikats von Galmair", ["nameDe"] = "Großmeistermedallie", ["nameEn"] = "Grandmaster's Medal", ["rareness"] = "2"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, ">", 99))
talkEntry:addCondition(condition_quest(710, "=", 15))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Das Feinschmiedesyndikat von Galmair erhebt dich in den Rang eines Großmeisters. Du erhältst zehn Stück reinem Geistes und eine Großmeistermedallie."))
talkEntry:addConsequence(consequence_item(3607, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(710, "=", 16))
talkEntry:addResponse("Gratulation, du bist nun ein echter Großmeister des Feinschmiedesyndikats von Galmair. Dieser reine Geist soll dir helfen, die besten Waren ganz Illarions herzustellen.")
talkEntry:addConsequence(consequence_item(3535, 1, 999, {["descriptionEn"] = "Grandmaster of the Finesmithing Syndicate of Galmair", ["descriptionDe"] = "Großmeister des Feinschmiedesyndikats von Galmair", ["nameDe"] = "Großmeistermedallie", ["nameEn"] = "Grandmaster's Medal", ["rareness"] = "2"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, "<", 100))
talkEntry:addCondition(condition_quest(710, "=", 15))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Please improve your finesmithing skills. The Finesmithing Syndicate of Galmair cannot promote you beyond your current rank Master.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 100 in finesmithing to advance in the ranks of the Finesmithing Syndicate of Galmair."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, "<", 100))
talkEntry:addCondition(condition_quest(710, "=", 15))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("Please improve your finesmithing skills. The Finesmithing Syndicate of Galmair cannot promote you beyond your current rank Master.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 100 in finesmithing to advance in the ranks of the Finesmithing Syndicate of Galmair."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.finesmithing, "<", 100))
talkEntry:addCondition(condition_quest(710, "=", 15))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Verbessere bitte deine Feinschmiedefertigkeit. Das Feinschmiedesyndikat von Galmair kann dich so nicht befördern. Du wirst im Rang eines Meisters geführt.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 100 in Feinschmieden um im Feinschmiedesyndikat von Galmair aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(710, "=", 16))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("So, you think you're the big show, Grandmaster %CHARNAME? You are!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(710, "=", 16))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addResponse("So, you think you're the big show, Grandmaster %CHARNAME? You are!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(710, "=", 16))
talkEntry:addCondition(condition_town(3))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addResponse("So, du denkst also, du bist nun wer, Großmeister %CHARNAME? Das stimmt tatsächlich!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Only citizens of Galmair may join the Finesmithing Syndicate.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addResponse("Only citizens of Galmair may join the Finesmithing Syndicate.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addResponse("Nur Bürger Galmairs können dem Feinschmiedesyndikat beitreten.")
talkingNPC:addTalkingEntry(talkEntry)
end
talkingNPC:addCycleText("Der beste Feinschmied, das bin ich!", "The best finesmith, that is me!")
talkingNPC:addCycleText("#me hat Goldstaub auf seinem Hemd.", "#me has gold dust on his shirt.")
talkingNPC:addCycleText("#me hat einen abgenutzten Hammer in seinem Gürtel.", "#me has a worn hammer hanging from his belt.")
talkingNPC:addCycleText("#me schmiedet sorgfältig ein Stück Kupfer, bis es die Form eines Amulettes annimmt.", "#me carefully forges a piece of copper, forming an amulet.")
talkingNPC:addCycleText("Es gibt keine bessere Arbeit als mit Gold.", "There is no finer work than with gold.")
talkingNPC:addCycleText("Es gibt nichts, was ich nicht mit meinen treuen Hammer machen kann.", "There is nothing I can't make with my trusty hammer.")
talkingNPC:addCycleText("Der Silberstreif am Horizont wird dir ganz anders erscheinen, wenn du erstmal ein Feinschmied bist.", "Silver lining gets a whole new meaning once you become a finesmith.")
talkingNPC:addCycleText("Das Feinschmiedesyndikat. Tritt ihm bei oder stirb arm.", "The Finesmithing Syndicate. Join today or die poor.")
mainNPC:addLanguage(0)
mainNPC:addLanguage(1)
mainNPC:setDefaultLanguage(0)
mainNPC:setLookat("Dieser NPC ist Tony Spirotelli der Feinschmied.", "This NPC is Tony Spirotelli the finesmith.")
mainNPC:setUseMessage("Fass mich nicht an!", "Hands off!")
mainNPC:setConfusedMessage("#me schaut dich verwirrt an.", "#me looks at you confused.")
mainNPC:setEquipment(1, 0)
mainNPC:setEquipment(3, 364)
mainNPC:setEquipment(11, 2384)
mainNPC:setEquipment(5, 0)
mainNPC:setEquipment(6, 0)
mainNPC:setEquipment(4, 0)
mainNPC:setEquipment(9, 826)
mainNPC:setEquipment(10, 53)
mainNPC:setAutoIntroduceMode(true)

mainNPC:initDone()
return mainNPC
end
local mNPC = initNpc()
initNpc = nil
local M = {}
function M.receiveText(npcChar, texttype, message, speaker) mNPC:receiveText(npcChar, texttype, speaker, message) end
function M.nextCycle(npcChar) mNPC:nextCycle(npcChar) end
function M.lookAtNpc(npcChar, char, mode) mNPC:lookAt(npcChar, char, mode) end
function M.useNPC(npcChar, char, counter, param) mNPC:use(npcChar, char) end
return M
