local consequence_item = require("npc.base.consequence.item")
local condition_item = require("npc.base.condition.item")
local consequence_quest = require("npc.base.consequence.quest")
local condition_skill = require("npc.base.condition.skill")
local condition_language = require("npc.base.condition.language")
local consequence_deleteitem = require("npc.base.consequence.deleteitem")
local basic = require("npc.base.basic")
local condition_town = require("npc.base.condition.town")
local talk = require("npc.base.talk")
local consequence_money = require("npc.base.consequence.money")
local condition_quest = require("npc.base.condition.quest")
local consequence_inform = require("npc.base.consequence.inform")
local function initNpc()
local mainNPC = basic()
mainNPC:setAffiliation(1)
local talkingNPC = talk(mainNPC)
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Help")
talkEntry:addConsequence(consequence_inform("[Game Help] This NPC is Zlatxhol the potter. Keywords: Hello, quest, potter."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hilfe")
talkEntry:addConsequence(consequence_inform("[Spielhilfe] Dieser NPC ist Zlatxhol der Töpfer. Schlüsselwörter: Hallo, Quest, Töpfer."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hello")
talkEntry:addTrigger("Greet")
talkEntry:addTrigger("Hail")
talkEntry:addTrigger("Good day")
talkEntry:addTrigger("Good morning")
talkEntry:addTrigger("Good evening")
talkEntry:addTrigger("Good night")
talkEntry:addResponse("Greetingsss to you.")
talkEntry:addResponse("Yess, greetingss.")
talkEntry:addResponse("Blessingss of the Mother upon you, greetingss")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Grüß")
talkEntry:addTrigger("Gruß")
talkEntry:addTrigger("Grüss")
talkEntry:addTrigger("Gruss")
talkEntry:addTrigger("Guten Morgen")
talkEntry:addTrigger("Guten Tag")
talkEntry:addTrigger("Guten Abend")
talkEntry:addTrigger("Gute Nacht")
talkEntry:addTrigger("Mahlzeit")
talkEntry:addTrigger("Tach")
talkEntry:addTrigger("Moin")
talkEntry:addTrigger("Mohltied")
talkEntry:addResponse("Grüßsse dir.")
talkEntry:addResponse("Ja, Grüßsse.")
talkEntry:addResponse("Grüßsse.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Hiho")
talkEntry:addTrigger("Hallo")
talkEntry:addTrigger("Hey")
talkEntry:addTrigger("Greeb")
talkEntry:addResponse("Greetingsss to you.")
talkEntry:addResponse("Yess, greetingss.")
talkEntry:addResponse("Greetsss.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Hiho")
talkEntry:addTrigger("Hallo")
talkEntry:addTrigger("Hey")
talkEntry:addTrigger("Greeb")
talkEntry:addResponse("Grüßsse dir.")
talkEntry:addResponse("Ja, Grüßsse.")
talkEntry:addResponse("Grüßsse.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Farewell")
talkEntry:addTrigger("Bye")
talkEntry:addTrigger("Fare well")
talkEntry:addTrigger("See you")
talkEntry:addResponse("May the rainsss be heavy and frequent.")
talkEntry:addResponse("May the ssea-Mother watch your path.")
talkEntry:addResponse("Farewell, zsss.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Tschüß")
talkEntry:addTrigger("Tschüss")
talkEntry:addTrigger("Wiedersehen")
talkEntry:addTrigger("Gehab wohl")
talkEntry:addResponse("Mögenss Regen häufig und ssstark sssein.")
talkEntry:addResponse("Mögenss die Meermutter dein Pfad leitenss.")
talkEntry:addResponse("Abschied, zsss.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Ciao")
talkEntry:addTrigger("Adieu")
talkEntry:addTrigger("Au revoir")
talkEntry:addResponse("Goodbye")
talkEntry:addResponse("Farewell")
talkEntry:addResponse("#me nods slowly, 'Goodbye'.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Ciao")
talkEntry:addTrigger("Adieu")
talkEntry:addTrigger("Au revoir")
talkEntry:addResponse("Gut wiedersehensss.")
talkEntry:addResponse("Abschied.")
talkEntry:addResponse("#me nickt langsam: 'Gut wiedersehensss'.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("How are you")
talkEntry:addTrigger("How feel")
talkEntry:addTrigger("How do you do")
talkEntry:addResponse("Zlatxhol iss fine, yess.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Wie geht")
talkEntry:addTrigger("Wie fühlst")
talkEntry:addTrigger("Wie ist es ergangen")
talkEntry:addResponse("Zlatxhol issst gut, ja.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("your name")
talkEntry:addTrigger("who are you")
talkEntry:addTrigger("who art thou")
talkEntry:addResponse("I be Zlatxhol, would you like to do a job for me?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("ihr name")
talkEntry:addTrigger("dein name")
talkEntry:addTrigger("wer bist du")
talkEntry:addTrigger("wer seid ihr")
talkEntry:addTrigger("wie heißt")
talkEntry:addTrigger("wie heisst")
talkEntry:addResponse("Ich sindss Zlatxhol, machenss du Aufgabe für michss?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("sell")
talkEntry:addTrigger("buy")
talkEntry:addTrigger("wares")
talkEntry:addTrigger("price")
talkEntry:addTrigger("trade")
talkEntry:addTrigger("purchase")
talkEntry:addResponse("I am not a trader.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("kauf")
talkEntry:addTrigger("waren")
talkEntry:addTrigger("preis")
talkEntry:addTrigger("Handel")
talkEntry:addTrigger("veräußer")
talkEntry:addTrigger("veräusser")
talkEntry:addTrigger("erwerb")
talkEntry:addResponse("Ich bin kein Händler.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("profession")
talkEntry:addResponse("I'm a potter, do you wantsss to help Zlatxhol?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("job")
talkEntry:addResponse("I'm a potter, do you wantsss to help Zlatxhol?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("job")
talkEntry:addTrigger("beruf")
talkEntry:addResponse("Ich binss Töpfer, wollen du michssz helfen?")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("potter")
talkEntry:addTrigger("craft")
talkEntry:addResponse("You need tongsss to take the hot potter ware out of the kiln! Don't burn your fingersss.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Töpfer")
talkEntry:addTrigger("Handwerk")
talkEntry:addResponse("Du brauchssst eine Zssange, um die heißsse Töpferware ausss dem Ofen zssu holen. Verbrenn dir nicht die Finger!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(707, "=", 0))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_item(24, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 1))
talkEntry:addResponse("The Guild of Potterss acceptss you as an apprentice. But you'll have to work hard firsst. Take thiss ssshovel and collect twenty lumpss of clay. You can findss clay in a clay pit sssouth of here just outsside the gate.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Pottery Guild of Cadomyr I. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(707, "=", 0))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_item(24, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 1))
talkEntry:addResponse("The Guild of Potterss acceptss you as an apprentice. But you'll have to work hard firsst. Take thiss ssshovel and collect twenty lumpss of clay. You can findss clay in a clay pit sssouth of here just outsside the gate.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Pottery Guild of Cadomyr I. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(707, "=", 0))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addConsequence(consequence_item(24, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 1))
talkEntry:addResponse("Die Töpferinnung wird deine Ausbildung übernehmen, ssz. Sszuerssst issst harte Arbeit. Nimm diese Schaufel und sssammle zwanzig Lehmklumpen. Lehm isssst in den Gruben sssüdlich von hier ausserhalb der Ssstadttore zu finden.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Die Töpferinnung von Cadomyr I. Detaillierte Informationen findest du im Questlog (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(707, "=", 1))
talkEntry:addCondition(condition_item(26, "all", ">", 19, nil))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_quest(707, "=", 2))
talkEntry:addResponse("Isss very fine clay thisss. But you are not a real potter yet. Keepss the clay. You needsss them later.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Ask Zlatxhol for your next task."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(707, "=", 1))
talkEntry:addCondition(condition_item(26, "all", ">", 19, nil))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("clay")
talkEntry:addConsequence(consequence_quest(707, "=", 2))
talkEntry:addResponse("Isss very fine clay thisss. But you are not a real potter yet. Keepss the clay. You needsss them later.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] Ask Zlatxhol for your next task."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(707, "=", 1))
talkEntry:addCondition(condition_item(26, "all", ">", 19, nil))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Lehm")
talkEntry:addConsequence(consequence_quest(707, "=", 2))
talkEntry:addResponse("Schöner lehmiger Lehm. Du bissst noch kein Töpfer. Dasss braucht mehr. Isst dein Lehm für weitere Ausssbildung.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Frage Zlatxhol nach deiner nächsten Aufgaben."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(707, "=", 1))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("Ssss, Zlatxhol wantsss ten clumps of clay, this is not enough claysss. Come back when you have finished the tassk!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(707, "=", 1))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("clay")
talkEntry:addResponse("Ssss, Zlatxhol wantsss ten clumps of clay, this is not enough claysss. Come back when you have finished the tassk!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(707, "=", 1))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Lehm")
talkEntry:addResponse("Zsss, ichse haben wollten zehn Lehmss! Dasss nicht sssein zehn Lehm. Kommen sszurück wenn fertig!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(707, "=", 2))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_item(2140, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 3))
talkEntry:addResponse("Now we make brickss with clayss. You go to kiln and makes ten bricksss. Here, me givesss you an old sset of tongss of mines.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Pottery Guild of Cadomyr II. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(707, "=", 2))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addConsequence(consequence_item(2140, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 3))
talkEntry:addResponse("Now we make brickss with clayss. You go to kiln and makes ten bricksss. Here, me givesss you an old sset of tongss of mines.")
talkEntry:addConsequence(consequence_inform("[Guild Quest] The Pottery Guild of Cadomyr II. For more information see the quest log (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(707, "=", 2))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addConsequence(consequence_item(2140, 1, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 3))
talkEntry:addResponse("Jetztss wir machen Zzziegel mit Lehm. Du gehen zum Ofen in Werkstatt neben mir und machen zehn Zzziegels. Hier ich geben dir alte Zzzange von mirs.")
talkEntry:addConsequence(consequence_inform("[Gildenquest] Die Töpferinnung von Cadomyr II. Detaillierte Informationen findest du im Questlog (Q)."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(707, "=", 3))
talkEntry:addCondition(condition_item(2588, "all", ">", 9, nil))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Layman with the Pottery Guild of Cadomyr. You are awarded twenty silver coins."))
talkEntry:addConsequence(consequence_deleteitem(2588, 10, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 6))
talkEntry:addConsequence(consequence_money("+", 2000))
talkEntry:addResponse("The Pottery Guild of Cadomyr isss proud to have a new member, Ssss. Here isss some money for a honourable potter-to-be. Ssssee me again once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(707, "=", 3))
talkEntry:addCondition(condition_item(2588, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("brick")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Layman with the Pottery Guild of Cadomyr. You are awarded twenty silver coins."))
talkEntry:addConsequence(consequence_deleteitem(2588, 10, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 6))
talkEntry:addConsequence(consequence_money("+", 2000))
talkEntry:addResponse("The Pottery Guild of Cadomyr isss proud to have a new member, Ssss. Here isss some money for a honourable potter-to-be. Ssssee me again once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(707, "=", 3))
talkEntry:addCondition(condition_item(2588, "all", ">", 9, nil))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Ziegel")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Töpferinnung von Cadomyr erhebt dich in den Rang eines Laiens. Du erhältst zwanzig Silberstücke."))
talkEntry:addConsequence(consequence_deleteitem(2588, 10, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 6))
talkEntry:addConsequence(consequence_money("+", 2000))
talkEntry:addResponse("Die Töpferinnung von Cadomyr isssst stolz, dich als neues Mitglied aufszunehmen. Dessshalb auch etwass Geld. Ich ssseh dich wieder, sssobald du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(707, "=", 3))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("You have not finished! I want ten bricksss, come backsss when you have finished.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(707, "=", 3))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("brick")
talkEntry:addResponse("You have not finished! I want ten bricksss, come backsss when you have finished.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(707, "=", 3))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Ziegel")
talkEntry:addResponse("Du nichtss fertig seinsss. Ich wollen zehn Zzziegels, kommen wieder wenn du fertig seinsss.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, ">", 9))
talkEntry:addCondition(condition_quest(707, "=", 6))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Novice with the Pottery Guild of Cadomyr. You are awarded ten piles of clay."))
talkEntry:addConsequence(consequence_item(26, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 7))
talkEntry:addResponse("You did well for honour and glory of our guild and the Queen, Ssss. The Pottery Guild of Cadomyr sssupportsss your effortsss with some clay. Come back to me once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, ">", 9))
talkEntry:addCondition(condition_quest(707, "=", 6))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Novice with the Pottery Guild of Cadomyr. You are awarded ten piles of clay."))
talkEntry:addConsequence(consequence_item(26, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 7))
talkEntry:addResponse("You did well for honour and glory of our guild and the Queen, Ssss. The Pottery Guild of Cadomyr sssupportsss your effortsss with some clay. Come back to me once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, ">", 9))
talkEntry:addCondition(condition_quest(707, "=", 6))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Töpferinnung von Cadomyr erhebt dich in den Rang eines Anfängers. Du erhältst zehn Klumpen Lehm."))
talkEntry:addConsequence(consequence_item(26, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 7))
talkEntry:addResponse("Sssehr gut. Du bringst der Töpferinnung und der Königin Ehre und Ruhm. Wir sssind stolzz dir mit etwass Lehm sszu helfen. Ich ssseh dich wieder, sssobald du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, "<", 10))
talkEntry:addCondition(condition_quest(707, "=", 6))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("I'm proud to sssee you Layman. You should ssstay more time at the kiln to become promoted, Ssss.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 10 in pottery to advance in the ranks of the Pottery Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, "<", 10))
talkEntry:addCondition(condition_quest(707, "=", 6))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("I'm proud to sssee you Layman. You should ssstay more time at the kiln to become promoted, Ssss.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 10 in pottery to advance in the ranks of the Pottery Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, "<", 10))
talkEntry:addCondition(condition_quest(707, "=", 6))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Ess issst mir eine Ehre einen Laien der Gilde sszu ssehen. Ich habe dich aber nicht ssso viel am Brennofen gesehen, sssz.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 10 in Töpfern um in der Töpferinnung aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, ">", 19))
talkEntry:addCondition(condition_quest(707, "=", 7))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Apprentice with the Pottery Guild of Cadomyr. You are awarded twenty piles of clay."))
talkEntry:addConsequence(consequence_item(26, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 8))
talkEntry:addResponse("You did well for honour and glory of our guild and the Queen, Ssss. The Pottery Guild of Cadomyr sssupportsss your effortsss with some clay. Come back to me once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, ">", 19))
talkEntry:addCondition(condition_quest(707, "=", 7))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Apprentice with the Pottery Guild of Cadomyr. You are awarded twenty piles of clay."))
talkEntry:addConsequence(consequence_item(26, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 8))
talkEntry:addResponse("You did well for honour and glory of our guild and the Queen, Ssss. The Pottery Guild of Cadomyr sssupportsss your effortsss with some clay. Come back to me once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, ">", 19))
talkEntry:addCondition(condition_quest(707, "=", 7))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Töpferinnung von Cadomyr erhebt dich in den Rang eines Lehrlings. Du erhältst zwanzig Klumpen Lehm."))
talkEntry:addConsequence(consequence_item(26, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 8))
talkEntry:addResponse("Sssehr gut. Du bringst der Töpferinnung und der Königin Ehre und Ruhm. Wir sssind stolzz dir mit etwass Lehm sszu helfen. Ich ssseh dich wieder, sssobald du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, "<", 20))
talkEntry:addCondition(condition_quest(707, "=", 7))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("I'm proud to sssee you Novice. You should ssstay more time at the kiln to become promoted, Ssss.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 20 in pottery to advance in the ranks of the Pottery Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, "<", 20))
talkEntry:addCondition(condition_quest(707, "=", 7))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("I'm proud to sssee you Novice. You should ssstay more time at the kiln to become promoted, Ssss.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 20 in pottery to advance in the ranks of the Pottery Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, "<", 20))
talkEntry:addCondition(condition_quest(707, "=", 7))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Ess issst mir eine Ehre einen Anfänger der Gilde sszu ssehen. Ich habe dich aber nicht ssso viel am Brennofen gesehen, sssz.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 20 in Töpfern um in der Töpferinnung aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, ">", 29))
talkEntry:addCondition(condition_quest(707, "=", 8))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Initiate with the Pottery Guild of Cadomyr. You are awarded thirty piles of clay."))
talkEntry:addConsequence(consequence_item(26, 30, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 9))
talkEntry:addResponse("You did well for honour and glory of our guild and the Queen, Ssss. The Pottery Guild of Cadomyr sssupportsss your effortsss with some clay. Come back to me once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, ">", 29))
talkEntry:addCondition(condition_quest(707, "=", 8))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Initiate with the Pottery Guild of Cadomyr. You are awarded thirty piles of clay."))
talkEntry:addConsequence(consequence_item(26, 30, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 9))
talkEntry:addResponse("You did well for honour and glory of our guild and the Queen, Ssss. The Pottery Guild of Cadomyr sssupportsss your effortsss with some clay. Come back to me once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, ">", 29))
talkEntry:addCondition(condition_quest(707, "=", 8))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Töpferinnung von Cadomyr erhebt dich in den Rang eines Initiatens. Du erhältst dreißig Klumpen Lehm."))
talkEntry:addConsequence(consequence_item(26, 30, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 9))
talkEntry:addResponse("Sssehr gut. Du bringst der Töpferinnung und der Königin Ehre und Ruhm. Wir sssind stolzz dir mit einigen Klumpen Lehm sszu helfen. Ich ssseh dich wieder, sssobald du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, "<", 30))
talkEntry:addCondition(condition_quest(707, "=", 8))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("I'm proud to sssee you Apprentice. You should ssstay more time at the kiln to become promoted, Ssss.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 30 in pottery to advance in the ranks of the Pottery Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, "<", 30))
talkEntry:addCondition(condition_quest(707, "=", 8))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("I'm proud to sssee you Apprentice. You should ssstay more time at the kiln to become promoted, Ssss.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 30 in pottery to advance in the ranks of the Pottery Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, "<", 30))
talkEntry:addCondition(condition_quest(707, "=", 8))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Ess issst mir eine Ehre einen Lehrling der Gilde sszu ssehen. Ich habe dich aber nicht ssso viel am Brennofen gesehen, sssz.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 30 in Töpfern um in der Töpferinnung aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, ">", 39))
talkEntry:addCondition(condition_quest(707, "=", 9))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Journeyman with the Pottery Guild of Cadomyr. You are awarded thirty piles of clay and a journeyman's certificate."))
talkEntry:addConsequence(consequence_item(3109, 1, 333, {["descriptionEn"] = "The owner of this certificate has successfully passed the examination as Journeyman. Zlatxhol - Pottery Guild of Cadomyr", ["descriptionDe"] = "Der Inhaber dieses Gesellenbriefes hat erfolgreich das Examen zum Gesellen bestanden. Zlatxhol - Toepferinnung von Cadomyr", ["nameDe"] = "Gesellenbrief", ["nameEn"] = "Journeyman's Certificate", ["rareness"] = "1"}))
talkEntry:addConsequence(consequence_item(26, 30, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 10))
talkEntry:addResponse("You did well for honour and glory of our guild and the Queen, Ssss. The Pottery Guild of Cadomyr is glad to have a new journeyman. Come back to me once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, ">", 39))
talkEntry:addCondition(condition_quest(707, "=", 9))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Journeyman with the Pottery Guild of Cadomyr. You are awarded thirty piles of clay and a journeyman's certificate."))
talkEntry:addConsequence(consequence_item(3109, 1, 333, {["descriptionEn"] = "The owner of this certificate has successfully passed the examination as Journeyman. Zlatxhol - Pottery Guild of Cadomyr", ["descriptionDe"] = "Der Inhaber dieses Gesellenbriefes hat erfolgreich das Examen zum Gesellen bestanden. Zlatxhol - Toepferinnung von Cadomyr", ["nameDe"] = "Gesellenbrief", ["nameEn"] = "Journeyman's Certificate", ["rareness"] = "1"}))
talkEntry:addConsequence(consequence_item(26, 30, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 10))
talkEntry:addResponse("You did well for honour and glory of our guild and the Queen, Ssss. The Pottery Guild of Cadomyr is glad to have a new journeyman. Come back to me once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, ">", 39))
talkEntry:addCondition(condition_quest(707, "=", 9))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Töpferinnung von Cadomyr erhebt dich in den Rang eines Gesellens. Du erhältst dreißig Klumpen Lehm und einen Gesellenbrief."))
talkEntry:addConsequence(consequence_item(3109, 1, 333, {["descriptionEn"] = "The owner of this certificate has successfully passed the examination as Journeyman. Zlatxhol - Pottery Guild of Cadomyr", ["descriptionDe"] = "Der Inhaber dieses Gesellenbriefes hat erfolgreich das Examen zum Gesellen bestanden. Zlatxhol - Toepferinnung von Cadomyr", ["nameDe"] = "Gesellenbrief", ["nameEn"] = "Journeyman's Certificate", ["rareness"] = "1"}))
talkEntry:addConsequence(consequence_item(26, 30, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 10))
talkEntry:addResponse("Gut gemacht. Wie ich sehe, hast du hart gearbeitet. Die Töpferinnung von Cadomyr freut sich dich als neuen Gesellen zu begrüßen sszu helfen. Ich ssseh dich wieder, sssobald du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, "<", 40))
talkEntry:addCondition(condition_quest(707, "=", 9))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("I'm proud to sssee you Initiate. You should ssstay more time at the kiln to become promoted, Ssss.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 40 in pottery to advance in the ranks of the Pottery Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, "<", 40))
talkEntry:addCondition(condition_quest(707, "=", 9))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("I'm proud to sssee you Initiate. You should ssstay more time at the kiln to become promoted, Ssss.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 40 in pottery to advance in the ranks of the Pottery Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, "<", 40))
talkEntry:addCondition(condition_quest(707, "=", 9))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Ess issst mir eine Ehre einen Initiaten der Gilde sszu ssehen. Ich habe dich aber nicht ssso viel am Brennofen gesehen, sssz.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 40 in Töpfern um in der Töpferinnung aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, ">", 49))
talkEntry:addCondition(condition_quest(707, "=", 10))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Specialist with the Pottery Guild of Cadomyr. You are awarded forty piles of clay."))
talkEntry:addConsequence(consequence_item(26, 40, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 11))
talkEntry:addResponse("You did well for honour and glory of our guild and the Queen, Ssss. The Pottery Guild of Cadomyr sssupportsss your effortsss with some clay. Come back to me once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, ">", 49))
talkEntry:addCondition(condition_quest(707, "=", 10))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Specialist with the Pottery Guild of Cadomyr. You are awarded forty piles ofclay."))
talkEntry:addConsequence(consequence_item(26, 40, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 11))
talkEntry:addResponse("You did well for honour and glory of our guild and the Queen, Ssss. The Pottery Guild of Cadomyr sssupportsss your effortsss with some clay. Come back to me once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, ">", 49))
talkEntry:addCondition(condition_quest(707, "=", 10))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Töpferinnung von Cadomyr erhebt dich in den Rang eines Spezialistens. Du erhältst vierzig Klumpen Lehm."))
talkEntry:addConsequence(consequence_item(26, 40, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 11))
talkEntry:addResponse("Sssehr gut. Du bringst der Töpferinnung und der Königin Ehre und Ruhm. Wir sssind stolzz dir mit einigen Klumpen Lehm sszu helfen. Ich ssseh dich wieder, sssobald du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, "<", 50))
talkEntry:addCondition(condition_quest(707, "=", 10))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("I'm proud to sssee you Journeyman. You should ssstay more time at the kiln to become promoted, Ssss.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 50 in pottery to advance in the ranks of the Pottery Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, "<", 50))
talkEntry:addCondition(condition_quest(707, "=", 10))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("I'm proud to sssee you Journeyman. You should ssstay more time at the kiln to become promoted, Ssss.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 50 in pottery to advance in the ranks of the Pottery Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, "<", 50))
talkEntry:addCondition(condition_quest(707, "=", 10))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Ess issst mir eine Ehre einen Gesellen der Gilde sszu ssehen. Ich habe dich aber nicht ssso viel am Brennofen gesehen, sssz.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 50 in Töpfern um in der Töpferinnung aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, ">", 59))
talkEntry:addCondition(condition_quest(707, "=", 11))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Expert with the Pottery Guild of Cadomyr. You are awarded ten bags of topaz powder."))
talkEntry:addConsequence(consequence_item(451, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 12))
talkEntry:addResponse("You did well for honour and glory of our guild and the Queen, Ssss. The Pottery Guild of Cadomyr sssupportsss your effortsss with some topaz powder. Come back to me once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, ">", 59))
talkEntry:addCondition(condition_quest(707, "=", 11))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Expert with the Pottery Guild of Cadomyr. You are awarded ten bags of topaz powder."))
talkEntry:addConsequence(consequence_item(451, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 12))
talkEntry:addResponse("You did well for honour and glory of our guild and the Queen, Ssss. The Pottery Guild of Cadomyr sssupportsss your effortsss with some topaz powder. Come back to me once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, ">", 59))
talkEntry:addCondition(condition_quest(707, "=", 11))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Töpferinnung von Cadomyr erhebt dich in den Rang eines Expertens. Du erhältst zehn Sack Topasstaub."))
talkEntry:addConsequence(consequence_item(451, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 12))
talkEntry:addResponse("Sssehr gut. Du bringst der Töpferinnung und der Königin Ehre und Ruhm. Wir sssind stolzz dir mit etwas Topasstaub sszu helfen. Ich ssseh dich wieder, sssobald du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, "<", 60))
talkEntry:addCondition(condition_quest(707, "=", 11))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("I'm proud to sssee you Specialist. You should ssstay more time at the kiln to become promoted, Ssss.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 610 in pottery to advance in the ranks of the Pottery Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, "<", 60))
talkEntry:addCondition(condition_quest(707, "=", 11))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("I'm proud to sssee you Specialist. You should ssstay more time at the kiln to become promoted, Sss.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 60 in pottery to advance in the ranks of the Pottery Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, "<", 60))
talkEntry:addCondition(condition_quest(707, "=", 11))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Ess issst mir eine Ehre einen Spezialisten der Gilde sszu ssehen. Ich habe dich aber nicht ssso viel am Brennofen gesehen, sssz.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 60 in Töpfern um in der Töpferinnung aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, ">", 69))
talkEntry:addCondition(condition_quest(707, "=", 12))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Adept with the Pottery Guild of Cadomyr. You are awarded ten bags of ruby powder."))
talkEntry:addConsequence(consequence_item(447, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 13))
talkEntry:addResponse("You did well for honour and glory of our guild and the Queen, Ssss. The Pottery Guild of Cadomyr sssupportsss your effortsss with some ruby powder. Come back to me once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, ">", 69))
talkEntry:addCondition(condition_quest(707, "=", 12))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Adept with the Pottery Guild of Cadomyr. You are awarded ten bags of ruby powder."))
talkEntry:addConsequence(consequence_item(447, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 13))
talkEntry:addResponse("You did well for honour and glory of our guild and the Queen, Ssss. The Pottery Guild of Cadomyr sssupportsss your effortsss with some ruby powder. Come back to me once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, ">", 69))
talkEntry:addCondition(condition_quest(707, "=", 12))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Töpferinnung von Cadomyr erhebt dich in den Rang eines Adeptens. Du erhältst zehn Sack Rubinstaub."))
talkEntry:addConsequence(consequence_item(447, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 13))
talkEntry:addResponse("Sssehr gut. Du bringst der Töpferinnung und der Königin Ehre und Ruhm. Wir sssind stolzz dir mit etwas Rubinstaub sszu helfen. Ich ssseh dich wieder, sssobald du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, "<", 70))
talkEntry:addCondition(condition_quest(707, "=", 12))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("I'm proud to sssee you Expert. You should ssstay more time at the kiln to become promoted, Ssss.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 70 in pottery to advance in the ranks of the Pottery Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, "<", 70))
talkEntry:addCondition(condition_quest(707, "=", 12))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("I'm proud to sssee you Expert. You should ssstay more time at the kiln to become promoted, Ssss.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 70 in pottery to advance in the ranks of the Pottery Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, "<", 70))
talkEntry:addCondition(condition_quest(707, "=", 12))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Ess issst mir eine Ehre einen Experten der Gilde sszu ssehen. Ich habe dich aber nicht ssso viel am Brennofen gesehen, sssz.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 70 in Töpfern um in der Töpferinnung aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, ">", 79))
talkEntry:addCondition(condition_quest(707, "=", 13))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Artisan with the Pottery Guild of Cadomyr. You are awarded twenty backs of diamond powder."))
talkEntry:addConsequence(consequence_item(452, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 14))
talkEntry:addResponse("You did well for honour and glory of our guild and the Queen, Ssss. The Pottery Guild of Cadomyr sssupportsss your effortsss with some diamond powder. Come back to me once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, ">", 79))
talkEntry:addCondition(condition_quest(707, "=", 13))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Artisan with the Pottery Guild of Cadomyr. You are awarded twenty backs of diamond powder."))
talkEntry:addConsequence(consequence_item(452, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 14))
talkEntry:addResponse("You did well for honour and glory of our guild and the Queen, Ssss. The Pottery Guild of Cadomyr sssupportsss your effortsss with sssome diamond powder. Come back to me once you are more experienced.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, ">", 79))
talkEntry:addCondition(condition_quest(707, "=", 13))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Töpferinnung von Cadomyr erhebt dich in den Rang eines Artisanens. Du erhältst zwanzig Sack Diamantstaub."))
talkEntry:addConsequence(consequence_item(452, 20, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 14))
talkEntry:addResponse("Sssehr gut. Du bringst der Töpferinnung und der Königin Ehre und Ruhm. Wir sssind stolzz dir mit etwas Diamantstaub sszu helfen. Ich ssseh dich wieder, sssobald du erfahrener bist.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, "<", 80))
talkEntry:addCondition(condition_quest(707, "=", 13))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("I'm proud to sssee you Adept. Isss hard work to becomes a massster potter.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 80 in pottery to advance in the ranks of the Pottery Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, "<", 80))
talkEntry:addCondition(condition_quest(707, "=", 13))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("I'm proud to sssee you Adept. Isss hard work to becomes a massster potter.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 80 in pottery to advance in the ranks of the Pottery Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, "<", 80))
talkEntry:addCondition(condition_quest(707, "=", 13))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Ess issst mir eine Ehre einen Adepten der Gilde sszu ssehen. Ich weisss, issst harte Arbeit um Meister der Töpfer ssszu werden, sssz.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 80 in Töpfern um in der Töpferinnung aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, ">", 89))
talkEntry:addCondition(condition_quest(707, "=", 14))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Master with the Pottery Guild of Cadomyr. You are awarded five pieces of pure fire and a special set of tongs."))
talkEntry:addConsequence(consequence_item(2553, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 15))
talkEntry:addResponse("You did well for honour and glory of our guild and the Queen, Ssss. The Pottery Guild of Cadomyr sssupportsss your effortsss with some pure fire and this special tool. Come back to me once you are more experienced.")
talkEntry:addConsequence(consequence_item(2140, 1, 999, {["descriptionEn"] = "Master of the Pottery Guild of Cadomyr", ["descriptionDe"] = "Meister der Toepferinnung von Cadomyr", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, ">", 89))
talkEntry:addCondition(condition_quest(707, "=", 14))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Master with the Pottery Guild of Cadomyr. You are awarded five pieces of pure fire and a special set of tongs."))
talkEntry:addConsequence(consequence_item(2553, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 15))
talkEntry:addResponse("You did well for honour and glory of our guild and the Queen, Ssss. The Pottery Guild of Cadomyr sssupportsss your effortsss with some pure fire and thins special tool. Come back to me once you are more experienced.")
talkEntry:addConsequence(consequence_item(2140, 1, 999, {["descriptionEn"] = "Master of the Pottery Guild of Cadomyr", ["descriptionDe"] = "Meister der Toepferinnung von Cadomyr", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, ">", 89))
talkEntry:addCondition(condition_quest(707, "=", 14))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Töpferinnung von Cadomyr erhebt dich in den Rang eines Meisters. Du erhältst fünf Stück reines Feuer und eine besondere Zange."))
talkEntry:addConsequence(consequence_item(2553, 5, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 15))
talkEntry:addResponse("Sssehr gut. Du bringst der Töpferinnung und der Königin Ehre und Ruhm. Wir sssind stolzz dir mit etwas reinem Feuer und dieser speziellen Zange sszu helfen. Ich ssseh dich wieder, sssobald du erfahrener bist.")
talkEntry:addConsequence(consequence_item(2140, 1, 999, {["descriptionEn"] = "Master of the Pottery Guild of Cadomyr", ["descriptionDe"] = "Meister der Toepferinnung von Cadomyr", ["rareness"] = "1"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, "<", 90))
talkEntry:addCondition(condition_quest(707, "=", 14))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("I'm proud to sssee you Artisan. Isss hard work to becomes a massster potter.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 90 in pottery to advance in the ranks of the Pottery Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, "<", 90))
talkEntry:addCondition(condition_quest(707, "=", 14))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("I'm proud to sssee you Artisan. Isss hard work to becomes a massster potter.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 90 in pottery to advance in the ranks of the Pottery Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, "<", 90))
talkEntry:addCondition(condition_quest(707, "=", 14))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Ess issst mir eine Ehre einen Artisanen der Gilde sszu ssehen. Ich weisss, issst harte Arbeit um Meister der Töpfer ssszu werden, sssz.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 90 in Töpfern um in der Töpferinnung aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, ">", 99))
talkEntry:addCondition(condition_quest(707, "=", 15))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Grandmaster with the Pottery Guild of Cadomyr. You are awarded ten pieces of pure earth and a grandmaster's medal."))
talkEntry:addConsequence(consequence_item(2552, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 16))
talkEntry:addResponse("What a high hounour, Ssss. I bow to a new Grandmaster of the Pottery Guild of Cadomyr. With this pure earth, you shall help make the most valuable goodss of Illarion.")
talkEntry:addConsequence(consequence_item(3535, 1, 999, {["descriptionEn"] = "Grandmaster of the Pottery Guild of Cadomyr", ["descriptionDe"] = "Großmeister der Töpferinnung von Cadomyr", ["nameDe"] = "Großmeistermedallie", ["nameEn"] = "Grandmaster's Medal", ["rareness"] = "2"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, ">", 99))
talkEntry:addCondition(condition_quest(707, "=", 15))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addConsequence(consequence_inform("[Guild rank] You advance to the rank of Grandmaster with the Pottery Guild of Cadomyr. You are awarded ten pieces of pure earth and a grandmaster's medal."))
talkEntry:addConsequence(consequence_item(2552, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 16))
talkEntry:addResponse("What a high hounour, Ssss. I bow to a new Grandmaster of the Pottery Guild of Cadomyr. With this pure earth, you shall help make the most valuable goodss of Illarion.")
talkEntry:addConsequence(consequence_item(3535, 1, 999, {["descriptionEn"] = "Grandmaster of the Pottery Guild of Cadomyr", ["descriptionDe"] = "Großmeister der Töpferinnung von Cadomyr", ["nameDe"] = "Großmeistermedallie", ["nameEn"] = "Grandmaster's Medal", ["rareness"] = "2"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, ">", 99))
talkEntry:addCondition(condition_quest(707, "=", 15))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Die Töpferinnung von Cadomyr erhebt dich in den Rang eines Großmeisters. Du erhältst zehn Stück reiner Erde und eine Großmeistermedallie."))
talkEntry:addConsequence(consequence_item(2552, 10, 333, nil))
talkEntry:addConsequence(consequence_quest(707, "=", 16))
talkEntry:addResponse("Welch hohe Ehre, sssz. Ich verneige mich vor einem neuen Großmeister der Töpferinnung von Cadomyr. Mit dieser reinen Erde wirst du die teuersten Waren Illarions herstellen.")
talkEntry:addConsequence(consequence_item(3535, 1, 999, {["descriptionEn"] = "Grandmaster of the Pottery Guild of Cadomyr", ["descriptionDe"] = "Großmeister der Töpferinnung von Cadomyr", ["nameDe"] = "Großmeistermedallie", ["nameEn"] = "Grandmaster's Medal", ["rareness"] = "2"}))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, "<", 100))
talkEntry:addCondition(condition_quest(707, "=", 15))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("I'm proud to sssee you Master. Isss hard work to becomes a massster potter.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 100 in pottery to advance in the ranks of the Pottery Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, "<", 100))
talkEntry:addCondition(condition_quest(707, "=", 15))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addTrigger("rank")
talkEntry:addResponse("I'm proud to sssee you Master. Isss hard work to becomes a massster potter.")
talkEntry:addConsequence(consequence_inform("[Guild rank] You need skill level 100 in pottery to advance in the ranks of the Pottery Guild."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_skill(Character.pottery, "<", 100))
talkEntry:addCondition(condition_quest(707, "=", 15))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addTrigger("Rang")
talkEntry:addResponse("Ess issst mir eine Ehre einen Meister der Gilde sszu ssehen. Ich weisss, issst harte Arbeit um Meister der Töpfer ssszu werden, sssz.")
talkEntry:addConsequence(consequence_inform("[Gildenrang] Du brauchst Level 100 in Töpfern um in der Töpferinnung aufzusteigen."))
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(707, "=", 16))
talkEntry:addCondition(condition_language("english"))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("The Pottery Guild of Cadomyr hailsss Grandmaster %CHARNAME.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(707, "=", 16))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addResponse("The Pottery Guild of Cadomyr hailsss Grandmaster %CHARNAME.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_quest(707, "=", 16))
talkEntry:addCondition(condition_town(1))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addResponse("Die Töpferinnung von Cadomyr grüßsst ihren Großmeister %CHARNAME.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addResponse("The Pottery Assssociation isss restricted to Cadomyr's citizzens. I don't haves anything for you to do, zsss.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("quest")
talkEntry:addTrigger("mission")
talkEntry:addTrigger("Auftrag")
talkEntry:addTrigger("Aufgabe")
talkEntry:addTrigger("Abenteuer")
talkEntry:addTrigger("Befehl")
talkEntry:addResponse("Die Töpferinnung sssteht nur Bürgern Cadomyrs offen, zsss.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("task")
talkEntry:addTrigger("adventure")
talkEntry:addTrigger("order")
talkEntry:addResponse("The Pottery Assssociation isss restricted to Cadomyr's citizzens. I don't haves anything for yous to do, zsss.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("rosalie")
talkEntry:addTrigger("edwards")
talkEntry:addResponse("The Queen Rosalie Edwards isss mother of Cadomyr, asss Zelphia isss mother of childrensss of the ssssea.")
talkEntry:addResponse("I'm proud to ssserve the Queen as a craftsmen.")
talkEntry:addResponse("Hail the Queen!")
talkEntry:addResponse("All pottery in the palace was made by our guild.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("queen")
talkEntry:addResponse("The Queen Rosalie Edwards isss mother of Cadomyr, asss Zelphia isss mother of childrensss of the ssssea.")
talkEntry:addResponse("I'm proud to ssserve the Queen as a craftsmen.")
talkEntry:addResponse("Hail the Queen!")
talkEntry:addResponse("All pottery in the palace was made by our guild.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("rosalie")
talkEntry:addTrigger("edwards")
talkEntry:addTrigger("König")
talkEntry:addResponse("Die Königin Rosalie Edwards issst Mutter vons Cadomyr ssso wie Zelphia issst Mutter von Kinder der Sssee.")
talkEntry:addResponse("Ich bin stolz der Königin als Handwerker zu dienen.")
talkEntry:addResponse("Hoch lebe die Königin!")
talkEntry:addResponse("Alle Töpferwaren im Palast stammen von unserer Innung.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addCondition(condition_language("english"))
talkEntry:addTrigger("Zelphia")
talkEntry:addTrigger("Tanora")
talkEntry:addResponse("Zelphia isss mother of childrensss of ssssea.")
talkEntry:addResponse("Temple of Zelphia isss in west of Cadomyr.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Zelphia")
talkEntry:addTrigger("Tanora")
talkEntry:addResponse("Zelphia issst Mutter der Kinder der Sssee.")
talkEntry:addResponse("Den Tempel Zelphias findest du im Westen der Stadt, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("god")
talkEntry:addTrigger("temple")
talkEntry:addResponse("Cadomyr hasss many templess, Ssss. Isss Zelphia in west, Zhambra near the palace, Malachin sssouth of town and Sirani in delta of Kantabi water ssstream.")
talkEntry:addResponse("Ssserve the Queen, Worship your God and become a honourable potter!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Gott")
talkEntry:addTrigger("Tempel")
talkEntry:addResponse("Cadomyr hat viele Tempel, sssz. Zelphiasss in Westen, Zhambrasss am Palast, Malachinsss im Sssüden der Stadt und Sirani on Delta desss grossen Kantabi Wasssserss.")
talkEntry:addResponse("Diene der Königin, Preise deinen Gott und werd ein ehrenvoller Töpfer!")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("clay")
talkEntry:addResponse("Best clay hasss to be ssssoft, ass butt of landstridersss baby.")
talkEntry:addResponse("My favourite clay pit is far in the sssouth near the ocean.")
talkEntry:addResponse("Pottery is not only burned clay, isss a art, Ssss.")
talkingNPC:addTalkingEntry(talkEntry)
end
do
local talkEntry = talk.talkNPCEntry()
talkEntry:addTrigger("Lehm")
talkEntry:addResponse("Lehm muss weich sein, wie der Po eines Landläuferbabiessss.")
talkEntry:addResponse("Meine bevorzugte Lehmgrube liegt weit im Sssüden am Meer, sssz.")
talkEntry:addResponse("Töpfern issst mehr alsss nur Lehm brennen, esss issst eine Kunst, sssz.")
talkingNPC:addTalkingEntry(talkEntry)
end
talkingNPC:addCycleText("#me schaut sich gelangweilt um.", "#me looks around bored.")
talkingNPC:addCycleText("#me kratzt sich am Kopf.", "#me scratches his head.")
talkingNPC:addCycleText("Wenns du Hilfe beim Töpfern brauchst dann fragt michss!", "If you need any help with pottery, jussst asssk me!")
talkingNPC:addCycleText("Zsss.", "Zsss.")
talkingNPC:addCycleText("Zsss!", "Zsss!")
talkingNPC:addCycleText("Zsss?", "Zsss?")
talkingNPC:addCycleText("#me zischelt.", "#me hisses.")
talkingNPC:addCycleText("Ssss..", "Ssss..")
talkingNPC:addCycleText("Ssss?", "Ssss?")
talkingNPC:addCycleText("Ssss!", "Ssss!")
talkingNPC:addCycleText("Tsss.", "Tsss.")
talkingNPC:addCycleText("#me lässt seinen Schwanz hin und her schnellen.", "#me wags his tail back and forth.")
mainNPC:addLanguage(0)
mainNPC:addLanguage(4)
mainNPC:setDefaultLanguage(0)
mainNPC:setLookat("Dieser NPC ist Zlatxhol der Töpfer.", "This NPC is Zlatxhol the potter.")
mainNPC:setUseMessage("Fass mich nicht an!", "Hands off!")
mainNPC:setConfusedMessage("#me schaut dich verwirrt an.", "#me looks at you confused.")
mainNPC:setEquipment(1, 0)
mainNPC:setEquipment(3, 457)
mainNPC:setEquipment(11, 194)
mainNPC:setEquipment(5, 0)
mainNPC:setEquipment(6, 0)
mainNPC:setEquipment(4, 0)
mainNPC:setEquipment(9, 183)
mainNPC:setEquipment(10, 0)
mainNPC:setAutoIntroduceMode(true)

mainNPC:initDone()
return mainNPC
end
local mNPC = initNpc()
initNpc = nil
local M = {}
function M.receiveText(npcChar, texttype, message, speaker) mNPC:receiveText(npcChar, texttype, speaker, message) end
function M.nextCycle(npcChar) mNPC:nextCycle(npcChar) end
function M.lookAtNpc(npcChar, char, mode) mNPC:lookAt(npcChar, char, mode) end
function M.useNPC(npcChar, char, counter, param) mNPC:use(npcChar, char) end
return M
